### ISSUE TITLE
Load from 2d array within vmap results in two gathers rather than just one

### ISSUE THREAD

**Issue by jlebar** [google/jax#1006]
```
import jax
import jax.numpy as np
import numpy as onp

def test(arr, x, y):
  return arr[x, y]

rand_x = onp.random.randint(0, 200, size=1024)
rand_y = onp.random.randint(0, 200, size=1024)
rand_arr = onp.random.uniform(0, 1, size=(200,200))
test_vmap = jax.vmap(test, in_axes=(None, 0, 0))
jax.jit(test_vmap)(rand_arr, rand_x, rand_y)
```

The `jax.jit` results in an XLA computation with two gathers, but the expression can be implemented with just one.

Two gathers is quite bad, because unnecessarily it materializes out a large array; you really don't want to do this.

I am not blocked on this, because I've worked around it by flattening the array and doing `x * width + y`.  But this is not ideal because it forces a layout upon XLA.  Also this is something that nobody other than an XLA expert is going to notice and work around in their code.

**Comment by mattjj** [comment]
Just adding more info to this: this behavior is because of how we implemented NumPy indexing in [`jax.numpy._rewriting_take`](https://github.com/google/jax/blob/8e794ad98806d61fdfed4bf243d81c8545f741cc/jax/numpy/lax_numpy.py#L2167), in that we basically handle one index at a time just for simplicity's sake (and because that code predates the Scatter and Gather HLOs!). We have slightly "better" logic in [other places](https://github.com/google/jax/blob/8e794ad98806d61fdfed4bf243d81c8545f741cc/jax/ops/scatter.py#L42) in that it handles NumPy indexing and produces a single Gather/Scatter, but [it's not as complete yet](https://github.com/google/jax/blob/8e794ad98806d61fdfed4bf243d81c8545f741cc/jax/ops/scatter.py#L98).

I think we always hoped that XLA would fuse multiple Gathers / slices together under a `jit`. How tricky is that?

**Comment by jlebar** [comment]
> I think we always hoped that XLA would fuse multiple Gathers / slices together under a jit. How tricky is that?

It's certainly possible, but not trivial.  If it was simply gather-of-gather that would be one thing (still nontrivial), but I'm observing it's gather-of-reshape-of-gather, and now this is "interesting".

I generally err on implementing these kinds of optimizations in the compiler even if it's somewhat complicated, because that's what it's there for.  But OTOH I don't know how hard it would be to change this on your end.
