### ISSUE TITLE
random.normal is slow when shape is a list instead of a tuple

### ISSUE THREAD

**Issue by matthewdhoffman** [google/jax#1038]
Like, 1000x slower:

![image](https://user-images.githubusercontent.com/509707/61555153-8bea4f00-aa13-11e9-9eb4-7f7aec1e09db.png)

Might be good to at least give an informative warning when the user passes in a non-tuple shape.

**Comment by mattjj** [comment]
Ah, this is because lists aren't hashable, so things are re-compiling every time...

**Comment by mattjj** [comment]
It's [this line](https://github.com/google/jax/blob/24d4aaf3e20d58dd66a3df8ffe0d0ea9e976c307/jax/api.py#L1124-L1125) calling [this function](https://github.com/google/jax/blob/24d4aaf3e20d58dd66a3df8ffe0d0ea9e976c307/jax/api.py#L1129-L1135) that's the culprit. We test hashability but I guess we could special-case lists there.

**Comment by mattjj** [comment]
The more general solution is probably to improve the `jit` docs. Lists (and other mutable data structures) can limit the opportunities for cache hits.

To be clear, this yield cache hits just fine:

```python
shape = [batch_size, D]
%timeit normal(key,  shape)
```

The problem is non-hashable types can only be identified by `id`, and since this code is creating a fresh list on each invocation, we're not getting any hits.

**Comment by matthewdhoffman** [comment]
Cool, thanks for the explanation!

**Comment by hawkinsp** [comment]
I think we can consider this issue fixed, because we now issue an error for unhashable `jit` argument types rather than silently recompiling.

```
ValueError: Non-hashable static arguments are not supported. An error occured while trying to hash an object of type <class 'list'>, [100, 100]. The error was:
TypeError: unhashable type: 'list'
```
