### ISSUE TITLE
[Docs] Add installation instructions to documentation

### ISSUE THREAD

**Issue by JeppeKlitgaard** [google/jax#10414]
Currently the installation instructions are only found in the GitHub README. Since installation is more involved than simply `pip install jax`, I think it would be really nice to copy/move over the installation instructions to the documentation, perhaps a subsection titled "Installation" under "Getting Started"?

**Comment by jakevdp** [comment]
Thanks for the request.

We've discussed this previously and the consensus at the time was that (1) we want installation instructions in the README because that's a common landing page for people, and (2) we don't want to maintain two separate copies of the installation instructions.

The result was the current state of things, where the installation instructions are only in the README.

**Comment by JeppeKlitgaard** [comment]
That makes a lot of sense. Feel free to close this issue – might be worthwhile to add a link to the GitHub README from documentation?

**Comment by jakevdp** [comment]
Thanks for the suggestion - Done in #10423
