### ISSUE TITLE
XOR for sparse matrix

### ISSUE THREAD

**Issue by tushuhei** [google/jax#10435]
The code blow returns `NotImplementedError: sparse rule for xor`.

```python
import jax.numpy as jnp
from jax.experimental import sparse
indices = [[0, 1], [1, 2]]
X = sparse.BCOO(([1 for _ in range(len(indices))], indices), shape=(3, 4))
y = jnp.ones(3, dtype=bool)

@sparse.sparsify
def xor(X, y):
  return y[:, None] ^ X

xor(X, y)
```

Please: add support for XOR operation over sparse matrices.

- [X] Check for duplicate requests.
- [X] Describe your goal, and if possible provide a code snippet with a motivating example.

**Comment by jakevdp** [comment]
Thanks for the question - in general our philosophy with sparse operations is to not implement ones that would require implicit conversion to dense. For example, you cannot add a scalar to a sparse matrix because the output is in general not sparse. If that's really what you want, you can explicitly convert the matrix to dense and add one.

I think this falls in the same category: because there are values of `y` that would require the output to be entirely dense, then the depending on the value of `y`, the output of the operation may be an entirely dense matrix. If that is what you want, then you should convert `X` to a dense matrix before computing the result, but we will not introduce code paths that do that implicitly.

**Comment by hawkinsp** [comment]
Could we indicate that in the error message more clearly?

**Comment by jakevdp** [comment]
That's a good idea – we could have something more specific than `NotImplementedError` for operations that are not implemented for fundamental reasons.
