### ISSUE TITLE
inconsistent behaviour for jax.numpy.power

### ISSUE THREAD

**Issue by mattbarrett98** [google/jax#10692]
Running
```python
import jax.numpy as jnp
x = jnp.array([2], dtype='int8')
y = jnp.array([64], dtype='int8')
print(jnp.power(x, y))
```
gives `[1]`, yet
```python
x = jnp.array(2, dtype='int8')
y = jnp.array(64, dtype='int8')
print(jnp.power(x, y))
```
gives `0`. Why does simply changing the shapes of `x` and `y` impact the value of the result?

**Comment by jakevdp** [comment]
The reason is that in the first case, the implementation is via `lax.pow`, while in the second case, since the input is a concrete integer, it is computed via an integer power optimization. Apparently the two approaches have different overflow characteristics.

**Comment by jakevdp** [comment]
Assigning to @hawkinsp who has put the most thought into these algorithms.

**Comment by hawkinsp** [comment]
This is working as intended: if you cause integer overflow, the behavior is implementation-defined. If that's a problem then... don't do that :-)

As to why they differ, I suspect it's because `lax.integer_pow`'s copy of the algorithm runs for a known number of iterations that depends on the right-hand side, whereas `jnp.power` runs for a fixed number (6 times) irrespective of the value of the right hand side. So they have slightly different overflow behaviors.
