### ISSUE TITLE
noob vmap question with if statement

### ISSUE THREAD

**Issue by murphyk** [google/jax#1076]
Hi

I'd like to vectorize the following '1d truncated Gaussian kernel' function

```
def kernel_scalar(x, lam=0.18, beta=1.0):
    if np.abs(x) > lam:
        return 0.0
    else:
        return np.exp(-beta*x**2)
```

I tried this
```
def kernel(xs):
    kernels = vmap(kernel_scalar)(xs)
    return kernels
```

but  when I try this
```
n = 10
xs = onp.random.randn(n)
k = kernel(xs)
```
I get this error
```
...
  File "/Users/kpmurphy/github/pyprobml/scripts/mean_shift_opt.py", line 8, in kernel_scalar
    if np.abs(x) > lam:

  File "/anaconda3/lib/python3.6/site-packages/jax/core.py", line 342, in __bool__
    def __bool__(self): return self.aval._bool(self)

  File "/anaconda3/lib/python3.6/site-packages/jax/abstract_arrays.py", line 38, in error
    raise TypeError(concretization_err_msg(fun))

TypeError: Abstract value passed to `bool`, which requires a concrete value. The function to be transformed can't be traced at the required level of abstraction. If using `jit`, try using `static_argnums` or applying `jit` to smaller subfunctions instead
```

I realize that dynamic if is not allowed inside jit, but I am not (explicitly) calling jit.
Also the return of both branches has the same type and shape, so why does
the value matter?

(I also realize it's easy to vectorize this  function with vanilla numpy, but I was hoping vmap would let me do everything with just scalar arithmetic :)

**Comment by jekbradbury** [comment]
`vmap` is essentially adding a batch dimension, and each example in the "batch" currently needs to execute the same instructions in the same order, putting the same restrictions on user code as `jit`. You can get around this by using `np.where` instead of `if` (or perhaps `lax.cond`, but that's unnecessary complexity for this example).

**Comment by mattjj** [comment]
As @jekbradbury said, just like `jit` must trace your code on an abstract value representing the set of all possible arrays `x` with a given shape/dtype (rather than on one concrete value for `x`), `vmap` must similarly trace your code on an abstract value that could represent any value in your batch. (For simplicity, we don't trace on an abstract value representing just the finite set of possible values in the batch, though in principle we could; we instead trace on an abstract value representing the set of all possible arrays with given shape/dtype, i.e. we trace at the same level for `vmap` and for `jit`.) That puts constraints on the Python code we can successfully trace with `vmap`, and in particular we can't trace value-dependent Python control flow and instead raise the error you saw.

Here are two ways to write this in a way that works with vectorization:

```python
def kernel_scalar(x, lam=0.18, beta=1.0):
  return np.where(np.abs(x) > lam, 0., np.exp(-beta * x ** 2)

def kernel_scalar(x, lam=0.18, beta=1.0):
  return lax.cond(np.abs(x) > lam, x, lambda _: np.zeros_like(x), x, lambda x: np.exp(-beta * x**2))
```

I think the former is more ergonomic, and when you `vmap` the latter function it basically turns into the former function anyway. But it does mean you're vectorizing it just like in vanilla NumPy. The latter _does_ let you assume the scalar case, which is cool, but the fact that you have to write `lax.cond` instead of a native Python `if` takes the fun out of it.

Please reopen if we failed to explain this constraint!
