### ISSUE TITLE
Incorrect cholesky jacobians?

### ISSUE THREAD

**Issue by coursekevin** [google/jax#10815]
I'm computing jacobians of the following equation with respect to B,
a = B<sup>-1</sup>c,
where a, c &in; R<sup> n</sup> and B &in; R<sup> n x n</sup> is SPD.

The jacobian should be,
da/dvec(B) = -(a^{T} &otimes; B <sup>-1</sup>),
where &otimes; indicates the Kronecker product. 

If I compute a = jnp.dot(inv(B), c) and then compute the jacobian with respect to B, I get what I would expect. If I compute a = cho_solve(cho_factor(B),c) and then compute the jacobian I get something different.

I've included a short snippet below highlighting the potential issue. 

```python
import jax
import jax.numpy as jnp
from jax import random, jacfwd
from jax.scipy.linalg import cho_solve, cho_factor, inv
from functools import partial

jax.config.update("jax_enable_x64", True)
jax.config.update("jax_platform_name", "cpu")


rng = random.PRNGKey(2022)
d = 2


def init_spd(d, rng):
    tril_ind = jnp.tril_indices(d)
    Q = jnp.zeros((d, d))
    Q = Q.at[tril_ind[0], tril_ind[1]].set(random.normal(rng, (d * (d + 1) // 2,)))
    Q = jnp.dot(Q, Q.T) + jnp.eye(d) * 1e-6
    return Q


rng, subkey = random.split(rng)
B = init_spd(d, subkey)
rng, subkey = random.split(rng)
c = random.normal(subkey, (d,))


def a(mode, B):
    if mode == "chol":
        a = cho_solve(cho_factor(B), c)
    elif mode == "inv":
        a = jnp.dot(inv(B), c)
    else:
        raise ValueError("No recognized mode")
    return a


# computing a with chol & inv gives the same result
print("a using chol")
print(a("chol", B))
print("a using inv")
print(a("inv", B))

# computing jacobians with chol & inv gives different results
print("da/dvec(B) with chol")
print(jacfwd(partial(a, "chol"))(B).transpose(0, 2, 1).reshape(d, d ** 2))
print("da/dvec(B) with inv")
print(jacfwd(partial(a, "inv"))(B).transpose(0, 2, 1).reshape(d, d ** 2))
print("da/dvec(B) manual")
print(-jnp.kron(a("chol", B).reshape(1, -1), inv(B)))
```

**Comment by mattjj** [comment]
Thanks for raising this!

I wouldn't quite call this a bug, but rather a subtle issue in writing a Python function which corresponds to the mathematical function we want. Indeed there are multiple reasonable mathematical functions we might want here!

The mathematical question has to do with whether we want to consider asymmetric perturbations to the input matrix. Is the input tangent space the space of all nxn matrices, or just all _symmetric_ nxn matrices? That is, is the domain of the mathematical function we have in mind all invertible matrices, or just symmetric (and positive definite) ones?

To make the `chol` and `inv` paths agree, we can add a call to `symmetrize = lambda X: (X + X.T) / 2.` like this:

```python
def a(mode, B):
    if mode == "chol":
      a = cho_solve(cho_factor(symmetrize(B)), c)  # note symmetrize(B)
    elif mode == "inv":
        a = jnp.dot(inv(symmetrize(B)), c)  # note symmetrize(B)
    else:
        raise ValueError("No recognized mode")
    return a
```

```
da/dvec(B) with chol
[[-449.75533508  -45.56447342  -45.56447342   -3.94970749]
 [ -62.87687425  -16.29812641  -16.29812641   -1.79947677]]
da/dvec(B) with inv
[[-449.75533508  -45.56447342  -45.56447342   -3.94970749]
 [ -62.87687425  -16.29812641  -16.29812641   -1.79947677]]
```

By adding these calls to `symmetrize` we're effectively projecting the input perturbations onto the vector subspace of symmetric matrices.

Without the call to `symmetrize`, the `inv` version of the function represents a mathematical function on all invertible matrices (not just symmetric ones) and so naturally the tangent space is all nxn matrices.

The `chol` version without the call to `symmetrize`, on the other hand, actually represents a mathematical function on the lower triangle of its input, and the space of perturbations is projected to the same. (That's because the `cho_factor` function only reads the lower triangle of its input, and the strict upper triangle is ignored.)

By having calls to `symmetrize` on both paths, we are (by composition) making them both functions on the symmetric part only of their input.

What do you think?

**Comment by mattjj** [comment]
By the way, to get the symmetric "manual" version, just write this:

```python
print((-jnp.kron(a("chol", B).reshape(1, -1), inv(B))
       - jnp.kron(inv(B), a("chol", B).reshape(1, -1))) / 2.)
```

**Comment by coursekevin** [comment]
Thanks for your very thoughtful response, this was really helpful! Your explanation makes total sense.  Definitely not a bug, this was my mistake.
