### ISSUE TITLE
save jitted functions to avoid recompiling large models

### ISSUE THREAD

**Issue by sokrypton** [google/jax#10966]
I didn't see an option to reopen an issue, so I'm starting a new one here:
https://github.com/google/jax/issues/679

jax appears to support cloud-pickling jit compilation according to the test:
https://github.com/google/jax/blob/main/tests/pickle_test.py

But testing it today, on a random function I wrote, this does not appear to be the case.
the unpickled function still requires jit compilation. Am I doing something wrong?
https://colab.research.google.com/drive/1VkJGTn0-eXa4_mj_ogmsBrDNiDkXq4LL

Motivation: Large models like AlphaFold require ~5 mins to compile. For small inference jobs (few seconds), most of the time is wasted just waiting for the model to compile. We were thinking the ability to save/load compiled models, should save lots of compute...
But it looks like the functionality is broken? :(

**Comment by YouJiacheng** [comment]
There are some related works in https://github.com/google/jax/tree/main/jax/experimental/compilation_cache

**Comment by ibulu** [comment]
ahh...this would be such a helpful feature!

**Comment by froystig** [comment]
Indeed, pickling isn't meant to avoid compilation. Saving the compiled artifact out-of-process roughly amounts to #476 (and possibly other related issues), which is still open as we still have it in mind. It requires work down the stack on different backends. As @YouJiacheng mentioned, there is a TPU-specific experimental cache at this point.

Within a running process, you can pre-compile thanks to #7733, which is effectively complete (documentation is in the works), but this doesn't provide any persistent save/load functionality for now.

Closing since this is essentially covered by discussion on #476.
