### ISSUE TITLE
incremental compilation with manual mark

### ISSUE THREAD

**Issue by YouJiacheng** [google/jax#10974]
We have persistent compilation cache(despite being only available on TPU), but we cannot easily do incremental compilation during debugging(performance of non-JIT code is unacceptable).

Imagine we have a complicated function `f`, but we only change some sub-functions during debugging.
Currently JAX will re-compile the whole function `f`.

It would be great if we can manually mark some sub-function as XLA-non-inline(including its corresponding part in `vmap`/`grad`/`jvp`... transformed `f`), i.e. using XLA call.

This will degrade the performance, thus it should not be a default behavior - I think it is convenient enough to mark it manually.

IIUC, if we only `jit` sub-functions instead of `f`, we cannot get satisfactory performance for `vmap`/`grad`/`jvp`... transformed `f`.
BTW, is there any documentation about `vmap`/`grad`/`jvp`... behavior when sub-functions are jitted?

**Comment by patrick-kidger** [comment]
+1 for "sub XLA graphs" as something that would be really *really* useful.

Incremental recompilation is one use-case. Another use case I've got is when doing something like -- excuse the pseudocode -- `jax.jit(for _ in range(...): big_function())`.

I'd love to be able to compile `big_function` only once, since at the moment this produces very long compile times. (As the loop is unrolled and each version of `big_function` treated separately.)

**Comment by pschuh** [comment]
We now have: `--jax_experimental_subjaxpr_lowering_cache` which can cache tracing the jaxprs and addresses part of @patrick-kidger 's suggestion. I don't think we can do much more on this beyond what a user could do by just removing the outer jit and jitting the components of their model individually until XLA supports noinline on those lowered functions. The problem is that XLA has to do buffer assignment for each of those `big_function()` which means that the generated code cannot be portable between multiple compilations.
