### ISSUE TITLE
`build.py` interfering with `.bazelversion`

### ISSUE THREAD

**Issue by nicholasjng** [google/jax#11246]
Homebrew's current `bazel` bottle is version 5.2, matching Bazel's latest release. But the presence of a `.bazelversion` file in the JAX repo, which currently holds `5.1.1`, forces the download of the pinned Bazel 5.1.1 binary if it is not available.

This creates an unnecessary download of the Bazel binary, since a version pin like that interferes with the build script logic here:

https://github.com/google/jax/blob/a90bde2c54db697e2a14d593689e91c695657a0c/build/build.py#L197-L202

This, a priori, allows anything newer than or equal to Bazel 5.1.1. Indeed, I think I remember this gate (please fact-check me on this) being first introduced due to a bump in the minimum required Bazel for TF reasons.

How do you feel about removing the `.bazelversion` file and gating solely on the Bazel version value inside the build script, like it is done right now? If the located Bazel is too old, a newer one will be downloaded in-tree as a last resort, anyway.

**Comment by hawkinsp** [comment]
It is actually somewhat intentional that we pin an *exact* version of Bazel: we don't test against anything other than 5.1.1 so all bets are off if you use anything different. It will *probably* work if you use something else with the same major version, but I think it's fine in some sense that you "acknowledge" that policy by deleting `.bazelversion` locally if you want that.

What do you think?

**Comment by nicholasjng** [comment]
Sounds fair. Do you happen to have a pro tip for how to maintain these changes locally side by side with the upstream git history? (Another one that comes to mind would be using a local TF repo instead of the http archive in the workspace)

Otherwise, I think this can be closed. Thanks for the answer!
