### ISSUE TITLE
jnp.array.base

### ISSUE THREAD

**Issue by ilemhadri** [google/jax#11585]
i wonder if jax can accomodate the `.base` call that numpy has to determine the base memory object for a array.

Example:
```
import jax.numpy as jnp
a = jnp.arange(3)
b = a[::-1]
assert(id(a.base)==id(b))
```

Alternatively, are there other tools to determine whether a specific array is a copy or a view of another jnp array?

**Comment by jakevdp** [comment]
This isn't as relevant for JAX, as JAX works a bit differently than numpy. Unlike NumPy, JAX arrays are read-only, so you don't have to worry about things like in-place updates affecting another view. Further, a buffer-backed JAX DeviceArray will never be a view of another: single operations will always result in the creation of a new buffer. However when a sequence of operations is JIT-compiled, the compiler generally will rearrange and fuse operations so that array copies are avoided in the compiled result. For that reason, inspection of the array buffer id is not really that useful or meaningful in JAX.
