### ISSUE TITLE
kwargs sometimes cannot work well with jit

### ISSUE THREAD

**Issue by zhongwen** [google/jax#1159]
Minimal repro:

```
from functools import partial
from jax import jit

@partial(jit, static_argnums=(3,))
def f(a, b, c, d):
  if d > 0:
    return a + b - c
  else:
    return d
```

`f(a=1, b=2, c=3, d=4)` would complain about `TypeError: Jitted function has static_argnums=(3,) but was called with only 0 positional arguments.`

but `f(1, 2, 3, 4)` works.

**Comment by zhongwen** [comment]
Related bugs: #952 #912

**Comment by mattjj** [comment]
This error is intentional, and unfortunately (AFAICT) necessary.

The underlying issue is that in Python there's no way to reliably determine a function's signature (it can be changed or hidden by decorators, `functools.partial`, etc.), which means there's no way to match named arguments to their positions (and vice-versa) given a calling set of args/kwargs. That in turn means static_argnums doesn't work with names. See #595 for a bit more info.

One solution is to use a wrapper like this:

```python
from functools import partial
from jax import jit

@partial(jit, static_argnums=(3,))
def _f(a, b, c, d):
  if d > 0:
    return a + b - c
  else:
    return d

def f(a, b, c, d):
  return _f(a, b, c, d)
```

Now callers of `f` can write `f(1, 2, 3, 4)` or `f(a=1, b=2, c=3, d=4)` or whatever calling convention they like; the single layer of indirection from `f` to `_f` means that Python standardizes the arguments for us. We use this trick inside JAX in a lot of places, like in random.py but also for every lax primitive, which is one reason why you see things like `def sin(x): return sin_p.bind(x)` in lax.py.

WDYT?

**Comment by shoyer** [comment]
> The underlying issue is that in Python there's no way to reliably determine a function's signature (it can be changed or hidden by decorators, `functools.partial`, etc.), which means there's no way to match named arguments to their positions (and vice-versa) given a calling set of args/kwargs. That in turn means static_argnums doesn't work with names.

This isn't quite true on Python 3, where `inspect.signature` can parse/bind arguments and even handles decorated functions properly (so long as they use `functools.wraps`).

Here's a (Python 3 only) version of `jit` using argument names instead of positions that  *should* be pretty robust:
```python
import inspect
import functools
import jax

def kwjit(fun, static_argnames=(), device_assignment=None):
  signature = inspect.signature(fun)
  for name, parameter in signature.parameters.items():
    if parameter.kind != inspect.Parameter.POSITIONAL_OR_KEYWORD:
      raise TypeError("kwjit can't handle positional only or keyword only args")
  for argname in static_argnames:
    if argname not in signature.parameters:
      raise TypeError(f"static argument {argname!r} not found in function "
                      f"signature: {signature}")

  static_argnums = [
      i for i, k in enumerate(signature.parameters) if k in static_argnames
  ]
  jitted = jax.jit(fun, static_argnums, device_assignment)

  @functools.wraps(fun)
  def wrapper(*args, **kwargs):
    bound_arguments = signature.bind(*args, **kwargs)
    return jitted(*bound_arguments.args)
  return wrapper
```
Example usage:
```
@functools.partial(kwjit, static_argnames=['d'])
def f(a, b, c, d):
  if d > 0:
    return a + b - c
  else:
    return d
```

This will *definitely* be slower than the existing `jit`, probably by a significant margin. `Signature.bind` does argument parsing in Python.

**Comment by romanngg** [comment]
Hello, has there been any progress on supporting `kwargs` in `vmap`? I noticed that they do work in `pmap`:

```
def f(a, *, b):
  return a + b

pmap(f)(np.ones((8, 1)), b=np.ones((8, 1)))
```
works, but 
```
vmap(f)(np.ones((8, 1)), b=np.ones((8, 1)))
```
gives
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-147-3b6e274f996f> in <module>()
----> 1 vmap(f)(np.ones((8, 10)), b=np.ones((8, 10)))

TypeError: batched_fun() got an unexpected keyword argument 'b'
```

**Comment by jakevdp** [comment]
The original issue has now been fixed for `jit`, and similar improvements for `vmap` and other transforms are tracked in #10614
