### ISSUE TITLE
Easy api for custom primitives and vjps

### ISSUE THREAD

**Issue by greydanus** [google/jax#116]
JAX supports custom primitives and vjps, just like Autograd did. Improvements:
1) add this to documentation
2) add a minimal example of this in the examples section
3) add a wrapper function if appropriate?

**Comment by jonasrauber** [comment]
Not sure if this is the right place: how can I define custom vmap primitives; in my case I am calling an external function that already supports batches and I want to vmap the code surrounding the call of this external primitive.

**Comment by mattjj** [comment]
@jonasrauber that question is from a while ago, but the short answer is that `custom_transforms` (as in `from jax import custom_transforms`) is for doing this. To be improved and documented...

**Comment by mattjj** [comment]
Just sketched out a custom VJPs API last night: https://gist.github.com/mattjj/2ba580930472e8e04c1759737268af92

The example there is trivial, and there's a bit more bookkeeping to be done to handle general code. But our initial thinking is that we can have a `defvjp` and a `defvjp_all`, to be used with `@custom_transforms`, where the former lets you specify a vjp function for each positional argument and the latter lets you specify a vjp for all arguments at once. (Maybe we can also provide a `defvjp_all_staged` if you want to compute some reduced residual information on the forward pass, rather than saving all the argument values.)

The funny bookkeeping in that gist is due to the fact that in JAX we usually don't specify VJPs (reverse-mode rules) directly, and instead only specify forward-mode rules; JAX generates reverse-mode autodiff through a composition of forward-mode, partial evaluation, and transposition transformations. But if you want to specify a VJP rule directly, that gist shows a trick to do it.

**Comment by mattjj** [comment]
Whoops, I didn't mean to close this in #818!
