### ISSUE TITLE
unexpected ppermute behavior for host-ragged arrays

### ISSUE THREAD

**Issue by namiller** [google/jax#11614]
When ppermute is invoked on arrays that are ragged in the non-pmap'd dimension (ie each host has a different length array) the results are surprising. It seems to take the shape from the destination host's current array and the values (padded with 0) from the source host.

On a system with 4 hosts and two local devices per host the following code will produce the following output:

```py
data = jp.arange(4*(jax.process_index()+1)).reshape(2, -1) * jax.process_index()
out = jax.pmap(ft.partial(jax.lax.ppermute, axis_name='host', perm=[(0, 4), (1, 5), (2, 6), (3, 7), (4, 0), (5, 1), (6, 2), (7, 3)]), 'host')(data)
print('result: ', jax.process_index(), data, out)
```

```
result:  0 [[0 0]
 [0 0]] [[ 0  2]
 [12 14]]

result:  1 [[0 1 2 3]
 [4 5 6 7]] [[ 0  3  6  9]
 [24 27 30 33]]

result:  2 [[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]] [[0 0 0 0 0 0]
 [0 0 0 0 0 0]]

result:  3 [[ 0  3  6  9 12 15 18 21]
 [24 27 30 33 36 39 42 45]] [[0 1 2 3 0 0 0 0]
 [4 5 6 7 0 0 0 0]]
```

**Comment by skye** [comment]
> arrays that are ragged in the non-pmap'd dimension (ie each host has a different length array)

This is undefined behavior in jax! See the first bullet point at the end of https://jax.readthedocs.io/en/latest/multi_process.html#running-multi-process-computations:

> Processes passing differently-shaped inputs to the same parallel function can cause hangs or incorrect return values. Differently-shaped inputs are safe so long as they result in identically-shaped per-device data shards across processes; e.g. passing in different leading batch sizes in order to run on different numbers of local devices per process is ok, but having each process pad its batch to a different max example length is not.

We have some work in-progress to raise an error message instead of silently doing the wrong thing, at least on TPU, but it's been stalled for a while and is blocked on a larger change that won't land for a few months. I'll see if we make this happen eventually, but for now, don't do this :)
