### ISSUE TITLE
x.at[idx].set(y) return different result (cpu vs gpu)

### ISSUE THREAD

**Issue by garam-kim1** [google/jax#11655]
### Test Code
```python
from jax import numpy as jnp

d = jnp.arange(3).reshape(3, 1)

d = d.at[((0, 1, 0), (0, 0, 0))].set(jnp.arange(3))
print(d)
```
### CPU result
```
[[2]
 [1]
 [2]]
```
### GPU result
```
[[0]
 [1]
 [2]]
```

**Comment by hawkinsp** [comment]
This is working as intended. https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html#jax.numpy.ndarray.at

Note:
"The order in which conflicting updates are applied is implementation-defined and may be nondeterministic (e.g., due to concurrency on some hardware platforms)."

Here you are applying two updates to index `(0, 0)`, and it is hardware-dependent which "wins".

Hope that helps!
