### ISSUE TITLE
Multithread pre-compile in CPU, execute in GPU or TPU?

### ISSUE THREAD

**Issue by yuanqing-wang** [google/jax#11788]
If I had a bunch of data points of various shapes and an abundance of CPU resources, would it be possible to precompile those ahead of time in this manner: https://github.com/google/jax/issues/9347 but in a multi-thread fashion presumably on CPU and execute them on GPU or TPU? 

```
import jax
import jax.numpy as jnp
fn = lambda x: x @ x @ x @ x @ x @ x # some very expensive function like NN
data = [jnp.ones((n, n)) for n in range(50)] # varies in shape
compiled = [jax.jit(fn).lower(x).compile() for x in data] # possible to multithread this?
```

**Comment by hawkinsp** [comment]
It should work to simply invoke your `jit` functions in parallel from separate threads with dummy inputs to warm up the cache. Does that resolve your problem?

**Comment by yuanqing-wang** [comment]
Would it be possible to `jit` on CPU in parallel and then execute on TPU/GPU?

**Comment by froystig** [comment]
> `compiled = [jax.jit(fn).lower(x).compile() for x in data] # possible to multithread this?`

Yes, you can take @hawkinsp's suggestion to warm the `jit` cache with many threads. Or you can do the same with the individual expressions in your list comprehension above. (To be precise, you will want to multithread the calls to `compile()`; there isn't much to gain from multithreading the `lower()` part due to Python GIL contention.)

> Would it be possible to `jit` on CPU in parallel and then execute on TPU/GPU?

Do you mean:

1. `jit` *for* CPU and execute on TPU/GPU? No, compiled executables are target-dependent.
2. `jit` in a Python process without a TPU/GPU device available, and later execute that in a separate Python process with a TPU/GPU? Not today, maybe some day. We'd need to be able to (a) cross-compile and (b) de/serialize executables, neither of which is entirely supported at present. Getting there will require work up and down the stack, including in the compiler and runtime on which JAX depends.
3. `jit` in a Python process with a TPU/GPU available, but have the work involved in compilation take place the CPU? Yes, that describes how things work today. The compiler runs on the host.

**Comment by yuanqing-wang** [comment]
Thanks @froystig ! I meant the third scenario. I'll simply try multithreading the `jit` operation for now. Thanks again!

**Comment by tewalds** [comment]
You're likely to have the greatest success with:
```
fn = jax.jit(fn)
compiled = {}
with futures.ThreadPoolExecutor() as pool:
  for x in data:
    lowered = fn.lower(x)
    compiled[x.shape] = pool.submit(lowered.compile)
compiled = {s: f.result() for s, f in compiled.items()}
```
Then choose the correct compiled version at use.

You want to lower in serial due to the GIL (and the inter-process compilation cache key uses the result of `lower` which uses a global counter), then compile in parallel since that doesn't depend on the GIL. Doing it with the normal jit calls currently is unlikely to compile in parallel since it grabs the device lock before the compile instead of only to execute the function on the device, serializing not only the compiles, but also blocking execution of already compiled versions while compiling.

**Comment by yuanqing-wang** [comment]
Thank you, @tewalds , this worked a treat. I was wondering if there is any other ways to further optimize this if we had endless number of CPUs (which I think is not an atypical computation infrastructure setting for many).

**Comment by tewalds** [comment]
Not that I know of. Parallelizing lowering is pointless in threads as long as the GIL still exists. I haven't tried parallelizing it in processes, but would be interested to know if you somehow get positive results there. 

I suspect there's room for improvement within jax to do one lowering pass that works for multiple shapes, or to cache the lowers between processes/machines. I suspect there's also room to generally speed up lowering by caching the results of a layer instead of lowering it repeatedly if it's instantiated in a loop, or similar. None of these are trivial for user level code though, and are more about speed than parallelism.
