### ISSUE TITLE
BUG: `jax.debug.breakpoint()` / jdb does not work in Jupyter lab.

### ISSUE THREAD

**Issue by HanGuo97** [google/jax#11880]
### Description

`jax.debug.breakpoint()` does not seem to work in Jupyter environment, though the same code works normally in a script setup.

### What jax/jaxlib version are you using?

0.3.16

### Which accelerator(s) are you using?

GPU

**Comment by sharadmv** [comment]
The CLI-based debugger reads from `sys.stdin` which is empty in a Jupyter notebook setting so the debugger immediately quits. To get around this, you have two options:

1. Use the `web-pdb` based backend. If you `pip install web-pdb` the `jax.debug.breakpoint()` will launch a web-based debugger automatically instead of the CLI one.
2. Fake `sys.stdin` to use `input()` instead (because `input()` works in Jupyter notebooks).

```python
class FakeStdin:
  def readline(self):
    return input()

@jax.jit
def f(x):
    jax.debug.breakpoint(backend="cli", stdin=FakeStdin())
    return jax.numpy.sin(x)
```

The longer term solution would be to build a custom UI for jupyter like we've done for Colab but this should do for the meantime.

Hope that helps!

**Comment by HanGuo97** [comment]
These are super useful -- thanks!
