### ISSUE TITLE
Can’t import both jax and tensorflow (causes kernel restart)

### ISSUE THREAD

**Issue by zeevikal** [google/jax#120]
hi,
after importing those libs:
```
import pandas as pd
import jax.numpy as np
import tensorflow as tf
```

I tried to run this cell and the results:

![image](https://user-images.githubusercontent.com/22215498/50051576-bdb5d300-011d-11e9-8b34-68eef24b0ecc.png)

**Comment by mattjj** [comment]
Currently we can’t import both jax and tensorflow. I’m not sure the exact reason but it has something to do with how we build XLA. Definitely a bug we need to fix, but for now there’s no workaround that I know of.

**Comment by mattjj** [comment]
By the way, unless you have additional info to suggest otherwise, I think this is not an OOM. I’ll revise the issue title to reflect my best understanding (that this is about importing both jax and tf). Let me know if we need to change it back. 

Thanks for bringing this up!

**Comment by hawkinsp** [comment]
Just to follow up: I finally had time to look at this. It turns out that the jaxlib (i.e. XLA) Python extension depends on a few small pieces of TensorFlow (mostly some C++ support libraries). If both the jaxlib and tensorflow Python extensions export the same symbols, a crash occurs. The fix is to restrict the set of symbols we export from the XLA python extension; there's no good reason for the XLA python extension to also export bits of TF.

I'll push a fix shortly.

**Comment by mattjj** [comment]
FYI @rsepassi

**Comment by hawkinsp** [comment]
PR #265 checked in a fix to jaxlib that should fix this problem.

Note that for the moment you'll either need to rebuild jaxlib from source, or wait until we build and push new Jaxlib wheels.

Hope that helps!

**Comment by rsepassi** [comment]
awesome!
