### ISSUE TITLE
jax.scipy.stats.logistic don't implement location and scale

### ISSUE THREAD

**Issue by langosco** [google/jax#12141]
### Description

The docstring of `jax.scipy.stats.norm.cdf` says it takes keyword arguments `loc` and `scale`, but running
```
jax.scipy.stats.logistic.cdf(1, loc=1)
```
raises a `TypeError: cdf() got an unexpected keyword argument 'loc'`. 

### What jax/jaxlib version are you using?

jax v0.3.16, jaxlib v0.3.15

### Which accelerator(s) are you using?

CPU

### Additional System Info

Python 3.8.10, Ubuntu

**Comment by jakevdp** [comment]
Thanks for the report – the reason the parameter is listed but not implemented is because the docsttring is copied from `scipy.stats` (you'll notice *"Original docstring below"* in the [doc page](https://jax.readthedocs.io/en/latest/_autosummary/jax.scipy.stats.logistic.cdf.html))

We'll leave this open as a feature request - if it's something you want to contribute, feel free to open a pull request!

**Comment by rajasekharporeddy** [comment]
Hi @langosco, @jakevdp 

Since the PR raised by @b0nce was merged, the issue has been resolved. 

The above mentioned code works without any error.

```
>>> jax.scipy.stats.logistic.cdf(1, loc=1)
Array(0.5, dtype=float32, weak_type=True)
```

Thank you
