### ISSUE TITLE
Document async dispatch in the README

### ISSUE THREAD

**Issue by hgt312** [google/jax#1219]
As title.

I use jax on my macbook.
I test the runtime of `numpy.add` and `numpy.multiply` use this code in notebook:
```python
from jax import numpy, jit
import time

a = numpy.ones((1000000,)) * 3
b = numpy.ones((1000000,)) * 5
f = jit(numpy.multiply, [0, 1])

for _ in range(10):   
    start = time.time()
    f(a, b)
    print(time.time() - start)
```
The result is:
```
0.0077419281005859375
0.0002968311309814453
0.00039196014404296875
0.0002570152282714844
0.0002429485321044922
0.00022792816162109375
0.0002338886260986328
0.0002510547637939453
0.0002651214599609375
0.0002579689025878906
```
It is much more faster than numpy, I want to know how it achieve this.

**Comment by lumip** [comment]
You really seem to have 2 questions here, which are:
1) Why is the first function call slower than the following calls?
2) Why are those faster than numpy?

I think I can briefly offer some insights on the first here but I can't claim to have in-depth knowledge of everything going on in JAX. Maybe some of the maintainers can offer a more thorough explanation if required (or in case I got some details wrong):

The reason is in the line `f = jit(numpy.multiply, [0, 1])`.
`jit` marks the function passed in to be just in-time compiled with XLA ("XLA (Accelerated Linear Algebra) is a domain-specific compiler for linear algebra[..]." [XLA page](https://www.tensorflow.org/xla)). Your `f` is essentially a wrapper/decorator around `numpy.multiply` that hides quite a pack of awesomness (smart abstraction layers and indirections used for recording what happens in the inner function, which is a simple `numpy.multiply`here but can really be almost anything). The first call you make to it causes that compilation to happen (which is why you have some initial overhead there) but all subsequent calls execute the compiled version of the function, which is really fast. 

As for the second question: The faster-than-numpy part could simply mean that the XLA/Tensorflow implementation is better optimized than numpy, but maybe there's also some more overhead when invoking numpy functions that we don't get with the jit-compiled version in jax.. that I can't say for certain.

Maybe check out the [How it works](https://github.com/google/jax#how-it-works) section of the Readme and the [quickstart guide](https://colab.research.google.com/github/google/jax/blob/master/notebooks/quickstart.ipynb), which also offer some insights on this.

**Comment by clemisch** [comment]
One general caveat considering benchmarking jax or XLA which seems to apply here:

The computation on `DeviceArrays` is asynchronous and returns before the actual numerical results have been computed. This makes functions seem incredibly fast in benchmarks, but the actual computation takes longer. 

You can circumvent this by calling the method `.block_until_ready()` on the output `DeviceArray`. As the name suggests, this blocks until the computation is really finished.

```python
from jax import numpy, jit
import time

a = numpy.ones((1000000,)) * 3
b = numpy.ones((1000000,)) * 5
f = jit(numpy.multiply, [0, 1])

for _ in range(10):   
    start = time.time()
    f(a, b).block_until_ready()   # block!
    print(time.time() - start)
```

**Comment by clemisch** [comment]
Although this is not about your jax questions: I thing using `time.time()` calls is not best practice for benchmarking as they have some overhead themselves. If you're using IPython, have a look at the `%timeit` macro. Otherwise I think you can use the `timeit` package manually.

**Comment by mattjj** [comment]
Thanks for the great discussion!

Check out [the docs on async dispatch](https://jax.readthedocs.io/en/latest/async_dispatch.html). As @clemisch pointed out, it's not that JAX is actually faster than NumPy (it's probably slower to compute the result, since NumPy is _super_ fast for what it does), but it's just not waiting for the result to be computed to return control back to Python.

Async execution is really important for keeping accelerators like GPUs crunching away rather than waiting for Python.

@lumip your comments are correct too, but even XLA probably can't speed up a simple operation like multiply. The benefits over raw NumPy only kick in when you compile programs that are composed of many operations, since that lets XLA do things like optimize the memory layout and fuse operations together to save reads/writes.

**Comment by hgt312** [comment]
Thanks for the answers!
I have guessed that it may be async. But I didn't look the doc, just read the README, seems that it should be updated?
Besides, is there global settings to change the behavior, MXNet can switch to use native engine by editing environment variable.

**Comment by mattjj** [comment]
I agree about adding a description of async behavior to the README.

About switching behavior, that's certainly something we could consider if there are users (like you!) who want it. If so, can you open a feature request with a detailed description of exactly what you want?

**Comment by hgt312** [comment]
I run the code from @clemisch on mbp.
```python
from jax import numpy, jit
import time

a = numpy.ones((1000000,)) * 3
b = numpy.ones((1000000,)) * 5
f = jit(numpy.multiply, [0, 1])

times = []
for _ in range(10):
    start = time.time()
    res = f(a, b)
    res.block_until_ready()   # block!
    times.append(time.time() - start)
[print(t) for t in times]
print("Avg:", sum(times) / 10)
```
The result is still strange.
```
0.020164966583251953
0.00022292137145996094
0.00013589859008789062
0.00019598007202148438
0.00032806396484375
0.0001862049102783203
0.00015163421630859375
0.0002200603485107422
0.0001552104949951172
0.0001308917999267578
Avg: 0.002189183235168457
```
And I try it on a gpu server, it's strange, too. 

I also try this, result seems always strange, but after the first loop, it is not as fast as above.
```python
from jax import numpy, jit
import time

a = numpy.ones((1000000,)) * 3
b = numpy.ones((1000000,)) * 5
f = jit(numpy.multiply, [0, 1])

times = []
for _ in range(10):
    start = time.time()
    res = f(a, b)
    res.block_until_ready()   # block!
    times.append(time.time() - start)
    a = a + 1  # add 1!
[print(t) for t in times]
print("Avg:", sum(times) / 10)
```

```
0.022282123565673828
0.0048656463623046875
0.005548954010009766
0.00591588020324707
0.006352901458740234
0.005952119827270508
0.005464076995849609
0.00551295280456543
0.005275249481201172
0.005731105804443359
Avg: 0.007290101051330567
```
I am confused for the results.

**Comment by hgt312** [comment]
@clemisch 
Strange means that the second and following is too faster then the first run, and it is much more faster then numpy.
If every time I give it different inputs, it is just a bit slower than numpy.
```python
from jax import numpy, jit
from jax import random
import time

f = jit(numpy.multiply, [0, 1])
key = random.PRNGKey(0)
times = []
for _ in range(10):
    a = random.uniform(key, (1000000,))
    a.block_until_ready()
    b = random.uniform(key, (1000000,))
    b.block_until_ready()
    start = time.time()
    res = f(a, b)
    res.block_until_ready()   # block!
    times.append(time.time() - start)
[print(t) for t in times]
print("Avg:", sum(times) / 10)
```
result (on my Mac):
```
0.023547887802124023
0.004973173141479492
0.00486302375793457
0.004798173904418945
0.0046329498291015625
0.004909038543701172
0.0048940181732177734
0.004618167877197266
0.0047550201416015625
0.00450897216796875
Avg: 0.0066500425338745115
```
Ignore the first run, the result has huge difference.
