### ISSUE TITLE
issubclass(jnp.float32, jnp.floating) does not work

### ISSUE THREAD

**Issue by ppwwyyxx** [google/jax#12289]
### Description

```
In [26]: issubclass(np.float32, np.floating)
Out[26]: True
In [27]: issubclass(jnp.float32, jnp.floating)
Out[27]: False
```

I expect the behavior to be consistent with numpy.

### What jax/jaxlib version are you using?

head

**Comment by jakevdp** [comment]
I think this is intended-ish. One of the main differences between numpy and JAX is that numpy has both scalar types (such as `np.float32(0)`) and array types (such as `np.array(0, dtype=np.float32)`). In JAX the decision was made early on to not have dedicated scalar types, but rather represent scalars as rank-zero arrays. Thus there is no such thing as a `jax.numpy.float32` object, and `jnp.float32` is just a convenience function to create a rank-0 array:
```python
In [1]: import jax.numpy as jnp

In [2]: x = jnp.float32(0)                                                                                                                                                                                                                                                   

In [3]: type(x)                                                                                                                                                                                                                                                              
Out[3]: jaxlib.xla_extension.DeviceArray
```
That's the main reason that `float32` and other scalar creation objects do not behave like numpy's scalar types.

A common pattern that we use in JAX instead is checking whether something is a subdtype:
```python
In [4]: jnp.issubdtype(jnp.float32, jnp.floating)  
OUt[4]: True
```
Would that work for your purposes?

**Comment by hawkinsp** [comment]
I had a specific request from other users that there needs to be a superclass to `jnp.float32` etc for a serialization use case. You want a superclass for `jnp.float32` just for testing whether an object is a thing like `jnp.float32`.

**Comment by ppwwyyxx** [comment]
Thanks! `jnp.issubdtype` works for my use case.

**Comment by jakevdp** [comment]
@hawkinsp we could probably make this happen by changing this: https://github.com/google/jax/blob/09a3796d5063940dc5e2402dea4e1bd89ffadfc1/jax/_src/numpy/lax_numpy.py#L170-L172

To something like this:
```python
 def _make_scalar_type(np_scalar_type): 
   meta = _ScalarMeta(np_scalar_type.__name__, (np_scalar_type.__mro__[1],), 
                      {"dtype": np.dtype(np_scalar_type)}) 
```
This makes it so that `issubclass(jnp.float32, jnp.floating)` returns True, but I'm not sure whether it might have other side-effects...

**Comment by jakevdp** [comment]
So I looked into this... it's not going to be straightforward to fix. If we do the `__bases__` solution, then `np.dtype(jnp.float32)` raises a warning because it's a non-recognized generic type. I tried deriving `jnp.float32` from `np.float32`, but this causes issues because then `jnp.float32` is a strict subdtype of `np.float32`, so for example `issubdtype(jnp.float32, np.float32)` returns False which breaks a bunch of user code. Additionally, we have workarounds for strange corner case behavior in `np.issubdtype` that no longer operate correctly (https://github.com/google/jax/blob/4746a39e59fc70caba161b00336b86687254df89/jax/_src/dtypes.py#L248-L253) and it's not obvious to me what the fix would be if `jnp.float32` derives from `np.generic`.

As for the idea of making `issubclass(_, jnp.floating)` raise an error... that instancecheck override has to take place on the metaclass of the second argument, so for example we couldn't cause it to raise an error if the second argument were `np.floating`, and if we define a custom `jnp.floating` then numpy scalar types would no longer be subclasses of it, so things like `issubclass(np.float32, jnp.floating)` would return False.

All said, I think doing *anything* here is opening up a huge can of worms that will have subtle side-effects and ramifications for a lot of common usages; my judgment is that keeping the current behavior is probably best.

I'm going to close this issue – thanks for raising it!
