### ISSUE TITLE
Custom PytreeNode constructors were given object() when used with vmap.

### ISSUE THREAD

**Issue by ppwwyyxx** [google/jax#12319]
### Description

```python
from jax.tree_util import register_pytree_node_class
import jax.numpy as jnp
from jax.experimental import checkify
import jax

@register_pytree_node_class
class Boxes:
  def __init__(self, arr: jnp.ndarray):
    self.arr = arr
    assert arr.ndim > 1 and arr.shape[-1] == 4
  
  def area(self) -> jnp.ndarray:
    return (self.arr[..., 2] - self.arr[..., 0]) * (self.arr[..., 3] - self.arr[..., 1])

  def tree_flatten(self):
    return ((self.arr,), None)
  
  @classmethod
  def tree_unflatten(cls, _, children):
    return cls(children[0])

def func(x: Boxes):
  return x.area() + 3

jax.vmap(func)(Boxes(jnp.ones((2, 2, 4))))
```

The above code throws:
```
  File "/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/jax/_src/api.py", line 1579, in vmap_f
    in_axes_flat = flatten_axes("vmap in_axes", in_tree, (in_axes, 0), kws=True)
  File "/jax/_src/api_util.py", line 391, in flatten_axes
    dummy = tree_unflatten(treedef, [object()] * treedef.num_leaves)
  File "/jax/_src/tree_util.py", line 77, in tree_unflatten
    return treedef.unflatten(leaves)
  File "/.../boxes.py", line 109, in tree_unflatten
    return cls(children[0])
  File "/.../boxes.py", line 33, in __init__
    assert arr.ndim > 1 and arr.shape[-1] == 4
jax._src.traceback_util.UnfilteredStackTrace: AttributeError: 'object' object has no attribute 'ndim'
```

If I don't do the assertion, the vmap works as expected.

JAX is constructing the pytree with dummy `object()` - that might not be a good idea?
Or, should I avoid assuming elements must be jax arrays (it seems like a reasonable assumption but indeed I won't be able to do things like `tree_map(lambda x: x.shape)` ) ?

### What jax/jaxlib version are you using?

latest

**Comment by patrick-kidger** [comment]
As part of its internal manipulations, JAX -- and some user-created libraries -- may sometimes replace a PyTree's leaves with `object()`s (or indeed any other object).

This is intended behaviour; it's actually quite powerful and allows for quite a lot of tree manipulation routines.

The fix here is to change your `tree_unflatten` method, so that you don't call `__init__`. Instead aim to just call `__setattr__` and assign the attributes that have been passed.

---

To give a complete worked example take a look at how [Equinox](https://github.com/patrick-kidger/equinox) handles this:

https://github.com/patrick-kidger/equinox/blob/5c6a43fa7ff6fc894f5e3e6419b3c0fdcae04bab/equinox/module.py#L264

(The context here is that `class MyClass(equinox.Module): ...` automatically registers your class as a custom pytree node, so that subclassing-a-module is the syntax used to create models / neural networks / etc.)

**Comment by jakevdp** [comment]
We have a section in the docs mentioning this: https://jax.readthedocs.io/en/latest/pytrees.html#custom-pytrees-and-initialization

You need to allow this sort of sentinel initialization in your pytrees if you want them to be compatible with JAX transforms

**Comment by ppwwyyxx** [comment]
Thanks this is very helpful! Closing
