### ISSUE TITLE
implicit uint64 array creation doesn't work like numpy

### ISSUE THREAD

**Issue by mattbarrett98** [google/jax#12375]
### Description

In numpy once the integers of an array exceed what can be represented by int64, arrays of type uint64 are created (which seems intuitive):
```
>>> import numpy as np
>>> np.array(9223372036854775808).dtype
dtype('uint64')
```

However, JAX will just throw an error in this case:
```
>>> import jax
>>> import jax.numpy as jnp
>>> jax.config.update("jax_enable_x64", True)
>>> y = jnp.array(9223372036854775808)
OverflowError: Python int 9223372036854775808 too large to convert to int64
```

**Comment by jakevdp** [comment]
Hi - thanks for the question. This is deliberate behavior: Jax departs from numpy and avoids value-dependent dtypes in a number of contexts because it can lead to confusing behavior. If you want to use unsigned dtypes, you should create them explicitly by passing a dtype argument to the array constructor.

**Comment by mattbarrett98** [comment]
ah yes, it makes sense that value checking wouldn't work well with the jit, thanks anyway.
