### ISSUE TITLE
jax.numpy.round causes crush

### ISSUE THREAD

**Issue by flyingshan** [google/jax#12426]
### Description

The log is as below:

2022-09-20 11:05:32.229988: F external/org_tensorflow/tensorflow/core/platform/statusor.cc:33] Attempting to fetch value instead of handling error UNIMPLEMENTED: Unimplemented MHLO -> HloOpcode: %113 = mhlo.round_nearest_even %112 : tensor<131072x8xf32

I tried to locate the problem and figured that the jax.numpy.round caused this problem, which is from:
mlp_features_ = np.round(mlp_features*255).astype(np.uint8)

I use jax==0.3.17 and jaxlib==0.3.14, when i downgrade them into jax==0.3.14 and jaxlib==0.3.10, the problem disappeared.
why did it happen?

### What jax/jaxlib version are you using?

jax==0.3.17 and jaxlib==0.3.14

### Which accelerator(s) are you using?

GPU, V100*8

### Additional System Info

LINUX

**Comment by mattjj** [comment]
Thanks for the report!

Can you share a self-contained runnable reproducer?

**Comment by hawkinsp** [comment]
I'm pretty sure this was a version incompatibility between jax 0.3.17 and jaxlib 0.3.14. If you use jaxlib 0.3.15, the problem should go away.

Normally we would add a workaround to `jax` to fix this, but the minimum `jaxlib` for the `jax` at head is 0.3.15, so the problem is already fixed.

Hope that helps!
