### ISSUE TITLE
Bug in C++ pytree implementation

### ISSUE THREAD

**Issue by shoyer** [google/jax#1257]
I haven't tracked it down yet, but the first commit in https://github.com/google/jax/pull/1256 fails with a core dump on OS X.

I'm guessing this is due to some missing cleanup step when a Python exception is raised.

**Comment by hawkinsp** [comment]
I think this is actually a pybind11 bug. The issue is that:
a) we are calling a pybind11-wrapped C++ method, but no overload matches
b) pybind11 calls `pybind11::repr()` to include the value in the error that it prints
c) the implementation of `repr()` raises a Python exception, which is converted into a C++ exception that pybind11 fails to catch.

I'll send a PR to upstream pybind11.

**Comment by shoyer** [comment]
Thanks for tracking this down!

**Comment by hawkinsp** [comment]
I believe https://github.com/pybind/pybind11/pull/2389 fixed this. (They ignored my PR. Sigh.)
