### ISSUE TITLE
Numerical difference before and after `jax_disable_jit`

### ISSUE THREAD

**Issue by modanesh** [google/jax#12833]
### Description

I have a code snippet that reads an image from file, normalizes it, and converts it to `jax.numpy` array. At the end, there's this line: `jax.config.update('jax_disable_jit', True)`. Once it reaches this line, the value of the image array changes. Although this numerical difference is small, but it is significantly important. You may take a look at the code in this Gist to reproduce the issue: [https://gist.github.com/modanesh/2c9c40d183c04c448c1c44a557b17c32](https://gist.github.com/modanesh/2c9c40d183c04c448c1c44a557b17c32)

### What jax/jaxlib version are you using?

jax v0.3.23, jaxlib v0.3.22

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.8, MacOS 12.6 (Intel)

**Comment by jakevdp** [comment]
Hi, thanks for the question and for the complete reproduction! This is working as intended (See [FAQ: JIT Changes the numerics of my function](https://jax.readthedocs.io/en/latest/faq.html#jit-changes-the-exact-numerics-of-outputs). The results you are seeing are equal to within typical floating-point roundoff error, and the difference comes from the fact that JIT may cause operations do be done in a different order.

To see that this is not just a JAX issue, observe the following, where we use numpy's mean over the array and its reverse. This computes the same value in a different order, and gets a different result:
```python
np_img = np.array(img)
fwd_mean = np.mean(np_img)
rev_mean = np.mean(np_img[::-1, ::-1])
assert fwd_mean == rev_mean, f"values are different by: {fwd_mean - rev_mean}"
# AssertionError: values are different by: -1.4901161193847656e-08
```
This roundoff error is typical of float32 values, which have 23 bits of mantissa, meaning that computations are accurate to roughly 1 part in $2^{23}$, which is approximately $10^{-7}$. If your results are sensitive to computational precision at that level, you might consider using 64-bit computations rather than 32-bit computions; see [Sharp Bits: 64-bit Precision](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#double-64bit-precision).

**Comment by modanesh** [comment]
Thanks for you thorough response.
