### ISSUE TITLE
`jacfwd(jacrev(f))(x)` not return the same results as `jacfwd(jacfwd(f))(x)` or `jacrev(jacrev(f))(x)`

### ISSUE THREAD

**Issue by nasyxx** [google/jax#12984]
### Description

`jacfwd(jacrev(f))(x)` not return the same results as `jacfwd(jacfwd(f))(x)` or `jacrev(jacrev(f))(x)`.

They should be the same value but...

And it's weird that this problem only occurs with the rev and then fwd.  See the examples and results below:

```python
import jax
import jax.numpy as jnp

def u(x, y):
    return -(1/(2 * jnp.pi ** 2)) * jnp.sin(x * jnp.pi) * jnp.sin(y * jnp.pi)

def u_xx(x, y):
    return jnp.sin(x * jnp.pi) * jnp.sin(y * jnp.pi) / 2

r1, r2 = u(.7, .7), u_xx(.7, .7)
print(f"u: {r1}, u_xx: {r2}")

rg = jax.grad(jax.grad(u))(.7, .7)
print(f"grad: {rg}")

rff = jax.jacfwd(jax.jacfwd(u))(.7, .7)
rrr = jax.jacrev(jax.jacrev(u))(.7, .7)
rrf = jax.jacrev(jax.jacfwd(u))(.7, .7)

rfr = jax.jacfwd(jax.jacrev(u))(.7, .7)  # not the same as before
rh = jax.hessian(u)(.7, .7)

print(f"ff: {rff}", f"rr: {rrr}",  f"rf: {rrf}", f"fr: {rfr}", f"hessian: {rh}", sep="\n")
```

<img width="917" alt="Screenshot 2022-10-26 at 12 48 29 AM" src="https://user-images.githubusercontent.com/5007613/197945004-b8fda40c-4be8-4f4e-afcf-c1c347deb2ca.png">

### What jax/jaxlib version are you using?

jax v0.3.23; jaxlib v0.3.22

### Which accelerator(s) are you using?

CPU

### Additional system info

3.10, macOS.

**Comment by hawkinsp** [comment]
It's not reasonable to expect exact equality of two floating point calculations. Floating point numbers are approximations, and different orders of operations can lead to results that differ, even if the results should be equal mathematically.

Here the different results are 1 [ULP](https://en.wikipedia.org/wiki/Unit_in_the_last_place) apart:

```
In [9]: rfr
Out[9]: DeviceArray(0.3272542357444763, dtype=float32, weak_type=True)

In [10]: rrf
Out[10]: DeviceArray(0.3272542655467987, dtype=float32, weak_type=True)

In [11]: jnp.nextafter(rfr, jnp.float32(1.0))
Out[11]: DeviceArray(0.3272542655467987, dtype=float32)
```

1 ULP of difference is as much precision as it is reasonable to expect from a floating point calculation. If you need more precision, you could compute in double precision rather than float (see https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#double-64bit-precision ).

Hope that helps!
