### ISSUE TITLE
Sparse matrix multiplication gives incorrect result

### ISSUE THREAD

**Issue by yhtang** [google/jax#13038]
### Description

The following 2x2 matmul would produce different results for dense and sparse matrices on A100/H100 GPUs (but not V100):
```
import numpy as np
import jax
import jaxlib
import jax.numpy as jnp
from jax.experimental import sparse
k = jax.random.PRNGKey(0)
A = jax.random.normal(k, (2, 2))
A_sp = sparse.BCOO.fromdense(A)
P = A @ A
P_sp = A_sp @ A_sp
print(P)
print(P_sp.todense())
print(jnp.allclose(P, P_sp.todense(), 1e-5, 1e-5))
```
Output:
```
[[ 3.042789 -0.967562]
 [ 0.435591  0.029328]]
[[ 3.041592 -0.967197]
 [ 0.435483  0.029472]]
False
```

Tested both CUDA 11.8 and 11.4 and got the same result. I also tested JAX 0.3.21 and 0.3.23 and both give the same result.

### What jax/jaxlib version are you using?

jax v0.3.23, jaxlib v0.3.22

### Which accelerator(s) are you using?

V100, A100, H100

### Additional system info

CUDA 11.8/11.4

@rsl18 @nouiz @mjsML

**Comment by jakevdp** [comment]
Thanks for the report - we're looking into this.

One question though: in the example you gave, it looks like the result is not incorrect, but rather has rounding error larger than you expected. Is that true of the behavior you're seeing in general?

One other question. Could you please re-run your example, but set `bcoo_cusparse_lowering` to False? i.e. add this at the top of the script:
```python
from jax import config
config.update('jax_bcoo_cusparse_lowering', False)
```
This will tell the matmul operation to compute the result via XLA rather than via cuSPARSE. Does this change the behavior?

Thanks!

**Comment by yhtang** [comment]
> One question: in the example you gave, it looks like the result is not incorrect, but rather has rounding error larger than you expected. Is that true of the behavior you're seeing in general, or are you seeing wildly incorrect results?

You are right, it does look like large rounding errors on the order of 1e-3~1e-4.

> One more thing to check: could you please re-run your example, but set bcoo_cusparse_lowering to False?

Will do and report back shortly.

**Comment by almogsegal** [comment]
Hi @jakevdp, setting bcoo_cusparse_lowering to False doesn't change the behavior. I did some debugging and noticed that cuSPARSE isn't being called. The path that is being taken is:
```
bcoo_dot_general -> _bcoo_spdot_general -> _bcoo_spdot_general_impl -> _bcoo_spdot_general_abstract_eval -> _bcoo_spdot_general_unbatched
```
Can you take a look? Thanks!

**Comment by tlu7** [comment]
May i know the cuda version that you are using?

**Comment by almogsegal** [comment]
CUDA 11.8.

**Comment by jakevdp** [comment]
OK, so I realized I was going down the wrong path here because this is sparse-sparse matmul, which doesn't have any CUDA lowerings yet (so `bcoo_cusparse_lowerings` is not relevant). This is implemented directly in XLA.

I tried running the example on a Colab CPU and GPU (T4 chip), both on JAX v0.3.23, and the outputs are as expected.

So this must have something to do with how the operation is expressed by XLA on the particular GPU chips you're working with.

**Comment by jakevdp** [comment]
I think the issue here is related to the one here: https://github.com/google/jax/issues/12008

Namely, on A100 (and possibly also H100?) XLA matrix multiplication defaults to lower precision. You can use higher-precision matmuls by doing something like this:
```python
with jax.default_matmul_precision("float32"):
  P_sp = A_sp @ A_sp
```
Does that fix the issue you're seeing?

**Comment by almogsegal** [comment]
Unfortunately, it doesn't fix the issue.
Is there any specific reason for not using cusparse here? I also saw in https://github.com/google/jax/issues/10255 that cuspase is not being used.

**Comment by jakevdp** [comment]
We're in the process of expanding the cuSparse lowerings for sparse operations, and haven't tackled sparse-sparse yet. That said, it's not clear to me that lowering to cusparse will work well in the sparse-sparse case, primarily because the output of this operation in cusparse has buffer sizes that are dependent on the content of the input, and JAX does not support this kind of dynamic shape in computations.

The #10255 issue is another aspect of this: cusparse has much more stringent requirements on its inputs than JAX's general BCOO format requires. For this reason, it's not always possible to lower operations to cusparse without expensive pre-processing of the inputs that generally negates any speed improvement that might come from lowering to cusparse.

**Comment by jakevdp** [comment]
Closing, because I don't think we're going to do further work on sparse-sparse matmul.
