### ISSUE TITLE
Typo in tutorial for custom derivative rules

### ISSUE THREAD

**Issue by btalamini** [google/jax#13048]
### Description

In the tutorial pages for custom derivatives rule in [this section](https://jax.readthedocs.io/en/latest/notebooks/Custom_derivative_rules_for_Python_code.html#use-jax-custom-vjp-to-define-custom-reverse-mode-only-rules), the second example looks like this:

```python
from jax import custom_vjp

@custom_vjp
def f(x, y):
  return jnp.sin(x) * y

def f_fwd(x, y):
  return f(x, y), (jnp.cos(x), jnp.sin(x), y)

def f_bwd(res, g):
  cos_x, sin_x, y = res
  return (cos_x * g * y, -sin_x * g)

f.defvjp(f_fwd, f_bwd)
```

I think there is an unwanted negation on the second return value of `f_bwd`. That is, I think it should read `return (cos_x * g * y, sin_x * g)`. The function `f` is only differentiated with respect to the first variable in the code that follows, so it doesn't affect the tutorial text.

**Comment by mattjj** [comment]
Thanks for noticing this, and explaining so clearly!

I think this may have been intentional originally, meant to add some difference between the custom_vjp rule and the standard derivative for this function (otherwise, why make a custom_vjp at all?). But it's confusing, and I agree we should just remove the negation.

Want to send a PR removing it?
