### ISSUE TITLE
Inconsistency with numpy on `astype` from float to uint32

### ISSUE THREAD

**Issue by j2kun** [google/jax#13101]
### Description

Minor bug in the jax.numpy API: astype from float32 to uint32 doesn't work the same as numpy

```
>>> np.array([-20, -25, -23, -12,  10], dtype=np.float32).astype(np.uint32)
array([4294967276, 4294967271, 4294967273, 4294967284,         10],
      dtype=uint32)
```

```
>>> jnp.array([-20, -25, -23, -12,  10], dtype=jnp.float32).astype(jnp.uint32)
DeviceArray([ 0,  0,  0,  0, 10], dtype=uint32)
```

However, the jax API works if you first convert to `jnp.int32` before converting to `jnp.uint32`

```
>>> jnp.array([-20, -25, -23, -12,  10], dtype=jnp.float32).astype(jnp.int32).astype(jnp.uint32)
DeviceArray([4294967276, 4294967271, 4294967273, 4294967284,         10],            dtype=uint32)
```

Seems to suggest a bug in the type conversion to uint32 specifically.

### What jax/jaxlib version are you using?

HEAD

### Which accelerator(s) are you using?

CPU

**Comment by jakevdp** [comment]
Thanks for the report – this is expected behavior, discussed in the [Sharp Bits](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#miscellaneous-divergences-from-numpy). Namely, in cases of incompatible typecasting, XLA and numpy make different choices regarding what to use for the fill value. The workaround is to not rely on specific behavior for incompatible typecasts.
