### ISSUE TITLE
Add support for RNNs using library calls

### ISSUE THREAD

**Issue by hawkinsp** [google/jax#13111]
XLA isn't going to generate great code for RNNs, particularly on GPUs.

We could teach XLA how to generate better RNN code, but n GPU, we should probably just add support for calling the optimized RNN (in particular LSTM) implementation in CuDNN/HipDNN.

**Comment by cgarciae** [comment]
We are trying to improve RNN support in Flax (see google/flax#2585), would be interesting to know what design decisions are taken here. In particular, would this imply that CuDNN would take care of the "scan loop" for specialized layers?

**Comment by zhangqiaorjc** [comment]
https://github.com/google/jax/pull/13319 has merged.

Also, here's an example LSTM module in Flax

```
class CudnnLSTM(nn.Module):
  input_size: int
  hidden_size: int
  num_layers: int
  dropout_rate: float = 0.0
  bidirectional: bool = False

  def setup(self):
    self.w = self.param(
        'lstm_weights',
        rnn.init_lstm_weight,
        self.input_size,
        self.hidden_size,
        self.num_layers,
        self.bidirectional,
    )

  def __call__(
      self,
      inputs: Array,
      input_paddings: Array,
      initial_states: Optional[Sequence[StateType]] = None,
      deterministic: bool = False,
  ) -> Tuple[Array, Sequence[StateType]]:
    # TODO(zhangqiaorjc): initial_states
    assert initial_states is None
    num_directions = 2 if self.bidirectional else 1
    batch_size = inputs.shape[0]
    dropout = 0.0 if deterministic else self.dropout_rate
    h_0 = jnp.zeros(
        (num_directions * self.num_layers, batch_size, self.hidden_size),
        jnp.float32,
    )
    c_0 = jnp.zeros(
        (num_directions * self.num_layers, batch_size, self.hidden_size),
        jnp.float32,
    )
    seq_lengths = jnp.sum(input_paddings, axis=-1, dtype=jnp.int32)
    y, _, _ = rnn.lstm(
        inputs,
        h_0,
        c_0,
        self.w,
        seq_lengths,
        self.input_size,
        self.hidden_size,
        self.num_layers,
        dropout,
        self.bidirectional,
    )
    return y
```

Example benchmark

```
class LstmBenchmark(absltest.TestCase):

  def test_lstm(self):
    batch_size = 32
    input_size = 512
    hidden_size = 256
    num_layers = 1
    dropout = 0.000000
    bidirectional = True
    seq_len = 500
    x = jnp.ones((batch_size, seq_len, input_size), dtype=jnp.float32)
    padding = jnp.zeros((batch_size, seq_len), dtype=jnp.float32)

    k = jax.random.PRNGKey(0)
    m1 = model.LSTM(
        hidden_size=hidden_size,
        bidirectional=bidirectional,
        num_layers=num_layers,
    )
    vars1 = m1.init(k, x, padding)
    m2 = cudnn_flax_model.CudnnLSTM(
        input_size=input_size,
        hidden_size=hidden_size,
        bidirectional=bidirectional,
        num_layers=num_layers,
    )
    vars2 = m2.init(k, x, padding)
    print('## Flax vars1 = ', jax.tree_map(lambda x: x.shape, vars1))
    print('## Cudnn vars2 = ', jax.tree_map(lambda x: x.shape, vars2))

    def loss_fn(m, w, x, padding):
      y = m.apply(w, x, padding)
      return jnp.sum(y)

    def step_fn(m, w, x, padding):
      bound_m = functools.partial(loss_fn, m)
      dw = jax.grad(bound_m)(w, x, padding)
      w = jax.tree_map(lambda v, dv: v - dv, w, dw)
      return w

    step_fn1 = jax.jit(functools.partial(step_fn, m1))
    step_fn2 = jax.jit(functools.partial(step_fn, m2))

    _ = step_fn1(vars1, x, padding)
    _ = step_fn2(vars2, x, padding)

    N = 10
    start_time = time.time()
    for i in range(N):
      vars1 = step_fn1(vars1, x, padding)
    jax.tree_map(lambda x: x.block_until_ready(), vars1)
    end_time = time.time()

    per_step_time = (end_time - start_time) * 1.0 / N
    print(f'Flax LSTM took {per_step_time*1e6} us/step')

    N = 10
    start_time = time.time()
    for i in range(N):
      vars2 = step_fn2(vars2, x, padding)
    jax.tree_map(lambda x: x.block_until_ready(), vars2)
    end_time = time.time()

    per_step_time = (end_time - start_time) * 1.0 / N
    print(f'Cudnn LSTM took {per_step_time*1e6} us/step')

    loss_fn1 = jax.jit(functools.partial(loss_fn, m1))
    loss_fn2 = jax.jit(functools.partial(loss_fn, m2))
    _ = loss_fn1(vars1, x, padding)
    _ = loss_fn2(vars2, x, padding)
    sess = xprof_session.XprofSession()
    sess.start_session(host_cpu_profile=True)
    l1 = loss_fn1(vars1, x, padding)
    jax.tree_map(lambda x: x.block_until_ready(), l1)
    l2 = loss_fn2(vars2, x, padding)
    jax.tree_map(lambda x: x.block_until_ready(), l2)
    url = sess.end_session_and_get_url(tag='xprof')
    print('xprof: ', url)


if __name__ == '__main__':
  absltest.main()
```

```
Flax LSTM took 112075.92487335205 us/step
Cudnn LSTM took 20186.972618103027 us/step
```

Roughly 5.5x speedup for fwd+bwd pass combined for 1-layer bi-LSTM. The speedup should be even larger with multi-layer LSTM.

**Comment by zhangqiaorjc** [comment]
@cgarciae the redesign of RNN in Flax FLIP LGTM https://github.com/cgarciae/flax/blob/rnn-flip/docs/flip/2396-rnn.md

I especially want to highlight that it's trick to implement bidirectional processing when there's padding involved, so it's a good idea to do that for our user in the new RNN library.

My only concern is performance. It's nice to have the cell abstraction because it makes the code really easy to read and makes it easy to nn.scan. However, one thing we notice that CUDNN does that XLA:GPU doesn't yet do is horizontal fusion.

Using PyTorch LSTM doc as a reference
<img width="606" alt="Screen Shot 2022-12-04 at 10 52 50 AM" src="https://user-images.githubusercontent.com/328992/205509681-9a30532c-df38-4a0b-ad0a-910e86129589.png">

You notice that for the gates, there are essentially two kinds of linear layer, one from input_size to hidden size and the other from hidden size to hidden size. If you concatenate similarly shaped kernels and do a single matmul with x_t and another with h_{t-1}, rather than 8 small matmuls, you can get better performance. A similar trick can be done with the bias add too.

It seems that even nn.OptimizedLSTMCell isn't doing exactly this.
https://github.com/google/flax/blob/8d3e987025a1d0ae7138d968a9d3978342600370/flax/linen/recurrent.py#L277-L280

Ideally XLA:GPU can recognize this fusion opportunity, but it doesn't yet. I believe there might be plans to do horizontal fusion in 2023, so we might just get it when the compiler is more capable. Alternatively, we can improve OptimizedLSTMCell to do a single matmul instead of 8 to do this optimization at the library level.

The other performance opportunity is to dispatch two directions in two separate streams to maximize parallelism, but unfortunately XLA:GPU doesn't currently support multiple compute streams, so there isn't too much we can do about it at the Flax level.

**Comment by zhangqiaorjc** [comment]
it might be possible to concatenate (x_t, h_{t-1}) and concat all the kernels, and do a single matmul instead of 2 matmul or 8 matmuls.

**Comment by zguo235** [comment]
@zhangqiaorjc Thank you for the example! I want to confirm that
`seq_lengths = jnp.sum(input_paddings, axis=-1, dtype=jnp.int32)` in the example is right. As
`padding = jnp.zeros((batch_size, seq_len), dtype=jnp.float32)` in the test,
is it right to use `seq_lengths = jnp.ones((padding.shape[0]), dtype=jnp.int32) * padding.shape[-1]`

**Comment by Sun-Xiaohui** [comment]
@zhangqiaorjc  Hi, I am confused about parameter `dropout` when I use `jax.experimental.rnn.lstm`. It failed when set `dropout`  not zero. for example:
 ```
y, _, _= jax.experimental.rnn.lstm(
        x,
        h_0,
        c_0,
        weights,
        seq_lengths=seq_lengths,
        input_size=input_size,
        hidden_size=hidden_size,
        num_layers=num_layers,
        dropout=0.1,
        bidirectional=bidirectional)
```
It will report an error : 
`jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.custom_call' failed: jaxlib/gpu/rnn_kernels.cc:254: operation cudnnRNNForward( handle.get(), rnn_desc, fwdMode, (const int32_t*)seq_lengths_buf, input_data_desc, input_buf, output_data_desc, output_buf, h_desc, h_0_buf, h_n_buf, c_desc, c_0_buf, c_n_buf, weight_space_size, weights_buf, d.workspace_size, workspace_buf, d.reserve_space_size, reserve_space_buf) failed: CUDNN_STATUS_INVALID_VALUE.`

Does this mean `rnn.lstm` does not support `dropout`? Thanks for your reply!
