### ISSUE TITLE
bfloat16 returns undesired values.

### ISSUE THREAD

**Issue by SeojinBang** [google/jax#13211]
### Description

JAX bfloat16 returns undesired values. For some integers, it works as expected (e.g., `jnp.float16(1284)`), but many others works unexpected. See below. 

```
import numpy as np
import jax.numpy as jnp

print('example 1.')
print('np.float16(1329) is   ', np.float16(1329))
print('jnp.bfloat16(1329) is ', jnp.bfloat16(1329))

print('example 2.')
print('np.float16(1006) is   ', np.float16(1006))
print('jnp.bfloat16(1006) is ', jnp.bfloat16(1006))

# example 1.
# np.float16(1329) is    1329.0
# jnp.bfloat16(1329) is  1328

# example 2.
# np.float16(1006) is    1006.0
# jnp.bfloat16(1006) is  1008
```

### What jax/jaxlib version are you using?

v0.3.25

### Which accelerator(s) are you using?

CPU

**Comment by hawkinsp** [comment]
The issue is that the values you are using are not exactly representable in `bfloat16`. e.g.:

```
In [27]: jnp.nextafter(jnp.bfloat16(1004), jnp.bfloat16(2000))
Out[27]: DeviceArray(1008, dtype=bfloat16)
```
The adjacent values are 1004 and 1008. 1006 cannot be represented exactly in a type with so few mantissa bits. If you need that precision, you shouldn't be using `bfloat16`. Note that `bfloat16` is not the same `float16`; `float16` has more mantissa bits and fewer exponent bits.

A good explanation can be found here: https://nhigham.com/2020/06/02/what-is-bfloat16-arithmetic/

Hope that helps!
