### ISSUE TITLE
jax.numpy.ones and jax.numpy.zeros always yield float32 dtypes

### ISSUE THREAD

**Issue by mganahl** [google/jax#1333]
The following code doesn't behave as expected:
```python 
a = jax.numpy.ones((2,2), dtype=np.float64)
print(a.dtype) #float32, I would expect float64
```
(same for `jax.numpy.zeros`)
see https://github.com/google/TensorNetwork/issues/251

**Comment by bddppq** [comment]
Because by default jax doesn't enable 64bit types 
https://github.com/google/jax/blob/5e0c0c9/jax/lib/xla_bridge.py#L43-L45
https://github.com/google/jax/blob/5e0c0c9/jax/lib/xla_bridge.py#L221-L224

Setting environment variable `JAX_ENABLE_X64=1` should work (or if you use absl in your python code you can specify the flag on command line).

**Comment by mattjj** [comment]
Thanks, @bddppq !

JAX does everything in 32bit by default because a primary use case is training neural networks, and because NumPy likes to promote things to float64, that means we deviate from NumPy behavior. But when the user explicitly requests a float64 value, this behavior is way too surprising.

We recently (#1234) added a warning for this, which might have only hit pypi yesterday:

```
In [1]: import jax.numpy as np

In [2]: print(np.ones((2, 2), dtype=np.float64))
/usr/local/google/home/mattjj/packages/jax/jax/lax/lax.py:4498: UserWarning: Explicitly requested dtype <class 'numpy.float64'> requested in ones is not available, and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  warnings.warn(msg.format(dtype, fun_name , truncated_dtype))
[[1. 1.]
 [1. 1.]]
```

Hopefully that warning will make these surprises less likely.

Let us know if you have other ideas for how to make this behavior less surprising!

**Comment by CamDavidsonPilon** [comment]
> JAX does everything in 32bit by default because a primary use case is training neural networks.

For my own curiosity, why do we prefer to train NN using 32bits? Just a size thing?

**Comment by mganahl** [comment]
thanks for the quick response! My bad, I should have read the docs more carefully! 
I think a warning will be enough for the user to figure out what's happening, and how to fix it.

thanks again!
