### ISSUE TITLE
Different behaviour with savemat for jax.Array

### ISSUE THREAD

**Issue by astanziola** [google/jax#13815]
### Description

Hi! In previous versions of jax (specifically, versions less than 0.4), it was possible to use a `jax.DeviceArray` as a substitute for a numpy array in certain circumstances. For example, the following code was previously functional:

```python
>>> from jax import numpy as jnp
>>> from scipy.io import savemat
>>> a = jnp.ones((4,))
>>> savemat("test.mat", {"a":a})
```
This would create a `.mat` file with a variable a that contained a length-4 array with all ones.

However, since the output of jax functions is now a `jax.Array`, the implicit conversion to a numpy variable no longer works, and the variable is not saved correctly. For example, if Itry to load the previously created file in MATLAB, it will show an empty structure:

```matlab
>> load test.mat
>> a

a = 

  struct with no fields.
```

I understand that this is not directly a problem with jax, but I believe it could potentially affect the compatibility of jax with other libraries. As jax becomes more popular for scientific computing, this could be an issue for many users.

I was wondering if it would be worth mentioning this potential problem in the [jax.Array migration guide](https://jax.readthedocs.io/en/latest/jax_array_migration.html)

### What jax/jaxlib version are you using?

jax v0.4.1

### Which accelerator(s) are you using?

GPU

### Additional system info

Linux

**Comment by jakevdp** [comment]
Interesting, thanks for the report. I was looking into it and found that using `format='4'` rather than `format='5'` works correctly with JAX arrays:
```python
from jax import numpy as jnp
from scipy.io import savemat, loadmat

a = jnp.ones((4,))

savemat("test.mat", {"a": a})
print(loadmat('test.mat'))
# {'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Wed Dec 28 13:33:59 2022', '__version__': '1.0', '__globals__': [], 'a': array([[None]], dtype=object)}

savemat("test.mat", {"a": a}, format='4')
print(loadmat('test.mat'))
# {'a': array([[1., 1., 1., 1.]], dtype=float32)}
```
I wonder why these treat their inputs differently?

**Comment by jakevdp** [comment]
It looks like format 4 explicitly converts inputs to arrays: https://github.com/scipy/scipy/blob/706fafea3d67d471fcac7a0308a8a6e6766b82ed/scipy/io/matlab/_mio4.py#L512

While format 5 does not, it converts its input with this function: https://github.com/scipy/scipy/blob/706fafea3d67d471fcac7a0308a8a6e6766b82ed/scipy/io/matlab/_mio5.py#L450

I can confirm that it treats `Array` and `DeviceArray` differently:
```python
# tmp.py
import jax.numpy as jnp
from scipy.io.matlab._mio5 import to_writeable
x = jnp.arange(5)
print(type(x))
print(to_writeable(x))
```
```
$ JAX_ARRAY=1 python tmp.py 
<class 'jaxlib.xla_extension.Array'>
<class 'scipy.io.matlab._mio5.EmptyStructMarker'>
$ JAX_ARRAY=0 python tmp.py 
<class 'jaxlib.xla_extension.DeviceArray'>
[0 1 2 3 4]
```
Still not sure what the difference might be... I'll dig-in a bit more.

**Comment by jakevdp** [comment]
Ah, the difference is that `jax.Array` has a `__dict__` attribute while `DeviceArray` does not:
```python
$ JAX_ARRAY=0 python -c "import jax.numpy as jnp; print(hasattr(jnp.arange(4), '__dict__'))"
False
$ JAX_ARRAY=1 python -c "import jax.numpy as jnp; print(hasattr(jnp.arange(4), '__dict__'))"
True
```
Because of that, [this line](https://github.com/scipy/scipy/blob/706fafea3d67d471fcac7a0308a8a6e6766b82ed/scipy/io/matlab/_mio5.py#L476) in `to_writeable` treats the two inputs differently.

@yashk2810 - do you know why `jax.Array` defines a `__dict__` method? Is it an intentional addition to the new array API?

**Comment by jakevdp** [comment]
OK, chatted with Yash offline and it looks like it's not trivial to remove the `__dict__` attribute from `jax.Array`.

This scipy implementation is very strange, because essentially *any* normal user-defined class will have a `__dict__` attribute. Here's another example of an object that fails with `loadmat`:
```python
import numpy as np
from jax import numpy as jnp
from scipy.io import savemat, loadmat

class MyArray:
    def __init__(self, arr):
        self._arr = arr
    def __array__(self):
        return self._arr

a = MyArray(np.arange(5.))

# Object is recognized by numpy as an array:
print(np.asarray(a))
# [0. 1. 2. 3. 4.]

# Object works with format='4'
savemat("test.mat", {"a": a}, format='4')
print(loadmat('test.mat')['a'])
# [[0. 1. 2. 3. 4.]]

# Object fails with default (format='5')
savemat("test.mat", {"a": a})
print(loadmat('test.mat')['a'])
# [[None]]
```
I'd probably consider this a bug in the `scipy.io.savemat` code: it seems very strange in array-oriented code that the presence of a `__dict__` attribute (which every normal class has by default!) supersedes the `__array__` method (which is explicitly defined by people who want their objects to convert to arrays). That said, this has been scipy's behavior [since 2009](https://github.com/scipy/scipy/commit/c31230f515409627ba522535332c2628fa549c4b), so I suspect the developers will be hesitant to change this.

I think your best bet here is probably to make sure you cast your inputs to numpy array before passing them to `savemat`, as this is what scipy seems to expect. i.e.:
```python
savemat("test.mat", {"a": np.asarray(a)})
```

**Comment by jakevdp** [comment]
Here's an issue from 2015 reporting this same failure for `xarray.DataArray`: https://github.com/scipy/scipy/issues/5371

Since @shoyer weighed-in there, he might have ideas about the best way forward here. Do you think it's worth raising this issue with scipy?

**Comment by shoyer** [comment]
This definitely seems like a scipy bug. At the very least it should be raising an error instead of silently failing on array-like inputs. I would encourage submitting a fix upstream.

**Comment by jakevdp** [comment]
Cool, thanks for the input @shoyer. @astanziola since this is your bug/issue, are you interested in surfacing this upstream at the scipy repo? If you're not interested, let me know and I'd be happy to take over. Thanks!

**Comment by astanziola** [comment]
Thank you very much for the super quick and in-depth analysis!

Regarding upstreaming this issue to scipy, I'm on leave (away from a computer) until the middle of January, so if you're happy to do it before then, @jakevdp, please feel free to do so!

**Comment by jakevdp** [comment]
Scipy PR proposal is here: https://github.com/scipy/scipy/pull/17676

Also, I think we should fix this on the JAX side for other reasons. I opened #13826 to track
