### ISSUE TITLE
'JaxprTracer' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by jemisjoky** [google/jax#1406]
The following works fine without jit:
```
from jax import jit

def foo(num):
    for _ in range(num):
        pass

jit(foo)(0)
```
But as it is, I get the following error:
```
Traceback (most recent call last):
  File "/Users/jemis/libraries/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/jemis/libraries/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jemis/jaxprtracer_int.py", line 7, in <module>
    jit(foo)(0)
  File "/Users/jemis/libraries/miniconda3/lib/python3.7/site-packages/jax/api.py", line 149, in f_jitted
    out = xla.xla_call(flat_fun, *args_flat, device_assignment=device_assignment, backend=backend)
  File "/Users/jemis/libraries/miniconda3/lib/python3.7/site-packages/jax/core.py", line 569, in call_bind
    outs = primitive.impl(f, *args, **params)
  File "/Users/jemis/libraries/miniconda3/lib/python3.7/site-packages/jax/interpreters/xla.py", line 367, in _xla_call_impl
    *map(abstractify, args))
  File "/Users/jemis/libraries/miniconda3/lib/python3.7/site-packages/jax/linear_util.py", line 217, in cached_fun
    ans, f_prev = cached_fun_body(f, args)
  File "/Users/jemis/libraries/miniconda3/lib/python3.7/site-packages/jax/linear_util.py", line 214, in cached_fun_body
    return call(f, *args), f
  File "/Users/jemis/libraries/miniconda3/lib/python3.7/site-packages/jax/interpreters/xla.py", line 381, in _xla_callable
    jaxpr, (pvals, consts, env) = pe.trace_to_subjaxpr(fun, master, False).call_wrapped(pvals)
  File "/Users/jemis/libraries/miniconda3/lib/python3.7/site-packages/jax/linear_util.py", line 165, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/jemis/jaxprtracer_int.py", line 4, in foo
    for _ in range(num):
TypeError: 'JaxprTracer' object cannot be interpreted as an integer
```
I'm working with pip installs of jax (0.1.46) and jaxlib (0.1.28)

Any insight into how to fix this in the short-term would be hugely appreciated. Many thanks :)

**Comment by jemisjoky** [comment]
This has a really simple fix using the `static_argnums` argument:
```
from jax import jit

def foo(num):
    for _ in range(num):
        pass

jit(foo, static_argnums=0)(0)
```
It would be helpful to have a more informative error message for this, such as this one which arises in other settings: `The function to be transformed can't be traced at the required level of abstraction. If using 'jit', try using 'static_argnums' or applying 'jit' to smaller subfunctions instead.`

**Comment by hawkinsp** [comment]
Yes, that's one fix. The other option is to use JAX control-flow primitives, e.g., `lax.fori_loop` or `lax.scan`, which you may prefer since they are often faster to compile than a Python loop that has the effect of unrolling the computation.

It's hard for us to give a really good error here, since it's an exception thrown by code that we didn't write (here, the implementation of `range`.) Perhaps the next best thing would be easily-discoverable documentation that describes what that error means and how to fix it?

**Comment by mattjj** [comment]
In Python 2 we had a better error message, because the `range` builtin would try to coerce its argument to an int by calling its `__int__` method. We overrode that method on our tracers/avals to provide a better message. But Python 3's `range` apparently doesn't call it!

I think we might be able to control the message by subclassing `int` or something weird like that... but maybe we should just document it better :)

**Comment by mattjj** [comment]
To understand what's going on, take a look at the [How it works](https://github.com/google/jax#how-it-works) section of the readme, as well as [What's supported](https://github.com/google/jax#whats-supported) (look for the string "control flow"). There's also an explanation in the [Gotchas notebook](https://colab.sandbox.google.com/github/google/jax/blob/master/notebooks/Common_Gotchas_in_JAX.ipynb) (linked from the readme).

**Comment by jemisjoky** [comment]
@hawkinsp and @mattjj, thanks for all the info on that! I somehow never stopped to read the How it works section earlier, and that clears up a lot of the confusion I had about this (and prior) `jit` error messages.

One other thing, the toy code example I gave is based on real code where I need to backpropagate through everything that's happening inside the for loop. Will replacing the for loop with a `lax.fori_loop` construct make the code non-differentiable?

**Comment by mattjj** [comment]
Yes, `lax.fori_loop` isn't differentiable. But [`lax.scan` is](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.scan.html#jax.lax.scan)! Can you use that?

Alternatively, you can do the `static_argnums` thing and just use Python control flow there. The downsides are (1) more recompilation (every time the 'static' arg changes, we recompile) and (2) possibly longer compile times because the loop would be unrolled into a larger XLA computation.

**Comment by jemisjoky** [comment]
Ahhh yes, that should work beautifully. Thank you so much!

**Comment by mattjj** [comment]
Happy to help!
