### ISSUE TITLE
Inconsistency between `jacfwd` and `jacrev` for functions with multiple outputs

### ISSUE THREAD

**Issue by vedpatwardhan** [google/jax#14149]
### Description

When a function returns multiple outputs, one of which is `nan`, `jacfwd` seems to return a `nan` corresponding to that output whereas `jacrev` returns a `nan` corresponding to all the outputs.

Consider the following example
```
import jax
import jax.numpy as jnp

x = jnp.array([-1., -2., -3.])
func = lambda x: (jnp.mean(x), jnp.mean(x**2), jnp.mean(jnp.sqrt(x))) 
print(func(x))
func1 = jax.jacrev(func)
func2 = jax.jacfwd(func)
print(func1(x))
print(func2(x))
```

Following is the output
```
(DeviceArray(-2., dtype=float32), DeviceArray(4.666667, dtype=float32), DeviceArray(nan, dtype=float32))
(DeviceArray([nan, nan, nan], dtype=float32), DeviceArray([nan, nan, nan], dtype=float32), DeviceArray([nan, nan, nan], dtype=float32))
(DeviceArray([0.33333334, 0.33333334, 0.33333334], dtype=float32), DeviceArray([-0.6666667, -1.3333334, -2.       ], dtype=float32), DeviceArray([nan, nan, nan], dtype=float32))
```

Given that the docs specify that both functions should compute the same values, is this the expected behaviour? Thanks 🙂

### What jax/jaxlib version are you using?

jax v0.3.14, jaxlib v0.3.14

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.8.10, Ubuntu 20.04.5 LTS (Focal Fossa)

**Comment by vedpatwardhan** [comment]
Hey @mattjj, any update on this? Thanks!

**Comment by mattjj** [comment]
Thanks for the question! Sorry I missed it for... a year and a half! Oops.

It's extra tragic because it has a simple answer: this is actually expected behavior, because of how un-mathematical nans are!

The issue is that `jacfwd` computes the Jacobian `J` as something like `J = J @ I`, while `jacrev` computes it like `J = I @ J`. (Those definitions are circular if we take the notation too literally, but what I really mean is `jacfwd` applies Jacobian-vector products to an input-space identity matrix, while `jacrev` applies vector-Jacobian products to the rows of an output-space identity matrix.)

So how come only `jacfwd` gives the correct answer? Notice:

```
In [1]: import numpy as np

In [2]: J = np.array([[0.33333334, 0.33333334, 0.33333334], [-0.6666667, -1.3333334, -2.       ], [np.nan, np.nan, np.nan]])

In [3]: J @ np.eye(3)
Out[3]:
array([[ 0.33333334,  0.33333334,  0.33333334],
       [-0.6666667 , -1.3333334 , -2.        ],
       [        nan,         nan,         nan]])

In [4]: np.eye(3) @ J
Out[4]:
array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])
```

It's strange that we have a matrix `A` for which `I @ A` and `A @ I` don't agree, but that's just because nans don't follow the usual laws of real numbers.

Apologies if that's unsatisfying, but it's just an unfortunate behavior of nans, as true for autodiff as it is for direct matrix multiplication in numpy.
