### ISSUE TITLE
JAX is much slower than autograd for 1-d functions on CPU

### ISSUE THREAD

**Issue by AxelBohm** [google/jax#14185]
### Description

For a simple 1-d scalar function JAX is almost 20x slower than autograd on CPU. With jit this reduces to 10x. See the code below.
Is there a reason for this? Can one fix it?

```python
import numpy as np
import time
import autograd
import jax

def eval(df, method):
    start_time = time.time()
    [df(i) for i in np.arange(0, 1, 0.001)]
    print(f"{method}: {(time.time() - start_time)} s")

def f(x): return x**2 + x

@jax.jit
def f_jit(x): return x**2 + x

eval(jax.grad(f), "jax")
eval(jax.grad(f_jit), "jax + jit")
eval(autograd.grad(f), "autograd")
eval(lambda x: 2*x + 1., "analytic")
```
The result being:
```python
jax:        1.3326 s
jax + jit:  0.7023 s
autograd:   0.0703 s
analytic:   0.0002 s
```

### What jax/jaxlib version are you using?

jax 3.25

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.9.7, Ubuntu 22.04

**Comment by mattjj** [comment]
Wow, we should hire those Autograd developers! :P

Try putting the `jax.jit` outside the `jax.grad`, like `eval(jax.jit(jax.grad(f)), ...)` or `eval(jax.jit(jax.grad(f_jit)), ...)`.

The more you can put under a `jit`, the more you're staging out for compilation and the faster things will be.

There are regimes where Autograd could be faster, like if you can't put your function under a `jax.jit`, because `numpy` has lower overheads than `jax.numpy` (e.g. it doesn't need to jit-compile) and because Autograd autodiff has lower overheads than JAX's autodiff. But when you can apply a `jax.jit`, do it!

**Comment by jakevdp** [comment]
We also have some general information about potential pitfalls around JAX microbenchmarks here: https://jax.readthedocs.io/en/latest/faq.html#benchmarking-jax-code

**Comment by AxelBohm** [comment]
> Wow, we should hire those Autograd developers! :P
> 
> Try putting the `jax.jit` outside the `jax.grad`, like `eval(jax.jit(jax.grad(f)), ...)` or `eval(jax.jit(jax.grad(f_jit)), ...)`.
> 
> The more you can put under a `jit`, the more you're staging out for compilation and the faster things will be.
> 
> There are regimes where Autograd could be faster, like if you can't put your function under a `jax.jit`, because `numpy` has lower overheads than `jax.numpy` (e.g. it doesn't need to jit-compile) and because Autograd autodiff has lower overheads than JAX's autodiff. But when you can apply a `jax.jit`, do it!

Wow, thanks so much!! Should I have mentioned that I am new to JAX? That was probably obvious from my question... 
With `jit` around `grad` JAX is 5x faster.
