### ISSUE TITLE
Add complex32 dtype support

### ISSUE THREAD

**Issue by magnusdk** [google/jax#14180]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

Using 16-bit (half-precision) floating point numbers reduces memory usage and can make the program run faster, compared to f.ex. 32-bit. My program is working with complex numbers and I'd like to take advantage of the 16-bit speed-up, but JAX only support `complex64`.

Can we add support for half-precision complex numbers (`complex32`)?

```python
import jax.numpy as jnp

f32 = jnp.array([1, 2, 3], dtype="float32")
print(f32.size * f32.itemsize)  # 12 (bytes)

f16 = jnp.array([1, 2, 3], dtype="bfloat16")
print(f16.size * f16.itemsize)  # 6 (bytes)

c64 = jnp.array([1, 2, 3], dtype="complex64")
print(c64.size * c64.itemsize)  # 24 (bytes)

c32 = jnp.array([1, 2, 3], dtype="complex32")
print(c32.size * c32.itemsize)  # 12 (bytes)  <- I want this, but complex32 is not supported
```

If not, is there anything that stops me from making JAX work with half-precision complex numbers today (f.ex. by creating a class that has two fields: `real <bfloat16>` and `imag <bfloat16>`)?

```python
from typing import NamedTuple
import jax.numpy as jnp

class Complex32(NamedTuple):
    real: jnp.ndarray
    imag: jnp.ndarray

c32 = Complex32(
    jnp.array([1, 2, 3], dtype="bfloat16"),
    jnp.array([4, 5, 6], dtype="bfloat16"),
)
jnp.abs(c32)  # TypeError: absolute requires ndarray or scalar arguments, got <class '__main__.Complex32'> at position 0.
```

Related issue: https://github.com/google/jax/issues/216

Thanks!

**Comment by jakevdp** [comment]
Hi - thanks for the request. This is not a trivial task, mainly because on most (or all?) backends, underlying BLAS/LAPACK libraries do not have complex32 support, so operating on complex32 would involve re-implementation of a lot of operations that for other dtypes lean on well-established system libraries. Further, many processors do not have native support for half-precision complex operations, so you'd probably have to either use a lot of emulation or temporarily cast to complex64 internally. Given those challenges, unless there is a very compelling use-case, I doubt JAX will add complex32 support.

**Comment by albertfgu** [comment]
Just wanted to jump in to say that there has been growing interest in recent models that do heavily use complex numbers, including large-scale models that might benefit a lot from half precision: e.g. https://arxiv.org/abs/2111.00396 https://arxiv.org/abs/2212.14052

It does seem quite challenging to add support though. How important do you think the backend implementations are - for example, let's say I have a model that uses relatively basic operations on complex numbers (say mainly just additions and multiplications). Do you think it could be faster to store complex numbers as pairs of bf16 arrays, manually code the complex operations in terms of their real components, and hope that XLA can optimize it well - instead of using c64 arrays?

**Comment by magnusdk** [comment]
Hi, thanks for the answer! I plan to test out my code with bf16 arrays and manually code the complex operations (once I find the time) and see if it get any faster. I will report back when I do :)

**Comment by matteoguarrera** [comment]
Hi @magnusdk have you tried to code up the complex32?

**Comment by jrhip** [comment]
Torch has complex32: [https://docs.pytorch.org/docs/stable/tensor_attributes.html](https://docs.pytorch.org/docs/stable/tensor_attributes.html)

I will have a look at how they've managed to do it. 
Edit: As mentioned above, BLAS/LAPACK does not support complex32: [https://github.com/pytorch/pytorch/issues/74537](https://github.com/pytorch/pytorch/issues/74537)
