### ISSUE TITLE
jax.numpy.take returns large negative number when given out of range index

### ISSUE THREAD

**Issue by MonliH** [google/jax#14193]
### Description

If I use `jax.numpy.take` to try to retrieve an index out of bounds, I get a large negative number:
```python
import jax.numpy as jnp
arr = jnp.arange(5)
print(jnp.take(arr, 10)) # -2147483648
```

I know that out-of-bounds indexing doesn't error for performance/implementation reasons,  but is the value `-2147483648` really a great choice? I think it might be a bit unexpected, e.g. the [documentation](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#out-of-bounds-indexing) says:

> the index is clamped to the bounds of the array since something must be returned

But it seems that the index here isn't being clamped.

### What jax/jaxlib version are you using?

jax v0.4.2, jaxlib v0.4.2

### Which accelerator(s) are you using?

TPU

### Additional system info

Python 3.8.10, TPU VM v3-8

**Comment by jakevdp** [comment]
Thanks for the report – this is expected behavior, though I understand it's somewhat unintuitive. There's some discussion of why JAX doesn' raise errors on out-of-bound indices here: http://go/jax-sharp-bits#out-of-bounds-indexing

So in this case, JAX must return some value of the specified dtype to indicate that the index was out-of-bounds. For float arrays, JAX will return `NaN`. But for int arrays, there is no equivalent of a `NaN` value, so for lack of a better choice JAX returns the minimum representable value.

If you'd like the fill value to be different, you can specify this using the `fill_value` argument of `jnp.take`. For example:
```python
jnp.take(arr, 10, fill_value=-1)
# -1
```

**Comment by MonliH** [comment]
I see, thanks for the explanation. I missed those docs, as I just read the main docstring anticipating it would discuss the out-of-bounds behaviour. Maybe we could add something commenting on this behaviour in the main docstring? Something like the note in the docstring for [`jax.numpy.ndarray.at`](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html#jax.numpy.ndarray.at):

> By default, JAX assumes that all indices are in-bounds. There is experimental support for giving more precise semantics to out-of-bounds indexed accesses, via the mode parameter (see below).
