### ISSUE TITLE
GSoC'23 in Jax

### ISSUE THREAD

**Issue by shivance** [google/jax#14228]
What are potential projects for Jax re: it's participation in GSoC'23 ?

I'm interested ! I would love to do some prior contributions as well regarding the same

**Comment by mattjj** [comment]
Thanks for asking about this, and for your eagerness to help!

I don't think the JAX core team is doing anything for GSoC though.

Since this issue tracker is mainly for the JAX core development team, and since we're not involved in GSoC, I think it makes sense to close this issue.

However, separate from GSoC, we try to mark issues as "good first issue" or "contributions welcome", so if you want to make contributions to the JAX core codebase then those may be the best place to start. Also, there may be other places to contribute in higher-level libraries.

Thanks again for asking!
