### ISSUE TITLE
Running vmap with jit disabled on a function with python control flow gives errors

### ISSUE THREAD

**Issue by kyrollosyanny** [google/jax#14245]
### Description

I have a function that takes in one value, does some nonlinear transformations to it based on some python control flow and outputs a single value.  Let's call it ```forward``` 

Now, I can call ```grad(forward)()``` to get the derivative wrt some parameters. Im trying to use ```vmap``` to run this on 10,000 samples. I know my function cannot be jitted (in it's current state) so I run: 

``` 
with jax.disable_jit:
       batched_fun=vmap(grad(forward)))(0,None)
       batched_fun(...some values...)

```

It gives the following error:

```
TypeError: Abstract value passed to `bool`, which requires a concrete value.
```

I know this bug was raised before but I went through the other posts and couldn't find an answer to fix this. Is there a way to get the gradient for the 10000 values  with vmap or other, without having the underlying function be jit-able?

### What jax/jaxlib version are you using?

pip install "jax[cuda11_cudnn82]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

### Which accelerator(s) are you using?

CPU

### Additional system info

Python V 3.10.6. WSL.

**Comment by mattjj** [comment]
Thanks for raising this!

Actually, it's not a bug; this is expected behavior with `vmap`. The issue is that different elements of the batch might need to take different paths in the control flow (e.g. different branches of an `if` when the boolean predicate to the `if` is batched). But we can't take both sides of Python control flow, so we can't trace such a function.

The error message is saying that we're tracing (i.e. specializing) on an abstract value representing the set of possible values in the batch (e.g. a value representing the set `{True, False}` for a boolean value), rather than specializing on a particular value (e.g. `True` or `False`), but some Python control flow in the function is demanding a concrete value, which we don't have.

Both `vmap` and `jit` behave similarly in that they trace on abstracted values rather than concrete ones: `vmap` because it needs to represent all elements in the batch, and `jit` because it needs to represent all possible values we might apply a function to later (since we're staging the computation out of Python to be compiled).

> Is there a way to get the gradient for the 10000 values with vmap or other, without having the underlying function be jit-able?

Technically yes, in some cases, but it sounds like no in your case.

We don't require the whole function to be jittable; we just need any values used in Python control flow to be available / specialized on during trace time. So if we used `vmap` without batching over e.g. the boolean predicate values of any `if`s, we'd be fine.

One way to get batchable (and jittable) control flow is to use structured control flow primitives like [`jax.lax.cond`](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.cond.html), [`jax.lax.switch`](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.switch.html), or the loop primitives. These are more restrictive than Python control flow, and more awkward to write, but the upside is that they're JAX-transformable, including with `vmap` (though `vmap`-of-`cond` may produce the equivalent of a `jnp.where`).

WDYT?

**Comment by kyrollosyanny** [comment]
@mattjj, Thanks a lot for your answer. That makes a lot of sense. Regarding "We don't require the whole function to be jittable; we just need any values used in Python control flow to be available / specialized on during trace time." Can you elaborate a bit more on that (i.e. what does available/specialized mean) or share some examples or doc?

Thanks

**Comment by mattjj** [comment]
Here are some references:
* [video (starting at about 32min in)](https://www.youtube.com/watch?v=BzuEGdGHKjc&t=1900s)
* [How to think in JAX tutorial](https://jax.readthedocs.io/en/latest/notebooks/thinking_in_jax.html)
* [Autodidax: JAX core from scratch](https://jax.readthedocs.io/en/latest/autodidax.html)

I may be forgetting some others!
