### ISSUE TITLE
memory profiler doesn't work with [colab] tpus

### ISSUE THREAD

**Issue by krahnikblis** [google/jax#14304]
### Description

following the instructions on [this](https://jax.readthedocs.io/en/latest/device_memory_profiling.html) page, which, btw are pretty incomplete ('hey go figure out how to install this list of obscure things [in our hosted environment where we could have just set it up for you but nah lolz] instead of the usual pip'), so i filled in the install portion from comments in some of these issue threads... separate suggestion, please provide complete examples - there's not a lot of good info on how to troubleshoot; everything about jax older than about 1yr is obsolete, and everyone and their grandma are still using pytorch (whyyy) so there's just not a lot of help available to troubleshoot things...

doc page says "Understanding how a JAX program is using GPU or TPU memory" but using it in your hosted tpu environment with your default distro of jax installed gives the error `AttributeError: 'jaxlib.tpu_client_extension.TpuClient' object has no attribute 'heap_profile'`

here's what i ran in colab, to try to figure out an **infuriating** JAX/XLA error stating `XlaRuntimeError: RESOURCE_EXHAUSTED: Could not allocate 10485760 bytes in memory 0x0x0_HBM0; 4374528 bytes allocatable, 14942208 bytes available` (this error is **bonkers**; 14942208 > 10485760):
```python
!apt update
!apt install golang-go
%env GOPATH=/root/go
!go version
!go install github.com/google/pprof@latest
jax.profiler.save_device_memory_profile("memory.prof") ## this causes the error TpuClient object has no attribute 'heap_profile'
```
so really i have 2 questions: why can't jax fit 10MB in 14MB of free space? 64GB there on TPUs and it's whining about 10MB meanwhile my "compute units" are ticking away... other question is, why doesn't this profiler work, and if it does, why doesn't the doc page explicitly explain how to make it do its magic?

### What jax/jaxlib version are you using?

whatever your default in colab is 

### Which accelerator(s) are you using?

TPU

### Additional system info

Colab Pro

**Comment by mattjj** [comment]
Thanks for the questions!

> why can't jax fit 10MB in 14MB of free space?

It's about fragmentation. Look at the "allocatable" line in the error message: `Could not allocate 10485760 bytes in memory 0x0x0_HBM0; 4374528 bytes allocatable, 14942208 bytes available`. So while there are 14942208 bytes in total which are free, only 4374528 bytes are allocatable.

> why doesn't this profiler work, and if it does, why doesn't the doc page explicitly explain how to make it do its magic?

Let me double check this but I suspect it's because Colab uses an old TPU interface which makes them slow (e.g. high latency) and makes some features not work. Memory profiling may be one of those missing features. If so, we'll update the docs page to reflect that.

Actually, I believe another missing feature on Colab TPUs is automatic memory defragmentation, which may solve your first issue.

Unfortunately, to use the newer [Cloud TPU VM](https://cloud.google.com/blog/products/compute/introducing-cloud-tpu-vms) interface to TPUs, which is faster and more feature-ful, you need to start your own Cloud TPUs rather than using Colab. That's not the situation we (the JAX team) want, but it's the current state of things.

> ('hey go figure out how to install this list of obscure things [in our hosted environment where we could have just set it up for you but nah lolz] instead of the usual pip')

We (the JAX team) don't control the Colab kernels, but they care about users and user requests, so if you want something installed by default on Colab then consider opening a request on their issue tracker (might be [this one](https://github.com/googlecolab/colabtools)).

> so i filled in the install portion from comments in some of these issue threads... separate suggestion, please provide complete examples

If you have time, could you provide more detail here? What threads and examples do you mean? (AFAICT the profiling page has code examples of running the tools, so do you mean installation examples, or are the examples for running the tools incomplete in some way?)

**Comment by krahnikblis** [comment]
> Actually, I believe another missing feature on Colab TPUs is automatic memory defragmentation, which may solve your first issue.

oh man, that's a frustration, but seems fitting. is there a driver or install i can run to add that defrag capability in colab? or is the older TPU they're using just not compatible with it? the memory fragmentation thing is what i've been trying to chase down, but can't figure out why it happens only in training but not inference, and no amount of reordering of variable/parameter setup, deleting of variables, device-get/device-put sequences, or casting everything to bfloat16 will help. so the profiler was a ray of hope, for a moment... i really don't want to split workflows and train using pytorch/gpu and run inference with jax/tpu...

> Unfortunately, to use the newer [Cloud TPU VM](https://cloud.google.com/blog/products/compute/introducing-cloud-tpu-vms) interface to TPUs, which is faster and more feature-ful, you need to start your own Cloud TPUs rather than using Colab.

the pricing for the cloud tpu is **significantly** more expensive (looks like for the same number of tpu cores, it's just over 50X as expensive). it's already a source of anxiety to dev and test on colab where every minute on the clock is costing. yeah i know it's only like 25 cents an hour, but when i originally signed up for it there wasn't this "compute units" billing model so when i learned that's why i suddenly would get cut off from TPUs it made me constantly aware of the need to rush, which goes against thorough testing of things... 

> If you have time, could you provide more detail here?

i don't have all of what i found - basically i just plug in "tpu" or "RESOURCE_EXHAUSTED" or whatever is vexing me into the issues search on here and Flax and and related library repos and so on till i find anyone experiencing anything relevant, and try what is suggested in those chains. sometimes it helps, mostly it's stale and old stuff that doesn't work anymore (e.g. found some [really neat jax colab tools](https://gist.github.com/levskaya/37f72b76bd5c72f9e5ce48ce154a9246), but they went obsolete looks like couple years back). i don't save the URLs of all the pages i visit and collect little nuggets from, unless i happen to find one that works, and i still have the tab open i found it on... 

but regarding the profiling tool doc page, it would be helpful to have the end-to-end example, from installation of Go and Graphviz, through an example program to profile, the use of the profile function to dump the memory info to file, and the reading/displaying of that file. as it was, i needed to go to the Go website and browse through all their marketing and documentation materials to find out what even was "Go" and how to get it... and their site didn't even have a working (for colab anyway) way to install it (their method puts the install in /usr/local/go/bin, which for whatever reason was not visible to the colab VM's OS), i actually had to find that in a jax issue thread somewhere (the APT install that i pasted above)...

**Comment by hawkinsp** [comment]
We don't support Colab TPUs any more, I'm afraid, since they haven't transitioned to the newer TPU VM architecture.

However, you can get a very similar experience from Kaggle notebooks, which *do* support the newer TPU VM architecture. (There's a slight catch with those also: they are on Python 3.8, for which current JAX has dropped support. But you should be able to use a reasonably recent JAX that way.)

It's possible Colab will migrate their TPUs at some point, at that point JAX would support them once again.

Hope that helps!
