### ISSUE TITLE
Suggestions for contributing.md

### ISSUE THREAD

**Issue by carlosgmartin** [google/jax#14315]
Suggestions to make the code contribution process for new users more streamlined and logically organized:
- Change `.[cpu]` to `".[cpu]"` to fix https://github.com/google/jax/pull/9194. (Side question: Is it necessary to specify `[cpu]` at all?)
- Move [Google contributor license agreement](https://jax.readthedocs.io/en/latest/contributing.html#google-contributor-license-agreement) to the beginning of [Contributing code using pull requests](https://jax.readthedocs.io/en/latest/contributing.html#contributing-code-using-pull-requests), since it's a prerequesite for contributing code as a whole.
- Move [Linting and Type-checking](https://jax.readthedocs.io/en/latest/contributing.html#linting-and-type-checking) to the step before "Make sure the tests pass by running the following command from the top of the repository", since it logically belongs at that stage of the process.
- Add the following to the step about running tests: "You can also test a specific function using the `-k` flag, e.g. `pytest -n auto tests/lax_scipy_test.py -k testLogSumExp`." This saves users time when testing a specific function.
- Move [Single-change commits and pull requests](https://jax.readthedocs.io/en/latest/contributing.html#single-change-commits-and-pull-requests) to the step that comes before pushing, to ensure users have squashed their commits before pushing.

Thoughts? I can open a PR if desired.

**Comment by jakevdp** [comment]
Great ideas, thanks for bringing them up! Regarding your installation question: the `[cpu]` is required, because otherwise jaxlib is not installed (jaxlib is an optional dependency for JAX because of the fact that specific jaxlibs are required for different architectures).

If you'd like to put together a PR, that would be great! Alternatively, if you don't have the cycles for it right now I'd be happy to take over and implement your ideas. Thanks!

**Comment by carlosgmartin** [comment]
@jakevdp Feel free to do so. Thanks.
