### ISSUE TITLE
`_FiiledConstant` type does not expose `device_buffer`

### ISSUE THREAD

**Issue by romanngg** [google/jax#1432]
If I create constant arrays like `x = np.ones((10, 10))`, they, as `_FilledConstants` will not expose `device_buffer` attribute to detect on which device they are residing.

**Comment by romanngg** [comment]
Note that the same applies to `np.ndarray` resulting from calling `jax.api.device_get`. It would be great to have a single method that would detect the array backend for all array types.

**Comment by jekbradbury** [comment]
`_FilledConstant`s don't have a `device_buffer` because they're not actual arrays backed by memory on any device (they're lazy, fake arrays that are composed purely of metadata, namely a fill value and shape, that -- like all array metadata -- lives on the CPU).

If you'd like to get a `DeviceArray` on CPU rather than a NumPy array, you can use `jax.jit(lambda x: x, backend='cpu')` for now. It's possible that this should be the result of `device_get` as well, now that we have multi-backend support; on the other hand, while some users use `device_get` to bring a value to the CPU, others probably use it with the goal of getting a NumPy array.

**Comment by skye** [comment]
Can you describe how you're using the device of these values? That might help us figure out the best thing to do here.

**Comment by romanngg** [comment]
Thanks James and Skye!

The use-case is to `jit` a function with the correct backend conditioned on where the input resides (https://github.com/google/neural-tangents/blob/97168d5d023cdd52ce9010a21ccca5f4d47819ec/neural_tangents/predict.py#L825)

It makes sense though to have constants be lazily evaluated, so I'm not sure what would be the right approach here. Perhaps it would make sense to have a method that just transfers a `DeviceArray` from one backend to another, without casting to `np.ndarray`, but no strong opinion here.

**Comment by jekbradbury** [comment]
Do you think the default behavior of `jit` should be to use the device that the inputs reside on, if they all reside on the same device? (this would be "pytorch-style" device placement, rather than the current behavior of "tf-style" device placement where `jit` with no device arguments will run on the default device, no matter where arguments live, and move stuff there first)

**Comment by romanngg** [comment]
Yes I think that would be reasonable! This would also allow us to get rid of some boilerplate code like above to select the backend.

**Comment by hawkinsp** [comment]
This is a moot issue because `_FilledConstant` itself has been gone for some time.
