### ISSUE TITLE
_pjit_lower_cached not caching same code

### ISSUE THREAD

**Issue by prazek** [google/jax#14589]
### Description

Hi JAXers, 

it seems that pjit jaxpr -> XLA cache (_pjit_lower_cached) does not cache simple cases like this:

```python
@pjit
def f(p):
  return sum(p.values())

before = pjit_lib._pjit_lower_cached.cache_info()
f({"a": 1.0})
f({"b": 1.0})

after = pjit_lib._pjit_lower_cached.cache_info()
assert after.misses == before.misses + 1
```

What I observed is that ClosedJaxpr have different hash, even though they have identical operations.

### What jax/jaxlib version are you using?

head

**Comment by yashk2810** [comment]
Your inputs are different leading to a different `in_tree` that you get via `arg_flat, in_tree = tree_flatten(arg)`

**Comment by mattjj** [comment]
In terms of the user API, we can't get a cache hit between `{'a': 1.0}` and `{'b': 1.0}`, i.e. on dicts with different keys, because the function might depend on the key values, e.g. the function could be `lambda p: f1(p) if 'a' in p else f2(p)`.

**Comment by yashk2810** [comment]
That's a much better explanation! Thanks Matt!

**Comment by mattjj** [comment]
To put a fine point on it: we'd get a cache hit here:

```python
@pjit
def f(p):
  return sum(p.values())

f({"a": 1.0})
f({"a": 1.0})  # use the same key
```

and here:

```python
f({"a": 1.0})
f({"a": 2.0})  # use the same key, even with different value
```

But JAX tracing and lowering (re)specializes on dict keys and hence doesn't get cache hits for dicts with different keys.

I think the TPU and GPU disk compilation caches _do_ get hits in these cases, since the HLO fingerprints compare equal (because the Python function, even though we retraced it, yielded the same jaxpr text and hence the same HLO).
