### ISSUE TITLE
Interacting with new jax array type

### ISSUE THREAD

**Issue by mattbarrett98** [google/jax#14768]
Before the `jax.Array` refactor, it was possible to interact with the class that jax arrays were instances of. This used to be `jaxlib.xla_extension.DeviceArray`, and you could (and still can) import this class and interact with it. For example:

```
from jaxlib.xla_extension import DeviceArray
import inspect
inspect.getsource(DeviceArray.__getitem__)
```
works fine. However, now arrays are instances of `jaxlib.xla_extension.Array` which you can't import:

```
from jaxlib.xla_extension import Array
```
fails with 
```
ImportError: cannot import name 'Array' from 'jaxlib.xla_extension' (/usr/local/lib/python3.8/dist-packages/jaxlib/xla_extension.so)
```

Why is this the case?

**Comment by jakevdp** [comment]
@yashk2810 - perhaps we can change the `__name__` attribute of `ArrayImpl` or its import path such that the two match?

**Comment by mattbarrett98** [comment]
@jakevdp ahh `ArrayImpl` is what I was looking for. Thanks! Yea I suppose it would be more intuitive if 
```python
import jax.numpy as jnp
x = jnp.array([1])
type(x)
``` 
were to give `jaxlib.xla_extension.ArrayImpl` rather than `jaxlib.xla_extension.Array`.

**Comment by hawkinsp** [comment]
I'll note that anything under `jaxlib` is a private API, so if there are names you need from that module we'll need to give them a different public alias unde `jax`.

**Comment by yashk2810** [comment]
Why are you interacting with the Array under jaxlib though? As Peter said, it is a private API.

**Comment by jakevdp** [comment]
Note that `type(x)` does return `ArrayImpl`:
```
import jax.numpy as jnp
x = jnp.array([1])
print(type(x) is ArrayImpl)
# True
```
It's just that `ArrayImpl.__name__` returns `Array` so that when you print the type, the printed name does not match the import path. This is the name inconsistency that I think we should fix (and, as a side, note, this name inconsistency is what's blocking us from document array attributes via sphinx cf. #14563)

Yash: is there a good reason that `__name__` does not match the import path for `ArrayImpl`?

**Comment by yashk2810** [comment]
Yeah, we should fix this.
