### ISSUE TITLE
Print values inside a vmap function

### ISSUE THREAD

**Issue by neon5d** [google/jax#1476]
How to print values with a vmapped function even without any jit?
From advi.py example, 

def elbo(logprob, rng, mean, log_std):
    **sample** = diag_gaussian_sample(rng, mean, log_std) 
    return logprob(sample) - diag_gaussian_logpdf(sample, mean, log_std)

def batch_elbo(logprob, rng, params, num_samples):
    rngs = random.split(rng, num_samples)
    vectorized_elbo = vmap(partial(elbo, logprob), in_axes=(0, None, None))
    return np.mean(vectorized_elbo(rngs, *params))

print(sample) in VS Code debug mode returns the below message
None
Traced<ShapedArray(float32[2])>with<BatchTrace(level=2/0)>

This seems to related to #1396. 
Even if I disabled all the jit, still I can't print values with the vmapp function.

**Comment by gnecula** [comment]
Like `jit`, `vmap` also traces the function in order to find the operations that need to be vectorized.  The print statement will show the abstract values that JAX is using to trace the function, before vmap.

I do not think there is a way right now to print; we do not yet have the jax.print operation.

**Comment by neon5d** [comment]
I got it. Hope to support jax.print soon.
Thank you
