### ISSUE TITLE
custom JVP with symbolic zeros can unintentionally err under jit

### ISSUE THREAD

**Issue by froystig** [google/jax#14833]
From discussion in #14805.

Run this:
```python
from functools import partial
import jax

Zero = jax.custom_derivatives.SymbolicZero

@jax.custom_jvp
def f(x, y):
    return x * y

@partial(f.defjvp, symbolic_zeros=True)
def fjvp(primals, tangents):
    x, y = primals
    tx, ty = tangents
    assert type(tx) is not Zero or type(ty) is not Zero
    return f(x, y), (
        ty if type(tx) is Zero else
        tx if type(ty) is Zero else
        tx + ty)

print(jax.jacfwd(jax.jit(f))(0.1, 0.2))
```

See this:
```
TypeError: Value SymbolicZero with type <class 'jax._src.ad_util.SymbolicZero'> is not a valid JAX type
```

There is no such error if `not jax.config.jax_jit_pjit_api_merge`. It prints `1.0`.

**Comment by mattjj** [comment]
Thanks for the ping, and for the diagnosis on the other thread. We'll take a look today.

**Comment by mattjj** [comment]
I think [here](https://github.com/google/jax/blob/75d0f6522d3e4623e7fd5bd512645e4cbab6b10d/jax/_src/custom_derivatives.py#L378) (and not earlier) we know which tangents are symbolically zero, yet we have a jaxpr which had to assume (defensively) that no tangents were zero. Concretely, with this repro we have the jaxpr

```
{ lambda ; a:f32[] b:f32[] c:f32[] d:f32[]. let
    e:f32[] = custom_jvp_call[
      call_jaxpr={ lambda ; f:f32[] g:f32[]. let h:f32[] = mul f g in (h,) }
      jvp_jaxpr_thunk=<function _memoize.<locals>.memoized at 0x7f77a4058670>
      num_consts=0
      symbolic_zeros=True
    ] a b
    i:f32[] = add c d
  in (e, i) }
```

and at the call site linked above we know `d` is symbolically zero.

There are at least two options:
1. instantiate zeros and run the jaxpr as it exists currently
2. prune the jaxpr given the now-known symbolic zero inputs

The latter would be more efficient execution-wise but may require a new jax pass. Could be fun!

The former would be a workaround to get things running, and under a jit I bet the efficiency wouldn't matter.

Unless someone says otherwise I say we pursue the former for now to (hopefully) unblock @rmoyard .

**Comment by mattjj** [comment]
Just read the thread on #14805 more carefully and I think the solutions in my previous message are not sufficient: the fundamental issue is this:

> Is there a way to access the information of what parameters were set trainable by the users (argnums)?

We want the user's rule to see which things are symbolically zero.

**Comment by mattjj** [comment]
So the `jvp_jaxpr_thunk` object needs to take as argument the symbolic zero pattern.

Now that I say that, though, I vaguely recall @froystig having written that at one point... ah, it's in #15221 (not yet merged) for custom_vjp rules, but I think we need the same thing for custom_jvp rules here.

**Comment by mattjj** [comment]
In addition to `jvp_jaxpr_thunk` taking a symbolic zero pattern as an argument, we need to change its output type to include the output symbolic zero information too.

**Comment by mattjj** [comment]
I hacked on #15426 yesterday but wasn't able to finish it then. We'll try to get back to it!

**Comment by rmoyard** [comment]
@mattjj Thanks for opening a PR :+1:  I am looking forward to using symbolic zeros

**Comment by mattjj** [comment]
#15426 is a complete fix, but it'll take a bit more work to land it in the Google monorepo, as some downstream users of JAX internals need to be fixed. Soon!

**Comment by mattjj** [comment]
@rmoyard let us know if there are any problems!

**Comment by rmoyard** [comment]
Thanks @mattjj, I will rewrite our custom JVPs using symbolic zeros 👍
