### ISSUE TITLE
Add a pmap cookbook

### ISSUE THREAD

**Issue by georgedahl** [google/jax#1487]
A notebook showing a rich and informative set of pmap examples would be an extremely valuable addition.

**Comment by dynamicwebpaige** [comment]
This is an excellent suggestion. 

There are some meaty docstrings in Lax's parallelization primitives, [`spmd_mnist_classifier_fromscratch.py`](https://github.com/google/jax/blob/92e5f93a290ec8146ab6a667abe54adbf39d61ff/examples/spmd_mnist_classifier_fromscratch.py#L17), etc., but it would be useful to have a cookbook and API docs.

**Comment by joaogui1** [comment]
I believe https://github.com/google/jax/blob/master/cloud_tpu_colabs/Pmap_Cookbook.ipynb solves this, what do you think @mattjj ?

**Comment by hawkinsp** [comment]
It does indeed. I think the remaining action item is to link the pmap cookbook into the regular JAX documentation a bit better.

(For a long time we had the cookbook ready to go, but we didn't have a free Colab environment with multiple accelerators that we could run it on. We do now because cloud TPU colabs are available.)

**Comment by joaogui1** [comment]
It's already linked under pmap (using SPMD Cookbook name), but maybe adding the cloud_tpu_colabs to docs/notebooks would be better?

**Comment by mattjj** [comment]
I think this is solved!
