### ISSUE TITLE
Build Fail Due to Triton Dependence on dlfcn.h

### ISSUE THREAD

**Issue by adam-hartshorne** [google/jax#14939]
### Description

Following on from https://github.com/google/jax/issues/14369, there is now a new issue with the use of Triton in JaxLib 0.4.6 (see attachment for full error readout)

external/triton/lib/Target/LLVMIR/LLVMIRTranslation.cpp(24): fatal error C1083: Cannot open include file: 'dlfcn.h': No such file or directory

Windows doesn't have the dlopen API, and thus there is no dlfcn.h header.
[jax_0_4_6_build_error.txt](https://github.com/google/jax/files/10951315/jax_0_4_6_build_error.txt)

### What jax/jaxlib version are you using?

jaxlib v0.4.6, jax 0.4.6

### Which accelerator(s) are you using?

GPU

### Additional system info

Windows 10, Python 3.9, Cuda 11.7, Cudnn 8.4.0

**Comment by hawkinsp** [comment]
JAX depends on XLA, and XLA:GPU these days depends on Triton.

This particular file is part of Triton:
https://github.com/openai/triton/blob/9b7c65a3a9639bb91bc5b7ce3017bf33c8347dd5/lib/Target/LLVMIR/LLVMIRTranslation.cpp#L25
and it's from the upstream source.

XLA builds Triton in a nonstandard way (using a Bazel build), but the source code is the same, so any fix to the .cpp/.h files would have to be sent to the upstream Triton repository.

(It might be easier to start with CPU builds, if you're not already looking at that, BTW, since they do not need Triton.)

**Comment by hawkinsp** [comment]
This issue no longer reproduces at head.
