### ISSUE TITLE
jnp.einsum docstring missing equation arg

### ISSUE THREAD

**Issue by brianwa84** [google/jax#15017]
### Description

The documented arg list for einsum is missing the first argument.

https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.einsum.html
`jax.numpy.einsum(*operands, out=None, optimize='optimal', precision=None, _use_xeinsum=False)`
compare to
https://numpy.org/doc/stable/reference/generated/numpy.einsum.html
`numpy.einsum(subscripts, *operands, out=None, dtype=None, order='K', casting='safe', optimize=False)`
(noting the 'subscripts' for the first arg)

**Comment by jakevdp** [comment]
Hi - thanks for the report! It looks like the issue is that the actual signature of `np.einsum` doesn't match its documented signature. For example:
```python
In [1]: import numpy as np

In [2]: np.einsum??
Signature: np.einsum(*operands, out=None, optimize=False, **kwargs)
Source:   
@array_function_dispatch(_einsum_dispatcher, module='numpy')
def einsum(*operands, out=None, optimize=False, **kwargs):
    """
    einsum(subscripts, *operands, out=None, dtype=None, order='K',
           casting='safe', optimize=False)

    Evaluates the Einstein summation convention on the operands.
...
```
Note that the coded signature matches the JAX implementation, but the signature written at the top of the docstring is different. Given that, I think JAX's implementation is correct, because it matches numpy's implementation. What do you think?

**Comment by jakevdp** [comment]
I suspect the reason for the mismatch on numpy's side is that the signature pre-dates python 3.0, so keyword-only arguments weren't originally possible to use here.

**Comment by brianwa84** [comment]
The numpy documentation is more helpful if you don't have memorized that
the equation comes first. An example usage would be even better.
