### ISSUE TITLE
`jit` breaks `is`

### ISSUE THREAD

**Issue by romanngg** [google/jax#1503]
Example:
```
import jax.numpy as np
from jax import jit

def _is(x, y):
  return x is y


a = np.ones((1, 1))
b = a

_is(a, b)       # True
jit(_is)(a, b)  # False
```

Is it possible to make `jit` preserve the default `is` behavior? Thanks!

**Comment by hawkinsp** [comment]
JAX tracing doesn't preserve object identity. Nor should it, I think. In general, we want to trace a function once and run it many times, irrespective of the object aliasing relationships amongst the parameters. JAX thinks of the parameters as values, not references.

Do you have a more concrete example of how this comes up in practice?

**Comment by romanngg** [comment]
Thanks Peter!

I was thinking about optimizations of this kind (simplified example):
```
def diff(x, y):
  is x is y:
    return np.zeros_like(x)
  return x - y
```
Our current workaround is to pass `y=None`, but I thought supporting `is` would be a bit cleaner and allow the user to call `diff(x, x)` without having to know the convention of passing `y=None` if the arguments are the same.

**Comment by jekbradbury** [comment]
I agree with Peter; the embedded language in JAX (on which all the transformations operate) only knows about values and functions of values, and doesn't have a notion of pointers, references, or object identity. In general we rely on end-to-end compilation with XLA to perform optimizations that might otherwise rely on things like mutation and object identity (if XLA sees a large chunk of your program, it may be able to prove that `x` and `y` always contain the same values and avoid the subtraction).

**Comment by mattjj** [comment]
Thanks for raising this!

+1 to what Peter and James said. To summarize: JAX programs under `jit` must be purely functional, and so as in Haskell and other purely functional languages object identity isn't preserved. We'd expect XLA to perform optimizations like these if it sees enough of the computation.

I'm going to close this issue, but please reopen if we should keep discussing.
