### ISSUE TITLE
Build on Centos7 with Cuda

### ISSUE THREAD

**Issue by justinchiu** [google/jax#152]
I'm trying to build from source on Centos 7, gcc 7, conda 4.5, python 3.6, cuda 9.2.

After successfully building and installing as per the readme, I end up getting

`ImportError: /n/holylfs/LABS/rush_lab/jc/code/jax/build/jaxlib/_pywrap_xla.so: undefined symbol: _ZNSaIPKN3xla14HloInstructionEEC1Ev`

after importing jax, which seems to indicate that that the ffi can't find the xla symbols. I'm new to bazel, so is there something I need to add to my LD_LIBRARY_PATH? Or did I miss a step?

**Comment by mattjj** [comment]
I'm also a newbie at build stuff, but I'm wondering: can you build TF on that setup? We build XLA as part of TF, and TF has a minimum system requirements that might not include this setup.

**Comment by mattjj** [comment]
I'm going to close this issue as inactive, but for anyone who wants to re-open it and follow up: a good first step would be to make sure TF itself can build and run from source on the platform (from googling, it looks like there are discussions on how to build TF on CentOS 7). If that doesn't work, then we likely can't get XLA (or JAX) to build either, since XLA has the same build requirements as TF.

Contributions here are welcome!
