### ISSUE TITLE
Efficiently shardable PRNG algorithm for GPU

### ISSUE THREAD

**Issue by sh0416** [google/jax#15484]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

https://jax.readthedocs.io/en/latest/jax.random.html#advanced-rng-configuration

In here, the efficiently shardable through jit is only for TPUs. Could you make it for GPU?

**Comment by mattjj** [comment]
Thanks for raising this!

Actually, those docs do _not_ mean to say that the efficiently shardable options, namely `rbg` and `unsafe_rbg`, only work on TPU; they work on CPU and GPU also!

Instead, those docs mean to say that:
* `rbg` and `unsafe_rbg` are the absolute fastest way to generate random values on TPUs, compared to other options on TPUs, and
* the values produced by `rbg` and `unsafe_rbg` on TPU are different than what they are on CPU, even given the same key value, and those both are also different from the values that are produced on GPU. (Perhaps the remarkable thing is that the default RNG, `Threefry`, produces the same raw random bits given the same key on CPU, GPU, and TPU, though numerical floating point differences could lead to downstream differences in values coming out of float-producing random samplers.)

There's another efficiently shardable option which I just noticed isn't listed there, but it's described [here](https://jax.readthedocs.io/en/latest/notebooks/Distributed_arrays_and_automatic_parallelization.html#generating-random-numbers). Basically, if you set the option `jax_threefry_partitionable` then the default Threefry PRNG becomes efficiently partitionable. It basically checks all the boxes except "Fastest on TPU", since nothing is as fast as `rbg` and `unsafe_rbg` on TPU.

Does that make sense?

**Comment by sh0416** [comment]
Oh.. I didn't notice the PRNG section in the distributed array document.

Yes, I totally understand. thanks for answering.

I will keep this keep open until your PR is closed.

Please close it if you want.

**Comment by sh0416** [comment]
Also, I think rbg is faster than threefry even on GPUs. :)

**Comment by mattjj** [comment]
That makes sense; I'd expect it to be the fastest on each platform actually!
