### ISSUE TITLE
Support static argnames/argnums to checkify

### ISSUE THREAD

**Issue by danijar** [google/jax#15504]
I tried using checkify today but it's not compatible with my code base because I'm relying on static argnames/argnums for some of the jitted functions. After wrapping the jitted functions with checkify, those inputs are misinterpreted as dynamic arguments and JAX raises an error because they aren't JAX types.

**Comment by mattjj** [comment]
Thanks for raising this!

> those inputs are misinterpreted as dynamic arguments

Well, `static_argnums`/`static_argnames` only affects the particular `jit` call to which those arguments are passed. In particular, they don't change the meaning of the body. So if I understand correctly, this issue isn't checkify-specific: for any `f` where `jit(checkify(f), static_argnums=(0,))` would fail with the error you describe, I believe `jit(jit(f), static_argnums=(0,))` would fail in the same way. In both cases, the function `g` to which the `jit(g, static_argnums=(0,))` is applied only accepts pytrees of jax types (ie arrays) as arguments.

So, there are (at least) two possible problem statements here, and I just want to figure out which one you have in mind:
1. make both `jit(jit(f), static_argnums=(0,))` and `jit(checkify(f), static_argnums=(0,))` (and `scan` etc) Just Work, by changing the meaning of the outer `jit`'s `static_argnums` to affect the body as well; or
2. change `checkify` only so that this issue doesn't arise (e.g. maybe `checkify` should try to avoid assuming  _any_ inputs are jaxtypes, independent of any caller's `static_argnums`).

Did you have one of these in mind?

**Comment by mattjj** [comment]
cc @LenaMartens

**Comment by danijar** [comment]
If I understand correctly, the issue is that `checkify(fn)(array_arg, string_arg)` tries to convert the args to JAX types, which fails to string types.

For jitting, `jit(fn, static_argnums=1)(array_arg, string_arg)` lets you use string types and recompiles the function when the string value changes.

Now, when I do `checkify(jit(fn, static_argnums=1))(array_arg, string_arg)` it fails because checkify can't deal with the string type, even though the jit inside can deal with it.

It seems like the workaround is to manually implement static args on the outside, something along the lines of this?

```python3
def transf_with_static(fn, transform, argname):
  transformed = {}
  def inner(*args, **kwargs):
    value = kwargs.pop(argname, None)
    if value not in cache:
      transformed[value] = transform(functools.partial(fn, **{argname: value}))
    return transformed[value](*args, **kwargs)
  return inner

fn = transf_with_static(fn, jit, 'string_arg')
fn = transf_with_static(fn, checkify, 'string_arg')
fn(array_arg=jnp.zeros(), string_arg='bar')
```

**Comment by mattjj** [comment]
Actually, this line isnt quite right:
```python
fn = with_static(jit, 'string_arg')(fn)  # Same as jit(fn, static_argnames='string_arg')
```

`jit`'s `static_argnums`/`static_argnames` can't be implemented in user code (i.e. on top of a `jax.jit` API which doesn't itself have those options). If you try using the solution quoted here, you'll always get retraces/recompiles between two applications of `fn` even when passing the same value for `string_arg`, because you're creating a fresh callable object (the `partial` instance) every time. That's why `jit` has `static_argnums`/`static_argnames` built in: not as a convenience but because it's the only way to get the caching behavior we want.

This kind of caching approach can work better with `checkify`, though I'm a bit certain because it now operates differently from e.g. `jax.grad` (basically it has some internal caching which makes it a bit different). I'd have to think about it.

I guess a third option is:
3. add `static_argnums` / `static_argnames` to `checkify`, perhaps just as a convenience (though it's not as convenient as it Just Working).

I'd rather make it Just Work if we can!

**Comment by danijar** [comment]
I don't quite follow. The `functools.partial()` in my call only happens when the specialization value isn't already in the cache dictionary. So it would only retrace once per unique value for `string_arg`.

**Comment by mattjj** [comment]
Sorry, I misread your code. (Actually I think it's a bit buggy in that you want to curry the `wrapped` fun on extra level and not get both `fn` and `args`/`kwargs` at the same time.)

You're right that you can get cache hits for equal values with this approach, so that part of my comment was mistaken. But now you have separate jit caches (so e.g. we can't get the same eviction logic we would get from having a single cache).

In general my only point was just that `with_static(jit, 'string_arg')(fn)` isn't _exactly_ the same as `jit(fn, static_argnames='string_arg')`.

Luckily, #15569 will solve the issue by making things Just Work! With that `checkify` will no longer place any constraints on the arguments passed to the `checkify`-decorated function. (Internally all the arguments are just closed over; we checked that the caching issues I was concerned about, basically the things #14250 and #14291 were fixing, no longer apply thanks to 6ec9082.)

**Comment by danijar** [comment]
Awesome! Thanks for also the explanation, that makes sense.
