### ISSUE TITLE
`jit` + `linear_transpose` raises error due to missing DCE  call

### ISSUE THREAD

**Issue by patrick-kidger** [google/jax#15660]
### Description

```python
import jax

def f1(x):
    return 2 * x, x > 0

def g1(x):
    return f1(x)[0]

jax.linear_transpose(g1, 1.)(1.)  # works

@jax.jit
def f2(x):
    return 2 * x, x > 0

def g2(x):
    return f2(x)[0]

jax.linear_transpose(g2, 1.)(1.)  # error!
# jax._src.traceback_util.UnfilteredStackTrace: NotImplementedError: Transpose rule (for reverse-mode differentiation) for 'gt' not implemented
```

It looks like `jax.linear_transpose` is missing a call to `pe.dce_jaxpr` prior to attempting the transpose.

I checked that `jax.grad` doesn't have the same issue. I assume it has a DCE call in there already somewhere.

### What jax/jaxlib version are you using?

JAX 0.4.8

**Comment by mattjj** [comment]
> I assume it has a DCE call in there already somewhere.

Not exactly; it doesn't call explicit DCE, but rather it only traverses the part of the operation graph which is connected to the output. That is, it's always had the (approximate) effect of DCE even before we had DCE rules.

The reason the `gt` is connected here using `linear_transpose`, and not in the `grad`, case, is actually because what disconnects that operation from the output is actually [the `gt` JVP rule](https://github.com/google/jax/blob/f312de8fa93789670b82798d4726ed2dd3610f07/jax/_src/lax/lax.py#L2214). But while we call JVP rules when running `grad`, we don't when running `linear_transpose`.

In one strict sense the function here isn't linear, since `x` is used in a nonlinear operation (i.e. in `gt`). But as you point out this program is linear after DCE. So we can be a bit less strict and allow `linear_transpose` to transpose any function that is linear after suitable normalization (in this case, after DCE).
