### ISSUE TITLE
Cannot use jit for @classmethod

### ISSUE THREAD

**Issue by SUSYUSTC** [google/jax#15727]
### Description

I'm trying to `jax.jit` a @classmethod but it does not work.

```
import jax
import jax.numpy as jnp
from functools import partial


class A:
    def __init__(self):
        pass

    @classmethod
    #@partial(jax.jit, static_argnums=0)  # this one does not work as well
    @jax.jit
    def zeros(shape):
        return jnp.zeros(shape)


print(A.zeros((2, 3)))
```

I got `TypeError: Cannot interpret value of type <class 'type'> as an abstract array; it does not have a dtype attribute`
If I use `@partial(jax.jit, static_argnums=0)` instead of `@jax.jit`, I got `TypeError: A.zeros() takes 1 positional argument but 2 were given`.

### What jax/jaxlib version are you using?

jax 0.4.8, jaxlib 0.4.7

### Which accelerator(s) are you using?

CPU

### Additional system info

python 3.11.3, Ubuntu 18.04

**Comment by JiaYaobo** [comment]
try this
```
class A:
    def __init__(self):
        pass

    @classmethod
    @partial(jax.jit, static_argnums=(0,1))
    def zeros(cls, shape):
        return jnp.zeros(shape)
```

**Comment by SUSYUSTC** [comment]
Thank you very much! I'm getting into a different but relevant problem:

```
import jax
import jax.numpy as jnp
from functools import partial


class A:
    def __init__(self):
        pass

    @classmethod
    @partial(jax.jit, static_argnums=(0, 1))
    def zeros(cls, shape):
        return jnp.zeros(shape)

    @classmethod
    @partial(jax.jit, static_argnums=(0, 1))
    def concatenate(cls, arrays):
        return jnp.concatenate(arrays)


@jax.jit
def concatenate(arrays):
    return jnp.concatenate(arrays)


print(A.zeros((2, 3)))
print(concatenate((jnp.array([0, 1]), jnp.array([0, 1]))))
print(A.concatenate((jnp.array([0, 1]), jnp.array([0, 1]))))
```

The first two lines work well, but I got `TypeError: unhashable type: 'ArrayImpl'` for the last line.

**Comment by SUSYUSTC** [comment]
For the above example, I somehow find `@partial(jax.jit, static_argnums=0` works for `A.concatenate`. Why do I have to use different arguments for the two similar functions?

**Comment by jakevdp** [comment]
`static_argnums` indicates which arguments to a JIT-compiled function should be static. Array properties like shapes and dtypes must be static, while arrays themselves cannot be static. With that in mind, the reason that `static_argnums=(0, 1)` is appropriate for the first function is that argument `1` is a shape (which must be static). The reason that `static_argnums=(0, 1)` is not appropriate for the second function is because argument `1` is an array (which must not be static). For more conceptual background on these topics, you might find this doc useful: https://jax.readthedocs.io/en/latest/notebooks/thinking_in_jax.html
