### ISSUE TITLE
class method does not modify attributes when jitted

### ISSUE THREAD

**Issue by SUSYUSTC** [google/jax#15817]
### Description

The class method `set_subsystem` in the following does not change the attribute `x` after jitted.

```
import jax
import jax.numpy as jnp
import numpy as np


class A:
    def __init__(self, x: jnp.ndarray):
        self.x = x

    def _tree_flatten(self):
        dynamic = (self.x, )
        static = {}
        return dynamic, static

    @classmethod
    def _tree_unflatten(cls, static, dynamic):
        return cls(*dynamic)

    @jax.jit   # if there is not jit here then everything is good
    def set_subsystem(self, index, sub: "A"):
        self.x = self.x.at[index].set(sub.x)


jax.tree_util.register_pytree_node(A,
                                   A._tree_flatten,
                                   A._tree_unflatten)


nall = 3
nsub = 2
x = jnp.array(np.random.random((nall, )))
x2 = jnp.array(np.random.random((nsub, )))

a = A(x)
a2 = A(x2)

print(a2.x)
print(a.x)
a.set_subsystem(jnp.arange(nsub), a2)
print(a.x)
```

I get
```
[0.01640831 0.84409314]
[0.76288915 0.3658373  0.30345497]
[0.76288915 0.3658373  0.30345497]
```
The expected output is
```
[0.01640831 0.84409314]
[0.76288915 0.3658373  0.30345497]
[0.01640831 0.84409314  0.30345497]
```

### What jax/jaxlib version are you using?

0.4.6

### Which accelerator(s) are you using?

CPU

### Additional system info

python 3.11.3, Ubuntu 18.04

**Comment by SUSYUSTC** [comment]
The function also works when it is not directly jitted but called by another jitted function

**Comment by jakevdp** [comment]
Hi - thanks for the question: the issue here is that you are attempting to compile an impure function. For more on this see the following discussions:
- [JAX Sharp bits: Pure Functions](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#pure-functions)
- [FAQ: JIT changes the behavior of my function](https://jax.readthedocs.io/en/latest/faq.html#jit-changes-the-behavior-of-my-function)

The problem is that `self.x = ...` is a side-effect, because `self` is modified in-place and not returned. You should avoid using such impure functions in JAX, because they are not compatible with JAX transforms including `jit`.

**Comment by SUSYUSTC** [comment]
I just tried 
```
    @jax.jit
    def set_subsystem(self, index, sub: "A"):
        result = self.__class__(self.x.copy())
        result.x = result.x.at[index].set(sub.x)
        return result

```
and 
```
result = a.set_subsystem(jnp.arange(nsub), a2)
```
and now it's working.
Do you mean that I should also return a new object whenever I want to change the attributes?

**Comment by jakevdp** [comment]
> Do you mean that I should also return a new object whenever I want to change the attributes?

Yes. If you want a jit-compiled function to have any effect, that effect should be in the return value of the function. If that effect involves modifying any object, then the modified object should be in the return value of the function. If it's not, then the function is impure and is not compatible with `jit` and other JAX transformations.
