### ISSUE TITLE
lstm

### ISSUE THREAD

**Issue by never-to-never** [google/jax#15860]
Jax does not provide an LSTM implementation. How to implement an LSTM network to classify MNIST based on jax?

**Comment by jakevdp** [comment]
Hi - thanks for the question! JAX itself is not a neural net library: it is an array library that provides the building blocks for efficient computation on GPU and TPU. Because of that, JAX itself doesn't include higher-level NN components, but for this you could check out other libraries the build on JAX, for example [flax](https://flax.readthedocs.io/).

Here's a list of flax examples that includes MNIST classification with LSTM: https://flax.readthedocs.io/en/latest/examples_core_examples.html
