### ISSUE TITLE
Use `await` instead of `block_until_ready`

### ISSUE THREAD

**Issue by Kelvinlby** [google/jax#15881]
1. `block_until_ready` is too complex.
2. `await` is used more widely in programming.

**Comment by jakevdp** [comment]
Thanks for the suggestion!

I don't think this change will be possible, because asynchronous programming is kind of an all or nothing thing. My understanding is that to allow `await arr` in place of `arr.block_until_ready()`, all JAX arrays would have to be awaitable and all functions that use them would have to be async functions. Adding that level of complexity would not be an improvement for JAX as a whole.
