### ISSUE TITLE
sparse-sparse matrix multiply creates unnecessary zero entries

### ISSUE THREAD

**Issue by Linusnie** [google/jax#15997]
### Description

When multiplying two sparse BCOO matrices it seems the result always stores explicit zero-entries even when the corresponding row/column of `a` and `b` are all zero:
```python
import jax
import numpy as np
a = jax.experimental.sparse.BCOO.fromdense(np.diag([1., 2.]))
b = jax.experimental.sparse.BCOO.fromdense(np.diag([3., 4.]))
(a @ b).data, (a @ b).indices
>>> (Array([3., 0., 0., 8.], dtype=float64),
     Array([[0, 0],
            [0, 1],
            [1, 0],
            [1, 1]], dtype=int32))
```
Expected output:
```python
>>> (Array([3., 8.], dtype=float64),
     Array([[0, 0],
            [1, 1]], dtype=int32))
```

### What jax/jaxlib version are you using?

0.4.8

### Which accelerator(s) are you using?

GPU

**Comment by jakevdp** [comment]
Hi - thanks for the report! This is working as intended. You're correct that sparse-sparse matmul often results in more stored elements than are strictly required, but those extra stored arguments are necessary due to the constraints of JAX's compilation model, which requires array shapes (and in this case the size of the sparse matrix buffers) to be known at compile time.

The issue is that the sparse matrix indices are only known at runtime, so the output buffers must be able to handle the worst case. When multiplying two matrices with number of specified elements `a.nse` and `b.nse`, the worst case is an output with `out.nse = a.nse * b.nse* (an easy way to imagine this is if the first matrix has all entries in a single column, and the second matrices has all elements in a single row).

To handle this, you have two options:

1) Call `out.sum_duplicates()` on the result of the matmul, outside JIT, in order to sum and remove duplicated entries. It might look like this:
```python
out = (a @ b).sum_duplicates()
print(out.data)
# [3. 8.]
print(out.indices)
# [[0 0]
#  [1 1]]
```

2) If appropriate, you can use a structured sparse representation (e.g. with `n_batch=1` on the leftmost input) such that the output *nse* will be more constrained.

Hope that helps!

**Comment by Linusnie** [comment]
ah I see, that makes sense! Would it somehow be possible to manually set the number of specified elements for the output? eg in this case I'm computing `Bi = S.T @ Ai @ S` for a bunch of very sparse matrices, but I know `Bi.nse == Ai.nse`.

**Comment by jakevdp** [comment]
How do you *know* that the output has the same nse as the input? Could you encode that knowledge by using structured sparsity for the `S` matrix (i.e. option 2 in my answer above)?

**Comment by Linusnie** [comment]
The `Ai`s are non-zero only on sub-blocks (different for every i) and `S = [[D, b], [0, 1]]` where `D` is diagonal

I ended up getting around the issue by simply rescaling the elements of `Ai` before constructing the sparse matrix, so no need for matrix-matrix multiplies :smile: 

In case it's useful here's a basic example to illustrate, goes OOM on my 12GB GPU:
```python
import numpy as np
import jax.numpy as jnp
from jax.experimental import sparse

def get_inds(n, block_size):
    block_inds = np.random.choice(n - 1, block_size - 1, replace=False)
    block_inds = np.hstack([np.sort(block_inds), n - 1])
    return block_inds[np.array(list(np.ndindex(block_size, block_size)))]

n = 48
n_batch = 3000
block_size = 5
A = sparse.bcoo_concatenate([
    sparse.BCOO(
        (
            np.random.randn(block_size * block_size),
            get_inds(n, block_size)
        ),
        shape=(n, n),
    )[None]
    for _ in range(n_batch)
], dimension=0)

S = sparse.BCOO.fromdense(np.block([
    [np.diag(np.random.randn(n - 1)), np.random.randn(n - 1)[:, None]],
    [np.zeros((1, n - 1)), 1.]
]))

A_scaled = (A @ S).transpose((0, 2, 1)) @ S
```
