### ISSUE TITLE
Inconsistent dtype output in jax.random.choice for double precision enabled

### ISSUE THREAD

**Issue by AdrienCorenflos** [google/jax#16019]
### Description

When using double precision, `jax.random.choice` returns inconsistent dtypes. When using a weight vector, the output dtype is set using `searchsorted` rules, i.e., based on the size of the array of weights at hand, while when none is used (uniform weights), the dtype is set using `jax.random.randint` rules (defaulting to `jnp.int_`). I believe the behaviour should be homogenous, no matter what the choice ends up being.

```python
import jax
import jax.numpy as jnp

jax.config.update("jax_enable_x64", True)
key = jax.random.PRNGKey(42)
w = jnp.array([1/3, 1/3, 1/3])

print(jax.random.choice(key, 3).dtype)
print(jax.random.choice(key, 3, p=w).dtype)
```

In practice, I believe that the implementation choice made in https://github.com/google/jax/blob/c22302ae2e0913efd5be23e136f2ff14b520d9cf/jax/_src/numpy/lax_numpy.py#L4824 is perhaps a bit redundant. Indeed, if the config has not enables double precision, `int64` will default to `int32` anyway, while, if it has, you were happy to pay the price in the first place.

WDYT?

### What jax/jaxlib version are you using?

jax v0.4.10 

### Which accelerator(s) are you using?

CPU

**Comment by jakevdp** [comment]
Thanks for the report! I think you're right that the return value should be consistent.

Regarding the comments on the `searchsorted` implementation: it's working as intended. We don't want to return `int64` by default if it's not required, even if the user has set `jax_enable_x64=True`. The reason is that the only way to create *any* 64-bit values is by setting the flag globally, so we want to be conservative in which 64-bit values we create.
