### ISSUE TITLE
Eigvalsh fails to diagonalize a matrix which regular numpy can diagonalize properly

### ISSUE THREAD

**Issue by ramasesh** [google/jax#1628]
I found a (40 x 40) matrix (dtype float32), which is essentially diagonal, that jax.numpy.linalg.eigvalsh() is somehow unable to diagonalize (returning NaNs), while numpy.linalg.eivalsh() handles it fine.  I couldn't find a simple way to generate a matrix like this, so I just uploaded the one that caused me problems in the attached mat.zip file.  

[mat.zip](https://github.com/google/jax/files/3807030/mat.zip)

**Comment by hawkinsp** [comment]
We discussed this offline.

The belief is that Cusolver's algorithm is failing to converge for this matrix, but this matrix isn't terribly well conditioned so it's not that surprising that eigendecomposition failed. Jax reports this by returning a matrix full of NaNs (there's no other error reporting mechanism).

Since it's not clear that we really could do much better here (beyond possibly a better error message), I'm closing this issue for now.

Thanks!
