### ISSUE TITLE
Segfault from iterating over result of `jax.random.split` on CPU.

### ISSUE THREAD

**Issue by trevorcai** [google/jax#1639]
The following code eventually segfaults with high probability.
A sweep of a hundred such processes with different seeds resulted in one such segfault for me in ~30 seconds, and several more within a few minutes.
```
UNROLL_LEN = 80
key = jax.random.PRNGKey(seed)
while True:
  keys = jax.random.split(key, UNROLL_LEN)
  key = keys[0]
  for subkey in keys[1:]:  # Line 30
    jax.device_get(jax.random.uniform(subkey))
```

The python stacktrace is:
```
File jax/interpreters/xla.py, line 615 in _value
File jax/interpreters/xla.py, line 685 in __iter__
File segfault/main.py, line 30 in main
```

The segfaulting thread includes the following lines:
```
@     0x555a10fee7a2         64  std::__u::__function::__policy_invoker<>::__call_impl<>()
@     0x555a13aefbeb        160  stream_executor::host::HostStream::WorkLoop()
```

Changing `UNROLL_LEN` from 80 to 20 makes the segfaults go away.

**Comment by hawkinsp** [comment]
I reproduced this under `gdb`, and observed a crash in XLA-generated code at the instruction:
```
vmovdqa %xmm2,0x400(%r12)
```
where `%r12` is 8-byte aligned, but `vmovdqa` requires 16-byte alignment.

The problem seems to be that under some conditions (especially GWP-Asan) the HostExecutor's memory allocator is returning buffers that are only 8-byte aligned. Changing the allocator to force a larger alignment fixes the problem.

**Comment by trevorcai** [comment]
Thanks for taking a look and the fix!

**Comment by hawkinsp** [comment]
This is now fixed but requires a `jaxlib` release.
