### ISSUE TITLE
No implicit conversions from fp8 types to bf16

### ISSUE THREAD

**Issue by jewillco** [google/jax#16705]
### Description

There do not appear to be implicit conversions defined from 8-bit floating point types to `bfloat16`.

**Comment by jakevdp** [comment]
Hi - thanks for the report. This is the expected behavior: the idea is that if you are working with `float8`, you are doing it quite intentionally, and implicit casting would be surprising. If you want the values to be cast for an operation, you can do it explicitly with e.g. `arr.astype('bfloat16')`.

**Comment by jewillco** [comment]
The problem is that it breaks mixed-type operations that use fp8 along with other types.

**Comment by jakevdp** [comment]
Mixed-type operations will not require implicit promotion, so I don't think this is a blocker.

**Comment by kmheckel** [comment]
This might become a feature request in order to support easy mixed precision training for nn's without having to go through and explicitly instrument code with astype() calls. Still working through this and will post an update with findings once I exam the problem closer.

**Comment by jakevdp** [comment]
I think this is one of those situations where there is no one-size-fits-all solution for all users. A similar case is type promotion of unsigned integers: several times we've considered removing implicit promotion of `uint*` values, because it often causes unexpected behavior (an example of that came up in the issue tracker this morning!) But every time we've explored that, we've run into many existing instances where implicit promotion of unsigned ints is expected, or required by existing code.

I still have a bit of an *a priori* belief that implicit `float8` promotion is likely to cause more problems than it solves... issues like this may be a counterexample, but how many unreported success cases are there where erroneous implicit promotion of `float8` was prevented? It's hard to say. Also, as I've mentioned elsewhere, the choice to add implicit float8 promotion is a one-way street: once we add it, it would be very difficult to remove if we realize it was the wrong decision.

**Comment by kmheckel** [comment]
@jakevdp I agree with your points and empathize with having to consider the implications of supporting and then potentially walking back implicit conversions for float8 types. Personally I don't see much of a distinction between allowing implicit conversions for float16 and allowing them for float8 but JAX is obviously a tool for a much larger community with different priorities and interests than just neural net quantization. Hopefully down the road if float8 becomes more mainstream this discussion could be revisited. Thank you so much for your time and work on this!

**Comment by jakevdp** [comment]
> Personally I don't see much of a distinction between allowing implicit conversions for float16 and allowing them for float8

The difference is that implicit conversions for `float16` were decided by NumPy a quarter century ago, when computation on accelerators was not something anyone could imagine. Conversions for `float8` are something we have the chance to decide now, knowing what we know now, and `float8` is new enough that I don't think we yet have a full handle on what the best design choice is... so for the time being it seems best to keep our choices open.

Maybe for the time being a good middle ground would be to add a new dtype promotion mode that allows implicit promotion of `float8`, something like `with jax.numpy_dtype_promotion('float8_promotion')`.

**Comment by jewillco** [comment]
Will individual libraries using JAX need to use that setting? Or particular places where we want mixed-type operations?

**Comment by jewillco** [comment]
I do not see why accelerators change anything here; aren't implicit conversions about language semantics? I don't see how the hardware affects them.

**Comment by jakevdp** [comment]
> I do not see why accelerators change anything here; aren't implicit conversions about language semantics?

Language semantics have a large intersection with the hardware that language runs on. For example, semantically NumPy promotes most operations to 64-bit. This made sense in a time when 64-bit CPUs were essentially the only imaginable computing environment. Once GPUs came along, people found that NumPy's type promotion semantics were very inconvenient for executing on accelerators, where silent up-casting to float64 can be very inconvenient (see e.g. https://github.com/numpy/numpy/issues/6860).

Design choices made by NumPy in 1998 were made in the context of the hardware of 1998. Design choices we make in 2023 are made in the context of the hardware we have in 2023.

**Comment by jakevdp** [comment]
Gave this a try in #16832; we had to abandon it because the best promotion semantics for float8 are context-dependent, and we can't find a default choice that's good for everybody.

I think that gives credence to the idea that we should not bake-in any implicit promotion design just yet.

Note that you now can perform mixed-precision operations with these types if you explicitly specify the preferred element type; for example:
```python
import jax.numpy as jnp
x = jnp.arange(10, dtype=jnp.float8_e5m2)
y = jnp.arange(10, dtype=jnp.bfloat16)
z = jnp.dot(x, y, preferred_element_type=jnp.bfloat16)
```
I think for the time being, we are going to continue requiring this kind of explicit casting for 4-bit ints and 8-bit floats.
