### ISSUE TITLE
hide typed key array class in favor of distinguishing key arrays by dtype

### ISSUE THREAD

**Issue by froystig** [google/jax#16716]
From the outside perspective, a typed key array should be known as a `jax.Array` with a special element type. Currently we support—and even encourage—distinguishing it based on a special array type (`PRNGKeyArray`) instead, but let's move away from that.

To achieve this, we'll want to hide the array type and expose the dtype in some way.

At least two notable ways in which this will affect code that has already started to use typed key arrays:

* `isinstance(keys, PRNGKeyArray)` will need an alternative based on `keys.dtype`

* Type annotations with `PRNGKeyArray` will need to be switched to `jax.Array`. This is more permissive in principle, but actually the current `jax.random` module sets `PRNGKeyArray` to `Any` during typechecking.

It might make sense to introduce a public convenience function to `jax.random` that determines that an array is a key array, analogous to `jnp.iscomplex` et. al. basically being dtype check conveniences as well. Maybe we call it `jax.random.isprngkey`?

cc #9263

**Comment by jakevdp** [comment]
Maybe `jnp.issubdtype(x.dtype, random.PRNGDtype)` or something like that?

**Comment by froystig** [comment]
We might want to be able to answer two questions:

* Is this an array of keys of a particular implementation (e.g. 'threefry2x32')?
* Is this an array of keys, of any RNG implementation?

There may be some analogy to Numpy's `issubdtype` versus dtype equality, although we don't have to follow suit even if so.

**Comment by patrick-kidger** [comment]
I think I'd propose treating this like any other dtype. E.g. adding dtypes `jax.dtypes.key` and `jax.dtypes.threefry`, such that `jnp.issubdtype(threefry, key)` and `jnp.issubdtype(key, jnp.generic)`.

**Comment by jakevdp** [comment]
Initial proposal in #16781

**Comment by NeilGirdhar** [comment]
I think I [ran into](https://github.com/microsoft/pyright/issues/5668) some changes related to this.

I like @patrick-kidger's suggestion for the runtime behavior.  For the static type checking, it may be worth considering making the dtype generic like NumPy does.  I [proposed this earlier](https://github.com/google/jax/pull/11859#issuecomment-1261395126) for common dtypes.  For RNG dtypes, it would be really nice because you could then provide a much more constrained type annotation:
```python
PRNGKeyArray = Array[jnp.generic]
```
This would then work as usual and give errors (at least with PyRight) if someone tries to pass another type of Jax array.

**Comment by jakevdp** [comment]
Thanks for the comment – it may be that typed generics would be useful for annotating dtypes, but we haven't looked more deeply into that. I personally tend to be pretty pessimistic about the usefulness of overly-sophisticated Python type annotations: in my experience they lead to far more noise and false positives than actual bugs caught. You end up having to write your code in a stilted way to appease the type checker, or alternatively sprinkle `# type: ignore` throughout, which entirely defeats the purpose. This is one reason why I kept `jax.Array` simple: it hits the sweet spot of enabling reasonable annotations and `isinstance` checks without introducing the diminishing returns of more complicated types.

That said, I think reasonable people can disagree, and if someone wanted to explore using more complicated types, I wouldn't get in their way.

Regarding the bug here: going forward, I don't think you should rely on `KeyArray` as a meaningful annotation. If anything, it should probably be aliased to `KeyArray = Array`, because key arrays are just jax arrays with a different dtype. Again, I think that would hit the sweet spot of being useful without being overly complex.

**Comment by NeilGirdhar** [comment]
> I personally tend to be pretty pessimistic about the usefulness of overly-sophisticated Python type annotations:

I agree with you in general.

Although in Jax, I bet 99% of arrays are either:
```python
RealArray = GenericArray[jnp.floating[Any]]  # or
KeyArray = GenericArray[jnp.generic]
```
Just distinguishing these two would be beneficial for not accidentally passing value arrays as keys and vice versa.

I understand if the Jax team has better things to do though.  Just on my wish list.



> Regarding the bug here: going forward, I don't think you should rely on `KeyArray` as a meaningful annotation.

I'm just using the definition provided by Jax:
```
from jax.random import KeyArray
```
Right now it seems to be `Any` in static analysis.  I guess that'll eventually change to `Array` in some future version of Jax?

**Comment by jakevdp** [comment]
> Right now it seems to be `Any` in static analysis. I guess that'll eventually change to `Array` in some future version of Jax?

In some future version of JAX, `KeyArray` will no longer be a public symbol, because it's an implementation detail that we don't want to expose to the user.

**Comment by jakevdp** [comment]
Finished in https://github.com/google/jax/pull/16781
