### ISSUE TITLE
Unexpected behavior in random number generation leading to inaccurate statistics

### ISSUE THREAD

**Issue by blackblitz** [google/jax#16845]
### Description

I generated a standard normal random sample and then with the sample as the mean another normal random sample with variance 1. The resulting sample represents a random variable resulting from the sum of two standard normal random variables, which thus must have mean 0 and variance 2. However, the sample variance was about 4, but using only the first 9998 of the 10000 sample points of the first sample, the resulting sample variance was about 2.

```python
from jax import numpy, random

key = random.PRNGKey(1337)
s1 = random.multivariate_normal(
    key, numpy.array([0]), numpy.eye(1), shape=(10000,)
)
s2 = random.multivariate_normal(key, s1, numpy.eye(1))
print(numpy.cov(s2, rowvar=False))
s3 = random.multivariate_normal(key, s1[:9998], numpy.eye(1))
print(numpy.cov(s3, rowvar=False))
```

The code above output 4.0274577 and 1.9568015 in that order.

### What jax/jaxlib version are you using?

0.4.13

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.11.3, Linux

**Comment by jakevdp** [comment]
Hi - thanks for the clear question!

This is actually working as expected, because you are re-using the same key, which leads to generation of non-independent samples. If you want to generate independent random samples, you should first split the key:
```python
from jax import numpy, random

key = random.PRNGKey(1337)

key1, key2 = random.split(key)

s1 = random.multivariate_normal(
    key1, numpy.array([0]), numpy.eye(1), shape=(10000,)
)
s2 = random.multivariate_normal(key2, s1, numpy.eye(1))
print(numpy.cov(s2, rowvar=False))
# 2.0262933
```
JAX's random number generator API is different than others you may have encountered in that it does not rely on side-effects to implicitly update a global key, rather you must explicitly split the key each time you use it. You can read more about this at [JAX Sharp Bits: Random Numbers](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#random-numbers).

**Comment by blackblitz** [comment]
Thanks for the helpful answer. It seems that instead of the variance of the sum of two independent standard normal random variables `var(X+Y)`, I estimated that of the double of a single random variable `var(2X)`, which is indeed 4.
