### ISSUE TITLE
bug in shape-checking rules for the case of fori_loop

### ISSUE THREAD

**Issue by MaxiLechner** [google/jax#1686]
The following three loops should all give the same results but the lax.fori_loop throws an error.
Could be related to #1681 

import jax.numpy as np
from jax.lax import fori_loop as fori_loop_jax

def fori_loop_python(lower, upper, body_fun, init_val):
    val = init_val
    for i in range(lower, upper):
        val = body_fun(i, val)
    return val

def body_fun(i,arr):
    a,b = arr
    return a-b[i]*b[i+1], b

s = np.ones([10,10])
r = s.shape[1]-1

E = 0
for i in range(r):
    E -= s[:, i] * s[:, i + 1]
print(E)

E, _ = fori_loop_python(0, s.shape[0]-1, body_fun, (0,s))
print(E)

E, _ = fori_loop_jax(0, r, body_fun, (0,s))[0]
print(E)

**Comment by mattjj** [comment]
Thanks for raising this!

I tweaked the error message to print with some more newlines, to make things line up:

```
TypeError: body_fun output and input must have identical types, got
(ShapedArray(int32[]), ShapedArray(int32[]), (ShapedArray(float32[10]), ShapedArray(float32[10,10])))
and
(ShapedArray(int32[]), ShapedArray(int32[]), (ShapedArray(int32[]), ShapedArray(float32[10,10]))).
```

As you can see, there's an `int32[]` input where we get a `float32[10]` output. The issue is that in the Python case you're relying on `0` getting rank- and dtype-promoted to a `float32[10]`, and that's not allowed for `lax.fori_loop`.

This works (notice I removed a `[0]` from the end):

```python
E, _ = fori_loop_jax(0, r, body_fun, (np.zeros(10),s))
```

We could probably be clearer in our documentation that, unlike the pure Python analogue, the input and output types have to be the same, not just consistent up to NumPy-style broadcasting/promotion.
