### ISSUE TITLE
Possible issue with partial gradient application

### ISSUE THREAD

**Issue by ziofil** [google/jax#1696]
I'm trying to define the derivative of a function at a point, for then compiling it with jit, but either I'm not doing it in the right way (with functools.partial) or there is a problem somewhere.

Define a simple function of x and y and its derivative with respect to x:
```python
from jax import grad

def f(x,y):
    return x+y

df = grad(f, argnums=0)
```

This works:
```python
from functools import partial

partial(f, x = 0.)(y = 1)
# 1.0
```

This doesn't:
```python
from functools import partial

partial(df, x = 0.)(y = 1)
# IndexError: tuple index out of range
```

why?

**Comment by mattjj** [comment]
Thanks for the question!

We should provide a better error message here, but essentially it's because we're trying to differentiate with respect to the first positional parameter (`argnums=0`) but we're not passing any positional arguments (both are passed as keywords).

So this works:

```python
partial(df, 0.)(y = 1)
```

You might think that we could identify keyword arguments with their positions, but unfortunately there's no robust way to do that in Python: it would require inspecting argument signatures, but signatures can be obscured by decorators and the like. The bottom line is that all `df` knows is that you're passing it two keyword arguments, yet its code expects there to be at least one positional argument when `argnums=0`, and `n+1` positional arguments when `argnums=n`.

We should improve this error message to something that explains at least `n+1` positional arguments must be passed by the caller when `argnums=n`, like we do for `jit` with `static_argnums`.
