### ISSUE TITLE
`jax.jit` crashes only as a class method (calling `jax.scipy.linalg.lu_solve`)

### ISSUE THREAD

**Issue by hrkz** [google/jax#17074]
### Description

Hi,

For some research, I have to solve a large set of LU systems (using vmap). I found that my code systematically crashes (on Jupyter "the kernel dies", on a Python script "segmentation fault") when I implement the jit function as a class method and define the first argument as static.

Here is a reduced snippet of the code that fails:
```python
key = jnr.PRNGKey(5)
lhs = jax.random.normal(key, (577, 770, 770))
rhs = jnp.zeros((577, 770))

class Solver:
  def __init__(self, lu):
    self.lu = lu
  def solve(self, rhs_0):
    return jax.vmap(jax.scipy.linalg.lu_solve)(self.lu, rhs_0)

  @partial(jax.jit, static_argnums=(0,))
  def solve_jit(self, rhs_0):
    return jax.vmap(jax.scipy.linalg.lu_solve)(self.lu, rhs_0)
  
lu = jax.vmap(jax.scipy.linalg.lu_factor)(lhs)

solver = Solver(lu)
sol = solver.solve(rhs)
sol = solver.solve_jit(rhs)
```

The first solve passes while the second one fails. I use a NVIDIA A100 so GPU memory should not be a problem here.
What is interesting is that I tried implementing the jit function as a classical function (outside of a class) and this runs without any problem.

### What jax/jaxlib version are you using?

jax 0.4.13, jaxlib 0.4.13+cuda11.cudnn86

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.10.12 running on Linux

**Comment by jakevdp** [comment]
Hi - the issue is that you've marked `self` as static, but `self` contains a very large array `self.lu` which is being embedded as a constant as a result of being declared static, and this is causing your code to exhaust the available memory.

To fix this (and in general) I'd recommend avoiding marking `self` as static when JIT compiling class methods: it can cause problems in other situations as well. You can read more about this at [FAQ: How to use JIT with methods?](https://jax.readthedocs.io/en/latest/faq.html#how-to-use-jit-with-methods).

**Comment by patrick-kidger** [comment]
Generally speaking it's an antipattern to use classes with raw JAX, for the reasons Jake highlights.

Try [Equinox](https://github.com/patrick-kidger/equinox).

**Comment by hrkz** [comment]
Thanks for the quick replies,
Indeed, I was aware that this probably had to do with GPU memory but didn’t know that static args would mean large storage / copies. 

It might be something interesting to mention in the doc, where solutions to JIT compiling code are given.

I’ll probably refactor mine to make it more « function based » instead of « class based », it seems to be the way to go.
