### ISSUE TITLE
build jaxlib from source

### ISSUE THREAD

**Issue by never-to-never** [google/jax#17093]
### Description

I compiled and installed jaxlib from source code according to the official tutorial, and found that the installation failed！
[https://jax.readthedocs.io/en/latest/developer.html#building-jaxlib-from-source](url)
The error message is as follows：
![image](https://github.com/google/jax/assets/27321035/4336c384-a4f9-4431-b961-25efb75adda1)
![image](https://github.com/google/jax/assets/27321035/c04c18b7-f3dd-4885-b80f-b55fc2833ec4)

This tutorial is very simple, but there have been many related problems about compiling and installing jaxlib from source code, please pay attention to this problem!

### Which accelerator(s) are you using?

gpu

### Additional system info

linux

### NVIDIA GPU info

![image](https://github.com/google/jax/assets/27321035/4b933152-6a62-4946-92a6-aa96903d2b33)

**Comment by hawkinsp** [comment]
It looks like the build failed, not installation. I'm not sure why it failed. Is it possible you're setting `LD_PRELOAD` for some reason in your environment? It looks like one part of Bazel was unable to contact another part of Bazel.

I'd recommend installing from a binary package since it's much easier...

**Comment by hawkinsp** [comment]
Closing, because there was no response to my questions. I recommend using a binary installation of JAX, which should be easy and effortless.
