### ISSUE TITLE
unexpected behaviour in jnp.prod

### ISSUE THREAD

**Issue by ShreyanshBardia** [google/jax#17105]
### Description

```
import jax.numpy as np
print(jnp.prod(jnp.array([1,-1]),dtype="uint16")),
print(jnp.prod(jnp.array([1,-1.0]),dtype="uint16"))
```
Output changes when dtype is "uint16" (or any other uint) and input array is changed from int to float. Ideally the output should have been same as that of int case. Below is example of numpy 
```

import numpy as np
print(np.prod(np.array([1,-1]),dtype="uint16")),
print(np.prod(np.array([1,-1.0]),dtype="uint16"))
```

### What jax/jaxlib version are you using?

0.4.14

### Which accelerator(s) are you using?

CPU

### Additional system info

Colab

**Comment by jakevdp** [comment]
Hi - thanks for the report! I think this is expected behavior, as mentioned in [Sharp Bits: Miscellaneous Divergences from NumPy](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#miscellaneous-divergences-from-numpy). This is an unsafe type cast (there is no way to represent a negative floating point value as an unsigned int) and in these cases XLA often makes different decisions than NumPy.

**Comment by ShreyanshBardia** [comment]
Oh okay, thanks for the information. Please forgive my ignorance.
