### ISSUE TITLE
ENH: Reflect changes from numpy namespace refactor Part 3

### ISSUE THREAD

**Issue by mtsokol** [google/jax#17155]
Hi! 
There are new changes coming to NumPy's top namespace in https://github.com/numpy/numpy/pull/24376.
As I checked, jax is impacted by removing `float_`, `complex_` and `issubsctype`. I wanted to ask which approach would you prefer for solving these discrepancies.

1. For `np.float_` and `np.complex_` is see that these are mapped to `float32` or `float64` depending on `jax_default_dtype_bits` configuration (same for complex). [Current NumPy implementation](https://github.com/numpy/numpy/blob/160c16f055d4d2fce072004e286d8075b31955cd/numpy/core/_type_aliases.py#L155) defines `float_` as `double` (i.e. `float64`) and `complex_` as `cdouble` and valid mapping in the Python realm is:
```
float16    | half
float32    | single
float64    | double (depr. float and float_)
float128   | longdouble
complex64  | csingle
complex128 | cdouble (depr. complex_ and cfloat)
complex256 | clongdouble
```
Would you agree to deprecate `float_` and `complex_` names in jax, or would you like keep mapping them to specific sized aliases as right now?

2. For `issubsctype`, would you like to:
  - deprecate and remove it
  - vendor implementation
  - import it from internals (`np.core.numerictypes.issubsctype`)?

**Comment by hawkinsp** [comment]
For `float_` and `complex_` we should remove them from the API (after a deprecation period), following upstream. I believe we might use these internally but that's no problem: they don't need to be in the public API.

For `issubsctype` we should do the same thing. It's only in our public API because it's in NumPy's public API.

**Comment by jakevdp** [comment]
Thanks for bringing this up! You mention `float_` and `complex_`, but will `bool_` and `int_` also be removed from the numpy namespace? I don't see them mentioned in the attatched PR, but it would seem consistent to remove them also.

**Comment by mtsokol** [comment]
> You mention `float_` and `complex_`, but will `bool_` and `int_` also be removed from the numpy namespace? I don't see them mentioned in the attached PR, but it would seem consistent to remove them also.

`float_` and `complex_` are being removed because one of the NEP 52 objectives is to remove all [other aliases](https://numpy.org/devdocs/reference/arrays.scalars.html#other-aliases). Right now I think `bool_` and `int_` won't be dropped.

> Also what about `np.uint`, which is analogous to the others mentioned here, but doesn't have a trailing underscore because it doesn't conflict with any Python builtin name?

That's correct, `np.int_` is meant to differentiate from builtin, therefore `np.uint` is without underscore.

There's one PR with some internal refactoring with a summary of current canonical names and sized aliases: https://github.com/numpy/numpy/pull/24411#issue-1848748494 (table is in the PR description).

**Comment by hawkinsp** [comment]
I'm missing why `int_` and `uint` aren't considered "other aliases" also. They are, in fact, aliases:

```
In [5]: np.int_
Out[5]: numpy.int64

In [6]: np.uint
Out[6]: numpy.uint64
```

**Comment by jakevdp** [comment]
OK, if that's the plan on NumPy's side we'll go with it, but it seems quite inconsistent to drop `float_` and `complex_`, but not drop `bool_`, `int_`, and `uint`.

**Comment by hawkinsp** [comment]
`bool_` isn't an alias, so it could never be dropped.

**Comment by jakevdp** [comment]
I'll comment on the NumPy issue; seems like a better place for that discussion.

**Comment by rgommers** [comment]
I'll note that some of the inconsistencies may be because of the sequencing of actions here. If things are unambiguous, we'd like to remove them from numpy's main namespace, to start narrowing down what's left. But to do that and not break CI of projects like JAX which test against numpy nightlies, those should be cleaned up first. Then there may be follow-ups when we've gotten to decisions about less obvious items.

> I'll comment on the NumPy issue; seems like a better place for that discussion.

Agreed. I see you've done that here already. There's so many decisions to make and quite a few are not 100% clear-cut. So your input is much appreciated.
