### ISSUE TITLE
type <class 'jaxlib.xla_extension.ArrayImpl'>is non-hashable when I use a class member function, while there is no problem when I use a general function.

### ISSUE THREAD

**Issue by zoeStartover** [google/jax#17158]
### Description

Hi, I am confused about using @partial.
I would not like the variable neg was traced, so I added the decorator @partial as the docs.  There was no problem when I ran the following code:

```
from functools import partial
import jax
import jax.numpy as jnp


@partial(jax.jit, static_argnums=(1,))
def f(x, neg):
  return -x if neg else x

arr = jnp.array([1,2])
result = f(arr, True)
```

However, when I added the function f to a class, **ValueError** appeared.

```
from functools import partial
import jax
import jax.numpy as jnp

class Test:
  @partial(jax.jit, static_argnums=(1,))
  def f(self, x, neg):
    return -x if neg else x

t = Test()
arr = jnp.array([1,2])
result = t.f(arr, True)
```

> ValueError: Non-hashable static arguments are not supported, as this can lead to unexpected cache-misses. Static argument (index 1) of type <class 'jaxlib.xla_extension.ArrayImpl'> for function f is non-hashable.

I am new to JAX. I want to know why the problem appears and how can I solve it? Are there any methods that gracefully convert **ArrayImpl**  to other hashable types?

### What jax/jaxlib version are you using?

jax 0.4.13

### Which accelerator(s) are you using?

CPU

### Additional system info

Python: 3.8, OS: WSL Ubuntu 22.04.2

**Comment by jakevdp** [comment]
The reason it differs is because `self` counts as an argument – so you'd have to use `static_argnums=(2,)` for the class method.

However, that doesn't tell the whole story, because you need to tell JAX how to appropriately handle `self` in this case. That's a frequently asked question with a not-so-simple answer that we cover here: https://jax.readthedocs.io/en/latest/faq.html#how-to-use-jit-with-methods

**Comment by zoeStartover** [comment]
> The reason it differs is because `self` counts as an argument – so you'd have to use `static_argnums=(2,)` for the class method if you want `neg` to be static.
> 
> However, that doesn't tell the whole story, because you also need to tell JAX how to appropriately handle `self` in this case. That's a frequently asked question with a not-so-simple answer that we cover here: https://jax.readthedocs.io/en/latest/faq.html#how-to-use-jit-with-methods

Thanks @jakevdp ! 

I carefully read how to use jax in class and it helps me a lot to understand jax. But I still want to solve the problem caused by static arguments not supporting non-hashable type. 

I have a program where the intermediate result computed by some arrays is **type ArrayImpl**.  I would like to use the intermediate result as the condition (if else). So I must use @partial  to ensure the intermediate result is not traced. This creates a contradiction. After I go through other issues, I still can't come up with a appropriate solution. Do you have any ideas?

**Comment by jakevdp** [comment]
Within JIT, you cannot use a JAX array as a static condition. I'd suggest taking a look at [JAX Sharp Bits: Control Flow](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#control-flow), and in particular the subsection [Python Control Flow + JIT](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#python-control-flow-jit).

If you want code to be conditioned on a dynamic value, you should use `lax.cond` rather than `if`/`else`.

**Comment by zoeStartover** [comment]
> Within JIT, you cannot use a JAX array as a static condition. I'd suggest taking a look at [JAX Sharp Bits: Control Flow](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#control-flow), and in particular the subsection [Python Control Flow + JIT](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#python-control-flow-jit).
> 
> If you want code to be conditioned on a dynamic value, you should use `lax.cond` rather than `if`/`else`.

Thanks for your suggestions @jakevdp .I tried another way to achieve my algorithm and it ran correctly. 
.It's very kind of you. I really appreciate it.
