### ISSUE TITLE
Dataclass cannot be hashed.

### ISSUE THREAD

**Issue by bkayalibayarg** [google/jax#17197]
### Description

If `obj` is a dataclass with a call function `__call__` and we register it as a pytree, jitting it (`jax.jit(obj)`) leads to `TypeError: unhashable type`. The same does not happen if `obj` is not a dataclass.

Here is a minimal example:

```python
from dataclasses import dataclass
import jax
import jax.numpy as jnp
from jax.tree_util import register_pytree_node


@dataclass
class A:
    val: jnp.ndarray

    def __call__(self, x):
        return self.val * x


class B:
    def __init__(self, val: jnp.ndarray):
        self.val = val

    def __call__(self, x):
        return self.val * x


def flatten(obj):
    return (obj.val, None)


def unflatten_a(aux_data, children):
    return A(*children)


def unflatten_b(aux_data, children):
    return B(*children)


register_pytree_node(A, flatten, unflatten_a)
register_pytree_node(B, flatten, unflatten_b)

b = B(jnp.zeros(10))
fast_call_b = jax.jit(b)
fast_call_b(1.0)

a = A(jnp.zeros(10))
fast_call_a = jax.jit(a)
fast_call_a(1.0)
```

### What jax/jaxlib version are you using?

jax v0.4.14, jaxlib v0.4.14

### Which accelerator(s) are you using?

CPU

### Additional system info

python 3.10.0, ubuntu 22.04

**Comment by jakevdp** [comment]
Hi - thanks for the question! I think this is working as expected. From the [`dataclass` docs](https://docs.python.org/3/library/dataclasses.html#dataclasses.dataclass):

> By default, [dataclass()](https://docs.python.org/3/library/dataclasses.html#dataclasses.dataclass) will not implicitly add a [__hash__()](https://docs.python.org/3/reference/datamodel.html#object.__hash__) method unless it is safe to do so. Neither will it add or change an existing explicitly defined [__hash__()](https://docs.python.org/3/reference/datamodel.html#object.__hash__) method. Setting the class attribute __hash__ = None has a specific meaning to Python, as described in the [__hash__()](https://docs.python.org/3/reference/datamodel.html#object.__hash__) documentation.

> If [__hash__()](https://docs.python.org/3/reference/datamodel.html#object.__hash__) is not explicitly defined, or if it is set to None, then [dataclass()](https://docs.python.org/3/library/dataclasses.html#dataclasses.dataclass) may add an implicit [__hash__()](https://docs.python.org/3/reference/datamodel.html#object.__hash__) method. Although not recommended, you can force [dataclass()](https://docs.python.org/3/library/dataclasses.html#dataclasses.dataclass) to create a [__hash__()](https://docs.python.org/3/reference/datamodel.html#object.__hash__) method with unsafe_hash=True. This might be the case if your class is logically immutable but can nonetheless be mutated. This is a specialized use case and should be considered carefully.

If you want your dataclass to be hashable, you should follow these instructions. Note that objects must be hashable to be used with `jax.jit`, because JAX's JIT implementation uses a hashtable with the callable as a key in order to avoid recompilation.

Note also that `pytree` registration or non-registration is irrelevant in this case – PyTree registration comes into play when an object is passed as an argument to a transformed function, but does not come into play when an object *is* the transformed function.

Hope that helps!

**Comment by bkayalibayarg** [comment]
Thank you!
