### ISSUE TITLE
Indexing error when looping over zero length arrays

### ISSUE THREAD

**Issue by f0uriest** [google/jax#17264]
### Description

MWE: 

```python
modes_old = jnp.empty((0,3))
modes_new = jnp.empty((4,3))
c_old = jnp.empty(0)
c_new = jnp.empty(4)

def body(i, c_new):
    mask = (modes_old[i,:] == modes_new).all(axis=1)
    c_new = jnp.where(mask, c_old[i], c_new)
    return c_new

fori_loop(0, modes_old.shape, body, c_new)
```

Gives an index error:
```
IndexError: index is out of bounds for axis 0 with size 0
```

Given that `modes_old.shape[0] == 0`, this shouldn't even be entering the body, but it seems like it is? 

### What jax/jaxlib version are you using?

jax==0.4.11, jaxlib==0.4.11

### Which accelerator(s) are you using?

CPU

**Comment by jakevdp** [comment]
Thanks for the report!

I believe this is expected behavior: JAX will always trace the body of the `fori_loop`, even in cases where the loop is executed zero times. See the similar discussion for `while_loop` in #3285.

Note also that there are places in JAX's codebase where behavior similar to what you're seeing is anticipated and accounted for; for example: https://github.com/google/jax/blob/b4f7928a8154435c92f6ce9d7f904c9f99c7132b/jax/_src/lax/linalg.py#L1133-L1137

**Comment by f0uriest** [comment]
Ahh I see, thanks!
