### ISSUE TITLE
Update autodidax to include pmap

### ISSUE THREAD

**Issue by ljppro** [google/jax#17413]
Hi,

The document autodidax is very useful for developers to understand the Jax Core with heavy comments. But somehow it is out of date now, do we have any plan to update this document to align the current Jax, for example, include pmap?

Many thanks

**Comment by mattjj** [comment]
Thanks for the kind words about Autodidax!

Actually Autodidax was added a couple years after `pmap` came into existence, so it's not that Autodidax is out-of-date. It just that Autodidax doesn't include everything.

I agree it'd be great to add `pmap`, or its soon-to-be successor `shard_map`. But I'm not sure when we'll be able to make it a priority.

I'll leave this issue open but with a low priority score. Hopefully we can get to it someday!

Thanks for the request.

**Comment by mattjj** [comment]
There's a good chance we'll end up rewriting autodidax, and when we do we'll likely include a model of `shard_map`.

However, I want to close this issue as stale since it's nominally about the current autodidax and `pmap`.

Thanks for raising it! As a result, we'll have `shard_map` in mind for autodidax v2.
