### ISSUE TITLE
 jax.random.randint slowdown under jax.vmap transformation

### ISSUE THREAD

**Issue by Howuhh** [google/jax#17462]
### Description

Hi! I have a situation where simply adding even one line with `jax.random.randint` generation slows down the code dozens of times, in fact completely eliminates all the benefits of parallelization using vmap. I made a simple demonstration (it doesn't reflect what the code actually looks like in my project, just the high level logical structure):

```python
import jax
import jax.numpy as jnp
import time
import numpy as np
from flax import struct

TIMESTEPS = 10_000
NUM_ENVS = 50


class State(struct.PyTreeNode):
    obs: jax.Array


def step(state, action):
    options = (
        lambda: state.obs + jnp.array((0, 1, 7)),
        lambda: state.obs + jnp.array((5, 0, 1)),
        lambda: state.obs + jnp.array((0, 1, 2)),
        lambda: state.obs + jnp.array((4, 0, 3)),
        lambda: state.obs + jnp.array((0, 3, 4)),
    )
    obs = jax.lax.switch(action, options)
    
    return state.replace(obs=obs)


def rollout(key):
    action_keys = jax.random.split(key, TIMESTEPS)

    def _body_fn(state, key):
        action = jax.random.randint(key, shape=(), minval=0, maxval=5)
        # action = jnp.asarray(np.random.randint(0, 5))  # with this vmap will work okay, linear scaling
        state = step(state, action)
        return state, None

    state = State(obs=jnp.array((0, 0, 0)))
    
    return jax.lax.scan(_body_fn, state, action_keys)[0]

def run_single():
    key = jax.random.PRNGKey(0)
    jit_rollout = jax.jit(rollout)

    jit_rollout(key).obs.block_until_ready()

    print(f"Benchmarking single...")
    start = time.time()
    jit_rollout(key).obs.block_until_ready()
    elapsed_time = time.time() - start

    fps = TIMESTEPS / elapsed_time
    print(f"Elapsed time: {elapsed_time:.5f}s, FPS: {fps:.0f}")
    return fps

def run_vmap():
    key = jax.random.PRNGKey(0)
    keys = jax.random.split(key, NUM_ENVS)
    
    jit_rollout = jax.jit(jax.vmap(rollout))

    jit_rollout(keys).obs.block_until_ready()
    print(f"Benchmarking vmap with {NUM_ENVS} envs...")
    start = time.time()
    jit_rollout(keys).obs.block_until_ready()
    elapsed_time = time.time() - start

    fps = (TIMESTEPS * NUM_ENVS) / elapsed_time
    print(f"Elapsed time: {elapsed_time:.5f}s, FPS: {fps:.0f}")
    return fps

single_fps = run_single()
vmap_fps = run_vmap()
print(f"FPS increase with vmap: {vmap_fps / single_fps}")
```

Result with numpy sampling:
```
Benchmarking single...
Elapsed time: 0.00019s, FPS: 52363346
Benchmarking vmap with 50 envs...
Elapsed time: 0.00007s, FPS: 6944211921
FPS increase with vmap: 132.6158940397351
```

Results with jax sampling
```
Benchmarking single...
Elapsed time: 0.00160s, FPS: 6253622
Benchmarking vmap with 50 envs...
Elapsed time: 0.03535s, FPS: 14144619
FPS increase with vmap: 2.261828482784204
```
I tested it on m1 cpu and A100 GPU with same results. I'm a bit confused, as this code is generally similar to almost all train loops used in RL + jax based environments. If it slows down that much, how do one work with it? Maybe I'm doing something wrong?

### What jax/jaxlib version are you using?

jax v0.4.14, jaxlib v0.4.11

### Which accelerator(s) are you using?

CPU, A100 GPU

### Additional system info

python 3.8, m1

**Comment by jakevdp** [comment]
Thanks for the question!

Regarding the NumPy baseline: I don't think this is really a fair comparison, because the numpy version does not reference `key`, and so all `jax.random` calls are dead code that are removed by the compiler. Additionally, the random values are only computed once at trace-time, so every step of the `scan` within every batch of the `vmap` is using the exact same "random" integer. This means that the unbatched version is very un-intensive computationally, and so via batching the compiler can make much better use of the device.

By contrast, in the JAX version you are computing a new set of random ints for each batch and each timestep (that's 500,000 random ints total vs. the 1 total in your numpy version!). This means that each batch of the `vmap` is more computationally intensive, so it gives the compiler much less "head-room" for the batched version of the computation.

Unless there's a detail I'm overlooking, I think this is behaving as expected. What do you think?
