### ISSUE TITLE
Slow XLA compile and high memory usage of `grad(odeint)` on high-dim problem

### ISSUE THREAD

**Issue by jacobjinkelly** [google/jax#1769]
(This is using the latest version of JAX, in particular this issue does not seem to be due to debug info that used to be traced).

[Here](https://github.com/jessebett/jax/blob/35a0eff020102d0a0d229d8cfbc69da42ecf9c84/examples/nodes_mnist_bug.py) is the code to reproduce the bug. It involves integrating a 64-dimensional ODE whose dynamics function is specified by a MLP. Notice I have slightly modified `odeint` to count the number of function evaluations (NFE) of the solver (see [here](https://github.com/jessebett/jax/blob/5f1fe586d1ad1477ddb35c8055769750bb573f35/jax/experimental/ode.py)) but I'm not using it in this example (in particular `build_odeint` ignores the NFE output).

I am able to run the code with JUST the forward pass (i.e. no use of `grad`), but I get the following warning:
```
2020-01-15 18:48:50.923917: E external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:55] 
********************************
Very slow compile?  If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
********************************
```
I am able to run the code with the backward pass (i.e. including `grad`) on the CPU when allocating 8G of memory (taking about 1 hour). The same job fails on the GPU when allocating 16G of memory. I got the job running on the GPU when allocating 32G of memory, which took about 7 hours.

[Here](https://drive.google.com/file/d/1PTwDLFmWjXlatTYuKiNSJdty8yhNrWvj/view?usp=sharing) is the XLA dump for the CPU, and [here](https://drive.google.com/file/d/1liAVdI7z3QBeneEbDGfIZ1SjuQTs1Ilu/view?usp=sharing) for the GPU when running the code with the backward pass.

**Comment by jessebett** [comment]
@mattjj This is what we were talking about in meeting with @duvenaud.

I rebased my fork to `google/jax#master` and Jacob confirmed that the memory issues are still a problem.

**Comment by mattjj** [comment]
Thanks for the ping! Sorry to hear it wasn't magically fixed already :)

**Comment by mattjj** [comment]
It's a US holiday today, but I'll follow up on this tomorrow (when I can rope in the XLA team if needed).

**Comment by mattjj** [comment]
I usually give up on compiles if they take more than a couple seconds! I'm always surprised at the patience our users sometimes give JAX.

Long compiles are bugs, so I'm really glad you raised this.

**Comment by mattjj** [comment]
I downloaded the xla_gpu directory you posted, and looked at module_4327.before_optimizations.txt, which was the largest before_optimizations.txt file (a whopping 217MB program!). The first 10k+ lines (!!) are all reshapes and unpacks, and even unpacking arrays down to the scalar level. I didn't look any further; my guess was there was something pathological happening around packing/unpacking of arrays.

Flattening pytrees of arrays down to single arrays using `ravel_pytree` can generate slicing/reshaping/packing/unpacking operations, which aren't needed if you just work directly with pytrees, i.e. if you just keep `params` as a pair of 2D arrays and never flatten them. But for this small example the pytree being flattened wasn't very big, so it couldn't on its own be generating so much code.

The real culprit was [this argument splatting](https://github.com/jessebett/jax/blob/35a0eff020102d0a0d229d8cfbc69da42ecf9c84/examples/nodes_mnist_bug.py#L70), where `flat_params` is the parameters splatted into a length-4224 tuple of scalars. That is, because of the `*` there, we're not just passing around the flattened array of shape `(4224,)`, but things were actually getting unpacked down to the scalar level. That was ultimately generating a ton of code (and calling `grad` increases the program size further, since there's both a forward and backward pass).

I [pushed a commit](https://github.com/jessebett/jax/commit/bffa9d3ae7dc971b8b5bdf6c485b84fbf0b95e35) to show the kind of revision I'd recommend. With that revision on the CPU backend, `loss` compiles and executes in 0.87sec and `grad(loss)` compiles and executes in 2.73sec. (Waiting 2.7sec is still testing my patience for compile times, but I'll give it a pass this time...)

You'll notice that in the commit I'm probably not producing the right VJP, because it wasn't immediately clear how to unpack the `result[-3]` array correctly. So I just made sure the shapes matched:

```python
    # return tuple([result[-5], vjp_times] + list(result[-3]) + [result[-1]])  # replaced this line
    dummy_hack = result[-3][:65*64].reshape(65, 64)
    dummy_hack2 =  result[-3][-64:]
    return (result[-5], vjp_times, dummy_hack, dummy_hack2, result[-1])
```

I'm pretty sure the right numbers are in there somewhere, but that's something you'll need to fix!


Unpacking arrays into scalars is a bad idea for performance in normal NumPy, but it's not catastrophic because we're just executing things rather than staging out and then attempting to super-optimize a program. That is, JAX kind of amplifies the NumPy performance model: patterns that are bad for NumPy performance can be _really super bad_ for JAX.

This seems worth trying to catch automatically and warn the user about. Actually, the way I caught the issue is I planted a debugger trace in [the `__iter__` method for JAX arrays](https://github.com/google/jax/blob/03b2ae6d5907e76472c0d43e5d7793e80523bb95/jax/lax/lax.py#L1495-L1502), which fired when the array being unpacked was bigger than size 10. It might be good to emit a warning in that case: any time a user is unpacking an array bigger than some small size, e.g. by  calling `list(arr)`, it's probably a mistake. So this might end up helping others avoid performance bugs too!

WDYT?

**Comment by jacobjinkelly** [comment]
Thanks for the very detailed reply, it makes perfect sense why this would cause such a slowdown.

I implemented your suggested fix and it fixed the long-compilation times. Since this issue appears to be independent of my slightly modified version of `odeint`, I'll refer to how the change would look like in master's version. The return of `vjp_odeint` ([here](https://github.com/google/jax/blob/master/jax/experimental/ode.py#L369)) should be changed to:
```
return tuple(result[-4], vjp_times, *unravel_args(result[-2]))
```
where I used `unravel_args` which is instantiated [here](https://github.com/google/jax/blob/master/jax/experimental/ode.py#L298) to construct the flattened dynamics function for the ode solver. 

As I recall, the original reason I was unpacking the flattened parameters is because otherwise I was getting the following error triggered [here](https://github.com/google/jax/blob/master/jax/api.py#L1732) having to do with the VJP not matching the structure of the inputs to the function. So I think this fix, in addition to the performance issue, would also make `odeint` more usable as users are no longer forced to unpack the flattened params.

I definitely agree with you that it'd be a good idea to warn the user if they're unpacking large arrays as I'm sure this could come up in a number of scenarios!
