### ISSUE TITLE
disable nvidia package downloads?

### ISSUE THREAD

**Issue by OH-AU** [google/jax#17974]
When installing jax via pip, by default it includes all of the prerequisite nvidia packages it needs which totals about 3GB on extraction.
Downloading nvidia_cublas_cu12-12.2.5.6-py3-none-manylinux1_x86_64.whl (417.8 MB)
Downloading nvidia_cuda_cupti_cu12-12.2.142-py3-none-manylinux1_x86_64.whl (13.9 MB)
Downloading nvidia_cuda_nvcc_cu12-12.2.140-py3-none-manylinux1_x86_64.whl (21.3 MB)
Downloading nvidia_cuda_runtime_cu12-12.2.140-py3-none-manylinux1_x86_64.whl (845 kB)
Downloading nvidia_cudnn_cu12-8.9.4.25-py3-none-manylinux1_x86_64.whl (720.1 MB)
Downloading nvidia_cufft_cu12-11.0.8.103-py3-none-manylinux1_x86_64.whl (98.6 MB)
Downloading nvidia_cusolver_cu12-11.5.2.141-py3-none-manylinux1_x86_64.whl (124.9 MB)
Downloading nvidia_cusparse_cu12-12.1.2.141-py3-none-manylinux1_x86_64.whl (195.3 MB)
Downloading nvidia_cuda_nvrtc_cu12-12.2.140-py3-none-manylinux1_x86_64.whl (23.4 MB)
Downloading nvidia_nvjitlink_cu12-12.2.140-py3-none-manylinux1_x86_64.whl (20.2 MB)

I already have all of these packages installed on my system and there is no reason for them to be installed esp as they're all shared libraries. Would it be possible to make this an optional install - perhaps an option to disable all as well as for each of the individual packages in case someone doesn't have them all? The issue is compounded when 100's of users on the same system install multiple environments with this requirement. (And I do appreciate the complexity of nvidia's (in?)compatibility between packages).
Thanks.

**Comment by hawkinsp** [comment]
Indeed, that's already supported: https://jax.readthedocs.io/en/latest/installation.html#pip-installation-gpu-cuda-installed-locally-harder
There's a link to this doc from the README (https://github.com/google/jax/blob/8f08ee9c201a1df65f8cadbb6658342342a77960/README.md?plain=1#L403).

We don't encourage that path, because it's much more complicated for users and you're much more likely to get it wrong (e.g., not install the right package versions). But it's there if you want it.
