### ISSUE TITLE
Does JAX support PRNG manager to ease the usage of PRNG keys?

### ISSUE THREAD

**Issue by youkaichao** [google/jax#17998]
It seems JAX code requires manually splitting keys each time we need a new key. Does JAX have any functionality like below, so that we can use PRNG keys more easily?

```python
# intended usage:
key = random.PRNGKey(0)  # or any other initial seed
with PRNGManager(key) as manager:
    output = jnp.array(random.normal(manager.new_key(), (3, 3)))
    sequence = jnp.stack([random.normal(subkey) for subkey in manager.new_n_keys(5)])
```

Currently, we have to manually split keys and keep track of the current key:

```python
key = random.PRNGKey(0)  # or any other initial seed
key, new_key = random.split(key, 2)
output = jnp.array(random.normal(new_key, (3, 3)))
key, *new_keys = random.split(key, 6)
sequence = jnp.stack([random.normal(subkey) for subkey in new_keys])
```

The implementation of `PRNGManager` can be very simple:

```python
from typing import List, Union

import jax.random as random
import jax.numpy as jnp

class PRNGManager:
    def __init__(self, key: jnp.ndarray):
        self.initial_key = key
        self.current_key = None

    def __enter__(self) -> 'PRNGManager':
        self.current_key = self.initial_key
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        # You can add any cleanup or handling here if needed
        pass

    def new_key(self) -> jnp.ndarray:
        keys = random.split(self.current_key, 2)
        self.current_key = keys[0]
        return keys[1]

    def new_n_keys(self, n: int) -> List[jnp.ndarray]:
        keys = random.split(self.current_key, n + 1)
        self.current_key = keys[0]
        return list(keys[1:])

```

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

**Comment by jakevdp** [comment]
Hi - thanks for the question! JAX doesn't support anything like this, and that is for good reason: your context manager hides mutable state (e.g. when it updates `self.current_key` within the `new_key()` method), and this sort of side-effect breaks JAX's computational model (See [JAX Sharp Bits: Pure Functions](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#pure-functions) for some discussion of this).

State-based RNGs like the one you're constructing here are definitely convenient in some cases, but they complicate program analysis in a way that makes JIT compilation, autodiff, parallelization, and other transformations much more difficult to implement robustly. You can read more about this and other factors that played into JAX's PRNG design at [JAX PRNG Design](https://jax.readthedocs.io/en/latest/jep/263-prng.html).

Note however that some downstream packages do implement something like what you have in mind: for example `flax` modules have a [`make_rng`](https://flax.readthedocs.io/en/latest/api_reference/flax.linen/module.html#flax.linen.Module.make_rng) method that operates somewhat like your `new_key` method: the reason this works is that flax imposes strict limits on the contexts in which this method can be called, and employs some tricks to plumb the implicit state through any JAX transformations. A tool like this would not work in more general JAX execution settings.

Likewise, your context manager would certainly work in the simplest of cases (e.g. top-level execution), but once you try using it in more general cases, e.g. in combination with transformations like `jit` and `vmap`, I think you'll find a lot of nasty corner cases that will silently lead to unexpected results due to its impure semantics breaking the contract of JAX transformations.

I hope that helps, and please feel free to weigh-in if anything is unclear!

**Comment by youkaichao** [comment]
Oh, I was thinking that we can use the context manager inside functions. We can keep pure functions, and just simplify the code inside pure functions.

Previously:

```python
def f(key):
	key, new_key = random.split(key, 2)
	output = jnp.array(random.normal(new_key, (3, 3)))
	key, *new_keys = random.split(key, 6)
	sequence = jnp.stack([random.normal(subkey) for subkey in new_keys])
```

Preferred:

```python
def f(key):
	with PRNGManager(key) as manager:
	    output = jnp.array(random.normal(manager.new_key(), (3, 3)))
	    sequence = jnp.stack([random.normal(subkey) for subkey in manager.new_n_keys(5)])
```

**Comment by jakevdp** [comment]
Sure, like I said there are definitely limited contexts in which something like this would work. But in general it won't work (and the failures will be silently-incorrect results rather than errors) so I think it's not an API that JAX would ever provide.

Of course, there's nothing stopping you from defining and using such a context manager yourself, but please just be aware that you have to use it carefully!

**Comment by youkaichao** [comment]
Yeah, I can of course use it by my own. I just wondering if this can save some time for JAX users. Say that if we can avoid the reference of `PRNGManager` across functions, then this would be safe.

**Comment by jakevdp** [comment]
A utility won't save time in the long-run if it leads to hard-to-detect bugs.

**Comment by jakevdp** [comment]
Thanks for the request - I'm going to close this as we don't have any plans to add a stateful random helper.
