### ISSUE TITLE
How does jax implement jax.lax.psum, jax.lax.all_gather and jax.lax.all_to_all?

### ISSUE THREAD

**Issue by anirudhitagi** [google/jax#18428]
### Description

Hello all,

I am new to Jax and I am exploring collective communications and so I wish to understand how does Jax implement `jax.lax.psum`(All reduce), `jax.lax.all_gather` and `jax.lax.all_to_all` ?

Is it implemented as Ring, Binary tree, halving-doubling or something else?
And does this implementation depend on the hardware it is being deployed on? For context, I am experimenting with TPU v-3 (v3-8 and v3-32)

Any documentation or explanation would be most appreciated !

Thanks and Regards,
AI

### What jax/jaxlib version are you using?

jax 0.4.19, jaxlib 0.4.19

### Which accelerator(s) are you using?

TPU

### Additional system info

tpu-ubuntu2204-base

**Comment by sharadmv** [comment]
> And does this implementation depend on the hardware it is being deployed on?

I believe XLA GPU uses NCCL for collectives on GPU and XLA TPU emits specific collective algorithms depending on the topology and set of devices being used for the collectives. I am unsure of the choice of algorithm so hopefully someone else can chime in on that front.

**Comment by anirudhitagi** [comment]
@jakevdp , @sharadmv , @pschuh 
Could you please help me understand this? To my best efforts I could not find any documentation explaining this. If you could point me in that direction, it would be really helpful! 

Best regards,
AI

**Comment by pschuh** [comment]
Looks like nccl may switch between ring and tree based on which performs best: https://github.com/NVIDIA/nccl/issues/256 . 

Note that all-reduce is normally reduce-scatter + all-gather. So if an impl uses a ring for all-reduce, all-gather is likely also a ring.

On a TPU, because the interconnects are configured entirely in chip-to-chip torus or meshes (depending on if you're using a subslice of a torus), its pretty hard to have something that doesn't look 'ring-like'. I'm pretty sure that ring-reductions are near optimal for TPU simply because all communication must happen through these neighbor-to-neighbor connections, the only caveat is that the optimal algorithm probably utilizes all 3 axes of the torus.

https://cloud.google.com/tpu/docs/system-architecture-tpu-vm might have more information.

**Comment by anirudhitagi** [comment]
Thank you so much for the clarification!
