### ISSUE TITLE
Installation Stuck

### ISSUE THREAD

**Issue by MelonPy** [google/jax#1864]
Hello,
When I tried to install your program it got stuck at 'INSTALLING NGROK'.
Do you have any solutions ?
Thanks

**Comment by hawkinsp** [comment]
Thanks for the issue report.

I don't think this is a JAX issue per se, but it's probably related to the package management system you are using to install JAX (`pip`? `conda`?). You'd need to provide more details of your exact setup and what commands you ran, but note that `ngrok` isn't a direct dependency of JAX, although perhaps it is an indirect dependency in your package manager. I doubt it, though.

I'm closing this because I don't think there's anything actionable for JAX here.
