### ISSUE TITLE
How to deal with the re-implementation of numpy functions depending of C functions?

### ISSUE THREAD

**Issue by epignatelli** [google/jax#1900]
As per title, is there / what is the procedure to re-implement numpy functions that depend on C functions, e.g. [`numpy.nonzero`](https://github.com/numpy/numpy/blob/v1.17.0/numpy/core/fromnumeric.py#L1759-L1849), depending on [`PyObject_NonZero`](https://github.com/numpy/numpy/blob/4b1cd4e118e543260cbe9c7fba51a1de37e03618/numpy/core/src/multiarray/item_selection.c#L2215-L2475)?

**Comment by hawkinsp** [comment]
In general, JAX implements all of its NumPy operations in terms of the primitive operations in `lax` (or in terms of other NumPy operations).

Rather than explain in detail, I thought it was probably quicker just to implement it:
https://github.com/google/jax/pull/1905

Take a look: does it make sense how it works?

Note that `nonzero` is unusual in the JAX world because its output shape is data-dependent. This means it cannot be `jit`ted unless we add more support for dynamic shapes to JAX. However, it's probably still useful to have an implementation even if it cannot be `jit`ted.

I hope that helps!

**Comment by epignatelli** [comment]
Thanks @hawkinsp, that example implementation is very clear.

Are you maintaining a list on non `jit`table methods, or just implementing it with those limits?
