### ISSUE TITLE
ImportError: cannot import name 'index_update' from 'jax.ops' (/home/home/.local/lib/python3.8/site-packages/jax/ops/__init__.py)

### ISSUE THREAD

**Issue by er1c-cartman** [google/jax#19211]
Please:

- [ ] Check for duplicate requests.
- [ ] Describe your goal, and if possible provide a code snippet with a motivating example.

Hi. I'm trying to run PRIEST, and the following link is about priest package
https://github.com/fatemeh-rastgar/PRIEST

The problem I'm having is I tried to run "rosrun priest planner_holonomic.py", but this error is happening

home@home-B760M-DS3H-DDR4:~/priest_ws/src$ rosrun priest planner_holonomic.py
Traceback (most recent call last):
  File "/home/home/priest_ws/src/PRIEST/priest/src/planner_holonomic.py", line 21, in <module>
    import mpc_expert
  File "/home/home/priest_ws/src/PRIEST/priest/src/mpc_expert.py", line 9, in <module>
    from jax.ops import index_update, index
ImportError: cannot import name 'index_update' from 'jax.ops' (/home/home/.local/lib/python3.8/site-packages/jax/ops/__init__.py)

I guess it's a problem with version of jax and jaxlib, but to be honest due to my lacking skills, I have no idea which version should I have to use to run this package.

What should I do to run this package??

Best regards :)

**Comment by jakevdp** [comment]
`jax.ops.index_update` was [deprecated](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-2-22-oct-12-2021) in JAX v0.2.22, and [removed](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-3-2-march-16-2022) in JAX v0.3.2. Instead of `jax.ops.index_update(x, i, y)`, you can use `x.at[i].set(y)`.

If you are using another package that calls `index_update` so that you're unable to change the call-site, then you'll have to use `jax` version 0.3.1 or older:
```
pip install jax[cpu]==0.3.1 -f https://storage.googleapis.com/jax-releases/jax_releases.html
```
You can find more information about installing older jaxlib versions at https://jax.readthedocs.io/en/latest/installation.html#installing-older-jaxlib-wheels.
