### ISSUE TITLE
Add scipy.stats.sem to jax.scipy.stats

### ISSUE THREAD

**Issue by carlosgmartin** [google/jax#19226]
Add [scipy.stats.sem](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.sem.html) to [jax.scipy.stats](https://jax.readthedocs.io/en/latest/jax.scipy.html#module-jax.scipy.stats). I can submit a PR for this.

**Comment by jakevdp** [comment]
Sounds good, feel free to tag me in the PR for review.

**Comment by rajasekharporeddy** [comment]
Hi @carlosgmartin 

Since the PR #19302 has been merged, this issue is resolved. I have tested a sample code on Colab with JAX version 0.4.24 and it works fine without any error.

```python
from jax.scipy.stats import sem
import jax.numpy as jnp
a = jnp.arange(20).reshape(5,4)
print(sem(a))
sem(a, axis=None, ddof=0)
```
Output:
```
[2.828427 2.828427 2.828427 2.828427]
Array(1.2893796, dtype=float32)
```
Also compared this result with that of `scipy.stats.sem`'s and it gives the same result (except the final output dtype of JAX is float32). 
```python
import numpy as np
from scipy import stats
a = np.arange(20).reshape(5,4)
print(stats.sem(a))
stats.sem(a, axis=None, ddof=0)
```
Output:
```
[2.82842712 2.82842712 2.82842712 2.82842712]
1.2893796958227628
```
You can find the [gist](https://colab.research.google.com/gist/rajasekharporeddy/56625e9824b7a5e77d7557eedf512445/-19226.ipynb) for your reference.

Could you please check and confirm the same

Thank you.
