### ISSUE TITLE
array.ravel() takes orders of magnitude longer

### ISSUE THREAD

**Issue by greydanus** [google/jax#193]
After switching a function from Autograd to Jax, I found that it ran 10^3 times slower. I tried to isolate the reason for this slowdown, and it appears to be the ravel function.

NumPy - 1.7 microseconds
Autograd - 2.8 microseconds
Jax - 173 microseconds

See example:
https://drive.google.com/file/d/1mkzMPPqkX-x_bTkiLXGyXXKiquN93l9I/view?usp=sharing

Any idea how to fix this?

**Comment by mattjj** [comment]
Thanks for digging into this, and making such a concise test.

My first thought was that this is a performance bug, but I decided I should poke at it a bit first!

**Comment by greydanus** [comment]
Here's the python code for the test:
```python
def test_func():
    result = np.ones((10, 10)).ravel()

import numpy as np
print('Running with NumPy:')
%timeit test_func()

import autograd.numpy as np
print('\nRunning with NumPy (Autograd):')
%timeit test_func()

import jax.numpy as np
print('\nRunning with Jax:')
%timeit test_func()
```

**Comment by mattjj** [comment]
@greydanus and I talked a bit off-thread. I'll summarize here for posterity!

There are two things going on here: NumPy's `ravel` is really fast (because it doesn't even do a copy), and separately the dispatch overheads for the XLA client that JAX uses are currently really slow (like ~70us per call on my machine, compared to 0.5us for NumPy). There's no fundamental reason JAX couldn't do the just as well as NumPy in both of these cases (especially the latter), but these things haven't been optimized yet. (Contributions welcome!)

Those two effects work together to make the difference particularly stark in this test: we pair JAX's currently-slow dispatch with really fast-to-execute operations. If the operations took more time (like milliseconds to multiply large matrices) then the fixed-size overhead of ~70us wouldn't look so bad. But on small operations, it's really costly.

@greydanus explained that his workload involves a lot of small operations. So other than waiting for JAX's XLA client to lower dispatch overheads, or for the JAX team to implement reshape-without-copy, what can JAX do for workloads with lots of small operations?

One answer is `jit`! That ~70us dispatch cost is for any JIT-compiled operation, no matter its size. If you can use `jit` to compile a lot of your operations together, you still only have to pay that dispatch cost once. In fact, using `jit` will compile away all the Python and tracing overheads (e.g. for doing autodiff), reducing overheads further. And the biggest win of all is that it gives a chance for XLA to end-to-end optimize the code, which includes things like eliminating unnecessary copies.

Another answer is that if NumPy covers your use case well, maybe because you can't use `jit` and you don't need to run on accelerator hardware, consider sticking with [Autograd](https://github.com/hips/autograd). Luckily, switching back and forth should be pretty easy: all your NumPy and `grad` code can stay the same, and you just need to change the import statement at the top. 

Finally, in addition to improving the overheads in the XLA client and reducing copies, there's one more avenue for getting JAX to be always-at-least-as-fast-as-Autograd on CPU: we have some ideas to get JAX to use NumPy (rather than XLA) on CPU when there's no JIT going on. That's still on the drawing board, though.

I'm going to close this issue for now because things are working as expected in this example, but we'll certainly keep improving JAX's dispatch performance.

**Comment by greydanus** [comment]
Thanks for the thorough response, Matt. The long-horizon idea of getting JAX to use NumPy on CPU would be pretty awesome for my use case (eg. run 200+ debugging tests, scaled down experiments, etc. on CPU and then run 5 big jobs on GPU once everything is working)
