### ISSUE TITLE
`broadcast_to` raise Disallowed host-to-device transfer when used inside jax.jit

### ISSUE THREAD

**Issue by Conchylicultor** [google/jax#19334]
### Description

Reproduction:

```python
@jax.jit
def test():
  return jnp.broadcast_to(0.1, (4,))

with jax.transfer_guard('disallow'):
  test()
```
Fail with:
```
XlaRuntimeError: INVALID_ARGUMENT: Disallowed host-to-device transfer: aval=ShapedArray(float32[]), dst_sharding=SingleDeviceSharding(device=TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0))
```

The `0.1` is a constant in the XLA graph, so this should not trigger any host-to-device transfer.

It's possible to silence the issue with `jnp.broadcast_to(jnp.asarray(0.1), (4,))` but original issue is a bug.

### What jax/jaxlib version are you using?

HEAD

### Which accelerator(s) are you using?

TPU

**Comment by jakevdp** [comment]
Thanks for the report. It looks like the issue comes from the implementation of `lax.asarray` (used by `broadcast_to`), which uses `device_put` for non-jax-array inputs: https://github.com/google/jax/blob/31efc2cc6ae6f7f20b78c742def23afcd6507625/jax/_src/lax/lax.py#L129-L137

I think we need to use a different strategy for converting scalars to arrays if we want to avoid triggering the transfer guard here.

**Comment by jakevdp** [comment]
#19511 should fix this
