### ISSUE TITLE
JAX issue with Conv

### ISSUE THREAD

**Issue by anirbanl** [google/jax#1934]
![image](https://user-images.githubusercontent.com/44803404/71652596-adef3980-2cf4-11ea-856d-5773ab6687fb.png)

I am facing the above error which trying to use a simple Conv layer in JAX (Trying on MNIST images). Not sure what is the issue. Any pointer will be appreciated. Thanks!

**Comment by mattjj** [comment]
I've written this bug a few times myself!

The issue is that `net_init` returns a pair, where the first element is the output shape and the second element is the parameters. So you likely want a line more like

```python
_, net_params = net_init(rng, in_shape)
```

We used to have [a small example in the README](https://github.com/google/jax/tree/1efe648d35a8531600ea3e902b203f48adabff18#neural-net-building-with-stax), but I just realized that I deleted it and never added it back anywhere...

Does that help?

**Comment by anirbanl** [comment]
Oops, I realize the mistake. Thanks for the prompt response. It works!

**Comment by mattjj** [comment]
We should revise stax to make this error impossible. Also, it's not necessary any more for the `init_fun`s to do shape inference manually: [JAX can do shape inference automatically with `eval_shape`](https://github.com/google/jax/blob/fd6067471e08862547e76fd0bd80eaa3dbf69b53/jax/api.py#L1949)! (It's just that stax's design is old, as it came into existence before a lot of JAX features...)
