### ISSUE TITLE
jax.numpy.arange resists JIT even with static shape 

### ISSUE THREAD

**Issue by njkrichardson** [google/jax#19433]
### Description

I'm aware that JIT requires statically shaped arrays, which prevents using `np.arange` in some cases. However, I seem to have stumbled across a case that does have static shapes and still raises an exception. 

```python 
import jax.numpy as np 
from jax import jit 

@jit 
def f(x: np.ndarray) -> np.ndarray: 
     return np.arange(x[0] - 1, x[0] + 1)

f(np.zeros(1).astype(int)) 
```

I may be misunderstanding, but in my head `arange` always returns an array of length `2` but JIT still doesn't allow this. 

I can work around this with something like 

```python 
return np.arange(-1, 1) + x[0] 
```

I'm just curious what mechanism is being used to infer/enforce static shapes and why it fails to determine that the first case is static. 

### What jax/jaxlib version are you using?

0.4.20 0.4.20

### Which accelerator(s) are you using?

CPU 

### Additional system info?

1.26.1 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] uname_result(system='Linux', node='12a91740ac7e', release='6.5.11-linuxkit', version='#1 SMP PREEMPT_DYNAMIC Wed Dec  6 17:14:50 UTC 2023', machine='x86_64')

**Comment by jakevdp** [comment]
Hi - thanks for the question!

It's not true that your `arange` will always return an array of length 2 – that requires knowing the values in the array `x`, and these values are not known at compile time.

**Comment by njkrichardson** [comment]
I'm sorry, there was a typo in my original question. You're absolutely right (for what was written), but I think in the case I'm referring to (using the same value) it is static.

**Comment by jakevdp** [comment]
Ah, I see what you're asking.

The issue here is that `x[0] - 1` is a traced value, and `x[0] + 1` is also a traced value. At compile time, these represent any  integer value, and `np.arange(any_integer_value, any_other_integer_value)` does not have a static shape.

Now, it's true that JAX *could* add trace-time logic to do the sort of algebraic simplification that would allow us to infer the static shape, but JAX tracing is not implemented in this way. In practice, going down this road turns out to be *very* complicated in the general case (some of the `shape_poly` code is similar in nature to this). One of the strengths of JAX is its relative simplicity of implementation, so we probably won't ever add that sort of additional algebraic simplification logic at trace time.

Does that make sense?

**Comment by njkrichardson** [comment]
Sure, totally fair: thanks very much for taking the time to sketch out that design decision.
