### ISSUE TITLE
Inconsistent TPU Core Detection on v5p-8 Instance

### ISSUE THREAD

**Issue by mosmos6** [google/jax#19493]
### Description

Hello JAX team,

I am encountering an issue with JAX where only 4 TPU cores are being detected on a Google Cloud Platform TPU VM instance configured with 8 cores (type v5p-8). This issue persists even after ensuring proper installation and configuration.

**Environment**:
- TPU VM Type: v5p-8 (supposedly 8 cores) (preemptible)
- JAX version: [0.4.23]
- JAXlib version: [0.4.23]
- Python version: [3.10]
- Google Cloud SDK version: [460.0.0]

**Steps to Reproduce**:
1. Created a TPU VM on GCP with `--accelerator-type=v5p-8`.
2. Installed `jax[tpu]` followed by other project dependencies.
3. Ran `import jax; print(jax.devices())` in Python and consistently found only 4 TPU devices listed.

**Expected Behavior**:
JAX should detect and utilize all 8 TPU cores as per the TPU VM configuration.

**Actual Behavior**:
Only 4 TPU cores are being detected by JAX, leading to `ValueError: each shard needs a separate device, but device count (4) < shard count (8)` when attempting to distribute work across 8 cores.

**Additional Context**:
- The issue occurs irrespective of using a virtual environment.
- The Google Cloud Console confirms the TPU VM is configured with 8 cores.

I am looking for guidance on why JAX is only detecting 4 cores and how I can resolve this to utilize all 8 cores as expected. Any help or insights you can provide would be greatly appreciated.

Thank you for your assistance!

**Comment by yliu120** [comment]
Hello!

The Cloud TPU v5p chip contains 2 tensorcores and 4 sparsecores as mentioned in the doc: https://cloud.google.com/tpu/docs/v5p-training#system-architecture

On a v5p-8 machine, I would imagine that 8 refers to the number of tensorcores on that machines. Here, JAX talks to 4 TPU devices/chips, essentially 2x2x1 (https://cloud.google.com/tpu/docs/v5p-training#v5p_tpu_configurations) = 4 but not every single TensorCores.

If you run `jax.device_count()`, it should return 4 instead of the number of tensorcores of a v5p-8 machine. You should define your mesh/sharding based on the actual device number.

**Comment by yliu120** [comment]
Please take a look at this code example. Hope it helps:
https://cloud.google.com/tpu/docs/run-calculation-jax#display_the_number_of_tpu_cores_available

**Comment by mosmos6** [comment]
@yliu120 Thank you for your quick reply. I set up v5p-16 (2 workers) and it detected "8 devices" as intended.
