### ISSUE TITLE
Can vmap vstack the outputs

### ISSUE THREAD

**Issue by rsmath** [google/jax#19506]
I am trying to run ``vmap`` on different sized inputs (that have the same number of columns). For example

```
x1 = np.random.rand(10, 3)
x2 = np.random.rand(20, 3)
```

I have two functions, ``f1, f2``, that I want evaluated on x1 and x2 respectively through vmap. The following is **NOT** allowed by jax

```
functions = [f1, f2]
xs = [x1, x2]

vfunc = vmap(lambda i, xs: lax.switch(i, functions, xs[i])

vfunc(jnp.arange(2), xs)
```

This throws the error because vmap by default does not vstack the outputs. Is there a way to vstack the outputs?

Thank you.

**Comment by jakevdp** [comment]
Hi, thanks for the question! `vmap` can stack outputs, but not for the data you provide in this example. The problem is that indices in `lax.switch` cannot be used to index into Python lists, because the indices are dynamic rather than static. You can address this by turning `xs` into an array rather than a list, but since JAX doesn't support ragged arrays, this requires making each of the entries the same shape. Once you do that, it should work (so long as you adjust the `in_axes` to not batch `xs` in your mapped function):
```python
import numpy as np
import jax.numpy as jnp
from jax import lax, vmap

x1 = np.random.rand(10, 3)
x2 = np.random.rand(10, 3)
functions = [jnp.sin, jnp.cos]
xs = jnp.array([x1, x2])

vfunc = vmap(lambda i, xs: lax.switch(i, functions, xs[i]), in_axes=(0, None))

result = vfunc(jnp.arange(2), xs)
print(result.shape)
# (2, 10, 3)
```
Is that along the lines of what you have in mind?

**Comment by rsmath** [comment]
Hi Jake! First, thank you so much for your prompt reply and answer. I really appreciate the help.

I now have a better understanding of ``vmap`` and ``lax.switch``. Unfortunately for my use case, the input shapes are different for each function along the first dimension. I will rethink my approach.
