### ISSUE TITLE
cholesky not working with vmap on complex arrays

### ISSUE THREAD

**Issue by txie-93** [google/jax#1952]
I tried to use `cholesky` on complex arrays with `vmap` but I get `Unimplemented` error.

```
A = np.eye(3).astype(np.complex64)
A_batched = np.stack([A, A])
jax.vmap(np.linalg.cholesky)(A_batched) 

RuntimeError: Unimplemented: Complex types are not implemented in Cholesky; got shape c64[2,3,3]: 
```

This isn't a problem if I don't use vmap.
```
np.linalg.cholesky(A)
DeviceArray([[1.+0.j, 0.+0.j, 0.+0.j],
             [0.+0.j, 1.+0.j, 0.+0.j],
             [0.+0.j, 0.+0.j, 1.+0.j]], dtype=complex64)
```

Is this a bug or am I doing anything wrong? This looks really strange.

**Comment by mattjj** [comment]
Thanks for the question!

What backend are you using (CPU/GPU/TPU)? (I'm guessing CPU.)

It looks like you're hitting [this unimplemented error in XLA](https://github.com/tensorflow/tensorflow/blob/adc3a1b1bec28849f62076e9b4be5c5963e5e5e7/tensorflow/compiler/xla/service/cholesky_expander.cc#L148).

I think the reason it's only coming up when you use `vmap` is that [JAX falls back to an XLA-based implementation](https://github.com/google/jax/blob/29db4203fec6b9796637034d48a62ac84fbcf43f/jax/lax_linalg.py#L146-L149), rather than using a LAPACK one in the un-batched case.

@hawkinsp we could just write a loop in our [`lapack.pyx` bindings](https://github.com/google/jax/blob/29db4203fec6b9796637034d48a62ac84fbcf43f/jaxlib/lapack.pyx#L772) to handle batch dimensions, right? I think that's how we [handle batch dimensions in other kernels](https://github.com/google/jax/blob/29db4203fec6b9796637034d48a62ac84fbcf43f/jaxlib/lapack.pyx#L308).

I'm going to mark this as a "good first issue" because there are plenty of examples in lapack.pyx and lax_linalg.py to pattern-match off of.

**Comment by mattjj** [comment]
(Also I un-assigned myself because I'm not working on this right now.)

**Comment by am-khan** [comment]
will attempt this!

**Comment by txie-93** [comment]
Thanks for the quick responses! @mattjj @hawkinsp @am-khan Just tested on GPU and it is a CPU-only issue. Look forward to the fix.

**Comment by hawkinsp** [comment]
@am-khan Oops! Sorry: I didn't see you wanted to work on this. Thanks for volunteering!

PR #1956 fixes this, and also improves the efficiency of batched Cholesky on GPU at the same time.

**Comment by mattjj** [comment]
@am-khan while @hawkinsp got the jump on you for this issue, it looks like [there's a very similar TODO for batched triangular solves](https://github.com/google/jax/blob/1ca9e9b251ebdea78df168d7a86f4719f49c553b/jax/lax_linalg.py#L404-L408).

**Comment by hawkinsp** [comment]
PR #1956 fixes this but it requires a jaxlib rebuild (or waiting until we push new jaxlib wheels). Hope that helps!

**Comment by am-khan** [comment]
thanks @mattjj is there a corresponding issue or can I just go ahead?

**Comment by mattjj** [comment]
You can just go ahead, though if you feel the same amount of satisfaction from closing issues that I do, feel free to open one and mention that you're working on it :)
