### ISSUE TITLE
Is it possible to use objects with Jax's machine learning library

### ISSUE THREAD

**Issue by Montana** [google/jax#1967]
Using classes works for me as long as I don't refer to any class objects inside my functions, but was wondering if using objects is possible with Jax? 

-Montana

**Comment by jbaron** [comment]
You can use objects, but need to also need register some code how to flatten and unflatten them when passing them to a traceable function. This is however a straight forward process. (some examples can be found here: https://jax.readthedocs.io/en/latest/notebooks/JAX_pytrees.html ).

Alternatively I sometimes use named tuples if I just want to group some parameters in order to increase readability of my code.

**Comment by Montana** [comment]
Thanks @jbaron, makes sense. Since I'm expecting NamedTuples to work like other Python builtins. I appreciate your response. 

-Montana

**Comment by umangjpatel** [comment]
Can you send me an example to do that? Like creating a class and extending it to work with JAX

**Comment by mattjj** [comment]
The technique @jbaron suggests works if you want your classes to be treated as containers, isomorphic to tuples (i.e. product types). The functions you register define the isomorphism: one function for how to take an instance and flatten it to an iterable (plus some metadata, like dict keys), and another for how to take the iterable (plus the metadata) and reproduce the a class instance equal to the original one.

Doing that will let instances of your own container-like classes be passed as arguments and returned as values to and from JAX-transformed functions (like jitted functions). After all, JAX will effectively see them as flat tuples, using the functions you provided to do the conversion back and forth.

Since I think @Montana 's original question was answered, and hopefully @umangjpatel 's request for an example was as well, I'll close this issue. Please open others if more questions come up!
```python
from jax import jit

class Special:
  def __init__(self, x, y):
    self.x = x
    self.y = y

@jit
def f(special):
  return special.x + special.y

special = Special(1, 2)

f(special)  # TypeError: Argument '<__main__.Special object at 0x7f1403ee5e10>' of type <class '__main__.Special'> is not a valid JAX type

from jax import tree_util
tree_util.register_pytree_node(Special, lambda s: ((s.x, s.y), None), lambda _, xs: Special(xs[0], xs[1]))

f(special)  # 3
```

Object identity is _not_ preserved (which is a [condition of functional purity](https://en.wikipedia.org/wiki/Referential_transparency)):

```python
@jit
def g(s1, s2):
  return s1 is s2

g(special, special)  # False
```

You can use methods on the instances you pass in, but side-effects won't work (they will likely silently fail rather than raising an error).

As @jbaron said, these things get flattened and then unflattened/re-created when being passed into or out of JAX-transformed functions, so if you keep that in mind it might be easier to remember the constraints (no object identity, no side effects).

**Comment by Montana** [comment]
This answered my question, thank you!

**Comment by jakevdp** [comment]
> I just wanted to highlight, that I don't think that this answer is entirely true - you can't just apply this method and have grad work totally.

To make this more explicit: objects which have impure methods (see [JAX Sharp Bits: Pure Functions](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#pure-functions)) will not work correctly with `jax.grad` and other transformations, even if they are registered as pytrees.

**Comment by yuichiro-student** [comment]
When I pass a class object to a function and want to ``jit`` it, do I need to specify the object to be ``static``?

**Comment by jakevdp** [comment]
> When I pass a class object to a function and want to `jit` it, do I need to specify the object to be `static`?

If you want a class object to be compatible with `jax.jit`, you should register the class as a pytree. See https://docs.jax.dev/en/latest/pytrees.html#extending-pytrees. Marking them as static may work in some contexts (e.g. if the class is immutable, only contains static attributes – no arrays – and has a meaningful `__hash__` and properly-behaving equality semantics) but will cause surprises in the more general case.

**Comment by yuichiro-student** [comment]
Thank you. I have a class that has only static attributes but has some member functions.

When I jit a function which has this class in its argument, it seems that with or without specifying the class ``static`` seems to affect the result. 

Is this what you mean by the term surprise?

**Comment by yuichiro-student** [comment]
In my case, I have a pytree (``class1``) with dynamic (children) and static (aux_data) members. I made all the arrays children, as I thought this was a required step. 

However, even though they, the children, are jax arrays, I don't need to change them when executing the code. They are the weight of a cost that is fixed over the execution.

I have a function that takes in ``class1`` as an input. In this case, can I set ``class1`` as a static variable when jitting the function? Or does it give some surprising effect, as you mentioned?

If there is something that I can read and study, please let me know.

**Comment by samskiter** [comment]
> In my case, I have a pytree (`class1`) with dynamic (children) and static (aux_data) members. I made all the arrays children, as I thought this was a required step.
> 
> However, even though they, the children, are jax arrays, I don't need to change them when executing the code. They are the weight of a cost that is fixed over the execution.
> 
> I have a function that takes in `class1` as an input. In this case, can I set `class1` as a static variable when jitting the function? Or does it give some surprising effect, as you mentioned?
> 
> If there is something that I can read and study, please let me know.

I actually recommend you look at Jax Libraries like Flax or Equinox - these both promise to make writing code in a more stateful/OO way possible.

**Comment by yuichiro-student** [comment]
Thank you, but even with them, I still need to specify when I want to handle elements as static manually. 

So, I need to answer my question. That is, when all members are static, can I handle the class static?

**Comment by jakevdp** [comment]
> when all members are static, can I handle the class static?

When all members of a class are static, you can safely mark the whole class static, so long as the class's `__hash__` and `__eq__` implementations properly account for all the class members.

**Comment by yuichiro-student** [comment]
Thank you. For the class, I get it.

However,  I still don't understand the general rule behind. 
In the documentation
https://docs.jax.dev/en/latest/pytrees.html#extending-pytrees
> When defining unflattening functions, in general children should contain all the dynamic elements of the data structure (arrays, dynamic scalars, and pytrees), while aux_data should contain all the static elements that will be rolled into the treedef structure. JAX sometimes needs to compare treedef for equality, or compute its hash for use in the JIT cache, and so care must be taken to ensure that the auxiliary data specified in the flattening recipe supports meaningful hashing and equality comparisons.

This is something you told me, I believe. 

How about a python dictionary? I passed it with floats and integers (no arrays) to a class/pytree and made it ``static`` / ``aux_data``, because I thought the dictionary was for constant values, which is not necessarily a justification. 

However, since a dictionary is neither immutable nor hashable, (correct me if I am wrong), should I register it as ``children``?
Then, it is not possible to create a value from the dictionary as a constant. 
Could you please advise me on how to handle the situation?

**Comment by jakevdp** [comment]
A python dictionary is a pytree, so it should be specified within children rather than within aux_data. In particular, a dict cannot be aux_data because it is not hashable.

You should stop thinking of "static" and "constant" as the same thing: they are not. Static values may or may not be constant within your program, and constant values in your program may or may not be static. They are orthogonal concepts.

A static value must be hashable, which in Python implies that it has simple equality semantics and is immutable. Maybe an easier way to think about it: a static value is anything that can be used as a dictionary key (because static values are used as the keys of the compilation cache).

Within a pytree, `aux_data` values must be static, and `children` values must be either arrays, array-like objects (like python scalars), or pytrees.

Does that make sense?

**Comment by yuichiro-student** [comment]
Thank you so much. 

I understand that the static and constant are orthogonal concepts. I mixed up the concept, as you pointed out. This is something I never understood on my own.

I had a ``class/pytree``, `class1` with a member  ``dict1={'size1':2}``, which I set ``aux_data``. I understand it is incorrect. However, the reason I did so was to use the value to create 
``zero_array = jnp.zeros(class1.dict1['size1'])`` 
in a function that takes in ``class1``.

When I set ``dict1`` as ``children``, jax through me an error. 

How then should I handle the ``dict`` with a constant value without setting it ``aux_data``?

**Comment by jakevdp** [comment]
If you have a dict of static values, then in the `flatten` function you could convert it to some hashable collection (like a tuple of `(key, value)` tuples) and then include it in `aux_data`. Then in `unflatten` you could reconstruct the dict.

**Comment by yuichiro-student** [comment]
Oh, I understand. I should stop having a dict with both constant and non-constant values to make my implementation easier.

Thank you so much.

There is no way to add ``brax.env`` as a member of a class, even if JAX does not throw any error, then.

Even if I misspecify ``children`` or ``aux_data``, jax does not always throw me an error. No error does not necessarily mean that I it works fine?

**Comment by yuichiro-student** [comment]
Is it possible to pass a function as an argument of pytree and set it ``aux_data``?

**Comment by samskiter** [comment]
I don't think so - a function can't be hashed down into a tree right?

**Comment by jakevdp** [comment]
Simple functions are fine as `aux_data`. Alternatively you can wrap them in `jax.tree_util.Partial` (along with optional arrays for partial evaluation) and then include it in `children` as a pytree.

**Comment by yuichiro-student** [comment]
Can you elaborate a bit more, and be more specific?

I would like to have ``brax.env.step`` function in the class/pytree. It can be either a member or method. 
https://github.com/google/brax

My first approach is to have ``env`` as a member and have the ``step`` function as a class method. Since ``env`` is not a JAX-supported type, I cannot include ``env`` as a ``children``. Also, since it is not immutable, I cannot include it as ``aux_data``. (Although it seems to be working fine without any errors.)

My second approach is to have ``brax.env.step`` function as a member and put it in ``aux_data``. I believe that it satisfies the requirement for being ``aux_data``, (immutable and hashable) but I wanted to check.

**Comment by jakevdp** [comment]
> I would like to have `brax.env.step` function in the class/pytree.

I don't see where `brax.env.step` is defined in the brax package. It doesn't look like `brax.env` exists. I looked in `brax.envs` thinking maybe you had a typo, but there's no `step` function defined in `brax/envs/__init__.py`.

If `step` is a simple Python function, it should be fine to include it in `aux_data`. Functions are hashable and immutable. The only place to be careful would be if it depends on mutable global state – then you might run into issues related to implicit global state if you use it in JIT (this is true of functions as static arguments whether or not they're part of a pytree).

**Comment by yuichiro-student** [comment]
Sorry, the ``step`` function is implemented for each environment, for example:
https://github.com/google/brax/blob/main/brax/envs/hopper.py

>The only place to be careful would be if it depends on mutable global state – then you might run into issues related to implicit global state if you use it in JIT (this is true of functions as static arguments whether or not they're part of a pytree).

This is problematic only when I change the global state that has implicit dependency.  Is my understanding correct?

**Comment by jakevdp** [comment]
> This is problematic only when I change the global state that has implicit dependency. Is my understanding correct?

Yes - if you have a function that depends on global state and you use it in JAX transformations like `jit`, `vmap`, `grad`, etc. then changes to the global state may not be reflected in subsequent executions. This is addressed in the discussion of [pure functions](https://docs.jax.dev/en/latest/notebooks/Common_Gotchas_in_JAX.html#pure-functions) in the JAX sharp bits.

**Comment by yuichiro-student** [comment]
Thank you. ``Hopper.step(state, action)`` function depends ``Hopper``, but since I don't change ``Hopper`` once I have created it, I believe it is safe to put the ``step`` function in ``aux_data``. 
It seems to be working with the transformations without any errors. 

I appreciate the sharp bits documents because it  explains essential concepts with examples. Thank you again.
