### ISSUE TITLE
`all_to_all` parallel primitive does not work on multi-host environments 

### ISSUE THREAD

**Issue by Britefury** [google/jax#1969]
When working on multi-host configurations, the `all_to_all` parallel primitive does not work due to not being in the whitelist at `jax.interpreters.pxla.multi_host_supported_collectives`.

My early experiments with it suggests that I was able to use it (or specifically `pswapaxes`) as a parallel `concat`, with the caveat that the order of the returned results was a little odd. Order wasn't important to me so this wasn't a problem in my specific case. :)

**Comment by hawkinsp** [comment]
@skye and @jekbradbury this works now, am I correct?

**Comment by skye** [comment]
No, it's still not in the supported collectives list. We could add it, because I think it works as well in multi-host as it does otherwise (i.e. it still presumably suffers from https://github.com/google/jax/issues/1332). Given that @Britefury has tried it, I'd be in favor of adding it to the list. If no one objects I'll do that shortly.
