### ISSUE TITLE
Enhance `vmap` to work with nested functions

### ISSUE THREAD

**Issue by Lando-L** [google/jax#19692]
Let's say I have the following example function:

```python
def foo(a: Array, b: Array, c: Array) -> Array:
    return a + b + c
```

I need this function to follow the following type signature:

```python
MyType = Callable[[Array], Array]
```

To achieve this I can use partial:

```python
def bar(b: Array, c: Array) -> MyType:
    return partial(foo, b=b, c=c)
```

Unfortunately, this way I lose the power of using `vmap`, e.g. `vmap(bar)` does not work since the return type of `bar` is a callable, which is not supported. I can still do `vmap(bar(b, c))`, however this only vectorises `bar` w.r.t `a`, not `b` and `c`.

It would be great if nested a callable, which only takes arguments of supported types (like `b` and `c`) and ultimately resolves to a supported type is considered valid as well.

Maybe allowing non positional arguments to be mapped could make this work, something like:

```python
vmap(bar(b, c), in_axes=0, in_kwarg_axes={b=0, c=0})
```

**Comment by jakevdp** [comment]
Hi - thanks for the request! I can't see any way that we'd be able to make this work: `bar(b, c)` is a Python function call that is evaluated, and the result is then passed to `vmap`. Because of this, there's no way for `vmap` to interact with the values of `b` and `c` that you are passing to `bar`.

of course, you could pass `b` and `c` via an outer funciton that's wrapped in `vmap` in order for `vmap` to know about them; something like this:
```python
@vmap
def outer(a, b, c):
  return bar(b, c)(a)
```
But this is basically re-constructing `vmap(f)`.

**Comment by Lando-L** [comment]
Hi, thanks for the fast reply. If `bar(b, c)` returns a partial object - like in the example - it should know about the keyword arguments `b` and `c`. However, I am not sure if `vmap` can make use of that information or just recognises this as a callable.

**Comment by jakevdp** [comment]
Sure, but `bar(b, c)` returns a partial object where `b` and `c` are already bound, before the `vmap` encounters the values. I don't think there's any way to do what you have in mind without a deep re-design of how `vmap` works, and my feeling is that the added complexity would not give you much that you can't already do with the existing interface.

**Comment by Lando-L** [comment]
I can see that. Thanks for the consideration!
