### ISSUE TITLE
Sparse JVP for efficient diag(J^T @ J)

### ISSUE THREAD

**Issue by Joshuaalbert** [google/jax#19711]
The motivating example for this is computing `diag(J^T @ J)`, where `J` is a Jacobian.

Suppose we have a function `f: R^n -> R^m` then we have `J_ij = d f_i(x) / dx_j` and then `(J^T @ J)_ik = sum_j (d f_i(x) / dx_j) * (d f_k(x) / dx_j)`, and therefore the diagonal is:

```
(J^T @ J)_kk = sum_j (d f_k(x) / dx_j)^2
```

Currently to compute the diagonal we need to do:

```python
def kth_diag(e_k):
  _, f_vjp = vjp(f, x)
  _, jvp_val_k = jvp(f, x, e_k) # <- Can we make this more efficient?
  H_kk = f_vjp(f, x, jvp_val_k)
  return H_kk

JtJ_diag = vmap(kth_diag)(eye(n))
```

This requires materialising an `n x n` matrix, just to extract the `k`-th element from the `jvp`.

Is there a way to use sparse methods to perform this computation?

If there would also be a sparse VJP then together it would enable a much larger class of differentiation than currently possible, i.e. arbitrary elements `d f_i / dx_j` could be constructed from the function `f` without the cost of standard basis extraction.

**Comment by mattjj** [comment]
Thanks for the question!

Actually, isn't your example code going to return an `n x n` matrix rather than a vector (and `diag(J.T @ J)` should be a length-`n` vector)? It seems like it's computing `J.T @ J @ I`, so you would then need to apply `diag` to the result. I think that could be improved a bit, but to think clearly about it let's first simplify away the autodiff and just think about matrices...

Here's an even easier question: given a matrix `A`, how would you compute `diag(A.T @ A)`? Or put another way: given a collection of vectors (stacked together as columns), how do we compute their squared l2 norms? We wouldn't need matrix multiplies at all: we could just use `vmap(jnp.vdot, 1, 0)(A)` aka `jnp.einsum('ij,ij->i', A, A)`.

Those work if `A` is available as a dense array, but if we only have implicit `v -> A v` access to `A` then we can either materialize it by vmapping over a standard basis (this means creating an `n` x n` matrix), or we can extract each column of `A` at a time and compute its squared norm (i.e. operate unbatched).

Having this kind of matrix-(dense)vector multiply access only _could_ be in a sense wasteful: we have to implement "get the `i`th column of `A`" as `jnp.dot(A, e_k)` where `e_k` is dense. But we may not be losing much: In reality `v -> A v` is rather something more like `v -> A_1 @ (A_2 @ (A_3 @ ... v)...)`. As soon as we apply the first A_t that is dense, we'll lose all sparsity anyway. (If instead _all_ our component A_t's were sparse, e.g. diagonal, then we could indeed do better.) But are all your component functions actually sparse, in terms of input-output Jacobians? If so, we should probably talk more about what kind of sparsity you have throughout `f`.

Assuming they're not, i.e. assuming you have some dense 'layers' in your computation, you might still improve the efficiency of the computation like this:

```python
import jax
from jax import jvp, vjp, vmap
import jax.numpy as jnp

A = jax.random.normal(jax.random.key(0), (5, 4))
def f(x):
  return jnp.sin(jnp.dot(A, x))

# baseline method

def kth_diag(e_k, x):
  _, f_vjp = vjp(f, x)
  _, jvp_val_k = jvp(f, [x], [e_k]) # <- Can we make this more efficient?
  out, = f_vjp(jvp_val_k)
  return out

x = jax.random.normal(jax.random.key(1), (4,))
JtJ = vmap(kth_diag, (0, None))(jnp.eye(4), x)
JtJ_diag = jnp.diag(JtJ)
print(JtJ_diag)


# alternative: only use jvp

def kth_diag(e_k, x):
  _, J_k = jax.jvp(f, [x], [e_k])
  return jnp.sum(J_k ** 2)

x = jax.random.normal(jax.random.key(1), (4,))

# batched (requires materializing an nxn matrix)
JtJ_diag = vmap(kth_diag, (0, None))(jnp.eye(4), x)
print(JtJ_diag)

# unbatched
one_hot = lambda i: jnp.zeros_like(x).at[i].set(1)
JtJ_diag = jnp.stack([kth_diag(one_hot(k), x) for k in range(4)])
print(JtJ_diag)
```

WDYT?

**Comment by Joshuaalbert** [comment]
Hi @mattjj, let's compare these methods using the cost_analysis debug info.

```python
import jax
import jax.numpy as jnp
from jax import jvp, vjp, vmap

def print_cost_analysis(cost_analysis):
    for k in sorted(cost_analysis[0].keys()):
        print(f"{k}: {cost_analysis[0][k]}")

if __name__ == '__main__':
    A = jax.random.normal(jax.random.PRNGKey(0), (5, 4))
    x = jax.random.normal(jax.random.PRNGKey(1), (4,))


    def f(x):
        return jnp.sin(jnp.dot(A, x))


    # baseline method

    def kth_diag(e_k, x):
        _, f_vjp = vjp(f, x)
        _, jvp_val_k = jvp(f, [x], [e_k])  # <- Can we make this more efficient?
        out, = f_vjp(jvp_val_k)
        return out


    def f1(x):
        JtJ = vmap(kth_diag, (0, None))(jnp.eye(4), x)
        return jnp.diag(JtJ)


    print(f1(x))
    print_cost_analysis(jax.jit(f1).lower(x).compile().cost_analysis())


    # alternative: only use jvp

    def kth_diag(e_k, x):
        _, J_k = jax.jvp(f, [x], [e_k])
        return jnp.sum(J_k ** 2)


    # batched (requires materializing an nxn matrix, and an mxn matrix internally)

    def f2(x):
        return vmap(kth_diag, (0, None))(jnp.eye(4), x)


    print(f2(x))
    print_cost_analysis(jax.jit(f2).lower(x).compile().cost_analysis())


    # unbatched (only ever instantiate length-n and length-m vectors)
    def f3(x):
        one_hot = lambda i: jnp.zeros_like(x).at[i].set(1)
        return jnp.stack([kth_diag(one_hot(k), x) for k in range(4)])


    print(f3(x))
    print_cost_analysis(jax.jit(f3).lower(x).compile().cost_analysis())
```

Indeed they produce the same results modulo numerical precision.

It looks like the baseline methods uses both the most FLOPS, and most bytes accessed.

```
[6.440715  5.6550355 8.008037  1.5978107]
bytes accessed: 888.0
bytes accessed operand 0 {}: 448.0
bytes accessed operand 1 {}: 308.0
bytes accessed output {}: 324.0
flops: 432.0
transcendentals: 5.0
utilization operand 0 {}: 7.0
utilization operand 1 {}: 7.0
```

The second method using only l2 norm of jvp uses fewer FLOPS and fewer bytes accessed.
```
[6.4407144 5.655036  8.008037  1.5978109]
bytes accessed: 520.0
bytes accessed operand 0 {}: 304.0
bytes accessed operand 1 {}: 180.0
bytes accessed output {}: 180.0
flops: 288.0
transcendentals: 5.0
utilization operand 0 {}: 5.0
utilization operand 1 {}: 4.0
```

But method 3, which is unbatched entirely, uses the fewest FLOPS and bytes accessed. But, at the cost of unrolling a loop.
```
[6.4407144 5.655036  8.008037  1.5978109]
bytes accessed: 232.0
bytes accessed operand 0 {}: 100.0
bytes accessed operand 1 {}: 136.0
bytes accessed operand 2 {}: 4.0
bytes accessed operand 3 {}: 4.0
bytes accessed output {}: 36.0
flops: 81.0
transcendentals: 5.0
utilization operand 0 {}: 2.0
utilization operand 1 {}: 11.0
utilization operand 2 {}: 1.0
utilization operand 3 {}: 1.0
```

3rd option would make sense when the size of `x` is small, but otherwise 2nd option. 

Also, can you explain how to interpret "utilization"? I expect that bigger is better for utilization, or perhaps bigger "sum of bytes accessed operand * utilization operand " is better.

**Comment by mattjj** [comment]
Nice, thanks for pasting the code for that!

We might want to look at how the costs scale with the size or complexity of the function in question, since it could be that there are small fixed-size costs that get washed out as the function gets more realistic.

> Also, can you explain how to interpret "utilization"? I expect that bigger is better for utilization, or perhaps bigger "sum of bytes accessed operand * utilization operand " is better.

I'm not sure... I think higher FLOP utilization is always better, but ultimately once operands get big enough it's a property of the arithmetic intensity of what we're trying to do, e.g. if you're doing matmuls (where the compute scales super-linearly with the bytes accessed) then we can ultimately drive utilization to its maximum, but if we're doing a small number of FLOPs per byte then we'll always be limited by memory bandwidth (basically a [roofline model](https://en.wikipedia.org/wiki/Roofline_model)). So I don't think utilization is very relevant here, until we are looking at a real workload you care about.

**Comment by Joshuaalbert** [comment]
Thanks for the explanation. The maximum of diagonal of JTJ is used in pre-conditioning some optimisation algos. Option 2 above will already improve one what's used in jaxopt. Thanks for the help!

**Comment by mattjj** [comment]
Glad to hear it! Always happy to field questions.
