### ISSUE TITLE
PyTreeDef equality comparisons should not compare aux data?

### ISSUE THREAD

**Issue by cooijmanstim** [google/jax#1984]
It seems that `__eq__`  comparison for PyTreeDefs also compares their aux data, [right here](https://github.com/google/jax/blob/9afa2c6b69695a015b1af7d1ccbb3546ddc002ae/jaxlib/pytree.cc#L237). Is this intended? It doesn't seem right to make any assumptions on aux data. In particular not all objects have sensible `__eq__`, such as ndarray types.

In my case I'm using the aux channel to allow the code inside e.g. jit to declare parameters and establish default hyperparameters on the first call. I know that seems like an abuse but it makes life so much easier.

**Comment by mattjj** [comment]
Thanks for the question!

It is intended. The aux data are still data, like dict keys, which matter for pytree equality. For example, without it the structures of any two dicts with different keys but the same number of entries would compare equal.

I think perhaps you'll have to build your own thing to accomplish what you want, rather than reusing pytrees (which seem to serve a different purpose).

Hope that helps!
