### ISSUE TITLE
Speed-up gained from using jit does not persist

### ISSUE THREAD

**Issue by gshartnett** [google/jax#1988]
I am new to JAX, and really liking it so far. One issue I am noticing, however, is that the speed gained from using jit seems to be somewhat inconsistent. I am attaching a screenshot showing a simple example. After first compiling a jit'ed function, I used timeit to measure how quickly it runs. It's very fast. If I then try to repeat the experiment, it's about 100x slower, on par with the speed of running the un-jit'ed function.

![Screenshot from 2020-01-12 09-31-07](https://user-images.githubusercontent.com/18697702/72222884-5768d300-351e-11ea-97b2-6c511e226e10.png)

Relatedly, is there a forum that might be more appropriate for this sort of question/issue? I suspect this is due to me misunderstanding how jit works rather than a bug.

**Comment by gnecula** [comment]
The problem is with the way you are doing the measurement. jit functions dispatch the computation to the device but do not wait for the result themselves; the waiting is done by subsequent uses of the results. You have to add `.block_until_ready()` if you want to measure the time until the result is ready:

```
for i in range(5):
  %timeit -n10 -r3 foo_jit(np.ones((500, 500))).block_until_ready()

10 loops, best of 3: 101 ms per loop
10 loops, best of 3: 101 ms per loop
10 loops, best of 3: 100 ms per loop
10 loops, best of 3: 100 ms per loop
10 loops, best of 3: 100 ms per loop
```

See https://jax.readthedocs.io/en/latest/notebooks/quickstart.html#Multiplying-Matrices and https://jax.readthedocs.io/en/latest/async_dispatch.html

**Comment by gshartnett** [comment]
Oh, I see now. I misunderstood how jit functions work. 

Thanks very much for this! I'll close the issue now.
