### ISSUE TITLE
Matrix-vector multiply: ValueError: all dimensions of x and y must be >= 16 

### ISSUE THREAD

**Issue by serhiykozak** [google/jax#20051]
### Description

A simple matrix-vector multiply Pallas implementation fails:

```
def matrix_multiply(x_ref, y_ref, o_ref):
    o_ref[:, :] = x_ref[:, :] @ y_ref[:, :]

@jax.jit
def matmul(x: jax.Array, y: jax.Array) -> jax.Array:
    return pl.pallas_call(matrix_multiply,
                          out_shape=jax.ShapeDtypeStruct((x.shape[0], y.shape[1]), x.dtype),
                          # interpret=True
                          )(x, y)

k1, k2 = jax.random.split(jax.random.PRNGKey(0))
x = jax.random.normal(k1, (32, 32))
y = jax.random.normal(k2, (32, 1)) 

print(matmul(x, y))
```

Error:
ValueError: all dimensions of x and y must be >= 16 
...
      dimension_numbers=(([1], [0]), ([], []))
      preferred_element_type=float32
    ] d e
    c[:,:] <- f
  in () }

Interestingly, changing the dimensions of y to (32, 16) or (32, 32) works fine, while (32, 8) still fails. There is no issue in the interpret=True mode. What exactly does the interpret mode do? 

Thank you. 

### System info (python version, jaxlib version, accelerator, etc.)

jaxlib=0.4.25
python=3.9
GPU=RTX4090

**Comment by davisyoshida** [comment]
This is a limitation of triton, not a pallas thing I think, see here: https://github.com/openai/triton/issues/1815

**Comment by mattjj** [comment]
Thanks for the question!

At first I thought we needed to improve the error, but actually "all dimensions of x and y must be >=16" seems pretty good! So I think we can close this issue, unless you have a specific recommendation for how we should improve the error message.

> What exactly does the interpret mode do?

Instead of lowering to Triton, it runs the computation in XLA:HLO. That means it doesn't have the same physical semantics as running in Triton, but it can be easier to debug.
