### ISSUE TITLE
Error using dynamic_update_slice with jit

### ISSUE THREAD

**Issue by kovasb** [google/jax#204]
Hi,

I have a function that works fine without jit, but bombs with jit. The issue seems to be that the shape of the array contains tracing constructs that are incompatible with logic in dynamic_update_slice.

```python
def dynamic_update_slice_test(first_row, pad_to_length):
  width = first_row.shape[0]
  empty_array = lax.full((pad_to_length,width), 0, first_row.dtype)  
  first_row_reshaped = np.reshape(first_row, (1,width))
  print(empty_array.shape)
  return lax.dynamic_update_slice(empty_array, first_row_reshaped, start_indices=[0])
```

My goal with this function is, given a 1-d array and a desired length, to create a 2-d array s.t. the initial given array becomes the first row, and the rest of the array is padded out with 0.

```
print(dynamic_update_slice_test(onp.array([1,2]),4)) 
->
(4, 2) # printing shape of empty_array
[[1 2] # result of function
 [0 0]
 [0 0]
 [0 0]]

dynamic_update_slice_test_jit = jit(dynamic_update_slice_test)
dynamic_update_slice_test_jit(onp.array([1,2]),4)
->
(Traced<ShapedArray(int32[]):JaxprTrace(level=-1/1)>, 2) # printing shape of empty_array
/usr/local/lib/python3.6/dist-packages/jax/lax.py in _dynamic_slice_indices(operand, start_indices)
   2533   if isinstance(start_indices, (tuple, list)):
   2534     start_indices = concatenate([reshape(i, [1]) for i in start_indices], 0)
-> 2535   return rem(start_indices, onp.array(operand.shape, start_indices.dtype))
   2536 
   2537 

ValueError: setting an array element with a sequence.
```

Any way to work around this? Thanks!

**Comment by mattjj** [comment]
Thanks for asking this, and for the great minimal example. The issue is actually a bit subtle, and it'd be nice if we could improve things here, at the very least to make the error message better.

The issue is that the shape of `empty_array` depends on the value of `pad_to_length`. (Ultimately, that's leading to [a line in lax.py](https://github.com/google/jax/blob/ad6859ebaa3e3ff24a68c7898e61cf67dbadb163/jax/lax.py#L2535) accidentally putting a traced object into a raw array, which isn't legal. I suspect we can just revise this code to raise a better error message, maybe by using `onp.asarray` rather than `onp.array` there, but I'll poke at that after posting this comment.)

We can only compile a function to XLA when we've specialized it far enough to have static (known at compile-time) shapes. We can achieve that in this example by using the `static_argnums` argument to `jit`, which says "statically specialize compiled code on the *value* of these arguments, and re-compile whenever they change". Concretely, this works:

```python
from __future__ import print_function

import numpy as onp

import jax.numpy as np
from jax import lax
from jax import jit

def dynamic_update_slice_test(first_row, pad_to_length):
  width = first_row.shape[0]
  empty_array = lax.full((pad_to_length, width), 0, first_row.dtype)
  first_row_reshaped = np.reshape(first_row, (1, width))
  print(empty_array.shape)
  return lax.dynamic_update_slice(empty_array, first_row_reshaped, start_indices=[0])

print(dynamic_update_slice_test(onp.array([1,2]), 4))

# mattjj added `static_argnums` on the next line
dynamic_update_slice_test_jit = jit(dynamic_update_slice_test, static_argnums=(1,))
dynamic_update_slice_test_jit(onp.array([1,2]), 4)
```

Would something like that work for your use case?

**Comment by mattjj** [comment]
df87d5c improves the error message to say this:

```
TypeError: `full` requires shapes to be concrete. If using `jit`, try using `static_argnums` or applying `jit` to smaller subfunctions instead.
```

**Comment by mattjj** [comment]
If you want some gory detail on what we mean by "concrete" and "specialized", [this comment from the weekend](https://github.com/google/jax/issues/196#issuecomment-451671635) explains some of it.

**Comment by kovasb** [comment]
Thanks a lot for the quick response. The suggested fix worked for me and I'm now unblocked. 

The mechanism makes sense, I was simply unaware of it. 

Thanks!
