### ISSUE TITLE
feat: allow setting default platform globally via Python

### ISSUE THREAD

**Issue by lucascolley** [google/jax#20415]
It would be very nice if we could globally set the default platform via `jax.config.update("jax_default_device", ...)`. This was mentioned as a to-do by @skye in gh-9118.

---

Context: I'm working on adding support for JAX in SciPy (scipy/scipy#20085), which involves testing across various devices. We have an environment variable `SCIPY_DEVICE`, which we currently use with PyTorch like `torch.set_default_device(SCIPY_DEVICE)`. It would be easier if we could keep this at the level of a string like "cuda" or "cpu" rather than having to pass in device objects.

Feel free to suggest an easier way to do this if you see one by the way!

**Comment by lucascolley** [comment]
Okay, I suppose `jax.config.update("jax_default_device", jax.devices(SCIPY_DEVICE)[0])` works - still, this would be nice to have!

**Comment by mattjj** [comment]
Hey @lucascolley , thanks for the request! But help me understand: does this already work? What's left to do?

**Comment by lucascolley** [comment]
Hey @mattjj, currently I can do `jax.config.update("jax_default_device", jax.devices('cuda')[0])`. This request (and the TODO in the code) is to just be able to do `jax.config.update("jax_default_device", 'cuda')` for the same result. And similarly for other platforms (cpu, tpu?)

**Comment by mattjj** [comment]
Thanks for clarifying!

That seems like a slight type error though... the default device needs to be a single device, whereas `'cuda'` refers to a platform, for which there may be (and typically are) several devices. I guess the intent is arguably clear, but it seems oddly single-device specific...

**Comment by yashk2810** [comment]
Does `jax.config.update('jax_platforms', 'cpu')` work?
https://github.com/google/jax/blob/0dde8f7f9607d09841ece7125dfc0773c3613fab/jax/_src/config.py#L912-L926

**Comment by lucascolley** [comment]
> Does jax.config.update('jax_platforms', 'cuda') work?

No, not quite. IIUC, that would mean that I can only use CUDA devices. I still want to be able use other platforms, just not by default.

A further extension: I would like `jax.config.update("jax_default_device", 'cuda:1')` to work also.

**Comment by slevang** [comment]
I was looking for similar flexibility. Turns out you can pass `jax_platforms` as a list, such as `"cpu,cuda"` which will default to placing arrays on cpu but still keep the cuda platform available for use. This doesn't work as a context manager though like `default_device`.

**Comment by lucascolley** [comment]
That's somewhat useful, although it still requires obtaining a list of available platforms.

> A further extension: I would like `jax.config.update("jax_default_device", 'cuda:1')` to work also.

In fact, this would probably be enough to address this issue alone. I understand that it seems like "a slight type error", but I think `'cuda:1'` is a very reasonable and useful syntactic-sugar for `jax.devices('cuda')[1]`

**Comment by mattjj** [comment]
Thanks for the discussion!

My understanding is that there's already a way to express this, using both `jax_default_device` and `jax.devices(platform)[index]`, and we're just talking about syntactic sugar / a convenience wrapper.

While I can appreciate that syntactic sugar can be convenient, in general it's also desirable to get expressiveness through composing up simple things rather than building complicated things. In this case, I'd rather not make `jax_default_device` more complicated (in the sense of accepting platform-like arguments, or developing a platform-and-device-index mini-language in strings).

I understand that there's no clear answer here, and you may disagree. But that's my current best judgement.

Thanks for the suggestion. Hopefully you can just define a convenience wrapper in your code that amounts to the same thing!
