### ISSUE TITLE
build.py specifies bazel 0.24 but uses repo_env which is new in bazel 0.26

### ISSUE THREAD

**Issue by cliffwoolley** [google/jax#2044]
https://github.com/google/jax/blob/master/build/build.py#L310 specifies that the minimum allowed bazel version is 0.24, but https://github.com/google/jax/blob/master/build/build.py#L167-L169 uses `--repo_env` (as opposed to `--action_env`), which was added in bazel 0.26 (in https://github.com/bazelbuild/bazel/commit/d7702b1 ).

**Comment by cliffwoolley** [comment]
@hawkinsp as this appears to stem from https://github.com/google/jax/commit/3e9ce2f .

**Comment by hawkinsp** [comment]
Oops! Sorry about that. The right fix is probably for us to bump the minimum version of bazel (0.24 is old at this point). I'll do that.

**Comment by skye** [comment]
Unfortunately I think there are other issues preventing us from upgrading bazel, at least when using the full build_jaxlib_wheels.sh stack. We may wanna revert to using --action_env for now, although ideally we fix the issues with new bazels.

**Comment by skye** [comment]
I may have been mistaken -- I was just able to build at least one jaxlib wheel with bazel 1.1.0. I'll try bumping the minimum version as suggested and see what happens when I try a fresh jaxlib build (I've been debugging a lot of build issues so it's possible I messed something else up along the way).
