### ISSUE TITLE
jax.config has no attribute 'update'

### ISSUE THREAD

**Issue by doctor-phil** [google/jax#20698]
### Description

Hello, I am following the directions from here: https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html
to enable 64 bit floating point. Specifically, using this code at startup:

```
# again, this only works on startup!
from jax import config
config.update("jax_enable_x64", True)
```

However, when I run this code it is throwing an
```AttributeError: module 'jax.config' has no attribute 'update'```

I was not having this issue with earlier versions (before `import jax.config as config; config.update(etc.)` was deprecated.)

### System info (python version, jaxlib version, accelerator, etc.)

jax:    0.4.26
jaxlib: 0.4.26
numpy:  1.26.4
python: 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
platform: uname_result(system='Windows', node='phils-laptop', release='10', version='10.0.22631', machine='AMD64')

**Comment by jakevdp** [comment]
I cannot reproduce this in JAX v0.4.26 running on Linux or OSX.

However, it looks like when you import `jax.config`, you're seeing the deprecated module (https://github.com/google/jax/blob/main/jax/config.py) rather than the config object (https://github.com/google/jax/blob/ff12b2ad639e922374771d52559fd71076751bac/jax/__init__.py#L48)

This may be due to some difference in how CPython resolves imports on Windows. Can you try doing this instead?
```python
import jax
jax.config.update("jax_enable_x64", True)
```

**Comment by doctor-phil** [comment]
Hi @jakevdp , writing it this way fixed the issue. Thanks!
