### ISSUE TITLE
Memory leak in a simple loop with no side effects

### ISSUE THREAD

**Issue by romanngg** [google/jax#2072]
When running this on the public Python 3 colab on a GPU, this program will very slowly but grow the RAM usage (e.g. grew from 1.5 to 2.5 in 30-60 minutes), even though apparently it should not. Note that a jitted function here is applied iteratively to inputs of different shapes (also note that the sizes of arrays actually _decrease_ as the loop progresses, so naively RAM usage should _go down_).

```
from jax.api import jit
from jax import random
from jax import numpy as np
from datetime import datetime

def f(x, y):
  return np.mean(x.T @ y)

f_jit = jit(f)

for i in range(15000, 0, -1):
  x = random.normal(random.PRNGKey(i), (500, i))
  for j in range(15000, 0, -1):
    y = random.normal(random.PRNGKey(j), (500, j))
    res = f_jit(x, y)
    if i % 500 == 0 and j % 500 == 0:
      print(datetime.now(), i, j, res)
```

[PS. This may appear artificial, but is motivated by a practical use-case where we have program that _GPU_ OOMs in a qualitatively similar for-loop that does not seem to have any side effects. I believe this simple example might be related.]

**Comment by mattjj** [comment]
I think we'd expect the compile cache to grow as this runs, and the compilation cache actually grows without bound right now (i.e. there's no eviction policy).

We probably want to provide more tooling around the compilation cache so that it's transparent what's going on, but in the meantime to check the hypothesis that this is the compilation cache growing, you can try clearing it periodically using this:

```python
from jax.interpreters import xla

xla._xla_callable.cache_clear()
```

(A slightly more ergonomic version would be if we just let you write `f_jit.cache_clear()` or something!)

**Comment by mattjj** [comment]
This program also grows memory without bound, a bit faster (just because I made the programs and hence the executables bigger):

```python
import itertools as it
import numpy as onp

from jax.api import jit, grad
from jax import numpy as np

funs = [np.sin, np.cos, np.tanh]

def f(x):
  for perm in it.permutations(funs):
    for fun in perm:
      x = fun(x)
  return x.sum()

f_jit = jit(grad(f))

for i in it.count(1):
  f_jit(onp.zeros(i)).block_until_ready()
```

But if I add something like

```python
from jax.interpreters import xla

...

  if i % 100 == 0:
    xla._xla_callable.cache_clear()
```

then it stops growing!

That suggests to me that we're looking at a compilation cache growth issue here, and so some not-mutually-exclusive options are:
1. add an eviction policy to the compilation cache (like LRU)
2. add some tools for users to inspect and manage cache sizes

**Comment by mattjj** [comment]
Actually, an easier way to clear the cache (without the `from jax.interpreters import xla` business) is just to redefine `f_jit` periodically, like

```python
  if i % 100 == 0:
    f_jit = jit(grad(f))
```

since dropping the reference to the function will cause JAX to clean up all the compilation stuff.

Also, the memory still seems to be growing, just _much_ more slowly. Maybe there's some other caching under the hood (not inside JAX IIUC)...

**Comment by romanngg** [comment]
Thank you Matt, one question: would it make sense for a GPU OOM in our more complex usecase to happen for this same reason, or the compilation cache should not have an impact on the GPU RAM?

**Comment by mattjj** [comment]
I can imagine scenarios where things like constants are cached in GPU memory, so it's plausible. Deleting/re-binding the callable as above should clear any such caches on the JAX end. Could you try that and see if it works in your situation?

**Comment by MiladInk** [comment]
@mattjj Unfortunately, when I try `xla._xla_callable.cache_clear()` I get this message:
`module 'jax.interpreters.xla' has no attribute '_xla_callable'` Is there an alternative way to do this or I am doing anything wrong?

**Comment by mattjj** [comment]
That function moved! It's a better idea just to drop your reference to the jitted function to clear any caches associated with it, e.g . [as in the example here](https://github.com/google/jax/issues/2072#issuecomment-578422773). Let me know if that doesn't work for you for some reason.

**Comment by mattjj** [comment]
I think this issue is resolved, though there's still tooling we want to add, e.g. to make it easy to inspect cache state and clear caches. (`f_jit._cache_clear()` now exists, but what if we want to delete all cache entries system-wide, as in #10826?)

Let's open more focused feature requests for things we want to add!
