### ISSUE TITLE
initialisers fail for 1D shaped arrays

### ISSUE THREAD

**Issue by david-waterworth** [google/jax#2075]
I've been experimenting with Jax for RNN's. I've been using [sharadmv/deepx](https://github.com/sharadmv/deepx) as inspiration since it contains an LSTM implementation (eventually I plan to investigate FLAX)

I've been running into an issue trying to initialise my parameters. I eventually narrowed it down to the fact that [_compute_fans](https://github.com/google/jax/blob/632326ac5c95e83c05201a6a88168cf682496c96/jax/nn/initializers.py#L45 ) fails for 1D arrays.

I'd set the default to `glorot_uniform` which ended up being used for the weight matrices and the bias vectors. Since I've setup the bias vector to be 1d - i.e. shape=(n,) the default in_axis=-2, out_axis=-1 resutls in an attempt to index the 2nd dimension of a 1d array.

I then tried to use the zeros and ones initialisers - but that failed as well. Most of the initialisers have signature f(**kwargs) return init(key, shape, dtype). However, zeros and ones has the signature of the inner lambda i.e. zeros and ones below has a different signature to uniform

```
def zeros(key, shape, dtype=np.float32): return np.zeros(shape, dtype)
def ones(key, shape, dtype=np.float32): return np.ones(shape, dtype)

def uniform(scale=1e-2):
  def init(key, shape, dtype=np.float32):
    return random.uniform(key, shape, dtype) * scale
  return init
```

**Comment by jekbradbury** [comment]
It's intentional that `_compute_fans` fails for 1D arrays: `glorot_uniform` and friends are only meaningful for weight matrices or convolutional filters (which have a well-defined notion of "fan_in" and "fan_out"), while biases are typically initialized to zeros (or, in the case of the LSTM forget gate bias, ones). The API for parameterized initializers like `uniform` is slightly different from basic ones like `ones`; all three of these should work:
```python
layer = my_layer(..., bias_init=initializers.zeros)
layer = my_layer(..., bias_init=initializers.uniform())
layer = my_layer(..., bias_init=initializers.uniform(scale=0.1))
```

**Comment by david-waterworth** [comment]
Thanks, that makes sense. I'll use zeros for now and see how that goes

**Comment by FelipeMartins96** [comment]
> It's intentional that `_compute_fans` fails for 1D arrays: `glorot_uniform` and friends are only meaningful for weight matrices or convolutional filters (which have a well-defined notion of "fan_in" and "fan_out"), while biases are typically initialized to zeros (or, in the case of the LSTM forget gate bias, ones). The API for parameterized initializers like `uniform` is slightly different from basic ones like `ones`; all three of these should work:
> 
> ```python
> layer = my_layer(..., bias_init=initializers.zeros)
> layer = my_layer(..., bias_init=initializers.uniform())
> layer = my_layer(..., bias_init=initializers.uniform(scale=0.1))
> ```

Hey @jekbradbury, so those initializers which uses 'fans' are not useful for bias initialization? not best practices?

I thought it was a "bug", as a ran into this problem trying to initialize biases using lecun_normal to mimic the DDPG networks, I wasn't sure if it applies only to weights, but thought it did since pytorch seems to initialize the bias weights using the same initializer.
