### ISSUE TITLE
"'JVPTrace' object is not callable" while taking grad of function with matrix trace operator

### ISSUE THREAD

**Issue by PgLoLo** [google/jax#2094]
You can not take a gradient of a function that uses the method `trace`. It will give you an error `TypeError: 'JVPTrace' object is not callable`

Code example:
```python
import jax
import numpy as np

def foo(x):
    return x.trace()

print(foo(np.random.randn(3, 3)))
print(jax.grad(foo)(np.random.randn(3, 3)))
```

**Comment by mattjj** [comment]
Thanks for catching this! The issue is that [even though we set up a `trace` method on our array types](https://github.com/google/jax/blob/35810c9dcd181b087959f6089deff320edef9872/jax/numpy/lax_numpy.py#L3417), we also have [a member of our Tracer class named `trace`](https://github.com/google/jax/blob/1afcac70dfeaa4ffc89d79dc64f72361e18c4a91/jax/core.py#L297), and that's what is getting returned here.

I think the right solution is to rename our `trace` member to be `_trace`.

For now, here's a workaround:

```python
import jax
import jax.numpy as np  # changed!

def foo(x):
  return np.trace(x)  # call the function, not the method
```
