### ISSUE TITLE
lax.while_loop with multiple conditions

### ISSUE THREAD

**Issue by elientumba2019** [google/jax#21186]
### Description
```python
   def cond_fun(t):
        return t < 10 # & True

    def body_fun(t):
        t = t + 1
        return t

    t = lax.while_loop(cond_fun, body_fun, 0)
    print(t)
```
    
Hello i need some assistance please.  When running the above code i get the value of 10. However the moment i uncomment the True value. i get Zero.
Is this a normal behavior ? does jax support multiple condition in the condition function ? I am interested in enforcing multiple conditions . Thank you.

### System info (python version, jaxlib version, accelerator, etc.)

python 3.8.13
jaxlib 0.4.10+cuda12.cudnn88
acceleraror Nvidia 3090

**Comment by jakevdp** [comment]
You can string together multiple conditions using the `bitwise_and` operator, `&`:
```python
def cond_fun(t):
    return (t < 10) & True
```
Note the parentheses, which are not optional in this case: because of Python's [operator precedence](https://docs.python.org/3/reference/expressions.html#operator-precedence) rules, `t < 10 & True` is equivalent to `t < (10 & True)`, which is why you were getting unexpected results.
