### ISSUE TITLE
grad of fori_loop leads to cryptic error message

### ISSUE THREAD

**Issue by terhorst** [google/jax#2129]
I encounter the following AssertionError when trying to use `grad()`:

https://github.com/google/jax/blob/5362ea1d3d5f529ff31ad777e17634db8a5bf18d/jax/interpreters/ad.py#L98

The function I'm trying to differentiate is rather complex, so I wouldn't be surprised if the error is related to something else in my code. However, I am unclear where to begin as I do not even understand the point of the assertion, and it does not have any surrounding documentation. So that I can debug further, can you help me understand what this is for?

**Comment by terhorst** [comment]
Here is a minimal example that reproduces this error:
```
import jax
import jax.numpy as np
A = np.arange(2 * 3 * 3).reshape(2, 3, 3)
def f(x):
  return jax.vmap(jax.scipy.linalg.expm, 0)(A * x)
jax.grad(f)(1.0)
```

**Comment by terhorst** [comment]
It seems like gradients for expm() are still very much a work in progress (#2062).

**Comment by mattjj** [comment]
Thanks for opening this. While it's true that `expm` derivatives are a WIP, the fact that this error happened points to another bug somewhere (a bug with error messages).

**Comment by mattjj** [comment]
I think the issue is that we're differentiating through the Padé-approximant implementation of `expm`, and that's hitting [a `lax.fori_loop`](https://github.com/google/jax/blob/4c30c0285c509764f3b1b937b8a6bc9f9b8dd061/jax/scipy/linalg.py#L326), which isn't reverse-mode differentiable (because the trip count is unbounded a priori). We also don't raise a good error for it.

**Comment by terhorst** [comment]
I worked around this by using the block augmentation trick:
```
expm = jax.custom_transforms(jax.scipy.linalg.expm)

@jit
def expm_frechet(A, E):
    n = A.shape[0]
    M = np.vstack((np.hstack((A, E)), np.hstack((np.zeros_like(A), A))))
    return expm(M)[:n, n:]

@jit
def expm_vjp(g, ans, A):
    n = A.shape[0]
    E = np.eye(n ** 2).reshape(-1, n, n)
    dA = jax.vmap(partial(expm_frechet, A.T))(E).reshape((n,) * 4)
    return np.einsum('abcd,cd->ab', dA, g)

jax.defvjp(expm, expm_vjp)
```
(This has much worse performance than the PR, but is sufficient for my application where n=4 or 5.)

**Comment by terhorst** [comment]
Amusingly, though the above functions seem to work fine, calling
```
jax.vjp(vmap(expm))
```
produces the same `AssertionError` as before.

**Comment by sriharikrishna** [comment]
I have added defjvp rules to  #2062 that should fix this. 
```
import jax
import jax.numpy as np
import numpy as onp
A = np.arange(3 * 3).reshape(3, 3)
def f(x):
  return jax.scipy.linalg.expm(A * x)
primals, f_vjp = jax.vjp(f, 1.0)
print(onp.array(f_vjp(1.0)))
```
gives:
```
[9391168.]
```
Note that `jax.grad` does not work: 
```
TypeError: Gradient only defined for scalar-output functions. Output had shape: (3, 3).
```

**Comment by gnecula** [comment]
@mattjj I have started to work on this. Can you give me some pointers for how to proceed? 

The problem is that the partial evaluation of a while_loop produces unknown primals and then assertion in linearize fails. I want to detect early that a while_loop is used in a VJP context. I tried to intercept while_loop with a custom_partial_eval_rule but that is used in JIT as well.
