### ISSUE TITLE
Jaccard distance

### ISSUE THREAD

**Issue by garanews** [google/jax#214]
I would benchmarking JAX in Jaccard distance test.
I have code in pure python, numpy and numba.
A snippet of the last one:

```
@numba.njit()
def jaccard(x, y):
    num_non_zero = 0.0
    num_equal = 0.0
    for i in range(x.shape[0]):
        x_true = x[i] != 0
        y_true = y[i] != 0
        num_non_zero += x_true or y_true
        num_equal += x_true and y_true

    if num_non_zero == 0.0:
        return 0.0
    else:
return float(num_non_zero - num_equal) / num_non_zero
```
Can you please help me to use JAX for this?
Thanks in advance

**Comment by hawkinsp** [comment]
In general you will have a better experience if you write JAX that uses vector operations instead of Python-level loops, where possible. The same property is true of plain old NumPy, for slightly different reasons. 

You can write Jaccard similarity in a vectorized way something like this (and we should definitely hook this up to scipy.spatial.distance.jaccard!)

```
@jit
def jaccard(x, y):
     x = np.asarray(x)
     y = np.asarray(y)
     xt = x != 0
     yt = y != 0
     num = np.sum(np.logical_xor(xt, yt).astype(np.int32))
     denom = np.sum(np.logical_or(np.logical_and(xt, yt), np.logical_xor(xt, yt)).astype(np.int32))
     return np.where(denom == 0, 0.0, num.astype(np.float32) / denom)
```

**Comment by garanews** [comment]
Have a look here: https://gist.github.com/garanews/3524563ac2d2651830125c3f6138de0e
I'm doing some test. 
With numba I have some issue using parallel=True option because numba doesn't support some string function that I need (for example contained in re module )

Do you think that with JAX I will be able to achieve this?

**Comment by mattjj** [comment]
That code is a bit much to review in detail, but hopefully @hawkinsp's code is a good starting point for computing Jaccard distance. Maybe one other useful piece of information is that JAX doesn't compile string manipulation operations, and you'll get clear errors if you ask it to.

Since the question about Jaccard distance was answered, I'm going to close this issue. If you have more JAX-specific questions, don't hesitate to ask.
