### ISSUE TITLE
It would be nice if jax.device_get returned numpy scalars

### ISSUE THREAD

**Issue by girving** [google/jax#2168]
The following behavior is not quite idiomatic numpy:

```
In [5]: jax.device_get(jnp.abs(7))
Out[5]: array(7, dtype=int32)
```

Ideally, this would instead print 7.  This is what would happen if rank 0 jax arrays converted to numpy scalars in `jax.device_get`, as is the default behavior in both numpy and tensorflow.

Is it possible to fix `jax.device_get` to make numpy scalars?

**Comment by shoyer** [comment]
NumPy does return scalars almost all the time instead of 0d arrays, but personally I find that behavior from NumPy pretty confusing/inconsistent. I would rather that functions have consistent return types, e.g., always return arrays.

If I were redesigning NumPy, I would even try to get rid of NumPy scalars entirely. So I consider this a bit of an improvement in JAX's design over the way NumPy works.

That's just my two cents, though, I'd love to hear from anyone else who has a strong opinion :).

**Comment by girving** [comment]
`array("A good chunk of me wanting this is making simple numbers print as simple numbers, so that I can find outputs easier to read.", dtype=object)`

**Comment by girving** [comment]
Basically numpy's default is scalars, so it wants to be loud if you return something nonstandard.  And jax is returning something nonstandard, so the result is loud.  The argument about redesigning numpy doesn't really apply in that sense given that numpy is fixed.

**Comment by mattjj** [comment]
Thanks for the idea, Geoffrey!

I think it’s unlikely we’ll ever want to add numpy scalar support; the power-to-weight ratio just isn’t good enough. It’s a non-goal to match numpy precisely; we already deviate from numpy in other ways (like precise dtype promotion semantics). I think shoyer’s point about “if I were redesigning numpy” is meant in that context: which parts of the numpy api is it a high priority to simulate, and which are just quirks at this point?

It’s possible I didn’t understand your point about printing, but I wonder if there’s a reason not just to check ndim or size?

Since we aren’t likely to work on this or even accept contributions in this direction, I’m going to close this one.

**Comment by girving** [comment]
The printing point is ergonomics: Python things that look like integers normally print as bare integers (`7`, say), while Jax integers print like `array(7, dtype=int32)`.  And if you want to extract the normal ergonomic integer you have to do something awkward like `x[()]`.

**Comment by mattjj** [comment]
Well actually, to be more precise, they repr as `array(7, dtype=int32)` but they print just like Python integers:

```python
In [1]: from jax import jit

In [2]: jit(lambda x: x)(7)
Out[2]: DeviceArray(7, dtype=int32)

In [3]: print(jit(lambda x: x)(7))
7
```

We want the repr method to act that way because, as per Python conventions, we want to indicate that the type of the object is different (ie repr conveys more information, and isn't made for printing ergonomics).

If you want to convert back to a Python integer or float, why not just use the builtin `int` or `float`?
