### ISSUE TITLE
How to convert jax model to tensorflow model

### ISSUE THREAD

**Issue by ai-gamer** [google/jax#2174]
I got some code using jax to train a neural net model. I would like to save the results and load it into tensorflow for further training. Could it be possible and how I can do it? Any suggestion would be helpful. Thanks a lot!

**Comment by hawkinsp** [comment]
It's certainly possible to do what you ask manually, but there's no library support for it. For example, you can save the network weights using `pickle` or `numpy`'s array I/O features and load the result into another system, such as Mxnet or PyTorch, provided you have an identical neural network definition in that system.

In general, this is probably out of scope for the core of JAX itself: JAX really focuses on NumPy + transformations, and this is a question for a neural network library built on top of JAX, of which there are several. For example, I believe Trax, which is built on top of JAX, may be able to do something along these lines. But JAX itself doesn't really have an opinion about neural networks or weights.

(We do have `jax.experimental.stax`, but it's more of a proof of concept than anything else.)

I hope that helps!

(Closing because I think this is out of scope for JAX itself.)

**Comment by ai-gamer** [comment]
Thanks for the reply. It helps.
