### ISSUE TITLE
Adding `remat` causes an error to otherwise working code

### ISSUE THREAD

**Issue by tomhennigan** [google/jax#2180]
When running the code below under `remat` we get the following error:

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-16-3143f2d8c2b3> in <module>()
     11 x = jnp.ones([1, 1, 1])
     12 f = jax.remat(f)
---> 13 jax.grad(f)(w, x)

17 frames
google3/third_party/py/jax/interpreters/ad.py in bilinear_transpose(lhs_rule, rhs_rule, cotangent, x, y, **kwargs)
    503 
    504 def bilinear_transpose(lhs_rule, rhs_rule, cotangent, x, y, **kwargs):
--> 505   assert (x is undefined_primal) ^ (y is undefined_primal)
    506   if x is undefined_primal:
    507     out = zero if cotangent is zero else lhs_rule(cotangent, y, **kwargs)

AssertionError: 
```

Without `jax.remat` the code does not error out and produces:

```
DeviceArray([[3.]], dtype=float32)
```

**Reproducer:**

```python
import jax
import jax.numpy as jnp

def f(w, x):
  a = jnp.dot(x, w)
  b = jnp.einsum("btd,bTd->btT", a, a)
  c = jnp.einsum("btT,btd->btd", b, a)
  return jnp.sum(c)

w = jnp.ones([1, 1])
x = jnp.ones([1, 1, 1])
f = jax.remat(f)  # comment this and things work
jax.grad(f)(w, x)
```

**Comment by girving** [comment]
@mattjj Does this reproduce for you?

**Comment by mattjj** [comment]
Yes, thanks for the easy repro!

**Comment by mattjj** [comment]
Simpler repro:

```python
import jax
import jax.numpy as jnp

@jax.jit
def mul(a, b):
  return a * b

def f(w, x):
  a = mul(w, x)
  b = mul(a, a)
  return b

w = 1.
x = 1.
f = jax.remat(f)  # comment this and things work
jax.grad(f)(w, x)
```

It's a bit tricky to unpack what's gone wrong here, but here goes!

As background (cf. #1719): is this jaxpr transposable?

```
{ lambda  ;  ; a.
  let b = add 2. 3.
      c = mul b a
  in [c] }
```

It sure looks like a linear function! But before #1749, which added `jax.remat`, JAX was not able to transpose it. Instead, we relied on JAX's aggressive partial evaluation machinery never to produce a jaxpr like that, and instead to produce one that looked like this:

```
{ lambda  ;  ; a.
  let b = mul 5. a
  in [b] }
```

However, `jax.remat` is all about leaving more to be evaluated during the backward pass; that is, the point of `jax.remat` is to prevent thorough partial evaluation and instead to leave in un-evaluated bits that we'll need to evaluate on the backward pass. That's why #1749 made our `ad.backward_pass` function more complicated.

The basic additional complexity is that before `ad.backward_pass` tries to transpose a jaxpr, it should try to evaluate as much as possible, like the `b = add 2. 3.` equation in the above example. The remaining stuff that can't be evaluated better be part of the linear computation to be transposed. This logic is simple for primitives, but gets a bit recursive when the jaxpr to be transposed has calls (i.e. `jit` functions) in it: we need to treat those as transparent and recurse into them to evaluate as much as possible.

This bug showed that our logic wasn't right, and wasn't evaluating enough. In particular, the assertion in the bilinear transpose rule was complaining that it was being asked to transpose a bilinear function with respect to one input, in which case exactly one of its two inputs should be an evaluated constant, yet it wasn't seeing either be an evaluated constant. The trouble was in recursing into calls, and it came up with `jnp.einsum` because `jnp.einsum` is `jit`-decorated.

#2214 will fix this, though I'm going to take this opportunity to see if I can remove the `ad._eval_primals` function entirely and just reuse our existing partial eval machinery...

**Comment by mattjj** [comment]
Ah, I think I see now why I didn't reuse the partial eval machinery: we don't have enough information readily available to make PartialVals (since we don't know the type of the `undefined_primal` values). Maybe I'll defer that cleanup to another day!

**Comment by girving** [comment]
Thanks for the fix and the interesting commentary!  Also, evidence that you have well designed software: fixing a subtle bug by reducing the total amount of code. :)
