### ISSUE TITLE
Passed `stacklevel=2` for the new `tree_flatten` deprecation warning.

### ISSUE THREAD

**Issue by patrick-kidger** [google/jax#21833]
It looks like the new warning is here:

https://github.com/openxla/xla/blob/ecf9651a31272bd46b99f34c6205a5e225a6424d/xla/python/pytree.cc#L598

I think it would be useful to pass whatever the C++ equivalent of `stacklevel=2` is here. Right now I have loads of warnings and no easy way to determine where they came from!

**Comment by jakevdp** [comment]
It looks like the stacklevel is hard-coded to `1` here: https://github.com/openxla/xla/blob/ecf9651a31272bd46b99f34c6205a5e225a6424d/xla/python/nb_helpers.h#L40

**Comment by hawkinsp** [comment]
`warnings.simplefilter("error")` is helpful here, but fair point, I'll take a look.

**Comment by hawkinsp** [comment]
In general `stacklevel` is a bit bogus, because we don't know which of the callers matter. e.g., you're calling via `tree_map`, most likely so you probably see `tree_map` here at the moment, but had you called `flatten_up_to` you'd be happy right now and the warning stack level would be correct. But I'll bump it up to 2 since it's very likely `tree_map` is the common case here.

**Comment by hawkinsp** [comment]
But if I bump it up to `3` then you see `jax.tree.map` if you used that API. I can't really win this game: any choice I make will be wrong for some call site.

**Comment by patrick-kidger** [comment]
> `warnings.simplefilter("error")` is helpful here, but fair point, I'll take a look.

Oh, good shout. Yup, that suffices for my purposes. (For anyone else reading this thread and using `pytest`, then `pytest -Werror` will do this for you.)

**Comment by hawkinsp** [comment]
And I'd recommend running your CI that way, if you want prompt warning of upcoming problems. We do that for our own CI.
