### ISSUE TITLE
Creating large constant is slow

### ISSUE THREAD

**Issue by JuliusKunze** [google/jax#2211]
```python
print(np.array([[0] * 2000] * 2000).shape)
```

is fast (<1s) for `import numpy as np`, and slow (> a few minutes) with `import jax.numpy as np`, both with CPU and GPU versions of jaxlib.

**Comment by gnecula** [comment]
I can see that unlike the original numpy, [jax.numpy.array](https://github.com/google/jax/blob/5e77789afe6118b80341d341f09b8b390edbf703/jax/numpy/lax_numpy.py#L1797) is putting the data on the device. The way it currently does that when the argument is a list is to process separately each element of the list. Perhaps somebody more knowledgeable can comment on why it is done that way. 

A workaround is to create the ndarray using the original NumPy and then put it all at once on the device:
```
np.array(onp.array(...))
```

**Comment by shoyer** [comment]
I think it's slow simply because `jax.numpy.array` is implemented in Python, by recursively calling into nested lists. JAX has a fair amount of overhead for every operation, and there are at least ~4000000 here.

In contrast, NumPy implements casting in C, so there's no overhead of nested Python function calls. That's definitely going to be a faster way to go when it will work, but on the other hand, it would break if one of numbers is replaced by an auto-diff tracer.

**Comment by gnecula** [comment]
I marked this as a candidate for explaining in the documentation.

**Comment by gnecula** [comment]
Just to keep track of this

**Comment by gnecula** [comment]
Documented in #2458
