### ISSUE TITLE
How to perform a Bucketize and dynamic_partition OP？

### ISSUE THREAD

**Issue by MoFHeka** [google/jax#22151]
1. Like tf.raw_ops.Bucketize
input=[123.5, 0.7, 10.3, 100.6, 11.7] boundaries=[1,11,111]
output=[3,0,1,2,2]

2. Like tf.dynamic_partition which also torch.ops.fbgemm.block_bucketize_sparse_features in torch
input=[123.5, 0.7, 10.3, 100.6, 11.7] partition=[1,0,2,0,1]
output=[0.7, 100.6] and [123.5, 11.7] and [10.3] 

Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

**Comment by jakevdp** [comment]
For `Bucketize`, so long as the buckets are sorted I think `jnp.searchsorted` will give what you want:
```python
>>> import jax.numpy as jnp

>>> input=jnp.array([123.5, 0.7, 10.3, 100.6, 11.7])

>>> boundaries=jnp.array([1,11,111])

>>> jnp.searchsorted(boundaries, input)
Array([3, 0, 1, 2, 2], dtype=int32)
```
For `dynamic_partition`, the operation seems like it's incompatible with the semantics of JAX transformations because the number and size of output arrays depends on the contents of the input arrays. If you say more about what you want to do with the partitioned values, we may be able to suggest some alternatives. But as an intermediate step, an API with the semantics of `dynamic_partition` would be problematic in JAX code.

**Comment by MoFHeka** [comment]
@jakevdp This is tensorflow internal dynamic_partition source code using XLA , can see what can be referred to?

https://github.com/tensorflow/tensorflow/blob/132c98b29c1a42298cd13055d1168c8d67177bc9/tensorflow/compiler/tf2xla/kernels/dynamic_partition_op.cc

**Comment by MoFHeka** [comment]
I thought that what could be implemented with XLA must be implemented with JAX, is it because JAX does not support dynamic tensor? So how does tensorflow use dynamic_shape in static graphs?在 2024年6月28日，20:45，Jake Vanderplas ***@***.***> 写道：﻿
That is tf2xla code for dynamic_partition – it's not particularly relevent to JAX.
If you want to write dynamic_partition in JAX, you can, but due to its inherently dynamic shapes it won't be compatible with JAX's transformations, including JIT-compilation. It might look something like this:
def dynamic_partition(input, partition):
  return [input[partition == i] for i in range(partition.max())]

**Comment by jakevdp** [comment]
You can implement it in JAX (my answer showed you how) but the operation cannot be compiled because it required dynamic shape semantics.
