### ISSUE TITLE
Slow JIT compilation when involving index_update and index_add

### ISSUE THREAD

**Issue by goingtosleep** [google/jax#2242]
I tried implementing a simple LU factorization in JAX as follows:

```python
import numpy as np
import jax.numpy as jnp
from jax.ops import index, index_update, index_add
from jax import jit

@jit
def LU_jax(A):
    U = A
    m, n = U.shape
    L = jnp.eye(n)
    for k in range(n-1):
        for j in range(k+1,n):
            L = index_update(L, index[j,k], U[j,k]/U[k,k])
            U = index_add(U, index[j,k:n], -L[j,k]*U[k,k:n])
    return L, U

n = 30
A = np.random.rand(n,n)
A_jax = jnp.array(A)
%time L_jax, U_jax = LU_jax(A_jax)
```

That gives the result (on Google Colab with GPU runtime):
```
CPU times: user 20.6 s, sys: 2.4 s, total: 23 s
Wall time: 29.1 s
```

The second time (with a new random matrix, similar dimension `30x30` as input), it only takes `18.4 ms`:
```
CPU times: user 19.3 ms, sys: 0 ns, total: 19.3 ms
Wall time: 18.4 ms
```

I think I'm doing something wrong that 30 seconds compilation time for `n=30` is quite slow. Please let me know the mistakes and is there any workaround?

**Comment by shoyer** [comment]
JAX is slow to compile code that involves large Python “for” loops, because it’s tracing approach to compilation doesn’t see Python control flow, only the action of it on variables.

You should be able to get fast compile times if you switch to lax.scan or lax.fori_loop.

Side note: JAX does come with an LU decomposition, in jax.scipy.linalg.lu, which is going to be faster than anything you write directly in JAX because it links to optimized implementations from BLAS or cusolver.

**Comment by hawkinsp** [comment]
One other thing I will note is that there is an in-Python LU decomposition that JAX uses as its TPU implementation, here:
https://github.com/google/jax/blob/b6e834117616977c85dae1e166124e3254304ca4/jax/lax_linalg.py#L497

The inner block kernel is rolled, which helps avoid the size explosion.
