### ISSUE TITLE
Add documentation for the pypi release of jax

### ISSUE THREAD

**Issue by Kamuish** [google/jax#22709]
I noticed that we only have *latest* as an option on the readthedocs documentation (which matches with the source in the repo). It would be nice to also have the documentation for the current pypi-installable version, as the two will not a match. 

I will give the example of jax.lax.map, where the documentation mentions the *batch_size* parameter and the pypi version does not have it.

**Comment by superbobry** [comment]
I remember we discussed this internally a few months ago, but I don't recall any fundamental reasons not do it.

Jake, wdyt?

**Comment by jakevdp** [comment]
Hi - we briefly experimented with versioned docs a while back, but abandoned the effort for a few reasons:

- search engines were indexing old versions of the docs, which was causing confusion
- it was more-or-less impossible to build older versions of docs, because the doc build does not pin all dependencies, and older JAX versions were incompatible with recent releases. Since we don't do patch versions, there was no way to address this

The result was patchy coverage for old versions that was more likely to be annoying than to be useful, and so we decided to go back to only documenting the latest version.

**Comment by Kamuish** [comment]
Thanks for the quick reaction!

In that case, is it safo to assume that the pypi version of jax considered an "old" version?

**Comment by jakevdp** [comment]
Yes, sometimes the docs are ahead of the most recent pypi release, but any specific case will usually be resolved within a couple weeks by the next release.

**Comment by Kamuish** [comment]
ok, thanks! Closing the issue now
