### ISSUE TITLE
`assert np.all(np.isfinite(x))` not working under jit

### ISSUE THREAD

**Issue by clemisch** [google/jax#2273]
Dear jax team,

I'd like to check an intermediate result `x` inside a jit'ed function to not contain any `NaN`s via `assert np.all(np.isfinite(x))`. 

I found that this does not work under jit. It does work though 

1. without jit or 
2. for `return np.all(np.isfinite(x))` under jit. 

If I can `return` but not `assert` under jit, what is the problem here?

--- 
repro:

```python
import jax
import jax.numpy as np

a = np.array([1., np.nan, 3.])

@jax.jit
def test_nan_return_jit(x):
    return np.all(np.isfinite(x))

print(test_nan_return_jit(a)) # works (False)



def test_nan_assert_nojit(x):
    assert np.all(np.isfinite(x))

print(test_nan_assert_nojit(a)) # works (AssertionError)



@jax.jit
def test_nan_assert_jit(x):
    assert np.all(np.isfinite(x))

print(test_nan_assert_jit(a)) # doesn't work (TypeError: Abstract value passed to `bool`)
```

**Comment by hawkinsp** [comment]
This is working as intended, and it's a fairly fundamental consequence of the design of JAX.

When you wrap a function with `jit`, we trace the function with symbolic ("abstract") values. However, whenever tracing encounters control flow (here, the `if` condition that is implicitly inside `assert`), in order to know which branch to take, we must have a concrete value for the `if`-condition. If we don't, you get an exception, much like the one you see there.

Taking a step back, you can't really call `assert` inside a `jit`-decorated function unless you are asserting properties that would be known at `jit` trace time, not run time. Here, the result of the assertion is clearly known only at runtime because it depends on `x`.

The workaround are:
* return a boolean value from `jit` and do the assertion outside (i.e., your first version)
* don't use `jit` around that function (i.e., your second version)

Does that help?

**Comment by clemisch** [comment]
Yes, thank you for the quick reply. 

I was naively expecting that the abstract tracing would still work with `assert`, because the implicit `if` inside it does not affect the control flow of the program. The shapes could be traced as if the `assert` would not exist, and if it triggers, it stops the program anyway.

**Comment by wookayin** [comment]
Does jax have some `Assert` ops that can be used with traced tensors, just like `tf.debugging.Assert` (https://www.tensorflow.org/api_docs/python/tf/debugging/Assert) ?

**Comment by sharadmv** [comment]
There are a few options here (all outlined on [this page on JAX's documentation](https://jax.readthedocs.io/en/latest/debugging/index.html)):
1. Use [`jax.experimental.checkify`](https://jax.readthedocs.io/en/latest/debugging/checkify_guide.html). This might be the closest to a `tf.debugging.Assert`-like experience.
1. Use `jax.debug.breakpoint` with a `lax.cond` (https://jax.readthedocs.io/en/latest/debugging/print_breakpoint.html#usage-with-jax-lax-cond)
1. Enable the `jax_disable_jit` config option (`with jax.disable_jit(): ...`) and inside use regular Python assertions and/or `pdb`.

**Comment by hansbuehler** [comment]
> Dear jax team,
> 
> I'd like to check an intermediate result `x` inside a jit'ed function to not contain any `NaN`s via `assert np.all(np.isfinite(x))`.
> 
> I found that this does not work under jit. It does work though
> 
> 1. without jit or
> 2. for `return np.all(np.isfinite(x))` under jit.
> 
> If I can `return` but not `assert` under jit, what is the problem here?
> 
> repro:
> 
> ```python
> import jax
> import jax.numpy as np
> 
> a = np.array([1., np.nan, 3.])
> 
> @jax.jit
> def test_nan_return_jit(x):
>     return np.all(np.isfinite(x))
> 
> print(test_nan_return_jit(a)) # works (False)
> 
> 
> 
> def test_nan_assert_nojit(x):
>     assert np.all(np.isfinite(x))
> 
> print(test_nan_assert_nojit(a)) # works (AssertionError)
> 
> 
> 
> @jax.jit
> def test_nan_assert_jit(x):
>     assert np.all(np.isfinite(x))
> 
> print(test_nan_assert_jit(a)) # doesn't work (TypeError: Abstract value passed to `bool`)
> ```

You can use ` jax.debug.callback` as follows:

```python
def check_finite( isfinite, name ):
    if not isfinite:
        raise Exception("*** not finite", name)    

```
and in your JAX code, for example to test validity of ``record``:

    jax.debug.callback( partial(check_finite, name="record"), isfinite=jnp.all( jnp.isfinite( record) ) )
