### ISSUE TITLE
jax2tf oddly casts uint8 input to uint32 before passing to radix sort.

### ISSUE THREAD

**Issue by chihuahua** [google/jax#22854]
### Description

An Alphabet model uses jax2tf and calls `jax.lax.top_k` with a jax.Array of dtype uint8 and shape (1, 1,32768):

For this call, XLA ends up calling radix sort. However, the radix sort is sub-optimal because the inputs are uint32 (instead of uint8). Of course, radix sort is faster across smaller dtypes (with fewer bytes).

The jax2tf bridge lowers the TopK call to a sort over uint32, thus slowing down the radix sort.

> @@(u32[1,32768]{1,0}, s32[1,32768]{1,0}, u8[271871]{0}) custom-call(u32[1,32768]{1,0}, s32[1,32768]{1,0}), custom_call_target="__cub$DeviceRadixSort

Why would the jax2tf bridge cast the uint8 input array to uint32 before passing it to radix sort?

I would expect HLO text more like this, where the uint8 inputs are passed directly:

> (u8[1,32768]{1,0}, s32[1,32768]{1,0}, u8[310527]{0}) custom-call(u8[1,32768]{1,0}, s32[1,32768]{1,0}), custom_call_target="__cub$DeviceRadixSort"

Someone on XLA team took a look and noticed that the casts to uint32 is not actually used in the optimized HLO. Could the jax2tf bridge instead generat HLO text that directly passes a uint8 directly sort? I believe this would have the number of sweeps required for radix sort and thus halve the latency of our sorts in this latency-sensitive model.

Is there reason that the input is cast to uint32?

To reproduce this issue, collect an XProf trace via running

```python
import tensorflow as tf

data = tf.random.uniform(
          shape=(1, 32768),
          minval=0,
          maxval=256,
          dtype=tf.int32,
      )
data = tf.cast(data, tf.uint8)
_, box_indices = tf.math.top_k(data, k=1024)
```

![image](https://github.com/user-attachments/assets/87a60019-74f4-4deb-bddf-237a1717e9d0)

Or feel free to just find and run my internal experimental `benchmark_tf_top_k_uint8` binary on a machine with a GPU.

### System info (python version, jaxlib version, accelerator, etc.)

My workstation at HEAD. Can be reproduced on V100. Possibly other GPUs too.

**Comment by gnecula** [comment]
I see in the jax2tf sources that when using `native_serialization=False`, the operands are promoted indeed to `uint32`, with a comment that this is due to the fact that `tf.math.top_k` does not support `uint8`: https://github.com/google/jax/blob/0b87bf48f97ace10c7aee19c8f980788891a2df7/jax/experimental/jax2tf/jax2tf.py#L3167

If that is the source of your issues, then you can solve them by using `native_serialization=True`. Note that only the native serialization mode is supported for jax2tf starting with this month. You should see a `DeprecationWarning`. The non-native-serialization mode is deprecated and will be removed.

I note also that your repro is about TF, it does not contain JAX. If that repro really reflects your issue, then this bug should go to TensorFlow.

**Comment by chihuahua** [comment]
> I note also that your repro is about TF, it does not contain JAX. If that repro really reflects your issue, then this bug should go to TensorFlow.

Thank you - That makes sense! 

> Note that only the native serialization mode is supported for jax2tf starting with this month.

It sounds like the `jax -> TF -> HLO` pathway will be removed this month - That is useful to know. Thank you!
