### ISSUE TITLE
Adding regularizers to Stax

### ISSUE THREAD

**Issue by sscardapane** [google/jax#244]
Some utilities for regularizing the cost functions would be useful in Stax. I have not seen this mentioned in #137. Is this planned?

Also, I was wondering about the best way to implement this in pure JAX. For example considering L2 regularization, with the flattening utility from #190 I could write:

```
w_flat, _ = ravel_pytree(w)
reg = np.sum(w_flat ** 2.0)
```

Looking a little bit on the code of tree_util I can also write:

```
reg= tree_reduce(lambda x, y: np.sum(x) + np.sum(y), tree_map(lambda wi: np.sum(wi**2.0), w))
```

Is there a simpler solution I am missing? More in general it would be useful to document tree utilities in the main doc.

**Comment by mattjj** [comment]
Thanks for suggesting this!

The `tree_reduce` version is better because otherwise all the arrays have to be concatenated together. It's possible that XLA could optimize away that explicit concatenation when under an `@jit`, but I'm not sure it will.

Here's another way to write it which avoids traversing the tree twice:

```python
from jax.tree_util import tree_flatten
import jax.numpy as np

def l2_squared(pytree):
  leaves, _ = tree_flatten(pytree)
  return sum(np.vdot(x, x) for x in leaves)
```

We could add this to Stax, or perhaps to an MNIST example file. We'd like to avoid making Stax into a monolith; part of the point is to show how easy it is to write neural net "layers" libraries, so you can write one yourself with whatever features you want.

**Comment by sscardapane** [comment]
A notebook with some "advanced" use cases would be terrific! Especially on the parts of the library that are less documented at the moment.
