### ISSUE TITLE
GitHub random number generator performance

### ISSUE THREAD

**Issue by jonasrauber** [google/jax#2482]
This is not exactly a bug report but something I noticed that might be good to know.

The random number generation in JAX is not just slower than e.g. PyTorch or TensorFlow (might be expected, though 10x compared to PyTorch seems large), it also has very different trade-offs. I compared two algorithms for random sampling from an n-dimensional ball and for all frameworks (NumPy, PyTorch, PyTorch GPU, TensorFlow GPU) one algorithm is faster than the other one, except for JAX, there it's the other way round.

https://github.com/jonasrauber/uniformly-sampling-nd-ball

Feel free to close this if you don't think it's worth any further consideration.

**Comment by jakevdp** [comment]
I'm not sure if there's anything actionable here – the implementation is pretty opaque (it generates JAX code via a third-party package that I didn't take the time to look into) so it's not clear whether best practices are being used for the benchmarks (see e.g. https://jax.readthedocs.io/en/latest/faq.html#benchmarking-jax-code)

Since this has sat for over two years, I'm going to close.
