### ISSUE TITLE
Mixed dtype in lax.scan

### ISSUE THREAD

**Issue by jcrichard** [google/jax#2486]
Hi,

I am not sure it is a bug as I am probably using `lax.scan` badly. When I pass integer and float data to the `scan` I have a shape exception.

Here is the reproducible example

```
import jax.ops as jop
from jax import jit
import jax.numpy as np
import jax.lax as lax

def get_loss(data):
    one_array = np.zeros(2) 
    loss = 0

    def inner_loop(carry, obsv):
        (loss, one_array) = carry
        val = one_array[obsv[0]]

        loss += 1
        return ((loss, one_array), None)

    carry = (loss, one_array)

    ((loss, one_array), _) = lax.scan(inner_loop, carry, data)

    return loss

data = np.array([[0, 1], [0, 1]])
jit_get_loss = jit(get_loss)
jit_get_loss(data)

data = np.array([[0, 1.1], [0, 1.1]])
jit_get_loss = jit(get_loss)
#jit_get_loss(data) # fail
```

So the question is how do you handle mixed datatype. Also, I guess it is not possible to pass a string in the data array?

thanks

**Comment by gnecula** [comment]
I believe that the problem is not with the scan itself, but with the indexing using floating-point indices. In your second call to `jit_get_loss` the data array is an array of floats (the whole array is promoted to floats, this is the behavior of NumPy). Hence `obsv` will be an array of floats in inner loop but you are using it to compute indices. 

In any case, this deserves a better error message. 

I think that the right way to implement this is to have two arrays, one array of integers with indices and  one array with additional data (what you had in `obsv[1]`). You can pass two arrays of the same length to scan and it will scan them both at the same time.

**Comment by jcrichard** [comment]
Thanks I did not know we could pass two arrays. I think it is the best and easiest way, thank you.

One last thing, is there a way to pass string array as well? Or it is not a valid type at all?

**Comment by gnecula** [comment]
array of strings is a numpy type, but neither JAX nor XLA do not know how to handle it, so you cannot use it directly (AFAIK). Perhaps if you can describe what you would be trying to achieve with an array of strings, I can think of an alternative.

**Comment by jcrichard** [comment]
Thank you for the answer. No need for now I can just encode the strings.

Thanks again for the help.

Le lun. 23 mars 2020 à 14:05, George Necula <notifications@github.com> a
écrit :
