### ISSUE TITLE
Spurious Exception: Tracer can't be used with raw numpy functions?

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#2502]
I cannot seem to make this minimum working example any smaller.  It seems like some combination of factors is causing this error, but I have no idea where to start.
```
import jax
import jax.scipy.special as jss
from jax import numpy as jnp


@jax.custom_jvp
def log_normalizer(q):
    return jnp.logaddexp(q[0], 0.0)


def nat_to_exp(q):
    return jss.expit(q)


@log_normalizer.defjvp
def ln_jvp(primals, tangents):
    x, = primals
    x_dot, = tangents
    y = log_normalizer(x)
    y_dot = nat_to_exp(x) * x_dot
    return y, y_dot


def cross_entropy_loss(p, q):
    # Bernoulli cross_entropy(p, q)
    p_dot_q = jnp.sum(p * q)
    ln = log_normalizer(q)
    return -p_dot_q + ln - jnp.zeros(())


# p are expectation parameters of a Bernoulli distribution corresponding to
# probability 0.4.
p = jnp.array([0.4])

# q are natural parameters of a Bernoulli distribution corresponding to
# log-odds 0, which is probability 0.5.
q = jnp.array([0.0])

print(jax.grad(cross_entropy_loss, 1)(p, q))
```

**Comment by mattjj** [comment]
Wow, this is a terrible error message we're raising. Like, so bad.

It's actually a shape error:

```
> /usr/local/google/home/mattjj/packages/jax/issue2502.py(22)ln_jvp()
     21     import ipdb; ipdb.set_trace()
---> 22     return y, y_dot
     23

ipdb> p y
DeviceArray(0.6931472, dtype=float32)
ipdb> p y_dot
Traced<ShapedArray(float32[1]):JaxprTrace(level=0/0)>
```

That is, `y` and `y_dot` are a scalar and a 1D array with length 1, respectively. This isn't checked in the custom_jvp machinery from #2026, and instead it falls through a strange cascade of steps ultimately leading to us calling `onp.shape` on a Tracer with an UnshapedArray for its abstract value. Ugh!

We should probably make `onp.shape(unshaped)` raise a better error message, but the more important action item here is to raise an error message when the output of the custom jvp rule has inconsistent shapes for the primal and tangent values.

That's how JAX can raise a better error. But also we need to fix this code here so that both primal and tangent outputs are scalars (or both are 1D arrays with the same shape).

WDYT?

**Comment by mattjj** [comment]
(I meant to add these kinds of error checks to #2026 a few weeks ago, but then had to stop working on it for a few weeks and forgot my context...)

**Comment by mattjj** [comment]
After #2503 this code produces a better error message:

TypeError: Custom JVP rule must produce primal and tangent outputs with equal shapes and dtypes, but got float32[] and float32[1] respectively.

Still not as good as having bug-free code, but I think this would have been much more actionable!

WDYT?

**Comment by NeilGirdhar** [comment]
Awesome, these new errors make it a lot easier to learn JAX too, so thanks for taking the time.
