### ISSUE TITLE
How to  accelerate use jit in loop

### ISSUE THREAD

**Issue by XDongiang** [google/jax#2515]
In my situation , i want use jit to compile the function once , and the big numpy array can be compile in the jit . but  in next loop the big numpy array will be change to another numpy array 

```python
from numpy import random
from jax.numpy import sqrt, pi, exp, log
import matplotlib.pyplot as plt
from jax import jit, grad
import iminuit
from iminuit.util import make_func_code, describe
sigma = 5.0
mu = 100.0
N = 100
tries = 2
s0 = sigma + random.randn(tries) * 0.5
s1 = mu + random.randn(tries) * 10.0
def _Likelihood(s, m, w):
    sum = 0
    for _x in w:
        term = -log(1 / (s * sqrt(2. * pi)) * exp(- ((_x - m) / s)**2 / 2.))
        sum += term
    return sum

def Likelihood(pars):
    return jit(_Likelihood)(pars[0], pars[1], x)

def my_dev_likelihood(pars):
    return jit(grad(_Likelihood))(pars[0], pars[1], x)

for ss, mm in zip(s0, s1):
    x = random.randn(N) * sigma + mu
    my_pars1 = (ss, mm)
    my_pars2 = (ss+0.1, mm+0.1)
    my_dev_likelihood(my_pars1)
    my_dev_likelihood(my_pars2)
```
in my code ,  i find that it is updata the x each loop in my_dev_likelihood , but the jit can not accelerate because x is a parameter , and x calculate in each loop in each  my_dev_likelihood . so i want some method that make the first  my_dev_likelihood the x is a const in function and be compile and in second my_dev_likelihood it will be fast ,and  in next loop the x will updata and creat new graph

**Comment by gnecula** [comment]
I am having a hard time understanding your description of the problem. One thing that would help would be to reduce the code to a minimum (one function with one loop and jit, and explaining which function call you expected to run faster. 

I see two loops in your code. The `for` loop inside `_Likelihood` is not compiled as a loop but is unrolled. I assume you have seen [this](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html). I suspect that you are talking about the second loop, which changes `x`, even though `x` is not an argument to the function. It is true that since `x` is not an argument, the first time the loop is compiled the value of `x` is stored in the compiled code. (That situation is also described in the `Pure Functions` part of the above notebook.)

You must pass `x` to the `_Likelihood` function.
