### ISSUE TITLE
Index all but one element in an array

### ISSUE THREAD

**Issue by john-heyer** [google/jax#2522]
Hello!

I have a function:
```
@jit 
remove_random_element(rng, arr):
    n = arr.shape[0]
     i = random.randint(rng, shape=(1,), minval=0, maxval=n)[0]
    indices = np.hstack((np.arange(i), np.arange(i + 1, n)))
    return arr[indices]
```
which does not work because arange tries to convert `i` into an `int` when it is an abstract value (using `astype` did not solve this.

I have tried other functional approaches such as:
```indices = np.where(np.arange(n) - i)```
but I receive a boolean indices error.

Is it possible to do this? Thanks!

**Comment by mattjj** [comment]
Great question! This is a fun puzzle. The "static shape" requirement can be a bit tricky in these cases.

I think your idea to use indexing is a good one. How about this?

```python
from jax import jit
from jax import random
from jax.ops import index, index_update
import jax.numpy as np

@jit
def remove_random_element(rng, arr):
  n = arr.shape[0]
  i = random.randint(rng, shape=(), minval=0, maxval=n)
  indices = np.arange(n - 1) + (np.arange(n - 1) >= i)
  return arr[indices]


key = random.PRNGKey(0)
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

arr2 = remove_random_element(key, arr)
print(arr2)
```

Another way to do it would be to use a `lax.while_loop` or two (e.g. one that copies over all the elements up to but excluding the i'th, then another that copies over the rest). I've found that almost anything can be done with a `lax.while_loop`, but that's a bit of a last resort since generating a gather or scatter op (as indexing does) would be more efficient.

WDYT?

**Comment by john-heyer** [comment]
Awesome! I really appreciate the quick response! 

I had also tried `arr[np.arange(n) != i] ` which gave the boolean indices error as well, but this solution is nice.  Thanks again :)

**Comment by mattjj** [comment]
Glad it helped! Don't hesitate to ask similar questions in the future. Maybe we can make a "`jit` golf" compendium of challenge problems.
