### ISSUE TITLE
Profile compilation time

### ISSUE THREAD

**Issue by alewis** [google/jax#2570]
I'd like to separately profile the compilation and execution time of a Jitted function. Is there a way to force recompilation?

**Comment by hawkinsp** [comment]
An easy way to force recompilation is to make a new function object each time you call `jit`. e.g.,
`jit(lambda *args, **kw: f(*args, **kw))(...)`
will recompile each time because `jit` works by function identity, not by function equivalence (which in general is undecidable, of course...)

Hope that helps!
