### ISSUE TITLE
`AssertionError` with new `custom_jvp` for `jax.nn.relu`

### ISSUE THREAD

**Issue by schmrlng** [google/jax#2578]
On this [commit](https://github.com/google/jax/commit/ca23be63fbaed20192cda5f921afe177ac8dcf4d) (currently just a few commits behind head, none of which look relevant), I'm finding that
```python
import jax
import jax.numpy as np
import collections

class F(collections.namedtuple("F", ["a"])):
  def __call__(self, x):
    return jax.nn.relu(self.a) * x

@jax.jit
def g(f, x):
  return f(x)

jax.grad(F(2.0))(0.)  # works, returns DeviceArray(2., dtype=float32)
jax.grad(g, argnums=(1,))(F(2.0), 0.)  # AssertionError
```
hits an `AssertionError` on this line: https://github.com/google/jax/blob/1bb9aaa88c09a90a115c0304c05b0fc25932523b/jax/interpreters/partial_eval.py#L239

Commenting out the `@jax.jit` on `g` or replacing `jax.nn.relu(self.a)` with `np.maximum(self.a, 0)` both avoid the error.

**Comment by mattjj** [comment]
Thanks for catching this! I wish I'd noticed this issue right when you opened it, since the fix is easy: that assertion assumed there were no trivial tracers present, but in some places we don't lower out of traces as eagerly as we should. (Sorry, that probably made no sense, but the moral is we just have to call `core.full_lower` to drop out of trivial traces.)

#2593 has the fix.
