### ISSUE TITLE
Gradient Conditions For A Total Variation Implementation 

### ISSUE THREAD

**Issue by turnersr** [google/jax#2690]
Hello,

I am trying to use JAX to implement total variation regulation. This would replace the L1 term in the regularized linear regression to: 
`lambda*np.linalg.norm(gradient(w), 1)`

How would I add gradient conditions? Would np.diff() be the correct solution? 

Best!

**Comment by clemisch** [comment]
Although I've seen the neighborhood for Gibbs prior regularization being defined symmetrically most of the time, the forward difference `np.diff` should work just as well in practice. If you want to regularize in all directions you have to loop over all axes:

```python
def total_variation(w):
    cost = 0.0
    for i in range(w.ndim):
        wd = np.diff(w, axis=i)
        cost += np.linalg.norm(wd, 1)
    return cost
```

If you want to apply a mask or weights, you should use the central difference `np.gradient` instead, as it returns value on the same coordinate grid as opposed to `np.diff`.

```python
def total_variation(w, weights):
    cost = 0.0
    for i in range(w.ndim):
        wd = np.gradient(w, axis=i)
        cost += np.linalg.norm(weights * wd, 1)
    return cost
```

(FWIW I'm thinking in terms of `w` being a 3D volume, don't know if that makes sense for your context.)

**Comment by turnersr** [comment]
Thank you! Is there any insight on to how the gradient for L1 is computed? The update function for total variation ends up looking like 19.5.1 in https://www.stat.cmu.edu/~ryantibs/convexopt-F15/scribes/19-case-studies-scribed.pdf . Should I use a L1 approximation that is differentiable? 

I am not sure what you mean by "neighborhood for Gibbs prior regularization ", but would love to learn more.

**Comment by clemisch** [comment]
I guess you'll have the same issues using L1 for regularization regardless of the backend. `abs` is just not differentiable at 0. What I want to say is, whether you should use a differentiable approximation (Huber loss for example) depends on your specific problem. Maybe L1 works fine in practice for your data. 

To be honest, I don't understand the $\gamma_i \in [-1, 1] if (D \beta)_i = 0$ in 19.5.1. Maybe that's why I'm answering your question so poorly.

With "Gibbs prior regularization" I meant the formal mathematical motivation for using nearest-neighbor regularization. And in this context, I've seen (coming from medical imaging) the neighborhood of a data point being defined symmetrically around that point most of the time.

**Comment by turnersr** [comment]
clemisch, thank you so much. This discussion was helpful. I am going to close this issue now that I understand how these parts interact.
