### ISSUE TITLE
improve the memory footprint of reverse-mode autodiff of conditionals

### ISSUE THREAD

**Issue by froystig** [google/jax#2775]
The way we define and differentiate `lax.cond` can lead to redundant memory allocation during reverse-mode AD. In particular:

1. Each branch of a conditional takes inputs of its own. Passing the same value to both branches results in fan-out into a primitive, and incurs the corresponding cost during reverse-mode AD. This fan-out is not essential. We could imagine a version of `cond` that accepts `true_operand`, `false_operand`, and, say, `both_operand`. This change need not be exposed to callers of `lax.cond`. We can consider identifying common operands automatically within `cond`, then binding an underlying primitive with an explicit `both_operand`.

2. During linearization, we generate conditionals whose [output holds enough space for the concatenation of residuals from either branch](https://github.com/google/jax/blob/685c0de99bbf7224d5644feab93f850e3e0a96c7/jax/lax/lax_control_flow.py#L736-L739). Only the residuals associated with the branch taken are meaningful, but we lack sum types and `cond` branches must have outputs of equal type. When residuals from either branch have common types, we can house them in the same output value and avoid doubling their memory cost due to concatenation.

**Comment by gnecula** [comment]
For #1, I agree that it is worthwhile to add a version of `cond` that takes the same operands for both branches. This put the control into the user's hands to decide what can be shared between the arguments of the true and false branches. (I believe that the only tricky part will be to merge the closed-over environments from the two branches.)

For #2, it can be a problem because JAX emits two conditionals, one for linearization and one for the reverse diff computation, and the output of the former must contain the residuals for both branches, only to be immediately passed into the next conditional to be split among the branches.  
(In mini JAX we emit a single conditional so we can pass the residuals for the true branch directly into the reverse diff of the true branch.)

However, even though the code that JAX emits seems sub-optimal, it seems that XLA fuses the two conditionals because they use the same condition. This means that the "doubling of memory because of lack of sum types for conditional outputs" is not likely a real issue.

**Comment by gnecula** [comment]
For #2 @mattjj explained to me that we cannot always count on XLA compiler to fuse the conditionals from the forward and backward pass, if there is other stuff in between them.

**Comment by froystig** [comment]
Fixed in #2993 and in #3416
