### ISSUE TITLE
float(x) does not work if x is a concrete tracer, but int(x) works

### ISSUE THREAD

**Issue by gnecula** [google/jax#2783]
I expected the following code to work:

```
 def func(x):
    return x if float(x) >= 0. else -x
 print(api.grad(func)(3.))
```

because `int(x)` works. Instead that code gives an error  
```
TypeError: JAX Tracer object cannot be interpreted as a float. Try using `x.astype(float)` instead.
```

Using `x.astype(float)` works, but I am wondering if it would not be more uniform to support `float(x)` as well.

**Comment by mattjj** [comment]
Actually I think no, see #2602 where we just changed this. It would make float act like a silent stop_gradient. 

If we added an EpsilonBall level of abstraction for AD then we could make float work on tracers with concrete avals, but there doesn’t seem to be much upside.

**Comment by mattjj** [comment]
To say a bit more: the reason `int` works is that we treat rounding to an integer with `int` as having a zero Jacobian, so we can drop out of the AD tracer and specialize the abstract interpretation of the Python function on the resulting integer value, even when (in principle) the input to `int` is only specialized to an EpsilonBall. (To be _really_ careful, we should fail at discontinuities of `int`.)

But we can't do the analogous thing for `float` because it is sensitive to small perturbations of its input.

We could in effect automatically rewrite `float(x)` to be the same as `x.astype('float')` or something, but we haven't had Python builtins produce tracers or ndarrays before, and that seems inconsistent with both Python builtin definitions and with how we treat `bool` and `int`.

WDYT?

**Comment by mattjj** [comment]
Here's a comment I was going to leave in #2508, but then thought it might fit better here:

In principle, JVPTracers should carry EpsilonBall abstract values, for which (sketching the idea, this is not real code):

```
# these produce non-Tracer, Python builtin values
int(EpsilonBall(0.1))  # 0
bool(EpsilonBall(0.1) > 0.)  # True

# these are errors
int(EpsilonBall(1.0)))  # error b/c int is discontinuous at 1.0
bool(EpsilonBall(0.0) > 0.)

# this is either an error, or we treat it as equivalent to lambda x: x.astype('float') and return a Tracer
float(EpsilonBall(0.2))
```

If we distinguished EpsilonBall abstract values then `float(ConcreteArray(0.2))` could be evaluated to the Python builtin float `0.2`. But since we're most often using ConcreteArray to really mean EpsilonBall, we can't do abstract evaluation on `float(ConcreteArray(0.2))` or correspondingly specialize the trace on that info.

**Comment by gnecula** [comment]
Thanks for explaining. I do think that this is a subtle issue, I do not know if people run into it in practice, or just when poking curiously at JAX. Do you think it is worth an entry in the FAQ? 

> WDYT? In particular, do you think we should make float(x) behave exactly like x.astype('float'), at least on Tracer instances?

I think that x.astype(float) will produce a tracer if x is a tracer, which would not make sense as the result of float(x).

**Comment by mattjj** [comment]
Hmm hard to say: what's the bar for adding to the FAQ? We could just wait until it's asked before adding it.

(I just remembered, based on a JAXers thread and a realization just now, that the original reason for adding the `__float__` override may have been for printing with `%f`.)

I defer to your judgement on the FAQ, though my own bias is towards inaction :)
