### ISSUE TITLE
np.sum over all axes should return scalar, not array

### ISSUE THREAD

**Issue by jonasrauber** [google/jax#280]
```python3
np.sum(np.array([5, 5]) == 3)
```

returns `array(0, dtype=int32)` instead of `0`.

This is kind of the opposite of #121.

**Comment by mattjj** [comment]
Thanks for pointing out this behavior. NumPy scalars, as opposed to zero-dimensional arrays like we have here, [can get a bit complicated](https://stackoverflow.com/a/794812).

To help us prioritize, could you say a bit about how important this behavior is to you?

**Comment by mattjj** [comment]
(Whoops, didn't mean to hit the 'close and comment' keyboard shortcut!)

**Comment by mattjj** [comment]
By the way, thanks for bringing up these discrepancies (here and in other recent issues). It's extremely helpful to us to know what we're missing and to be able to discuss and think through these cases. We really appreciate it!

**Comment by jonasrauber** [comment]
It’s not of particular importance to me, just thought I bring it up. Maybe it should be listed under „current discrepancies between numpy and jax.numpy“.

**Comment by mattjj** [comment]
Happy almost-anniversary to this issue!

Over time we've decided to move away from NumPy in a few places. One is in treatment of scalars versus rank-0 arrays (as here), and a related one is dtypes. Mainly we've decided to prefer simplicity (e.g. in avoiding some esoteric and value-dependent dtype casting rules) over strict adherence to NumPy.

We should probably document this discrepancy, but we've got a lot of things worth documenting and I think this might be very low on the priority list. Since this issue hasn't caused much pain over the last year, I'm going to close it instead of leaving it open for documentation :)
