### ISSUE TITLE
jax.random.randint raises an error if minval and maxval have different rank than len(shape)

### ISSUE THREAD

**Issue by dwf** [google/jax#2836]
```python
import numpy as np
import jax
jax.random.randint(jax.random.PRNGKey(1), shape=(50, 2), minval=np.array([0, 0]), maxval=np.array([2, 2]))
```
results in (after a long stack trace)
```
TypeError: rem got arrays of different rank: (50, 2), (2,).
```
The docs specify that `minval` and `maxval` need only be broadcast-compatible with `shape`, and I assume that includes with rank-promotion, so I believe this is not the intended behaviour.

**Comment by mattjj** [comment]
Great question. Actually, we did not intend to support rank promotion here: we've gotten a good amount of feedback from users that automatic (i.e. silent) rank promotion leads to more bugs than conveniences. We even [added an option](https://jax.readthedocs.io/en/latest/rank_promotion_warning.html) so that rank promotion in `jax.numpy` can raise either a warning or an error! We briefly tried making that warn/error-by-default but rank promotion is so common in NumPy that we backed off.

However, since `jax.random` isn't part of the NumPy API and is instead already a JAX-y API, we decided not to support rank promotion for it. However, I think we could raise a clearer error message here.

WDYT? If you had gotten a clear error message about not supporting rank promotion, would you have been happy to add e.g. a singleton axis yourself? Everything is subject to criticism and revision, so we're eager to hear thoughts and opinions.

**Comment by dwf** [comment]
Ah, okay. Yes, once I figured out what was going on I happily added the axis myself, no big deal. I don't go out of my way to use rank promotion for the same reasons you've mentioned, but I was receiving the three arguments programatically and did the lazy thing of just adjusting `shape`.

A better error message would be great, but what made me assume it was a bug is the phrase "broadcast-compatible", which I assumed meant NumPy broadcasting rules in all of their mildly error-prone glory. In order to avoid more erroneous bug reports, I might suggest either:

* that the `jax.random` documentation include a note at the top about broadcasting, flagging the deviation from NumPy broadcasting semantics outside of `jax.numpy`; 
* replacing "broadcast-compatible" with "broadcast-compatible with matching rank" therein.

If the deviation is spelled out somewhere else, I missed it, and also Sphinx/RTD search is not that great at relevance. 🙂

**Comment by mattjj** [comment]
We fixed this at some point! The code in the OP runs without error.
