### ISSUE TITLE
vmap into dynamic_slice -- TypeError: unhashable type: 'BatchTracer'

### ISSUE THREAD

**Issue by tbsexton** [google/jax#292]
Is it possible to vmap over inputs to a dynamic indexer? E.g., trying to implement a likelihood function for a non-absorbing random walk by splitting into partitions of individual absorbing random walks (see [p.4 here](http://pages.cs.wisc.edu/~jerryzhu/pub/out-rw-flag.pdf), for example). 

The most straight-forward way I could think to do this in jax was to use `dynamic_slice_in_dim` on the markov chain, which can be used to index/partition the transition matrix as needed. Obviously this is vectorizeable, but the input "batch" will be which state I'm currently treating like the absorbing state. 

Issue starts when it seems I can't use the iterable used for `vmap` as an input to the `dynamic_slice_in_dim` function, as it throws an unhashable type error. Here's some example code: 

```python
def P_i(T, a, idx):
    """we need to partition the transition matrix
        $$ T =
        \begin{pmatrix}
         Q & R \\
         0 & I
        \end{pmatrix}
        $$
    where:
        $Q$: the non-absorbing transitions,
        $R$: non-absorbing to absorbing transitions
    Then, probability of being absorbed is given as
        $$P = (I-Q)^{-1} R$$
    However, this inversion may not exist, and may be numerically unstable.
    Instead, this can be rearranged into a linear system of equations,
    $Ax = b$, and solving for $P$ as $x$ gives
        $$(I-Q)P = R$$

    In this case, we only want the probability of transitioning from the
    most recent state to the current absorbing state.
    """

    a_trans = dynamic_slice_in_dim(np.array(a), 0, idx)  # visited
    a_absrb = dynamic_slice_in_dim(np.array(a), idx, len(a)-idx)  # not visited

    Q = T[a_trans, :][:, a_trans]
    R = T[a_trans, :][:, a_absrb]
    I = np.identity(Q.shape[0])

    P = linalg.solve(I - Q, R)  # Probability of absorption...
    return P[-1, 0]  # ...from previous state (P[-1,:] by construction) into next


def invite_likelihood(T, a):
    """Calculate the log-likelihood of a transition matrix $T$, given censored
    observed INVITE sequence $a$.
    """
    # need to include all possible states in T at the end of a
    frontload_a = list(a) + list(set(range(T.shape[0]))-set(a))

    transition_prob = vmap(partial(P_i, T, frontload_a))(np.arange(1, len(a)))

    return -np.log(np.sum(np.array(transition_prob)))
```

The function `P_i` is working well, such that trying 
```python 
for i in list(map(partial(P_i, T, frontload_a), range(1,len(a)))):
    print(i)
```
gives the desired values. Using vmap appears to break the functionality, however.

**Comment by mattjj** [comment]
Ah I think it might be easy to complete it into a full repro. I added these imports to the top:

```python
from functools import partial

import jax.numpy as np
from jax.numpy import linalg
from jax.lax import dynamic_slice_in_dim
from jax import vmap
```

And these lines at the bottom:

```python
T = np.array([[0.9, 0.1],
              [0.,  1.0]])
a = np.array([0, 0, 0, 0, 1, 1, 1])

print invite_likelihood(T, a)
```

I'm not seeing exactly the same error message, but I do see an error that makes sense to me, and could have led to the error message you saw (maybe the message is different because we've updated JAX a few times since you opened the issue).

The error I'm seeing is this:

```
/usr/local/google/home/mattjj/packages/jax/jax/lax.pyc in _dynamic_slice_translation_rule(c, operand, start_indices, s
lice_sizes, operand_shape)
   1882 def _dynamic_slice_translation_rule(c, operand, start_indices, slice_sizes,
   1883                                     operand_shape):
-> 1884   return c.DynamicSlice(operand, start_indices, slice_sizes)
   1885
   1886 def _dynamic_slice_jvp_rule(g, operand, start_indices, slice_sizes,

/usr/local/google/home/mattjj/miniconda2/lib/python2.7/site-packages/jaxlib/xla_client.pyc in DynamicSlice(self, opera
nd, start_indices, slice_sizes)
   1079       A LocalOp representing the added DynamicSlice op.
   1080     """
-> 1081     return self._client.DynamicSlice(operand, start_indices, slice_sizes)
   1082
   1083   def DynamicUpdateSlice(self, operand, update, start_indices):

/usr/local/google/home/mattjj/miniconda2/lib/python2.7/site-packages/jaxlib/pywrap_xla.pyc in DynamicSlice(self, opera
nd, start_indices, slice_sizes)
    365
    366     def DynamicSlice(self, operand, start_indices, slice_sizes):
--> 367         return _pywrap_xla.LocalComputationBuilder_DynamicSlice(self, operand, start_indices, slice_sizes)
    368
    369     def DynamicUpdateSlice(self, operand, update, start_indices):

TypeError: Argument sequence element cannot be converted to int
```

Not very informative! Really what's happening is that on this line:

```python
a_trans = dynamic_slice_in_dim(np.array(a), 0, idx)  # visited
```

the `idx` variable is abstracted to shape level by `vmap` because `vmap` wants to know how your function would behave with any possible integer value of `idx`, which would let it generate a function that operates on many values of `idx` at once. But the shape of evaluating that `lax.dynamic_slice_in_dim` depends on the *value* of `idx`. When shape information is lost, `vmap` (like `jit`) currently raises an error, instead of continuing to trace on values abstracted to an unshaped level. (For a bit more on tracing and abstract values, if you're interested, see [this comment](https://github.com/google/jax/issues/196#issuecomment-451671635).)

One thing we need to do here is improve the error message by making `lax.dynamic_slice_in_dim` try to force its third argument to be a concrete int.

As for revising this code, `vmap` can only work with it if all the intermediate shapes don't depend on concrete values. That might be possible, but it'll take some thinking...

**Comment by mattjj** [comment]
> Is it possible to vmap over inputs to a dynamic indexer?

I guess the short answer is no!

Do you know how you would vectorize this by hand? If so, we might be able to stare at that and figure out how we could get `vmap` to do it for us.

**Comment by tbsexton** [comment]
Ok, so I've thought about it a bit (apologies for the long lead time, I went ahead and implemented a working model in autograd just as a PoC to make sure I could get something to work). 

I haven't done this yet, but the way I'm thinking might work is to pre-process all of the partitions by padding with zeros. 

I.e. what I've been doing is performing the above partition on the fly as part of the loss function, looping over for every observation (for N total nodes at the i'th observation, Q is i x i and R is i xN). Since autograd ignores control flow, and I can perform this partitioning purely as a slice operation (instead of element assignment), everything works. To vectorize this, I suppose it's possible to pad Q and R with zeros, so that every operation will always be solving with NxN matrices. And given a set of observations, it's totally possible to pre-process them to be a set of Q's and R's that we train on directly. 

Obviously this will make every observation NxN so vectorization (should) be trivial. It's awful memory-innefficient, however, though like I said, I haven't tested my idea yet. 

I can imagine that having jax automatically pad sequential-style data like this, such that observations get post-padded and targets get pre-padded (to the max length of any in the list of training data?), could be useful, but seems a little hackey.

**Comment by mattjj** [comment]
Aha, great! This sounds like exactly the same issue that people run into when, for example, trying to batch RNN computations on ragged sequence lengths. If we want to make use of SIMD hardware (which is what vmap is about), we might need to do some kind of padding+masking to express things in a vmap-friendly way (or alternatively, for more memory efficiency, have some other sparse representation).

I say "great" because we're working on some new function transformations that should help this use case (see the "automasking" branch, which needs updating). But they're not ready yet, and might not be for a couple months.

In the meantime, this computation is just hard to batch in any system, and vmap on its own doesn't help. The best we have right now is "check back in a month and JAX might be able to help with this too!"

I'm going to close this issue if it's alright with you, but reopen if you think there's a JAX bug here (rather than an open challenge).

**Comment by tbsexton** [comment]
Sure thing, and I'll keep notifications on for this thread, in the meantime. Is it alright to post a working example here if/when I get jax to work with padding?

**Comment by mattjj** [comment]
Sure, that'd be great! Actually it might be best to open a new issue in that case, to ensure we notice it.
