### ISSUE TITLE
SVD in gpu is very slow compare to cpu

### ISSUE THREAD

**Issue by nthakor** [google/jax#2980]
I am using NVIDIA-T4 GPU
![image](https://user-images.githubusercontent.com/19538934/81149677-abc01480-8f4c-11ea-99b3-df1c5873600b.png)
and my cpu configuration is 
![image](https://user-images.githubusercontent.com/19538934/81149720-c1353e80-8f4c-11ea-83a3-624001230adf.png)

I am trying to recover 10k X 10k matrix using svd. my code is following 

```python
import jax
import jax.numpy.linalg as la
import jax.numpy as np
from jax import jit, lax
import numpy as onp
from jax.config import config; config.update("jax_platform_name", "cpu");config.update("jax_enable_x64","true")

@jax.partial(jit, static_argnums=1)
def k_rank_approax(X, k=10):
    k = min(k, min(X.shape))
    u, s, vt = la.svd(X, full_matrices=False, compute_uv=True)
    Xk = np.dot(u[:, :k], np.dot(np.diag(s[:k]), vt[:k, :]))
    return Xk

%%time
x = np.asarray(onp.random.random((10000,10000)))
xk = k_rank_approax(x,10000)
```
When using cpu backed time is 
```
CPU times: user 799 ms, sys: 132 ms, total: 931 ms
Wall time: 928 ms
```
with gpu backed it takes around 4-5 min.
```
CPU times: user 4min 5s, sys: 2min 4s, total: 6min 9s
Wall time: 6min 9s
```

**Comment by hawkinsp** [comment]
JAX mostly just calls NVidia's cusolver library for SVD on GPU, so this is probably a cusolver issue.

However, isn't the likely cause that a T4 GPU has 1/32th the fp64 FLOPs as compared to fp32 FLOPs? i.e., it's a GPU without a lot of fp64 compute capability?

Can you
a) try fp32
b) try a GPU with more fp64 FLOPs (e.g., a V100)
c) see if another framework, e.g., TensorFlow/PyTorch/CuPy perform better?

I suspect there's not a lot we can do here; if I'm guessing right, you have the wrong GPU for 64-bit compute.

**Comment by hawkinsp** [comment]
Also please read: https://jax.readthedocs.io/en/latest/async_dispatch.html

I suspect your benchmark needs a `block_until_ready()` call.

**Comment by nthakor** [comment]
even with fp32 there is a huge difference in performance. But GPU performance of Jax is consistent with cupy and other gpu based libraries.

**Comment by hawkinsp** [comment]
I must admit even looking at a trace of device activity on a V100 it's not obvious to me why the Cusolver version is so slow. It looks like a significant fraction of its time isn't spent on GPU-side work. The V100 is about 4x faster than on your T4, though, and that's likely related to 64-bit compute.

However, note that the CPU timing you have before is wrong because it's missing a `block_until_ready()`. So perhaps GPU isn't that bad in comparison to CPU? On a Google Cloud Platform `n1-standard-64`, I timed the CPU-only version at around 3m50s, somewhere in between the V100 and the T4.
