### ISSUE TITLE
NotImplementedError: Batching rule for 'root' not implemented

### ISSUE THREAD

**Issue by lukasheinrich** [google/jax#3021]
Hi,

we are using the root finding ability of jax in one of our projects and would like to vectorize the evaluation with vmap. However the batching operation for it seems not defined. Where / How would this need to be added?

Thanks.

**Comment by shoyer** [comment]
`lax.custom_root` should supporting batching as of the last few JAX releases (see https://github.com/google/jax/pull/2485). Can you try upgrading to the latest release?

Side note: I'd love to learn about how you're using `root`! I haven't seen many uses of it in the wild yet, since we haven't written the corresponding higher level jax.scipy routines for equation solving yet.

**Comment by hawkinsp** [comment]
It sounds like current releases of Jax resolve this problem. Closing; feel free to reopen if you are still experiencing issues.

**Comment by lukasheinrich** [comment]
hi @hawkinsp , @shoyer yes I updated to the latest jax and it works. The context is differentiable quantum field theory calculations. Hope to share more soon :)
