### ISSUE TITLE
random.logistic returns -inf

### ISSUE THREAD

**Issue by virajmehta** [google/jax#3043]
If I call jax.random.logistic with key array([2308802225, 3876068305], dtype=uint32) and shape=(10000, 12), the sampled array contains -inf. I don't think this behavior is correct or at least it is not expected and causes downstream code that assumes finite floats to crash.

I can work around this, but I think it's worth fixing. Thanks!

**Comment by jakevdp** [comment]
This is a consequence of using a 32-bit implementation of the standard logit generating function: x is drawn from a uniform distribution between 0 and 1, then transformed according to `y = log(x / (1 - x))`. For real numbers there is an infinitessimally small chance of `x=0` which maps to `y=-inf`, in 32-bit arithmetic the chance is approximately 1 in 2^30.

I'll think about how to best address this.

**Comment by jakevdp** [comment]
Wait, it's even worse than that, because ``uniform()`` only randomizes the mantissa: this means the chance is about a 1 in 2^23 of getting -inf; that's confirmed empirically:
```
>>> (uniform(PRNGKey(0), (100000000,)) == 0).sum()
DeviceArray(19, dtype=int32)
```
I think the best approach would be to modify the generating algorithm to use 32-bit unsigned integers rather than 32-bit uniform floats; then the chances of hitting this would be one in 4 billion, rather than 1 in 8 million as it is currently.

**Comment by hawkinsp** [comment]
Could you avoid the problem by drawing from the range `(0, 1)` instead of `[0, 1)` ?

**Comment by jakevdp** [comment]
Yes, that would fix the -inf issue. But it still might be preferable to use an approach that allows the result to have a cardinality greater than 2^23
