### ISSUE TITLE
No 'unbroadcasting' when using custom_jvp

### ISSUE THREAD

**Issue by j-towns** [google/jax#3056]
```python
>>> import jax.numpy as np
>>> from jax import custom_jvp, grad
>>>
>>> a = np.array([1., 1.])
>>>
>>> @custom_jvp
... def f(x):
...   return a * x
...
>>> @f.defjvp
... def f_jvp(primals, tangents):
...   x, = primals
...   dx, = tangents
...   return a * x, a * dx
...
>>> print(grad(lambda x: np.sum(f(x)))(np.array(1.)))
[1. 1.]  # This should be a scalar
```
It looks like this is because the multiplication `a * x` broadcasts `x`, and normally that would induce a `broadcast_in_dim` in the jaxpr for the jvp, but it doesn't. With the custom_jvp we get
```python
>>> from jax import make_jaxpr, linearize
>>> make_jaxpr(linearize(f, 1.)[1])(1.)
{ lambda b ; a.
  let c = mul b a
  in (c,) }
```
If we linearize an instance of `f` without the custom_jvp we get
```python
>>> make_jaxpr(linearize(lambda x: a * x, 1.)[1])(1.)
{ lambda b ; a.
  let c = broadcast_in_dim[ broadcast_dimensions=()
                            shape=(2,) ] a
      d = mul b c
  in (d,) }
```
Not sure if this is fixable or whether we just need to require users to do explicit broadcasting in their custom_jvp definitions?

**Comment by mattjj** [comment]
Unfortunately this is because our AD system assumes broadcasts are explicit, and we've [made sure our JVP rules follow that constraint](https://github.com/google/jax/blob/007cdf2f9eb46f665ae9d39bad5992a4bf994100/jax/interpreters/ad.py#L499-L505). But there's no reason for a user to have to know that.

Now that we have shapes available in jaxprs, we can handle this in transpose rules instead.

**Comment by mattjj** [comment]
#6470 should fix this!
