### ISSUE TITLE
Bug with jax.disable_jit (or lax.cond, or vmap?)

### ISSUE THREAD

**Issue by GeorgOstrovski** [google/jax#3093]
Attempt at minimal reproducing example: 
```python
def fn(t):
  return jax.lax.cond(t > 0, 0, lambda x: 0, 0, lambda x: 1)
fn = jax.vmap(fn)

with jax.disable_jit():
  outputs = fn(jnp.array([1]))
```
fails with 
```
Encountered value: Traced<ShapedArray(bool[])>with<BatchTrace(level=11/0)>
  with val = DeviceArray([ True], dtype=bool)
       batch_dim = 0
```
It does not fail without the `disable_jit()` and it does not fail without the `vmap` (input a scalar in that case).

**Comment by mattjj** [comment]
Thanks for raising this! This is a known problem, though I forget if there's already an issue for it.

The problem is that:
1. when in a `disable_jit` context, the control flow primitives like `cond` [just fall back to a Python implementation](https://github.com/google/jax/blob/7c687b245b34397c13563a714ad9bf0290b419e3/jax/lax/lax_control_flow.py#L530-L534) motivated by better debugging, yet
2. this Python implementation isn't `vmap`-traceable (because in this case `vmap` abstracts the boolean `t > 0` to the Shaped level).

Probably the best option is to run the Python implementation only when `bool(pred)` can be evaluated at trace time (i.e. when that call doesn't raise an abstract value error), and call into the non-Python version when it fails.
