### ISSUE TITLE
Error in backward-mode differentiation of ℝ → ℂ function

### ISSUE THREAD

**Issue by PhilipVinc** [google/jax#3121]
Hi,
First of all I'd like to thank you for the wonderful work you put forward with Jax. 
We recently started using it in [netket](https://github.com/netket/netket), a package for solving quantum-many body problems with neural-networks, and have been very pleasantly surprised by the performance and ease of use, so much that we rewrote most of our code to take advantage of it!

However, when dealing with wavefunctions we have to work a lot with complex functions. It is within this context that I noticed a silent error arises when trying to use reverse-mode over a ℝ → ℂ function (so, `grad` and `jacrev`).

Consider the following case:
```python
import jax
w=(jax.np.array([1.0]), jax.np.array([0.5]))

jax.grad(lambda w: w[0].sum() + 1j* w[1].sum(), holomorphic=True)(w)
(DeviceArray([1.], dtype=float32), DeviceArray([0.], dtype=float32))

 jax.jacrev(lambda w: w[0].sum() + 1j* w[1].sum(), holomorphic=True)(w)
(DeviceArray([1.], dtype=float32), DeviceArray([0.], dtype=float32))
```
- The gradient is wrong, it should be complex-valued. I have the feeling you are probably competing the right gradient but you cast it at the end to the original type, resulting in this error.

As a temporary fix, I figured out I can just promote types to be complex and compute the gradient by saying that the function is holomorphic, and re-scaling the complex part, though it would be nice if this could be fixed.
```python 
wc=(jax.np.array([1.0], dtype=jax.np.complex64), jax.np.array([0.5], dtype=jax.np.complex64))

jax.jacrev(lambda w: w[0].sum() + 1j* w[1].sum(), holomorphic=True)(wc)
(DeviceArray([1.-0.j], dtype=complex64), DeviceArray([0.+1.j], dtype=complex64))
```

Slightly related,  I understand why you ask the user to mark the function to be holomorphic once you hit a complex result, but in this case it's a bit weird: ℝ → ℂ functions are always holomorphic. I don't know if anything can be done about it.

cc @gcarleo

**Comment by gcarleo** [comment]
Yes, thank you, we are really enjoying the clarity of Jax's APIs! It makes working with complex-valued quantum wave functions much easier and requires a lot less boilerplate than with other approaches. 

Something related to what @PhilipVinc was saying (in the same spirit of mixed real complex typing). There is this slight issue with vjp for complex vectors and real functions and vice versa:  
 
```python
import jax
import jax.numpy as jnp


f = jnp.sin

x = jnp.ones(3)
v = jnp.ones(3)

# R->R Works
val, f_jvp = jax.vjp(f, x)

print(f_jvp(v))


# X Real and V complex Works only if casting x to complex
x = jnp.ones(3, dtype=jnp.complex64)
v = jnp.ones(3) + 1.0j * jnp.ones(3)

val, f_jvp = jax.vjp(f, x)
print(f_jvp(v))


# X Complex and V real Works only if casting v to complex
x = jnp.ones(3) + 1.0j * jnp.ones(3)
v = jnp.ones(3, dtype=jnp.complex64)

val, f_jvp = jax.vjp(f, x)
print(f_jvp(v))
```

The second case can be implemented calling two jvp with real x, instead of casting x to complex (most likely that is going to be also more efficient than casting). I was wondering if you have plans to implement these mixed-typing cases directly into the AD engine or if we should handle them separately in our code. 

Thank you!

**Comment by jekbradbury** [comment]
Broadly speaking it's perfectly reasonable to implement the complex AD semantics you need in your own code: everything is pretty easy to construct out of unambiguous R -> R derivatives. JAX [makes particular choices in `grad`](https://jax.readthedocs.io/en/latest/notebooks/autodiff_cookbook.html#Complex-numbers-and-differentiation) that are different from some other libraries: we treat a R -> C or C -> C function as if it were a function onto the reals (i.e., we throw out the complex component). In the special case where f is holomorphic C -> C, that definition lines up with the complex derivative; in other cases, it doesn't.

**Comment by mattjj** [comment]
I haven't paged this issue in yet, but I wonder if the comment on #610 might be useful.

**Comment by jekbradbury** [comment]
Yes, that looks very relevant and perhaps worth making an FAQ!

**Comment by gcarleo** [comment]
Thank you @jekbradbury  and @mattjj for the quick feedback! 

Indeed I agree that there is absolutely no ambiguity in the vjp APIs, and the conventions taken in JAX for complex numbers are clear. 
I was just remarking that it might be quite convenient for users if vjp (and jvp) had a mixed-type usage consistent with matmul. 

For example, a matmul with complex mat and real vector, just works in numpy: 

```python
import jax
import jax.numpy as jnp

# Real matrix
J = jnp.ones((3, 3))

# Complex vector
v = (1.0 + 1.0j) * jnp.ones(3)

# Mixed typing works without casting
out = jnp.matmul(J, v)
```

however an equivalent vjp wouldn't work unless one manually performs a tree flattening and unflattening

```python
# Function of real parameters
x = jnp.ones(3)
f_jvp = jax.vjp(jnp.sin, x)[1]

## Jacobian-vector product doesn't work without casting
# out = f_jvp(v)

## This **would** work if addition and scalar multiplication were overloaded for PyTrees
# out = f_jvp(v.real) + 1.0j * f_jvp(v.imag)

# This works (but it might be non-trivial for some users)
from jax.tree_util import tree_map, tree_flatten, tree_unflatten

res, td = tree_flatten(f_jvp(v.real))
ims, td = tree_flatten(f_jvp(v.imag))

out = tree_unflatten(td, [re + 1.0j * im for re, im in zip(res, ims)])
```

In the example above, casting x to complex might also be an option, however for non-linear functions I suspect that computing a jvp for complex parameters is more than twice as expensive as calling f_jvp on real parameters?

**Comment by mattjj** [comment]
Hmm, well in your example you have a complex vector input, and that works with `jacfwd` / `jacrev` as well because you're clearly modeling a C->C function:

```python
import jax
import jax.numpy as jnp
from jax import jacfwd, jacrev

# Real matrix
J = jnp.ones((3, 3))

# Complex vector
v = (1.0 + 1.0j) * jnp.ones(3)

def f(v):
  return jnp.matmul(J, v)

print(jacrev(f, holomorphic=True)(v))  # notice complex v input
```

```
[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]
```

Calling it at `jnp.ones_like(v)` works the same way, but not `jnp.ones(v.shape)`.

I think the fundamental issue here is JAX can't know that you think of `f` as a `C->C` function unless you pass in a complex input, and therefore can't know to construct an input basis with complex dtype, because Python is polymorphic and we only ascribe an input type to `f` right when we execute it using the inputs you provide.

We could:
1. raise an error if you pass `holomorphic=True` but don't provide a complex dtype input, or
2. automatically cast inputs to complex dtype when `holomorphic=True`.

I think you might be requesting the latter.

WDYT?

**Comment by mattjj** [comment]
I think we should raise errors! #3149 (wip) is an attempt to do that.

**Comment by gcarleo** [comment]
Yes, I guess that raising an error is maybe a better option! I suspect that doing a casting by default to complex when the vector v is complex might incur in a performance penalty (but this should be measured, it's just a hunch). 

In any case, maybe my analogy with matmul was not ideal, but essentially the point I was trying to make is that functionally vjp is essentially this:

```python
def m_vjp(f,x,v):
    jac=jacfwd(f)(x)
    return jnp.matmul(v,jac)
```

right? However this very function, since it calls matmul, already works in the case when x is real and v is complex, whereas this one requires a casting 

```python
def vjp(f,x,v):
    #this works only casting function parameters to same type of v
    #possibly inefficient ?
    f_vjp = jax.vjp(f, x.astype(jnp.complex64))[1]
    return f_vjp(v)
```

I was trying to understand if the behavior of m_jvp could be made default also in jax.vjp

**Comment by mattjj** [comment]
After #3149, the code in the OP raises

```
TypeError: jacrev with holomorphic=True requires inputs with complex dtype, but got float32.
```
