### ISSUE TITLE
Vanilla python function returns different result with jax

### ISSUE THREAD

**Issue by thomas-huet** [google/jax#3134]
I've written some naive implementation of matrix operations to measure the performance impact of jax on non-numpy code and obtained different results when using jax (either using `jit` or `value_and_grad`):

```python
import jax.numpy as np
from jax import jit

def make_mat(m, n):
  a = []
  for i in range(0, m):
    a.append([])
    for j in range(0, n):
      a[i].append(0)
  return a

def mat_mul(a, b):
  m = len(a)
  n = len(b[0])
  c = make_mat(m, n)
  for i in range(0, m):
    for j in range(0, n):
      for k in range(0, len(b)):
        c[i][j] += a[i][k] * b[k][j]
  return c

def trace(m):
  tot = 0
  for i in range(0, len(m)):
    tot += m[i][i]
  return tot

def transpose(m):
  a = make_mat(len(m[0]), len(m))
  for i in range(0, len(m)):
    for j in range(0, len(m[0])):
      a[j][i] = m[i][j]
  return a

def f(v):
  v = [v]
  #print(v)
  m = mat_mul(transpose(v), v)
  #print(m)
  mm = mat_mul(m, m)
  #print(mm)
  return trace(mm)

v = [float(n-5) for n in range(0, 30)]

print(f(v))
print(jit(f)(v))
```

It prints `24552025.0` for the vanilla python version and `24552024.0` for the jit version.

**Comment by hawkinsp** [comment]
I think all you're seeing here is floating-point precision.

If I change your code to use `onp.float32` where `onp` is the classic `numpy` package (no JAX), I get `24552024.0`. Alternatively, since JAX uses 32-bit floats by default, if we enable 64-bit mode in JAX (https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#Double-(64bit)-precision) then JAX spits out `24552025.0`. i.e., you're just seeing the effects of 32-bit precision.

An unrelated note: JAX isn't particularly well optimized for scalar loop nest code (e.g., the `for` loops in your code). You will see better performance if you make use of array-at-a-time operations, (e.g., `jax.numpy.matmul` and jax.numpy.transpose`).
