### ISSUE TITLE
Undefined names: 'vals', '_scatter', and 'rescatter'

### ISSUE THREAD

**Issue by cclauss** [google/jax#317]
[flake8](http://flake8.pycqa.org) testing of https://github.com/google/jax  on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./jax/interpreters/parallel.py:249:38: F821 undefined name 'vals'
      return call_primitive.bind(f, *vals, **params)
                                     ^
./jax/interpreters/parallel.py:372:10: F821 undefined name '_scatter'
  return _scatter(source, target, target_axis, name)
         ^
./jax/interpreters/parallel.py:422:9: F821 undefined name 'rescatter'
    x = rescatter(x, ydim, name)
        ^
3     F821 undefined name 'vals'
3
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by hawkinsp** [comment]
Thanks for the issue report!

The errors this code points to are in an experimental module that isn't quite finished yet. So it's possible it's not in a working state. I appreciate that we would need to fix them before enabling a flake8 travis presubmit.

Assigning to Matt since he's working on finishing up this code and I'm sure once finished this problem will be fixed also.

**Comment by cclauss** [comment]
Final tips...  Put __# noqa__ on any line that you want flake8 to ignore.  There is also __# flake8: noqa__ to ignore a whole file.
