### ISSUE TITLE
float32 vs float64 issues

### ISSUE THREAD

**Issue by benjaminpope** [google/jax#3187]
Dear Jax team,

I don't think you'll be able to debug this straightforwardly - I have a big physical optics simulation package for astronomy, that I have written in Jax in order to be able to differentiate image features with respect to phases in the input wavefront.

In https://github.com/benjaminpope/morphine/blob/master/notebooks/morphine_pharo_xara.ipynb I have implemented a model to generate something called 'kernel phases', which are useful for high resolution imaging - basically, the kernel operator constructed by SVD of a Jacobian of the output Fourier phases with respect to the input. 

The standard way of doing this is analytic - here is an example of it being applied to real data: https://github.com/benjaminpope/morphine/blob/master/notebooks/frantz_test.ipynb 

(The idea is to use autodiff to make it flexible and applicable to all sorts of different cameras and telescopes, which are analytically intractable.)

When I run the Jax code in float32 dtype it gives nearly the same results as the standard method, but when I use the float64 format it gives wildly different and obviously incorrect results: https://github.com/benjaminpope/morphine/blob/master/notebooks/pharo_test.ipynb

Now these packages are large and complex and involve a lot of physics going on there, so I don't know where the issue is! But the key points are making a big Jacobian, finding its SVD, and applying the null space in that SVD to analyze data. It has to go back and forth between float and complex datatypes to do the optics. Are there any steps in here you would ordinarily expect to introduce bugs when you change datatypes?

All the best,

Ben

**Comment by shoyer** [comment]
This project sounds very cool!

My best tip is to try to nail down *exactly* in which step of your complex codebase results go wrong. If you’re using jit, the new Jax.experimental.host_callback module may be helpful in identifying where things go wrong.

Poor results with float64 rather than float32 is definitely the opposite of what we normally find :). A few wild guesses:

- are you ever comparing to zero or another floating point value exactly, e.g., when you’re calculating the nullspace of that SVD? I can imagine rounding happening in float32 but not float64. Generally you want to compare vs some small value to identify “zero” in floating point math (e.g., derived from np.finfo).
- maybe part of your code is inadvertently still running with float32, which causes problems by being out of sync with the main calculation in float64? Some JAX functions may still inadvertently default to float32, e.g., this may be the case for some neural net libraries.
- Unlikely, but maybe you’re hitting some strange XLA or JAX bug? Float64 is definitely less we’ll exercised than float32. If this is the case we definitely want to know so we can fix it.

**Comment by hawkinsp** [comment]
Any news?

**Comment by benjaminpope** [comment]
As far as news goes - quite peculiar. See the SVDs of the transfer matrices in 64 and 32 bit - you can see that the SVD goes to much higher dynamic range in singular values in 64 bit mode, as expected. One thing that makes perfect sense is that the large singular values, which are identical, correspond to identical vectors. But what is strange is that they differ for small singular values even below the cutoff. So there is something in the transfer matrix that is slightly different too.

And we have bad performance on the data analysis problem using the 64 bit kernel operator. I don't know why this might be?

<img width="382" alt="Screen Shot 2020-06-27 at 6 04 52 PM" src="https://user-images.githubusercontent.com/6024213/85917817-db323400-b8a0-11ea-826a-7fbeec78fc8c.png">

**Comment by jakevdp** [comment]
It looks like the small singular values are degenerate, so it would not be surprising if the associated vectors don't exactly match.

As for why the analysis performs better in 32-bit than 64-bit, it may be that the reduced precision acts as a form of regularization on the model that ends up being beneficial to the metric you're using to evaluate performance.

**Comment by RobRomijnders** [comment]
Could this issue be related? 

https://github.com/google/jax/issues/6553

**Comment by hawkinsp** [comment]
I'm going to close this issue because it's not clear that it's a JAX issue! If we can narrow the problem down to a problem that's clearly the fault of JAX, we can take another look...
