### ISSUE TITLE
lax.while_loop fails with zero iterations

### ISSUE THREAD

**Issue by jakevdp** [google/jax#3285]
Ran into a strange bug where a `lax.while_loop` failed unless jit was disabled; this is the distilled version:
```python
import jax.numpy as jnp
import jax

def loop_cumsum(vals):
  def body_fun(i, state):
    return state + vals[i]
  init = vals.dtype.type(0)
  return jax.lax.fori_loop(0, len(vals), body_fun, init)

with jax.disable_jit():
  print(loop_cumsum(jnp.arange(0)))
# 0

loop_cumsum(jnp.arange(0))
# IndexError: index is out of bounds for axis 0 with size 0
```
It appears that the `_initial_style_jaxpr` is indexing into the empty array.

**Comment by mattjj** [comment]
Very nice short example!

I'm not sure, but upon reflection I think this might be working as intended: the loop body in some sense contains a type error, in that when `vals` has type `ShapedArray((0,), int32)` then there is no value for an integer `i` such that `vals[i]` is valid. So even though the loop body will be executed for zero iterations, the program is still invalid.

Analogously:

```c
int main(void) {
  int i = 0;
  while (0) {
    i[0] += 1;
  }
}
```

```
$ gcc foo.c
foo.c: In function ‘main’:
foo.c:4:6: error: subscripted value is neither array nor pointer nor vector
    4 |     i[0] += 1;
      |      ^
```

However, the potential inconsistency here is that in Python it's fine to have any syntactically correct loop body for a loop that executes zero iterations! So we're deviating from Python, though in a kind of reasonable way.

For this specific case, and perhaps an analogous one involving `scan`, we could detect at tracing/staging time that this `fori_loop` will execute zero iterations and thus match Python-ish behavior (essentially by skipping the loop entirely at trace time), but the issue would still be present for `while_loop` in general. Since this came up in a real use case, I think I'll try adding the one-liner (I hope) heuristic to make this work.

**Comment by hawkinsp** [comment]
I hit this here too: https://github.com/google/jax/blob/dd81a8dded3191110a2db884581c1d4dacd364fb/jax/lax_linalg.py#L520

**Comment by gnecula** [comment]
I think that while relaxing the constraints for a loop with no iterations makes more program executable by JAX, it also complicates the mental model by adding special cases to the general requirement that the body of while/for must be JAX traceable, and it is traced by JAX.
