### ISSUE TITLE
Step size as a Pytree

### ISSUE THREAD

**Issue by manuel-delverme** [google/jax#3296]
I'm trying to have per-parameter (group) learning rates with adam, but at the moment the step size has to be the same for every parameter.

What I'm trying to achieve is this:
```scaled_delta = tree_util.tree_multimap(lax.mul, step_sizes, delta)``` 

Is this possible in the official implementation?
By looking at the code it seems the `@optimizer` decorator does not allow pytrees as step_sizes

https://github.com/google/jax/blob/8008aa9ef251f708e9c74b0c7823fad8b78c553f/jax/experimental/optimizers.py#L378

**Comment by mattjj** [comment]
Thanks for the question!

Before diving in, as some overall context, it's best to [think of `jax.experimental.stax` and `jax.experimental.optimizers` as examples](https://github.com/google/jax/blob/master/jax/experimental/README.md#-note-each-mini-library-is-meant-to-be-an-inspiration-but-not-a-prescription) rather than official implementations. In particular they aim to be easy to read and modify for your own purposes.

As for this question, I think we can write a new version of `adam` and `optimizers` like this:

```python
from functools import partial
from jax import grad
import jax.numpy as jnp
from jax.util import unzip2
from jax.tree_util import tree_flatten, tree_unflatten
from jax.experimental.optimizers import OptimizerState

def optimizer(opt_maker):
  def tree_opt_maker(*args, **kwargs):
    init, update, get_params = opt_maker(*args, **kwargs)

    def tree_init(x0_tree):
      x0_flat, tree = tree_flatten(x0_tree)
      initial_states = [init(x0) for x0 in x0_flat]
      states_flat, subtrees = unzip2(map(tree_flatten, initial_states))
      return OptimizerState(states_flat, tree, subtrees)

    def tree_update(i, step_size_tree, grad_tree, opt_state):
      states_flat, tree, subtrees = opt_state
      step_size_flat, _ = tree_flatten(step_size_tree)
      grad_flat, _ = tree_flatten(grad_tree)
      states = map(tree_unflatten, subtrees, states_flat)
      new_states = map(partial(update, i), step_size_flat, grad_flat, states)
      new_states_flat, _ = unzip2(map(tree_flatten, new_states))
      return OptimizerState(new_states_flat, tree, subtrees)

    def tree_get_params(opt_state):
      states_flat, tree, subtrees = opt_state
      states = map(tree_unflatten, subtrees, states_flat)
      params = map(get_params, states)
      return tree_unflatten(tree, params)

    return tree_init, tree_update, tree_get_params
  return tree_opt_maker

@optimizer
def adam(b1=0.9, b2=0.999, eps=1e-8):
  def init(x0):
    m0 = jnp.zeros_like(x0)
    v0 = jnp.zeros_like(x0)
    return x0, m0, v0
  def update(i, step_size, g, state):
    x, m, v = state
    m = (1 - b1) * g + b1 * m
    v = (1 - b2) * jnp.square(g) + b2 * v
    mhat = m / (1 - b1 ** (i + 1))
    vhat = v / (1 - b2 ** (i + 1))
    x = x - step_size * mhat / (jnp.sqrt(vhat) + eps)
    return x, m, v
  def get_params(state):
    x, m, v = state
    return x
  return init, update, get_params
```

Here's example usage:

```python
def loss(lst):
  x, y = lst
  return jnp.dot(x, x) + jnp.dot(y, y)

x0 = [jnp.ones(2), jnp.ones(3)]
step_size = [0.1, 0.05]
num_iters = 100

print(loss(x0))

init, update, get_params = adam()
state = init(x0)
for i in range(100):
  x = get_params(state)
  state = update(i, step_size, grad(loss)(x), state)

x = get_params(state)
print(loss(x))
```

```
5.0
7.045568e-05
```

It might also be that `jax.experimental.optix` can do this out-of-the-box; I'm not sure. That might be factored out of `jax.experirmental` at some point soon, but it's commonly used e.g. with Haiku, so I wouldn't be surprised if it had more features like this!


What do you think?

**Comment by mattjj** [comment]
I think this answer covered the issue, so I'm going to close the issue for now, but please let me know if there's more to figure out here (or open new issues for new questions!).
