### ISSUE TITLE
pass kwargs to net_init functions in jax.experimental.stax

### ISSUE THREAD

**Issue by John-Boik** [google/jax#3301]
I've written some custom code for a GRU unit, and it would be helpful if I could pass keyword arguments to its init_fun. I've modified code in jax.experimental to allow for this, but it would be helpful if passing kwargs was allowed by default.

To keep things simple, let's say I wish to create a neural network with a Dense unit as follows, where I pass kwargs to net_init: 

```
net_init, apply = jax.experimental.serial(
            Dense(10)
            )
shape, params = net_init(rng, (-1,10), mykwarg="test")
```  

This is possible if three changes in jax.experimental are made. The first is to change elementwise as follows:
 
```
def elementwise(fun, **fun_kwargs):
  """Layer that applies a scalar function elementwise on its inputs."""
  init_fun = lambda rng, input_shape, **kwargs: (input_shape, ())  #  **kwargs is added here.
```

The second is to change Dense as follows:
`
def init_fun(rng, input_shape, **kwargs):   # **kwargs is added here.
`

The third change is to serial as follows:

```
def init_fun(rng, input_shape, **kwargs):  # **kwargs added here.
  params = []
  for init_fun in init_funs:
    rng, layer_rng = random.split(rng)
    input_shape, param = init_fun(layer_rng, input_shape, **kwargs)  # **kwargs added here.
```
Other functions in jax.experimental may also need **kwargs added to their init_fun definition.

**Comment by mattjj** [comment]
Hey, @John-Boik , thanks for the suggestion!

I'm split about this. I think we only added `**kwargs` to `apply_fun` to handle optional `rng` arguments. But threading opaque `**kwargs` everywhere is opaque and mysterious, whereas the main goal of stax is to be simple, readable, and explicit. In fact, that's the main goal so as to make it easy to fork and adapt, exactly as you've done, with anything from small changes to large ones! (Relatedly, see [this message on stax minimalism, and how we generally won't merge PRs adding new features](https://github.com/google/jax/blob/master/jax/experimental/README.md#neural-net-building-with-stax).)

For that reason, even though `apply_fun` has `**kwargs` now and this update to the `init_fun` signature would be analogous, I'd rather update things so that _neither_ takes `**kwargs`, and we figure out a more explicit way to pass an optional rng key into the layer constructors and combinators.

What that means for this particular issue, though, is that I'm leaning that we shouldn't make this change to jax.experimental.stax.

Does that make sense? What do you think?

**Comment by John-Boik** [comment]
Thanks @mattjj. Sure, that makes sense. Thanks for explaining. I believe others have suggested a cookbook of adaptations, one of which could be mine. Or, maybe this issues section serves as such.

**Comment by mattjj** [comment]
That's an interesting idea! Indeed I think the [Flax project](https://github.com/google/flax)'s HOWTO guides are a brilliant way to accomplish that sort of goal. I don't think we have any active efforts to make such a cookbook of adaptations in JAX core right now, but I agree it could be very nice.

For organization purposes, I'll close this issue, but since stax is in the title it'll be easy to pull up if/when we start working on that kind of thing.

Thanks again for the idea!
