### ISSUE TITLE
Running Numba and JAX at the same time leads to silently corrupted results from JAX

### ISSUE THREAD

**Issue by shoyer** [google/jax#3454]
Note: this may be an issue with Colab's installations of Numba/JAX rather than a direct issue with JAX.

To reproduce:
https://gist.github.com/shoyer/9bcd131e88d2f572d65ce9fe5040f360

If I run the cell doing the calculation with Numba first, the JAX calculation gives the different (incorrect) result shown.

If I don't run the cell with Numba, then JAX gives the correct result.

**Comment by clemisch** [comment]
Maybe I'm missing something, but could it be that the numba function changes `x` inplace which leads to the changed jax output?

**Comment by mattjj** [comment]
@clemisch that sounds like a pretty good hypothesis! Indeed removing the `x[:] = y` makes the outputs equal.

How about just `x, y = y, x` at the bottom to swap the pointers, rather than `x[:] = y`? Should save a copy for numba too. With that change, I get this:

![image](https://user-images.githubusercontent.com/1458824/84700094-758c9200-af07-11ea-9fd0-d3d1807a6476.png)

**Comment by mattjj** [comment]
Never mind, swapping pointers does not seem to work with numba. Removing the `x[:] = y` is still a good fix for the `n=1` case though :)

**Comment by shoyer** [comment]
OK, good catch!

I also had another bug in my code, doing out of bounds indexing. It turns out both Numba and JAX will happily let you do that without erroring, which they both implement in different ways!

On the plus side we now have a nice little Numba vs JAX (on CPU) microbenchmark. It looks like Numba is about twice as fast as JAX here, both to compile and to run the code:
https://gist.github.com/shoyer/00e79a120968701fc716f6a8584b4ba0
