### ISSUE TITLE
Reason for not having a tanh activation function?

### ISSUE THREAD

**Issue by chisarie** [google/jax#3515]
I can see from the documentation [here](https://jax.readthedocs.io/en/latest/jax.nn.html#activation-functions) that there is no `tanh` activation function in jax. For now I am using the function `jax.lax.tanh`. Is this the right thing to do? Or is there a better alternative?

**Comment by shoyer** [comment]
I would generally recommend using the functions exposed by `jax.numpy` over `jax.lax` (which is is lower level). In this case, that would mean `jax.numpy.tanh`

**Comment by mattjj** [comment]
+1 to what @shoyer said.

We include a function in `jax.nn` if it doesn't already exist elsewhere (and it's neural net related). Since this function is in `jax.numpy`, it makes sense to use that one. (Actually, [`jax.numpy.tanh` is a thin wrapper around `jax.lax.tanh`](https://github.com/google/jax/blob/33c455a1a8c0fce75ac9ec6d094353221a22b938/jax/numpy/lax_numpy.py#L364), the only differences being that `jax.lax.tanh(0)` is an error because of the int dtype of the input, but `jax.numpy.tanh(0)` promotes its input like most NumPy functions do.)

Thanks for the question!

**Comment by chisarie** [comment]
Everything clear, thank you very much for the answer and for this amazing project!
