### ISSUE TITLE
A scan or "tf.while_loop"-like function to reduce jit times for recurrent computations.

### ISSUE THREAD

**Issue by sussillo** [google/jax#352]
I'm writing some RNN code in JAX, currently using for loops.  The code executes really quickly, but I notice the jit compile times can be of the order of minutes.

**Comment by sussillo** [comment]
Just discovered jax/jax/lax.py:fori_loop, so I'll take a look there.

 fori_loop(lower, upper, body_fun, init_val):
  """Loop from `lower` to `upper` by reduction to `while_loop`.

**Comment by hawkinsp** [comment]
Another workaround you might try is to `jit` smaller pieces. For example, the body of the recurrent loop would be an obvious choice.

**Comment by mattjj** [comment]
Thanks for opening an issue for this!

Unfortunately the existing looping constructs `lax.fori_loop` and `lax._while_loop` (we should remove the underscore from the name, which isn't needed anymore, and document both) aren't differentiable, and can't be because they might perform in-place updates on loop-carried variables.

We're working on differentiable primitives `lax.map` and `lax.scan`, and I think the latter is what you will need. We might have a prototype in a week if all goes well, but for now you either have to suffer long compile times or lose differentiability.

**Comment by hawkinsp** [comment]
PR #473 added a first draft of `lax.scan`, although it isn't differentiable or batchable yet.

**Comment by hawkinsp** [comment]
I think we can declare that PR #704 fixed this. We can open new issues for any enhancements.
