### ISSUE TITLE
Performance issue with sparse dot product using jit/GPU

### ISSUE THREAD

**Issue by romanodev** [google/jax#3717]
I am trying to compute the dot product between a sparse matrix and a vector.

The sparse matrix is represented by its row indexes, column indexes, and associated data (COO format). While everything performs as expected when using jit/CPU, computational times become unreasonable when using GPUs. Here is the gist:

https://gist.github.com/romanodev/c2c2fbfc1e788d3fd5eeeb44803b6761

This is my first approach to JAX, so I wouldn't be surprised if there was a working solution already.

**Comment by jekbradbury** [comment]
Tight loops implemented using `lax.fori_loop`, `lax.while_loop`, or `lax.scan` tend to be very inefficient on GPU, since the best the compiler can currently do is to launch one CUDA kernel per loop iteration. Since your loop is performing a single scalar update per step, but CUDA kernels have about 5 microseconds of per-launch overhead, that overhead dominates useful compute.

Luckily, in your case, the loop can be implemented with NumPy advanced indexing instead, resulting in a single compiled CUDA kernel and much faster timing:

```python
@jax.jit
def dot_product2(row,col,data,b):

    updates = data * b[col]
    return jnp.zeros_like(b).at[row].add(updates)
```
```
>>> %timeit dot_product2(rows,cols,data,b).block_until_ready()
10000 loops, best of 3: 130 µs per loop
```

**Comment by romanodev** [comment]
@jekbradbury, fantastic. Thanks!
