### ISSUE TITLE
"Batching rule for 'primal_fun_lin' not implemented" error when using `jacfwd`

### ISSUE THREAD

**Issue by DylanMuir** [google/jax#3727]
I want to compare performance between forward- and backwards-mode autodiff, comparing `jacfwd` and `jacrev`. `jacrev` and `grad` both work as expected on my scalar function; however `jacfwd` raises the following error:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/Users/Shared/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/batching.py in get_primitive_batcher(p)
    213   try:
--> 214     return primitive_batchers[p]
    215   except KeyError as err:

KeyError: primal_fun_lin

...

Users/Shared/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/batching.py in process_primitive(self, primitive, tracers, params)
    131     else:
    132       # TODO(mattjj,phawkins): if no rule implemented, could vmap-via-map here
--> 133       batched_primitive = get_primitive_batcher(primitive)
    134       val_out, dim_out = batched_primitive(vals_in, dims_in, **params)
    135       if primitive.multiple_results:

/Users/Shared/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/batching.py in get_primitive_batcher(p)
    215   except KeyError as err:
    216     msg = "Batching rule for '{}' not implemented"
--> 217     raise NotImplementedError(msg.format(p)) from err
    218 
    219 def defvectorized(prim):

NotImplementedError: Batching rule for 'primal_fun_lin' not implemented
```

How should I go about determining what operation is causing the issue here, and is there anyway I can provide a "batching rule" for the operation?

Thanks for any advice and suggestions!

**Comment by jekbradbury** [comment]
I believe this is mostly a misleading error. Your function appears to contain a `custom_vjp`, and IIRC it's currently not possible to perform forward-mode AD (e.g. `jvp` or `jacfwd`) on functions that contain `custom_vjp`s (as opposed to reverse-mode AD using `grad` or `jacrev`). But if that's the problem you should have seen an error that says so rather than an error that talks about batching rules.

CC @mattjj for fact-check on `custom_vjp` and latest thoughts about supporting forward-mode AD of it.

**Comment by shoyer** [comment]
In theory, you can do forward-mode AD by doing reverse mode twice -- VJPs are linear functions, so applying another VJP just transposes it, which gives you a JVP:
https://j-towns.github.io/2017/06/12/A-new-trick.html
https://github.com/HIPS/autograd/pull/175

This might be a viable way to define forward-mode AD for situations where `custom_vjp` is used, though I would be loathe to support it unless we were _sure_ that JAX/XLA can compute it without extra function evaluations/memory. Based on the discussion in https://github.com/HIPS/autograd/pull/175 I suspect this is almost certainly the case under `jit`, though certainly JAX and XLA will do quite a bit more work to get there.

In most cases, of course, it is probably a better idea to write JVPs, though for linear functions this currently requires writing a JAX primitive because `custom_jvp` doesn't give you a way to define transposes.

**Comment by DylanMuir** [comment]
Hi @jekbradbury and @shoyer,

First up I want to say how impressively responsive you all are to issues and questions — I hesitate to post issues on open-source packages, since I know how little time everyone has to work on these things! But when it comes to `jax`, someone always jumps in really quickly with useful feedback. It's awesome, and I appreciate it!

I'm in fact using `jax.custom_gradient`, which I now see has been deprecated. I'm defining it for a very simple transfer function (Heaviside in the forward pass; ReLU in the backward pass), so I'll attempt to solve the problem by defining a `custom_jvp` and/or `custom_vjp`. Or even a primitive, if necessary.

Thanks again for your suggestions, and I'll report back.

```python
@custom_gradient
def step_pwl(x: FloatVector) -> (FloatVector, Callable[[FloatVector], FloatVector]):
    """
    Heaviside step function with piece-wise linear derivative to use as spike-generation surrogate

    :param FloatVector x: Input value

    :return (FloatVector, Callable[[FloatVector], FloatVector]): output value and gradient function
    """
    s = np.clip(np.floor(x + 1.0), 0.0)
    return s, lambda g: (g * (x > -0.5),)
```

**Comment by jekbradbury** [comment]
Aha! Yes, in fact the inability to support `vmap` (used in `jacfwd`) was a major reason why we had to deprecate the old `custom_transforms` interface. In the case of a function like `step_pwl`, you are probably best off using `custom_jvp` since the function is scalar/elementwise; that way both forward- and reverse-mode AD will work fine.

**Comment by DylanMuir** [comment]
Implemented, and it functions. Thanks again!

Unfortunately, `jacfwd` is much much slower for the BPTT use case that I am benchmarking, compared with `grad`. I'm a little surprised, since the problem becomes column-deep rather than row-wide --- I had assumed that forward-mode would then be more efficient for BPTT.

```python
@jax.custom_jvp
def step_pwl(x: float) -> float:
    """
    Heaviside step function with piece-wise linear derivative to use as spike-generation surrogate

    :param float x: Input value

    :return (float, Callable[[float], float]): output value and gradient function
    """
    return np.clip(np.floor(x + 1.0), 0.0)
        
@step_pwl.defjvp
def step_pwl_jvp(primals: Tuple[float], tangents: Tuple[float]) -> Tuple[float, float]:
    x, = primals
    x_dot, = tangents
    return step_pwl(x), x_dot * (x > -0.5)
```

**Comment by hawkinsp** [comment]
It sounds like the original issue here is resolved? Perhaps open a new issue for the performance problem, if you would like?
