### ISSUE TITLE
result of jnp.ones_like in jitted function should not be traced

### ISSUE THREAD

**Issue by martinjrobins** [google/jax#3731]
The output value of `jax.numpy.ones`, with a shape dependent on the shape of the input argument, is a constant in a jitted function. However, the output of `jax.numpy.ones_like` is traced. This behavior is unnecessary and `ones_like` should return a constant array as well.

To reproduce:

```python
import jax
import jax.numpy as jnp

@jax.jit
def f_ones(arg):
    res = jnp.ones(arg.shape, arg.dtype)
    print(res)
    return res

@jax.jit
def f_ones_like(arg):
    res = jnp.ones_like(arg)
    print(res)
    return res

f_ones(1.)
# 1.0 printed
f_ones(jnp.array([1, 2, 3], dtype=jnp.float32))
# [1. 1. 1.] printed

f_ones_like(1.)
# Traced<ShapedArray(float32[]):JaxprTrace(level=-1/1)> printed
f_ones_like(jnp.array([1, 2, 3], dtype=jnp.float32)) 
# Traced<ShapedArray(float32[3]):JaxprTrace(level=-1/1)> printed
```

**Comment by hawkinsp** [comment]
This behavior of `ones_like` is intentional, and exists to avoid materializing large constants inside `jit` blocks. If `ones_like` did not lift into the trace then we would end up with a potentially large constant array of `1`s in the executable.

It is somewhat awkward that `jnp.ones` and `jnp.ones_like` don't act consistently inside a `jit` block. However, we are shortly to land a new "omnistaging" branch (https://github.com/google/jax/pull/3370), which would lift both `jnp.ones` and `jnp.ones_like` into the trace if used within a `jit` block. 

Hope that helps! Does it answer your question? If it does not, can you say a bit more about why it violates your expectations?

**Comment by martinjrobins** [comment]
Thanks for the info, this makes a lot of sense. Perhaps this could be mentioned explicitly in your documentation on control flow and JIT? (https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#python-control-flow-+-JIT). This section gives a few examples of normal python control flow being ok as long as they are based on static args or array shapes, and I would ordinarily expect this to extend to `jnp.ones` and `jnp.ones_like` as well.

Can you advise on the recommended way to explicitly form (smallish) array constants in a jitted function, or is it the recommendation to never do this? My specific example is that I have an function (an ode solver) that takes in a static argument which is a n x n matrix, and then augments this with an identity matrix (using `jnp.identity`). A little later in the algorithm I then have some indexing operations and some standard python control flow based on the number and location of zeros along the diagonal of the augmented matrix. At the moment this all works fine as my augmented matrix is a constant, but if `jnp.identity` is going to be lifted into the trace in the future then the control flow and indexing will break.

**Comment by shoyer** [comment]
> Can you advise on the recommended way to explicitly form (smallish) array constants in a jitted function, or is it the recommendation to never do this?

I would generally just use NumPy to create such constants, though there might be some other tricks that help in your situation...

**Comment by martinjrobins** [comment]
Perfect, thanks both. Closing this as answered.
