### ISSUE TITLE
Implementing custom transformations?

### ISSUE THREAD

**Issue by thisiscam** [google/jax#3749]
I really like the design of JAX, that at its core is a program transformation system.  

So I was wondering how easy would it be to implement some of my custom program transformations.

For example, I wanted to implement the following transformation:
```
def f(x):
  return x + np.exp(x)

def expected_transformed_f(x, x_prime):
  return x + np.exp(x_prime) + np.exp(x_prime) * (x - x_prime)

x, x_prime  = ... random ...
assert custom_transform(f)(x, x_prime) == expected_transformed_f(x, x_prime)
```

In particular, what the transformation is doing is that it identifies the subexpression `np.exp(x)`, and rewrite it with its first order Taylor expansion around `x_prime`. Then it adds the `x_prime` as a new formal parameter to the transformed function.

1. I thought the transformation should be achievable with Jax; if so, what would be a good place for me to look at for a starter?

2. I have already peeked into Jax's core a little bit, and was wondering what's the relationship between linear_util.transform and Trace/Tracer? My understanding is that the former is just a utility wrapper, while the later is doing the actual lifting of the program transformation (while doing an abstract interpretation). 

3. Is there some documentation of Trace/Tracer? In particular, I got confused of what `pure`, `lift` etc does...

**Comment by hawkinsp** [comment]
This seems like it would do better as a Github discussion (https://github.com/google/jax/discussions), rather than an issue. There's no action for us to take here. Closing; feel free to reopen in the discussions section.

To answer your concrete question, have you seen:
https://jax.readthedocs.io/en/latest/notebooks/Writing_custom_interpreters_in_Jax.html
and
https://jax.readthedocs.io/en/latest/notebooks/How_JAX_primitives_work.html

?
