### ISSUE TITLE
Are there a tutorial or interesting example of how to use Jax with pytorch?

### ISSUE THREAD

**Issue by brando90** [google/jax#3818]
mainly as a pytorch user, I'd like to be able to use this promising project without having to learn all my stuff from scratch. Is this possible? Are there examples with jax + pytorch?

**Comment by mattjj** [comment]
It's too bad @apaszke is away this week, since he'd be the perfect person to offer some ideas!

I don't think there are any examples or well-paved paths yet. At the low level, it's possible to do zero-copy handoff between the two libraries using DLPack, as in [these tests](https://github.com/google/jax/blob/master/tests/array_interoperability_test.py). @zdevito recently started [a discussion](https://github.com/google/jax/discussions/3699) on how to make that more efficient, and I think he and @hawkinsp are investigating some options there. At the higher level, like end-to-end neural net examples or something, I'm not aware of any work.

So I think the overall state is that we need more brave explorers to start finding and paving paths for JAX + PyTorch interoperation. We're keen to support such explorations!

**Comment by brando90** [comment]
Sounds interesting!

I am curious, what would be the advantages for pytorch users to use Jax? From reading the description:

> With its updated version of Autograd, JAX can automatically differentiate native Python and NumPy functions.

and the examples:

```
grad_tanh = grad(tanh)  # Obtain its gradient function
print(grad_tanh(1.0))   # Evaluate it at x = 1.0
# prints 0.4199743
```

so it seems it makes things differentiable in an optimized way.

I am wondering what happens if we feed into Jax python code that isn't just numpy. e.g. it has pytorch calls or even if it calls external binaries/code in other places. I'm curious to know how and what would happen in those cases.

**Comment by brando90** [comment]
@mattjj 

> So I think the overall state is that we need more brave explorers to start finding and paving paths for JAX + PyTorch interoperation. We're keen to support such explorations!

how would those explorations look like?

**Comment by mattjj** [comment]
> I am curious, what would be the advantages for pytorch users to use Jax?

Well, the README is all about what JAX can do, so that's a good place to start!

> I am wondering what happens if we feed into Jax python code that isn't just numpy. e.g. it has pytorch calls or even if it calls external binaries/code in other places.

That's easier to answer: you'll just get a loud error.

> how would those explorations look like?

Well, that's up to you! I just mean that folks who need some kinds of interop between JAX and other systems will start to explore those paths, and we're here to support them as they arise.


I think we've covered the original question about as well as we can, so I'm going to close this issue. Don't hesitate to open more issues with specific questions as they arise!
