### ISSUE TITLE
Differentiation through lax.scan fails when scan is inside custom JVP

### ISSUE THREAD

**Issue by dpfau** [google/jax#3819]
This is an issue that probably hasn't come up before because not too many people combine custom JVPs, lax.scan and second derivatives. I have a custom JVP (for the determinant) that has a lax.scan inside it. When I take the second derivative of the determinant, and therefore the first derivative of the lax.scan call, I get an error due to the `consts_lin` list to `scan_transpose` having things in the wrong order - apparently it should be some number of Falses followed by all Trues, but I have a True, then False, then all Trues. I suspect this is due to some sneaky interaction between scan_transpose and the custom JVP.

To reproduce the error, roll back the fork in github.com/dpfau/jax to [this](https://github.com/dpfau/jax/commit/deb39aad24bc8e7e8cfcad9dd0319601f06e960e) commit, then run linalg_test.py, specifically the test of second derivatives of the determinant with grad_type='safe'. That should lead to test failures with an error in scan_transpose.

**Comment by jekbradbury** [comment]
WIP debugging notes:

In the scan body of `_cofactor_triangular_solve`, every indexing operation invokes `_index_to_gather`, which inits `gather_indices` to `np.zeros((0,), dtype=index_dtype)` and then concats an integer to it (`gather_indices = concatenate((gather_indices, i), -1)`). Because the argument to that concat is a NumPy array, it gets baked into the scanned jaxpr as a somewhat degenerate literal const (1-D, but with a shape of (0,)). There are five indexing operations in the body, so there are five of these literal consts alongside four values captured from the scope outside the scan. The literals have no tangent, and the scan's input is also a literal (although the carry init is tied in and thus "captured"), so by the time we bind the scan to the jvp trace we have `nonzeros=[False, True, False, True, False, True, False, True, False, True, False]` (as well as `linear=[False]*11`, `num_consts=9`, and `num_carry=1`). Whew.

This stays the same through fixpoint, and then we prune the zeros out for binding the jvp scan, so `len(consts_dot)=4`, `len(init_dot)=1`, `len(xs_dot)=0`. The args for the scanned jvp body jaxpr come out of `ad.jvp_jaxpr` in the order `consts, init, xs, consts_dot, init_dot, xs_dot`, so `ad.rearrange_binders` is called to reorder them into `consts, consts_dot, init, init_dot, xs, xs_dot`. Then we set linear=True for every dotted value, giving `jaxpr_jvp_linear=[False]*9 + [True]*4 + [False] + [True] + [False] + []`.

partial_eval: scan 1 (non-staged part) goes to 26 arguments...

I don't understand why consts_lin should be falses followed by trues, but xs_lin should be trues followed by falses...

**Comment by jekbradbury** [comment]
It looks like the error in transpose of scan was trying to tell us something, and we weren't doing a great job of listening; #3917 aims to improve that.

The thing it wanted to tell us was "your custom JVP is nonlinear!" and it looks like the way to fix that is to switch
```python
def _body(x, i):
    m = n-i-1
    partial = (u[m] * dd[..., i]) @ x
    residual = b[m] * prodrev[i] - partial
    return x.at[m].set(residual), None
```
to
```
def _body(x, i):
    m = n-i-1
    partial = (u[m] * dd[..., i]) @ x
    residual = b[m] * prodrev[i] - partial
    return x.at[m].add(residual), None
```
as `scatter_add` is transposable while `scatter` is not (and you're scattering into zeros at disjoint locations, so `add` should behave identically here).

**Comment by dpfau** [comment]
Ah - that is indeed obscure. Thanks!
