### ISSUE TITLE
cpu warning suppresses logging

### ISSUE THREAD

**Issue by niklasschmitz** [google/jax#3839]
Hi,

I'm using the python logging module and discovered some interaction with the cpu fallback warning, if I define array constants before setting up the logger (I want the logger to depend on further args at runtime, while the constants might be e.g. in an imported module)

Here's a small `repro.py`:
```python
import jax.numpy as jnp
import logging

x = jnp.array([1,2,3])
print(x)

logging.basicConfig(level=10)

logging.info("this is some info log")  # does not show up
logging.warning("this is some warning") # shows up
```
leads to 
```
$ python repro.py
/site-packages/jax/lib/xla_bridge.py:130: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')
[1 2 3]
WARNING:root:this is some warning
```

But if I switch the order of `logging.basicConfig` and the definition of `x`, both logs get printed to console  as expected (at loglevel 10).

Is this expected?

**Comment by skye** [comment]
According to the [basicConfig docs](https://docs.python.org/3/library/logging.html#logging.basicConfig):
> This function does nothing if the root logger already has handlers configured, unless the keyword argument force is set to True.

I verified that adding `force=True` to your example causes the info log to appear.

I think what's happening is that JAX initializes its runtime the first time is a value is created, and this runtime initialization has some debug logging, which must be triggering a `basicConfig` call (also from the docs: "The functions debug(), info(), warning(), error() and critical() will call basicConfig() automatically if no handlers are defined for the root logger"). I'm not sure of the details because JAX uses [abseil logging](https://abseil.io/docs/python/guides/logging), but it seems plausible this would interact with the standard `logging` module.

Does this answer your question?

**Comment by niklasschmitz** [comment]
Thank you for the detailed reply!
Adding `force=True` indeed solves it for me (together with upgrading to python 3.8 for the keyword).
