### ISSUE TITLE
cudaGetErrorString symbol not found

### ISSUE THREAD

**Issue by BoyuanJackChen** [google/jax#3951]
Just trying to create an rng with 
```
rng, key = jax.random.split(rng)
```

The error is unprecedented. I recently killed all python procedures in nvidia-smi, and reinstalled jaxlib with GPU. I have confirmed that 
```
from jax.lib import xla_bridge
print(xla_bridge.get_backend().platform)
```
Does return "gpu". Nonetheless it doesn't work here. Is there a way to fix?

**Comment by hawkinsp** [comment]
Can you try setting the environment variable `TF_CPP_MIN_LOG_LEVEL=0` and share what gets printed when you try to run a JAX computation?

I'm wondering if this is because of an issue such as either a CUDA version mismatch or an inability to find CUDA libraries. What version of CUDA do you have installed and what's the path to the jaxlib package you are using?

**Comment by BoyuanJackChen** [comment]
I reinstalled jaxlib by building. The problem is fixed!
