### ISSUE TITLE
Do JAX jit'd Python loops run faster than jit'd LAX loop constructs?

### ISSUE THREAD

**Issue by sussillo** [google/jax#402]
Please see the GIST [Minimal repro](https://gist.github.com/sussillo/76e191ba07bf2e75a4d4945f749549fe) where I tried to implement a recurrent computation (an echostate network) both in JAX and LAX. Using the lax.fori_loop resulted in a roughly 3x slow-down over jax jit'd naive python for loop.

```
JAX speed
Params seed 100001
JAX run 0.0160 sec

LAX speed
LAX run 0.0418 sec

```
This is not blocking me, but I was surprised by it and I cannot find anything I did wrong, though I may have misused the APIs in some way.  JAX versions are listed as comment in the gist.

**Comment by mattjj** [comment]
Thanks for bringing up this issue! Hope you don't mind that I tweaked the title to be a bit more explicit.

My current best guess is this might be a potential performance improvement for XLA to make. Some thoughts below.

When you use a regular Python loop construct under JAX's `@jit`, JAX (like Autograd) doesn't even see the Python loop and instead just traces out the unrolled computation; as a consequence, the program that gets staged out to XLA is also unrolled. When you instead use a `lax.while_loop` (or `lax.fori_loop`), the JAX tracer sees that loop as a primitive, and stages out a [loop construct in the XLA program](https://www.tensorflow.org/xla/operation_semantics#while).

In the latter case, XLA gets strictly more information: it sees that there's a loop construct, and it has the option to unroll it when it's statically unrollable. (TODO for us: check that JAX is lowering the loop in a way that keeps static-unrollability transparent for XLA, since [we do lift constants into the loop carry tuple](https://github.com/google/jax/blob/27bedc2a15084013da6b6f18cfc9eaeab8d5ccec/jax/lax.py#L2841).) So it should be able to generate code that is at least as good.

From XLA's perspective, there are the usual tradeoffs with unrolling here: unrolling a loop could increase the code size (which might increase execution time if the code has to be loaded onto the device for each kernel launch), but enables some more optimizations and involves fewer branches. It may be that "branches" are expensive for the GPU backend because the loop condition might need to be pulled back to the host and checked there on each iteration, meaning more synchronizations than would be necessary in the unrolled case. Still, it seems that in principle XLA could do some unrolling or partial unrolling to mitigate that effect in cases like this one.

Separate from questions of execution time, one of the main reasons to use loop constructs now is to reduce compile times: unrolling big loops can mean staging out a large program to XLA, and since XLA does a lot of optimizations, that can mean a lot of redundant work.

So as a general rule of thumb, we can think of using loop constructs like `lax.while_loop` and `lax.fori_loop` as tools to reduce compile times, often by a huge amount, but that could sometimes result in reduced execution performance. In principle those reductions in execution performance could be minimal, but right now there are probably cases where XLA loops aren't nearly as fast to execute as the unrolled code.

**Comment by mattjj** [comment]
@hawkinsp added another hypothesis to the list of things-for-us-to-investigate: it could be that the loop is causing XLA to choose bad memory layouts.

**Comment by jonasrauber** [comment]
Just to clarify: using a lax loop construct and jitting the whole loop should _always_ be faster than using a python loop and only jitting the loop body (if there is a sufficient number of iterations and ignoring the loop body)?!

**Comment by hawkinsp** [comment]
It looks like for some reason XLA's while->for loop optimization is not firing, and this means that we spend a significant fraction of time on each loop iteration synchronizing the loop counter (?) from the GPU back to the host. I'm following up with the XLA folks.

**Comment by mattjj** [comment]
> Just to clarify: using a lax loop construct and jitting the whole loop should _always_ be faster than using a python loop and only jitting the loop body (if there is a sufficient number of iterations and ignoring the loop body)?!

I didn't mean to say that; I meant to compare a Python loop under `@jit` (which would be fully staged into the XLA computation in an unrolled form) with a primitive loop construct. I believe those are the cases in the OP. Neither of those is the second scenario you mentioned, where we're executing FLOPs in a loop in Python (with or without a jitted body).

Providing a rolled loop is giving more information to the compiler, and so under the Sufficiently Smart Compiler hypothesis that should always be better. But manual loop unrolling can be helpful when you know better than the compiler's heuristics (e.g. based on the distribution of workloads you expect). I believe that's [true even of modern C compilers](https://ridiculousfish.com/blog/posts/old-age-and-treachery.html).

**Comment by jonasrauber** [comment]
@mattjj sorry, my comment was rather a related question when I have a while loop that can‘t be unrolled (should not have put it here): is it faster to use a lax while_loop construct and jitting everything vs. sticking to unjitted python while loop with jitted loop body? I would assume so, but maybe lax while loop has still some downsides?

**Comment by mattjj** [comment]
@jonasrauber No problem!

Hmm I'd expect the `lax.while_loop` and `lax.fori_loop` constructs to be faster. The main downside is that they're not reverse-mode differentiable (though they could be made forward-mode differentiable; it's the partial-eval step that is hard for reverse mode).

**Comment by hawkinsp** [comment]
This is now fixed, but to get the fix, you either need to rebuild jaxlib from source or to wait until we push new binary wheels to PyPI (probably later this week).
