### ISSUE TITLE
statically determine VJP

### ISSUE THREAD

**Issue by trevorcai** [google/jax#4311]
I have a use case where I'd like a function transformation that looks roughly like:
```
f_fwd, f_bwd = jax.shaped_vjp(f, *example_primals)
f_fwd :: primals_in -> (primals_out, activations)
f_bwd :: (activations, cotangents_in) -> cotangents_out
```
Where I'm happy raising to ShapedVal for the primals. I'd like to do this statically so I don't end up recompiling `f_fwd` and `f_bwd`.
It seems like the autodiff machinery could reasonably expose this - after all, this is what grad-of-jit sort of does already - but I'm not sure how to reach in and expose this.

Notes from follow-up offline:
I want `f_fwd` and `f_bwd` to be parts of different XLA computations, i.e. in different `jax.pmap` scopes, and to be able to manipulate the activations output of `f_fwd` (e.g. by pulling it onto host or moving it between devices).
There's no need to have a sensible internal structure; I'm happy to just treat it as an opaque pytree of DeviceArrays.

**Comment by mattjj** [comment]
This might take some iteration to get exactly right, so bear with me.

To some extent this already works just using `jax.vjp` (thanks to @NeilGirdhar and #3667), in that the callable returned by `jax.vjp` is a pytree (i.e. a container) of its activations/residuals:

```python
import jax
from jax.tree_util import tree_flatten
import jax.numpy as jnp

def f(x):
  y = jnp.sin(x)
  z = jnp.sin(y)
  return z

x = jnp.array([1., 2., 3.])
y, f_vjp = jax.vjp(f, x)

leaves, _ = tree_flatten(f_vjp)
print(leaves)
# [DeviceArray([ 0.5403023 , -0.41614684, -0.9899925 ], dtype=float32), DeviceArray([0.66636676, 0.6143003 , 0.9900591 ], dtype=float32)]
```

(Note that with a scalar argument, no leaves come out because of how jaxprs inline scalars as literals. We could iterate on that if it's undesirable but I'm going to assume scalars don't matter for the moment.)

Moreover, we don't have to worry about recompilation if we just put a `jax.jit` on `f`:

```python
import jax
from jax.tree_util import tree_flatten
import jax.numpy as jnp

@jax.jit
def f(x):
  print('re-tracing / re-compiling f')
  y = jnp.sin(x)
  z = jnp.sin(y)
  return z

x = jnp.array([1., 2., 3.])
y, f_vjp = jax.vjp(f, x)  # prints

y, f_vjp = jax.vjp(f, x)  # no print
```

We could restructure that to put even more under the `jit`, again leveraging the fact that `f_vjp` is a pytree:

```python
import jax
from jax.tree_util import tree_flatten
import jax.numpy as jnp

def f(x):
  y = jnp.sin(x)
  z = jnp.sin(y)
  return z

@jax.jit
def f_fwd(x):
  return jax.vjp(f, x)

x = jnp.array([1., 2., 3.])
y, f_vjp = f_fwd(x)
```

This is close to your example, but without needing `jax.shaped_vjp` or `example_primals` at all. To bring it even closer:

```python
import jax
from jax.tree_util import tree_flatten, tree_unflatten, Partial
import jax.numpy as jnp

def f(x):
  y = jnp.sin(x)
  z = jnp.sin(y)
  return z

@jax.jit
def f_fwd(x):
  y, f_vjp = jax.vjp(f, x)
  res, f_vjp_tree = tree_flatten(f_vjp)
  def f_bwd(res, cotangents):
    f_vjp = tree_unflatten(f_vjp_tree, res)
    return f_vjp(cotangents)
  return y, res, Partial(f_bwd)

x = jnp.array([1., 2., 3.])
y, res, f_bwd = f_fwd(x)
print(res)
# [DeviceArray([ 0.5403023 , -0.41614684, -0.9899925 ], dtype=float32), DeviceArray([0.66636676, 0.6143003 , 0.       9900591 ], dtype=float32)]

y_bar = y  # reuse y as cotangents
x_bar = f_bwd(res, y_bar)
print(x_bar)
print(jax.vjp(f, x)[1](y))
# (DeviceArray([ 0.26845413, -0.20171776, -0.13786028], dtype=float32),)
# (DeviceArray([ 0.26845413, -0.20171776, -0.13786028], dtype=float32),)
```

If you really want the `jax.shaped_vjp` step with `example_primals`, we could make that work but it won't save anything (i.e. it won't save recompiles), and I think it'd require some more boilerplate using internal APIs. The above version uses only public APIs.

WDYT?

**Comment by trevorcai** [comment]
Nice, this makes a lot of sense! In my case the `jax.shaped_vjp` step makes life a lot easier for me, but it seems quite straightforward now that you've shown the tree_flatten/tree_unflatten trick with `f_vjp`:

```
# Top-level JIT to avoid useless FLOPs when finding vjp tree structure.
@functools.partial(jax.jit, static_argnums=0)
def shaped_vjp(f, x):
  f_vjp_tree = jax.tree_structure(jax.vjp(f, x)[1])

  def f_fwd(x):
    print('tracing fwd')
    y, f_vjp = jax.vjp(f, x)
    return y, jax.tree_leaves(f_vjp)

  def f_bwd(res, cotangents):
    print('tracing bwd')
    f_vjp = jax.tree_unflatten(f_vjp_tree, res)
    return f_vjp(cotangents)

  return jax.tree_util.Partial(f_fwd), jax.tree_util.Partial(f_bwd)
```

**Comment by trevorcai** [comment]
Some quick tests seem to say that this is doing something reasonable, so I'm happy to move forward with this as a library function in my codebase (no upstream required). Feel free to close the issue!

**Comment by mattjj** [comment]
Nice! Glad this worked out.
