### ISSUE TITLE
Unclear shape mismatch error from using jax.mask

### ISSUE THREAD

**Issue by phinate** [google/jax#4420]
First, I know that documentation is incoming & `mask` is unfinished, but the use cases I've seen from twitter made me want to explore :)

So I'm trying to `vmap` a neural network over a set of arrays all with a fixed length of 4, but with the *number* of arrays varying. The plan is then to `vmap` again over batches containing lists of varying length, which seems to be the main use of `mask`.

Here's my attempt at reverse-engineering the tests for `mask` in this context:

```python
import jax
import jax.numpy as jnp
from jax.experimental import stax
from jax.random import PRNGKey

from functools import partial


init_random_params, predict = stax.serial(
    stax.Dense(10),
    stax.Relu,
)

data = jnp.asarray([[1,2,3,4],[5,6,7,8]])

n = len(data) # dim to mask over

_, network = init_random_params(jax.random.PRNGKey(2), (-1, 4))

nn = jax.vmap(predict,(None,0)) # vmap over input

msk = partial(jax.mask,
              in_shapes=[[('_','_'),()],'(n,4)'], # [weights, input] 
              out_shape='(n,10)')

```
Testing this function results in the following "shape mismatch", but I'm unclear on exactly *which* shapes are mismatched, as the error dives into `jax` internals:
```pytb
msk(nn)([network,data], dict(n=n))
> AssertionError                            Traceback (most recent call last)
<ipython-input-102-b28743375cd5> in <module>
     24               out_shape='(n,10)')
     25 
---> 26 msk(nn)([network,data], dict(n=n))

~/miniconda3/lib/python3.8/site-packages/jax/api.py in wrapped_fun(args, logical_env)
   1585       raise TypeError(f"Tree mismatch: Input {in_tree} and shape spec {in_shapes_tree}.")
   1586     logical_env = {unique_ids[name] : val for name, val in logical_env.items()}
-> 1587     in_shapes = map(masking.finalize_spec, in_specs, map(np.shape, args_flat))
   1588     padded_env = masking.bind_shapes(in_shapes, [x.shape for x in args_flat])
   1589     f = lu.wrap_init(fun)

~/miniconda3/lib/python3.8/site-packages/jax/util.py in safe_map(f, *args)
     33   for arg in args[1:]:
     34     assert len(arg) == n, 'length mismatch: {}'.format(list(map(len, args)))
---> 35   return list(map(f, *args))
     36 
     37 def unzip2(xys):

~/miniconda3/lib/python3.8/site-packages/jax/interpreters/masking.py in finalize_spec(polymorphic_shape, padded_shape)
    309 def finalize_spec(polymorphic_shape, padded_shape):
    310   return tuple(_parse_lit(d) if e is _monomorphic_dim else e
--> 311                for e, d in zip(polymorphic_shape, padded_shape))
    312 
    313 def parse_spec(spec=''):

~/miniconda3/lib/python3.8/site-packages/jax/util.py in safe_zip(*args)
     25   n = len(args[0])
     26   for arg in args[1:]:
---> 27     assert len(arg) == n, 'length mismatch: {}'.format(list(map(len, args)))
     28   return list(zip(*args))
     29 

AssertionError: length mismatch: [1, 2]
```

I could also totally be doing this wrong -- I reverse-engineered the PyTree shapes using error messages, for instance :)

Any comments are appreciated, and sorry for jumping the gun if this is trivially resolved by docs!

(Thanks for making this feature too!)

**Comment by jekbradbury** [comment]
I think your `in_shapes` are a little off; the parameters have shapes (4,10) and (10,), so that doesn't match `('_','_')` (you'd need `in_shapes=[[('(_,_)','_'),()],'(n,4)']`). With that fixed, your example hits a different error inside the `mask` logic, though.

That second issue is:
- the code for `vmap` of elementwise operations (`broadcast_batcher`) broadcasts unmapped inputs to the batch dimension using `bdim_at_front`
- when an unmapped input is a `DeviceArray`, that `broadcast` operation invokes the lazy broadcast machinery, forming a lazy `DeviceArray` that represents the broadcasted value without materializing it
- when the batch dimension is masked (your use case) that lazy array is invalid and reports a physical shape that includes a polymorphic (logical) dimension in the batch axis rather than a padded dimension 
- a polymorphic dimension showing up in the physical shape of an array breaks the masking logic

I think that's fundamentally a bug in the lazy array system (not taking into account the possible presence of masking).

I was hoping that, because (post-omnistaging) lazy arrays only show up in computations with concrete values, you could work around this by using `jit(msk(nn))` rather than `msk(nn)`, but that appears not to be the case (so I might be misinterpreting where the bug is, or there might also be a bug somewhere in `DynamicJaxprTrace`).

**Comment by hawkinsp** [comment]
jax.mask is long gone. Closing as stale.
