### ISSUE TITLE
How to use multiple GPUs in one process?

### ISSUE THREAD

**Issue by aaaa-a** [google/jax#4423]
I use environment variable to specify a GPU. As a result, in one process, I can only use one GPU. If I want to use multiple GPUs, I have to use multi-process in python. But the communication between processes is inefficient in python. Is it possible to use multiple GPUs in one process?

**Comment by tomhennigan** [comment]
I'm assuming the environment variable you are referring to is `CUDA_VISIBLE_DEVICES`, you can use this to specify >1 visible device `CUDA_VISIBLE_DEVICES=0,1 ./my_program`. You should see two GPUs in `jax.local_devices()`.

**Comment by aaaa-a** [comment]
> I'm assuming the environment variable you are referring to is `CUDA_VISIBLE_DEVICES`, you can use this to specify >1 visible device `CUDA_VISIBLE_DEVICES=0,1 ./my_program`. You should see two GPUs in `jax.local_devices()`.

Sorry, my expression is vague. For example, I have 2 batch data. I want to allocate 2 batch data to 2 GPUs respectively. For now, the only wat to do this I know is multi-process. I can set CUDA_VISIBLE_DEVICES=0 in one of the process and 1 in another process. But as I have said, the communication between two process is inefficient. I want to find a way to realize this in one process to avoid the communication between two process.

**Comment by mattjj** [comment]
Thanks for the question! I think you're looking for `jax.pmap` ([readme](https://github.com/google/jax#spmd-programming-with-pmap), [colab](https://colab.sandbox.google.com/github/google/jax/blob/master/cloud_tpu_colabs/Pmap_Cookbook.ipynb), [reference docs](https://jax.readthedocs.io/en/latest/jax.html#jax.pmap)), which lets you program multiple accelerators in an SPMD way.

If you want to write MPMD rather than SPMD code, then you can just use `jax.jit` with the `device` argument, where you can use `jax.local_devices()` to get references to your GPU devices. You can read more about device placement [in the FAQ](https://jax.readthedocs.io/en/latest/faq.html#controlling-data-and-computation-placement-on-devices).
