### ISSUE TITLE
Use exact GELU

### ISSUE THREAD

**Issue by hendrycks** [google/jax#4428]
jax.nn.gelu uses the approximate form of the GELU, but [tensorflow](https://github.com/tensorflow/tensorflow/blob/938cc7bf9c4f354361e18e3ba485af53e602d341/tensorflow/python/keras/activations.py#L311) and [pytorch](https://pytorch.org/docs/stable/generated/torch.nn.GELU.html?highlight=gelu#torch.nn.GELU) use the exact version.

I believe the exact form is more numerically stable and similarly fast. Figure 16 of the [Performer paper](https://arxiv.org/pdf/2009.14794.pdf) (@xingyousong) showed the GELU running into NaN issues, and I suspect this is because jax uses the approximate version.

**Comment by hawkinsp** [comment]
Interesting! https://github.com/google/jax/pull/1556 switched to the approximate version. @trevorcai @jekbradbury

**Comment by jekbradbury** [comment]
Exact GeLU is significantly slower on TPUs (easily noticeable even in end-to-end step time). We’d be happy to take a PR adding the exact implementation as an option, but keeping the approximate one as the default?

**Comment by hendrycks** [comment]
> Exact GeLU is significantly slower on TPUs
Interesting. For PyTorch this was not the case: https://github.com/pytorch/pytorch/issues/39853#issuecomment-658806898 The exact version was slightly faster.
> We’d be happy to take a PR
Sadly I don't know what optimizations would make them similarly fast.

**Comment by jekbradbury** [comment]
In JAX under a JIT, both versions are quite well optimized (fused, etc.). But TPUs are not very fast at certain kinds of vector math, and the exact GeLU happens to hit some of those cases (I think).

**Comment by hendrycks** [comment]
https://github.com/google/jax/pull/1556#issuecomment-545130783 says
> Confirming that my benchmarks are showing jax.grad(jax.jarrett(gelu)) as slower than jax.grad(gelu) on GPU as well.

So do you think the issue is with both TPUs and GPUs yet PyTorch on GPUs doesn't have a problem?

**Comment by hawkinsp** [comment]
I just tried some new JAX timings on TPUv2 (two generations old) and V100 (one generation old), mostly because I had easy access to them via Colab.

I found that on V100 when compiled with `jax.jit`, the approximate formulation is 1.12x faster on the forward pass (which seems relatively insignificant), but on TPUv2 the approximate formulation is 1.75x faster. The difference on the backward pass was much smaller. I would guess this is related to `erf` being much more expensive to compute than `tanh` on TPU. It's possible we could optimize our `erf` implementation, which would presumably improve the relative performance of the exact formulation on both platforms.

Since the performance differences are so large, at the moment it does seem like we might do best to let users choose which they want.

**Comment by hawkinsp** [comment]
PR #4438 adds an `jax.nn.gelu(..., approximate=True)` keyword argument to select between the exact and approximate versions. It does not switch the default to the exact version yet.

Separately, I have a PR coming that optimizes the implementation of `erf` in XLA such that the exact formulation matches the performance of the approximation on V100, and comes very close on TPU.

However, I need to try some end-to-end benchmarking on TPU before switching the default; we are guessing that in the context of a larger model like BERT the approximation would still be faster.
