### ISSUE TITLE
Jax indexing code runs extremely slowly?

### ISSUE THREAD

**Issue by arjun-mani** [google/jax#4436]
This code takes more than 15 seconds to run, while running it in standard numpy is instantaneous. I've looked around but can't find any explanation why. Intuitively, it feels like doing a simple indexing operation should not take nearly this long. Would appreciate any insight here, thank you so much. 

```
import jax
import jax.numpy as jnp
from jax import jit

@jit
def foo(a):
	for i in range(128):
		for j in range(128):
			s = a[0]
	return 0

 
a = jnp.zeros(128)
foo(a)
```

(128 is arbitrary, just happens to be relevant to my use-case).

**Comment by wrzadkow** [comment]
Code compiled using `jax.jit` generally takes a lot of time when run for the first time, because the just-in-time compilation is performed. All subsequent runs should be much faster.

I tried your code and replaced your last line with
```
t = time.time()
foo(a)
print(f'Including just-in-time compilation {time.time()-t}')
t = time.time()
foo(a)
print(f'Run using compiled code {time.time()-t}')
```
and got on my setup
```
Including just-in-time compilation 35.65647530555725
Run using compiled code 0.0005266666412353516
```


How long does it take in your setup if you try to run `foo` for a second time? 

In m

**Comment by machineko** [comment]
I meet the same problem at first with my code, so I've check common gotcha's especially here [in-place-updates](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#%F0%9F%94%AA-In-Place-Updates)

You can see that the first call will probably create new array every time you assign value to array element and will copy it (it was case with my code :P)

Also, first JIT call can be a lot longer cause of unrolling of the loops inside [for_loops](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#fori_loop)

```python
@jit
def foo(a):
	for i in range(128):
		for j in range(128):
			s = a[0]  # here you probably create new array every time it assigment happend without jitted function in pure python it'll be a 'pointer'
	return 0
```

**Comment by jakevdp** [comment]
The reason this takes a long time to run is because you are timing the tracing and compiling of the function.

`jax.jit` effectively unrolls all Python loops in the course of tracing the function, so it essentially turns this code snippet into a flat list of 128 * 128=16384 operations in sequence, and then this list of operations is fed to XLA for compilation.

In practice, I believe XLA compilation scales as roughly the square of the number of operations, so code like this performs rather poorly.

You can read more about how JIT interacts with Python control flow in https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#python-control-flow-+-JIT
