### ISSUE TITLE
Cross multiplication on JAX is faster in CPU compared to GPU

### ISSUE THREAD

**Issue by CleanPegasus** [google/jax#4474]
I tried taking the cross product of two (10,000 * 10,000) matrics on NumPy, TensorFlow and Jax to compare the time it takes to complete the operation.
On CPU:
Numpy took **58.32** seconds
TensorFlow took **64.802** seconds
Jax took **0.034** seconds

On GPU:
Numpy took **59.04** seconds (understandable because NumPy doesn't use GPU or TPU acceleration)
TensorFlow took **0.197** seconds
Jax took **2.02** seconds

Why is Jax slower on GPU(2.02 seconds) as compared to CPU(0.034 seconds)?

**Comment by clemisch** [comment]
From the large difference on CPU I suspect you did not use `.block_until_ready()` on the result array when measuring the time? JAX normally computes asynchronously, which means that the function call returns immediately even though the actual numerical computation is not finished. 

So, instead of 

```python
%timeit fun(arr)
```

for `fun` returning an array, rather use 

```python
%timeit fun(arr).block_until_ready()
```

**Comment by CleanPegasus** [comment]
It works. Thank you
