### ISSUE TITLE
np.mean raises warning when input is float64 in jax 0.2.1

### ISSUE THREAD

**Issue by fehiepsi** [google/jax#4490]
With the new update, the following script
```python
import numpy as np
import jax.numpy as jnp
jnp.mean(np.ones(30))  # or jnp.mean(1)
```
raises the warning
```
UserWarning: Explicitly requested dtype float64 requested in sum is not available,
and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64
configuration option or the JAX_ENABLE_X64 shell environment variable. See
https://github.com/google/jax#current-gotchas for more.
  warnings.warn(msg.format(dtype, fun_name , truncated_dtype))
```
I think this new behavior is unexpected so I would like to open this issue.

**Comment by jakevdp** [comment]
Thanks for the report. I believe the reason this started appearing in 0.2.1 is because of #4444. The best fix would be to call `dtypes.canonicalize_dtype()` here before passing the dtype to `sum()`: https://github.com/google/jax/blob/d4da9cc12cc785b0d174bdadddf29a5167239724/jax/numpy/lax_numpy.py#L1864-L1867
