### ISSUE TITLE
Support more numpy methods in `xla.DeviceArray`

### ISSUE THREAD

**Issue by moskomule** [google/jax#455]
Hi, the current version of jax does not allow `array.tanh()`, for example. I think this simplifies codes using jax:

```python
# from
np.tanh(np.exp(array))
# to
array.exp().tanh()
```

**Comment by mattjj** [comment]
Thanks for suggesting this!

We do have the flexibility to do this, but [those aren't methods on regular numpy ndarrays](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html). We aim to follow the numpy API since it's extremely well-considered, and in this case it's not clear where to draw the line (should all numpy functions also be attached as methods to ndarrays?).

There's a second reason that it can be better not to attach extra methods. If you write this:

```python
import jax.numpy as np
import numpy as onp

x = onp.zeros(10000)
y = np.exp(x)
```

Then JAX will actually execute that on the GPU (if you have one). If we instead dispatch on the type of `x` by calling a mehod, only numpy's code would get execute and we'd have no hope of executing on the GPU.

In any case, this is worth bringing up and thinking through. I don't think we'll make this change in core JAX, but perhaps it wouldn't be hard for users who want this functionality to add a few lines to their own code to attach whatever methods they want. [This code shows how to do it](https://github.com/google/jax/blob/2dae120d54846aa69e851aa584f724c9f7ba1903/jax/numpy/lax_numpy.py#L2125-L2207).

**Comment by moskomule** [comment]
Thank you for the detailed reply. I've used PyTorch instead of numpy so I didn't notice that.

The code you show is helpful.
