### ISSUE TITLE
Curious jit behavior in nested class functions

### ISSUE THREAD

**Issue by choltz95** [google/jax#4645]
Hi, I'm sure that I'm missing something, but what is the reason that I get significant speedups when the (jited) nested function is factored out?

Basically, what are the differences between the last two of the following implementations? I'm guessing for some reason the nested function is being redundantly compiled each call, but why is this the case?

Appreciate any guidance.

Unjitted sequence of operations:
```
def take_action(self, obs):
    logits = self.net_apply(self.params, obs)
    softm_logits = stax.softmax(logits.flatten())
    sorted_logits = jnp.sort(softm_logits)
    conf = sorted_logits[-1] - sorted_logits[-2]
    action = jnp.argmax(logits)
    return logits,action,conf
```

Sequence of ops with a nested jit
```
def take_action(self, obs):
    @jit
    def _take_action(params, obs):
        logits = self.net_apply(params, obs)
        softm_logits = stax.softmax(logits.flatten())
        sorted_logits = jnp.sort(softm_logits)
        conf = sorted_logits[-1] - sorted_logits[-2]
        action = jnp.argmax(logits)
        return logits,action,conf
        
    return _take_action(self.params, obs)
```

"factored" functions
```
@partial(jit, static_argnums=(0,))
def _take_action(self, params, obs):
    logits = self.net_apply(params, obs)
    softm_logits = stax.softmax(logits.flatten())
    sorted_logits = jnp.sort(softm_logits)
    conf = sorted_logits[-1] - sorted_logits[-2]
    action = jnp.argmax(logits)
    return logits,action,conf 

def take_action(self, obs):
    return self._take_action(self.params)
```

**Comment by jakevdp** [comment]
JAX's JIT compilation happens the first time a function is called, and any subsequent call of *that function object* will not need to re-compile.

When you define a function within a function, the inner function is re-defined each time the outer function is called, and so it is not the same object. For the purposes of `jax.jit`, this means it is seen as a new function object that has not yet been executed, and therefore must be traced and compiled. As a simple example, consider this:
```python
from jax import jit

def f(x, y):
  @jit
  def g(y):
    print('tracing')
    return x + y
  return g(y)

f(1, 2)  # prints "tracing"
f(1, 2)  # prints "tracing"
```
If the jitted function is defined outside the closure, it only traces once (because only one copy of the function exists):
```python
@jit
def g(x, y):
  print('tracing')
  return x + y

def f(x, y):
  return g(x, y)

f(1, 2)  # prints "tracing"
f(1, 2)  # no print - uses compiled XLA
```

**Comment by choltz95** [comment]
Thanks for clarifying!
