### ISSUE TITLE
aggressive JIT recompilation with equal-but-not-identical args

### ISSUE THREAD

**Issue by willwhitney** [google/jax#4712]
I'm having an issue with a JIT-compiled function being recompiled at every run. This seems to happen whenever an argument set as static is not _identical_ to its previous value (in the sense of `is` or `id(arg)`), rather than when it is not _equal_ to its previous value (in the sense of `==`).

Is this an expected behavior / a limitation of the compilation model?

---

As a simple example, consider:

```python
@jax.partial(jax.jit, static_argnums=(0,))
def dummy_add_fn(dummy, x):
    return x + 1
```

If we run + profile this, we find that whenever the identity of `dummy` changes, the function recompiles.

```python
dummy_arg = [0]
real_arg = jnp.zeros((3,))
with jax.profiler.TraceContext("Run 1"):
    dummy_add_fn(dummy_arg, real_arg)  # <- JIT compilation
with jax.profiler.TraceContext("Run 2"):
    dummy_add_fn(dummy_arg, real_arg)  # <- no compilation

dummy_arg = [0]
with jax.profiler.TraceContext("Run 3"):
    dummy_add_fn(dummy_arg, real_arg)  # <- compiles again
```

This happens even though `[0] == [0]`.

**Comment by mattjj** [comment]
This is expected behavior, but we intend to revise it. It's not a limitation, just a choice we made early on that was a bad one.

The idea is that unhashable objects (like lists) are silently treated via object identity semantics. See #2813 and the recent discussion on #4572.

We think this is a major foot-gun and so we're working to revise it into an error instead, but it required updating a bunch of Google-internal users who were relying on the previous behavior. #3712 made JAX's own internals not rely on the old/current work-by-object-identity-on-unhashable-arguments behavior. I think within a month JAX won't have this behavior anymore. Hopefully sooner.

For now, the solution is just not to use a list here: use a tuple instead. In general, any class with `__eq__` and `__hash__` defined (i.e. any hashable class) will work the way you expect based on the equality semantics those two methods define, whereas any unhashable class will silently work by object identity semantics (until we revise it to raise an error).

Hope that makes sense!

**Comment by willwhitney** [comment]
I see, that makes sense! Appreciate the quick reply!

In my actual code I was running into this with a Flax `struct.dataclass`, not a list — it sounds like even with the current behavior this could have been worked around on their end.
