### ISSUE TITLE
Unimplemented: binary integer op 'power'

### ISSUE THREAD

**Issue by iandanforth** [google/jax#48]
```python
def square(x):
  return x**2

val = 3
dfn = grad(square)
print(dfn(val))
```

I was surprised this threw an error. Changing it to `val = 3.0` works as expected.

**Comment by mattjj** [comment]
This seems like an important operation to offer :)

I think the binary integer pow function isn't implemented in XLA, since we seem to be getting [this error](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/service/elemental_ir_emitter.cc#L1280) and the `kPow` opcode doesn't seem to appear in that list. Maybe just an oversight. I'll follow up with XLA folks.

**Comment by mattjj** [comment]
A second issue here is that `grad` should raise an error on non-floating argument types.

**Comment by mattjj** [comment]
hawkinsp@ guessed that XLA's Pow HLO is meant to model `std::pow`, which apparently doesn't work on integer values either. We should solve this in JAX at the `jax.numpy` level.

**Comment by hawkinsp** [comment]
Thanks for the issue report!

I added support for integer powers to `jax.numpy.power`.

I also filed https://github.com/google/jax/issues/424 for raising an error if taking `grad` of an integer.
