### ISSUE TITLE
jacrev and nan

### ISSUE THREAD

**Issue by notEvil** [google/jax#4900]
Hi,

when I run the following

```python
import jax
import numpy


def f(y, t):
    return y ** t


y = numpy.arange(1, 4, dtype=float)
y[-1] = float("nan")
t = 1.0


print(jax.hessian(f, argnums=1)(y, t))
print(jax.jacfwd(jax.jacrev(f, argnums=1), argnums=1)(y, t))
print(jax.jacfwd(jax.jacfwd(f, argnums=1), argnums=1)(y, t))
```

(jax v0.2.5, jaxlib v0.1.57, CPU backend) I get

```
[nan nan nan]
[nan nan nan]
[0.       0.960906      nan]
```

Afaik it shouldn't matter if `jacfwd` or `jacrev` is used. The actual code I run is more involved, but the issue is the same. (It doesn't matter if `t = 1.0` or `t = numpy.array([1.0])`)

Hope I didn't miss an obvious reason in the docs.

**Comment by mattjj** [comment]
Thanks for the super clear repro!

I don't think there's an obvious reason here! I think it's the very-subtle issue discussed in #1052, but in this case applying in our own differentiation rules.

**Comment by notEvil** [comment]
Thanks for the explanation! Seems like a hard nut to crack.

I just tried `print(jax.vmap(jax.hessian(f, argnums=1), in_axes=(0, None))(y, t))` and it yields the correct result. I'll try this in a larger context and report back.

**Comment by notEvil** [comment]
The jaxprs essentially differ only in one line: `hessian` does `z = reduce_sum[ axes=(2,) ] y` whereas `vmap(hessian)` does not. Would you recommend `vmap` as a workaround?

**Comment by mattjj** [comment]
Actually, I think the issue here is that the Hessian is essentially

```
H =
array([[[0.       ]],

       [[1.3862944]],

       [[      nan]]])
```

where I added singleton axes for the scalar inputs to get a shape of `(3, 1, 1)` for clarity.

`jacfwd` essentially computes the Hessian like `np.einsum('ijk,j,k->i', H, np.ones(()), np.ones(()))`, while `jacrev` computes it like `np.einsum('ijk,il,k->l', H, np.eye(3), np.ones(1))`:

```
In[2]: import numpy as np  # original numpy!

In[3]: H = np.array([0.       , 1.3862944,       np.nan])

In [4]: np.einsum('ijk,j,k->i', H.reshape(3, 1, 1), np.ones(1), np.ones(1))
Out[4]: array([0.       , 1.3862944,       nan])

In [5]: np.einsum('ijk,il,k->l', H.reshape(3, 1, 1), np.eye(3), np.ones(1))
Out[5]: array([nan, nan, nan])
```

As you can see, when `nan` is involved, it's not the case that multiplying by identity matrices on different sides produce the same result! See also https://github.com/google/jax/issues/14149#issuecomment-2244251006 which was very similar.
