### ISSUE TITLE
Omnistaging slows execution time by a factor of 100

### ISSUE THREAD

**Issue by TalfanBarnie** [google/jax#4902]
Hello, I have a fairly substantial jax program that takes longer to compile and runs ~100 times slower when omnistaging is turned on. I'm trying to figure out what the culprit is but I'm new to jax and I'm not sure where to begin - I was wondering if anyone had any pointers where to start? Many thanks!

**Comment by TalfanBarnie** [comment]
Actually, I imagine this falls under #4643, in particular the point about when to use jax numpy versus regular numpy for controlling what gets staged - my code uses jax numpy everywhere, so maybe I'm really looking for advice on what to change to regular numpy?

**Comment by mattjj** [comment]
This sounds like it could be an XLA bug, both because it's slower to compile (which can happen with omnistaging because we end up staging bigger programs out to XLA) and because it's slower to execute (if we give XLA _more_ information, it shouldn't produce an executable that is slower).

What backend are you on (CPU/GPU/TPU), and would it be possible to provide some kind of runnable repro? (It doesn't have to be minimal.)

**Comment by mattjj** [comment]
It always helps to learn how to "think in JAX", but this sounds like a bad performance surprise which is on us to fix, not on you, dear user.

**Comment by TalfanBarnie** [comment]
Many thanks for getting back to me so quickly! In trying to create a runnable repo I discovered what the problem was - the jitted function included a very large matrix that was used in various computations but didn't actually affect the output - after refactoring to remove it,  and with omnistaging turned on, the code now compiles and runs quicker than it did originally. This is with Jaxlib 0.15.7 and Jax 0.2.5, compiling to CPU.

I'm wondering why this fixed it - am I right in thinking that jax wasn't staging out computations with this matrix because there was no dependency on it, but now with omnistaging that happens anyway?

The issue is solved for me, but let me know if a repo would still be useful for you and I'll create one!

**Comment by mattjj** [comment]
Interesting! Indeed before omnistaging, JAX's tracing machinery would essentially dead-code-eliminate values/operations like that; after omnistaging we essentially leave it to XLA. I'd expect XLA to do a better job of DCE than JAX did, but maybe something went wrong here.

I don't want to create extra work for you, but I would still be interested in creating a repro somehow, so that we can investigate. Maybe your description is enough for us to go on, but anything you can provide along those lines would be helpful.

**Comment by TalfanBarnie** [comment]
.... and now I can't reproduce it! I guess there must have been something else going on, but I don't have a commit to get the old code back. Sorry about this! If the same problem arises again I'll save the changes next time ....

**Comment by mattjj** [comment]
Ah, no worries at all. Thanks to you we'll be on the lookout for this cropping up again, and we'll know more information about it if it does. 👍 

I'll close this issue for now, but please don't hesitate to open new ones as issues inevitably arise!
