### ISSUE TITLE
Building on OSX with CUDA

### ISSUE THREAD

**Issue by alexbw** [google/jax#5]
I have a Mac laptop with a CUDA-compatible card in it (last generation they sold!) and have CUDA 9.2 and cuDNN 7.2.1 installed, and both seem to be working fine. I'm getting a build failure for JAX.

```
ERROR: /private/tmp/jax-build/jax-bazel-output-user-root/output-base/external/org_tensorflow/tensorflow/compiler/xla/service/gpu/BUILD:784:1: C++ compilation of rule '@org_tensorflow//tensorflow/compiler/xla/service/gpu:gpu_layout_assignment' failed (Exit 1)
external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_layout_assignment.cc:53:18: error: constexpr variable 'kAllNCHW' must be initialized by a constant expression
  constexpr auto kAllNCHW =
                 ^
external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_layout_assignment.cc:54:7: note: non-constexpr function 'make_tuple<stream_executor::dnn::DataLayout, stream_executor::dnn::FilterLayout, stream_executor::dnn::DataLayout>' cannot be used in a constant expression
      std::make_tuple(DataLayout::kBatchDepthYX, FilterLayout::kOutputInputYX,
      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/tuple:1094:1: note: declared here
make_tuple(_Tp&&... __t)
^
external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_layout_assignment.cc:56:18: error: constexpr variable 'kAllNHWC' must be initialized by a constant expression
  constexpr auto kAllNHWC =
                 ^
external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_layout_assignment.cc:57:7: note: non-constexpr function 'make_tuple<stream_executor::dnn::DataLayout, stream_executor::dnn::FilterLayout, stream_executor::dnn::DataLayout>' cannot be used in a constant expression
      std::make_tuple(DataLayout::kBatchYXDepth, FilterLayout::kOutputYXInput,
      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/tuple:1094:1: note: declared here
make_tuple(_Tp&&... __t)
^
2 errors generated.
Target //jax:build_jax failed to build
```

Any ideas?

**Comment by mattjj** [comment]
I think @hawkinsp nailed this in f3513a7. See the commit message for details (and for excellent ASCII art).

**Comment by jkyl** [comment]
Same issue here. I am not a C++ programmer, but I believe the issue comes from [XLA using `std::make_tuple`  as a `constexpr`](https://github.com/tensorflow/tensorflow/blob/c3030df6b9a65257893c8bad1e04567e3044994c/tensorflow/compiler/xla/service/gpu/gpu_layout_assignment.cc#L53), which is supported by GCC but not actually valid C++11/14, and therefore fails with macOS's toolchains. 

[This StackOverflow answer](https://stackoverflow.com/a/45468084) suggests a number of workarounds:
> In C++11/14, static constexpr variables must be _defined_ somewhere
> ...
> take a real reference or pointer to them
> ...
> change z to a constexpr function and call it when you want to use it 

I may open an issue over at TensorFlow, but they no longer support CUDA builds on macOS anyway, so probably a fool's errand.

**Comment by hawkinsp** [comment]
@jkyl I believe the `constexpr` annotation on `std::make_tuple` was added in C++14. A sufficiently new gcc or clang should have no problem with it.

This error unrelated to CUDA itself and the CUDA/CuDNN versions are irrelevant, however the problem is in code that is only built for GPU builds.

I think you have two options: (a) update your compiler to something newer (do you have the latest XCode installed?), or (b) send a PR/issue to TensorFlow making the code C++11 compatible. I suspect the use of C++14 is an oversight here and they would accept a PR for C++11 compatibility.

**Comment by jkyl** [comment]
@hawkinsp Thanks for your quick reply!

Strangely enough this happened with XCode 10.1. It seems that the associated clang uses C++11 by default . I will try to build with `-std=c++14` and report back.
