### ISSUE TITLE
Intersphinx: objects.inv missing

### ISSUE THREAD

**Issue by KristianHolsheimer** [google/jax#5001]
Hi there,

One of my build pipelines failed due to a missing intersphinx inventory file.

The command that fails is:
```
wget -O doc/_intersphinx/jax.inv https://jax.readthedocs.io/en/latest/objects.inv
```
> --2020-11-24 13:34:02--  https://jax.readthedocs.io/en/latest/objects.inv
> Resolving jax.readthedocs.io (jax.readthedocs.io)... 2606:4700::6811:2152, 2606:4700::6811:2052, 104.17.33.82, ...
> Connecting to jax.readthedocs.io (jax.readthedocs.io)|2606:4700::6811:2152|:443... connected.
> HTTP request sent, awaiting response... 502 Bad Gateway
> 2020-11-24 13:34:14 ERROR 502: Bad Gateway.

Do you know what may have caused this?

PS I looked at your readthedocs [builds](https://readthedocs.org/projects/jax/builds/), but they look healthy.

**Comment by mattjj** [comment]
Hmm, jax.readthedocs.io is having trouble loading for me right now:

![image](https://user-images.githubusercontent.com/1458824/100040602-7251d800-2dbc-11eb-87f7-e5dac48fef32.png)

Maybe it's just readthedocs server troubles?

**Comment by mattjj** [comment]
downforeveryoneorjustme.com confirms:

![image](https://user-images.githubusercontent.com/1458824/100040650-8d244c80-2dbc-11eb-882a-768cd0bc75e8.png)

I think this is likely just a server issue on their end. I hope you don't mind if I close this issue since I don't think it's JAX-specific, though if there's reason to think it is JAX-specific let's reopen!

**Comment by KristianHolsheimer** [comment]
No worries, yeah it must be something on their side. Thanks for the quick response @mattjj
