### ISSUE TITLE
lax.scan reverses `init` instead of `xs` according to the doc

### ISSUE THREAD

**Issue by LoicRaillon** [google/jax#5002]
```python
import jax

def forward(nf, x):
    n = nf + 1
    return n, (nf, x)

_, (nf, x) = jax.lax.scan(forward, jax.numpy.array(0, dtype=int), jax.numpy.arange(5), reverse=True)

print(f"\nnf: {nf} \nx: {x}")

nf: [4 3 2 1 0] 
x: [0 1 2 3 4]
```

According to the documentation I expect `x` to be reversed but the flag reverse=True works only on `init`.
I have a question not related to this issue but what is best practice for indexing with scan? Increment the carry as above or iterate with a `jax.numpy.arange`?

Thanks for your amazing work !

**Comment by jakevdp** [comment]
Thanks for the question! The semantics of `reverse` are a bit confusing, but I think this is the correct output. The scan happens over the reversed array, so that `nf=0` corresponds to `x=4`, `nf=1` corresponds to `x=3`, etc.

The arrays are returned in an order corresponding to the inputs, not in an order corresponding to the sequence in which they were scanned.

Does that make sense?

**Comment by LoicRaillon** [comment]
It makes sense ! Thanks for your time, I'm closing this issue.
