### ISSUE TITLE
Jax version of tensor_jacobian_product

### ISSUE THREAD

**Issue by smartalecH** [google/jax#5098]
What would be the best way to implement autograd's `tensor_jacobian_product()` in Jax?

**Comment by hawkinsp** [comment]
If nothing else, the implementation from autograd (https://github.com/HIPS/autograd/blob/c6f630a5ec18bd30f1485bc0dbbccb8664c77510/autograd/differential_operators.py#L98) works essentially unmodified in JAX:

```
import numpy as np
import numpy.random as npr
import jax
from jax import numpy as jnp

def tensor_jacobian_product(fun, argnum=0):
  """Builds a function that returns the exact tensor-Jacobian product, that
  is the Jacobian matrix left-multiplied by tensor. The returned function
  has arguments (*args, tensor, **kwargs)."""
  def vector_dot_fun(*args, **kwargs):
      args, vector = args[:-1], args[-1]
      return jnp.tensordot(vector, fun(*args, **kwargs), axes=np.ndim(vector))
  return jax.jacfwd(vector_dot_fun, argnum)

fun = lambda a: jnp.roll(jnp.sin(a), 1)
a = npr.randn(5)
V = npr.randn(5)
J = jax.jacfwd(fun)(a)
np.testing.assert_allclose(jnp.dot(V.T, J), tensor_jacobian_product(fun)(a, V))
```

**Comment by smartalecH** [comment]
Great, thanks @hawkinsp. 

That's what I currently do. I didn't know if there was a more efficient method using `vmaps` or something else.

Either way, this seems to work well.

**Comment by hawkinsp** [comment]
Maybe @mattjj has ideas for more efficient implementations, though!

**Comment by mattjj** [comment]
Indeed, `vmap` is better, but we're already getting that benefit! In Autograd, [`jacobian` must loop over each element of an output standard basis and apply the (unbatched) VJP function to each](https://github.com/HIPS/autograd/blob/c6f630a5ec18bd30f1485bc0dbbccb8664c77510/autograd/differential_operators.py#L60), whereas in JAX [`jax.jacfwd`](https://github.com/google/jax/blob/7084e3d42c9785c0a0489ac9d8b22ae31166db8f/jax/api.py#L866) and [`jax.jacrev` both use `vmap` under-the-hood to automatically batch things](https://github.com/google/jax/blob/7084e3d42c9785c0a0489ac9d8b22ae31166db8f/jax/api.py#L938).

That said, you can avoid the `jnp.tensordot` (and even avoid importing `jax.numpy` at all), so that the function works automatically on arbitrary pytrees, by using `vmap` and `vjp` (or `jvp`) directly. Check out the docs on [matrix-Jacobian products](https://jax.readthedocs.io/en/latest/notebooks/autodiff_cookbook.html#Jacobian-Matrix-and-Matrix-Jacobian-products) in the autodiff cookbook!

**Comment by smartalecH** [comment]
Indeed, the `vmap` approach works rather well! Thank you @mattjj and @hawkinsp for your help!
