### ISSUE TITLE
Array Shape as Random Variable

### ISSUE THREAD

**Issue by OlaRonning** [google/jax#5100]
Hi,

How can I treat an array's shape as a random variable when JIT compiling a function in Jax? See the toy example below.

```python
import jax

@jax.jit
def f(data, rng_key):
    n, m = data.shape
    shape_key, sub_key = jax.random.split(rng_key)
    rand_shape = jax.random.poisson(shape_key, 1, (2,))  # <--- Random Variable
    sub_indices = jax.random.randint(sub_key, (rand_shape.sum(), 3), 0, n)
    subsamples = data[sub_indices, :]
    return subsamples

rng_key = jax.random.PRNGKey(0)
f(jax.numpy.arange(10 * 5).reshape((10, 5)), rng_key)
```
Which produces the following error:
``` 
TypeError: Shapes must be 1D sequences of concrete values of integer type, got (Traced<ShapedArray(int32[])>with<DynamicJaxprTrace(level=0/1)>, 3).
If using `jit`, try using `static_argnums` or applying `jit` to smaller subfunctions.
```

**Comment by jakevdp** [comment]
Hi, thanks for the question! In short, this sort of operation - where array shapes are dynamic rather than static values - is not supported by JAX's compilation model. All shapes of arrays used in a jitted function must be static, i.e. determined at trace-time.

One way you might work around this is to choose a maximum size, and only fill the first *n* entries of this array, then pass this information along to the function that consumes the array. There is work in progress to make this sort of solution more automatic, using a masking transform.

**Comment by OlaRonning** [comment]
Hi @jakevdp,
Thanks for letting me know, I'll close this issue and look into the state of masking :)
