### ISSUE TITLE
'jaxlib.xla_extension.Buffer' object has no attribute '_value'

### ISSUE THREAD

**Issue by lukepfister** [google/jax#5140]
This bug seems to have crept in somewhere between 0.2.6 and 0.2.7.

On `jax=0.2.6`, `jaxlib=0.1.57+cuda110`, the following code works:

```python 
import jax
x = jax.device_put(np.ones((32, 32)))
print(x.device_buffer)
```

While on `jax=0.2.7`, I get the following error:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-32006f6a371a> in <module>
      1 import jax
      2 x = jax.device_put(np.ones((32, 32)))
----> 3 print(x.device_buffer)

~/miniconda3/envs/jax/lib/python3.8/site-packages/jax/interpreters/xla.py in _forward_method(attrname, self, fun, *args)
    999 
   1000 def _forward_method(attrname, self, fun, *args):
-> 1001   return fun(getattr(self, attrname), *args)
   1002 _forward_to_value = partial(_forward_method, "_value")
   1003 

AttributeError: 'jaxlib.xla_extension.Buffer' object has no attribute '_value'
```

Happy to submit a PR, but I'm not sure where to start looking on this.

**Comment by mattjj** [comment]
Thanks for raising this!

@jblespiau any guesses? I noticed this:

```python
In [2]: type(y)
Out[2]: jax.interpreters.xla._DeviceArray

In [3]: type(y.device_buffer)
Out[3]: jaxlib.xla_extension.Buffer
```

It looks like calling `print` on a `Buffer` (i.e. calling its `__str__`) is now erroring this way.

**Comment by jblespiau** [comment]
For me it works at head from within google:

In [10]: jitted = jax.jit(lambda x: x+1)
In [11]: jitted(1)
Out[11]: DeviceArray(2, dtype=int32)
In [12]: jitted(1)
Out[12]: Buffer(2, dtype=int32)
In [13]: type(jitted(1))
Out[13]: google3.third_party.tensorflow.compiler.xla.python.xla_extension.Buffer
In [14]: str(jitted(1))
Out[14]: '2'


`_value` is defined in xla.cc:

https://github.com/tensorflow/tensorflow/blob/6b599c349909e69f6e24e202ffdbf448baf72b74/tensorflow/compiler/xla/python/xla.cc#L335


So this is because, __str__  on a Buffer requires jaxlib 0.1.58, as it will access `_value`. I guess before it was defaulting to some pybind11 default.

was print(x.device_buffer) only printing `Buffer + some memory address`?

It will be solved by the next release of xla.cc. I don't think losing the feature to print the device_buffer is key?

**Comment by lukepfister** [comment]
It isn’t a pressing issue on my end.

I ran into it while troubleshooting compatibility with an external code
base.  This obviously wasn’t my real problem.

**Comment by mattjj** [comment]
@jblespiau thanks for looking into it, and for the detailed comment! If as you say this will be solved with the next jaxlib release, then that seems like a great plan to me.

**Comment by jakevdp** [comment]
Seems to have been fixed in a subsequent jaxlib release.
