### ISSUE TITLE
Failure installation Jax for GPU with version 0.1.57

### ISSUE THREAD

**Issue by Bodisatva** [google/jax#5148]
System: Ubuntu 18.04
Python:  3.8
CUDA: V10.1.243
Env: pipenv

Issues: Failure installation Jax for GPU with version 0.1.57. No issues with Jax CPU install

pipenv install  jax jaxlib==0.1.57+cuda101 -f https://storage.googleapis.com/jax-releases/jax_releases.html
Installing jax…
Adding jax to Pipfile's [packages]…
✔ Installation Succeeded 
Installing jaxlib==0.1.57+cuda101…
Error:  An error occurred while installing jaxlib==0.1.57+cuda101!
Error text: 
ERROR: Could not find a version that satisfies the requirement jaxlib==0.1.57+cuda101 (from -r /tmp/pipenv-pnynxvq3-requirements/pipenv-lnboz_1m-requirement.txt (line 1)) (from versions: 0.1, 0.1.1, 0.1.32, 0.1.33, 0.1.34, 0.1.35, 0.1.36, 0.1.37, 0.1.38, 0.1.39, 0.1.40, 0.1.41, 0.1.42, 0.1.43, 0.1.44, 0.1.45, 0.1.46, 0.1.47, 0.1.48, 0.1.50, 0.1.51, 0.1.52, 0.1.55, 0.1.56, 0.1.57)
ERROR: No matching distribution found for jaxlib==0.1.57+cuda101 (from -r /tmp/pipenv-pnynxvq3-requirements/pipenv-lnboz_1m-requirement.txt (line 1))

**Comment by hawkinsp** [comment]
This appears to be a `pipenv` bug. Consider using `pip` instead.

Another option if you still want to use `pipenv` would be to download the wheel you want (look at https://storage.googleapis.com/jax-releases/jax_releases.html in a browser to find the link) and install the `.whl` file with `pipenv`.

Closing since as far as I can tell there's no action for us to take; you could report a bug to the `pipenv` maintainers.

Hope that helps!

**Comment by Bodisatva** [comment]
Fair enough. Thanks for the reply !
