### ISSUE TITLE
optionally attach user source line info to tracers / jaxpr eqns

### ISSUE THREAD

**Issue by mattjj** [google/jax#522]
We'd like to be able to associate the code of transformed functions, and in particular the XLA HLO generated by `jit`, with the user source code that generated it. We can do that by using the `inspect` module to get the line info, and then attaching that information to Tracer instances and/or to jaxpr eqns generated (for the specific case of partial_eval.py).

This is another instance of reviving a feature from an older version of JAX. Here's a snippet we had to get the user line info, though stuffing it into the `OpMetaData` instance was something specific to plumbing it through to XLA HLO (whereas now we might want to attach it to JAX's data structures first). We'd pass `skip_files` as a list of JAX source files.

There might be some overhead to inspecting stack frames, so we could hide this behind a flag.

@j-towns want to take a look at this?

```python
import inspect
import os

def _user_source_info(skip_files=()):
  """Retrieves the user source information as an OpMetadata instance.

  Args:
    skip_files: iterable of filenames to skip over, moving further up the stack.

  Returns:
    XLA OpMetaData representing the source information for the caller stack
    frame, or None if no "user" source code location can be found.
  """
  frame = inspect.currentframe()
  while frame:
    filename = os.path.basename(frame.f_code.co_filename)
    if filename not in skip_files:
      lineno = frame.f_lineno
      return xla_bridge.get_xla_client().OpMetadata(
          op_type=None, op_name=None, source_file=filename, source_line=lineno)
    else:
      frame = frame.f_back
  return None
```

**Comment by mattjj** [comment]
This could help with #475.

**Comment by j-towns** [comment]
This is related to [this old Autograd issue](https://github.com/HIPS/autograd/issues/359). One thing that the suggestion above is lacking is the ability to inspect the frame as you might from a Python debugger (something I find extremely useful).

I'm wondering if it might be possible to reach an equivalent frame from the debugger by re-running the function and raising an exception when the frame corresponding to a problematic jaxpr is reached... Sorry this is a little vague, just putting down thoughts.

**Comment by j-towns** [comment]
> re-running the function and raising an exception when the frame corresponding to a problematic jaxpr is reached

Suppose we're tracing through during this re-execution, and trying to figure out if the jaxpr eqn we're creating is precisely equivalent to the problematic jaxpr eqn, for which we have saved some meta-data. If we call the problematic jaxpr eqn `p`, and the current jaxpr eqn `q`, I think we need to check the following:

p.primitive == q.primitive
p.params == q.params
p.args == q.args

_and_ I think that we require that the above 3 conditions hold for all of the parents of p/q _and_ all of their descendents. Parents should be ok to deal with because we can just keep a running hash of everything as we trace. For descendents, I think we'd need to know the entire jaxpr and back-propagate hashes of the necessary info. Also do-able (and interesting — this is backprop-esque message passing), but requires a bit of code.

**Comment by j-towns** [comment]
>Doing this whilst staying within q's Python frame may be tricky or impossible.

That may not be necessary. It looks like you can save a 'traceback' object, and then have the [debugger jump to that traceback](https://docs.python.org/3/library/pdb.html#pdb.post_mortem), just tried it and it seems to work with pdb.

**Comment by mattjj** [comment]
Thanks for your comments here, @j-towns. 

Unfortunately we explored this a bit and found that retrieving source info was too slow in Python (requiring a filesystem access for each line!). I think we should just close this issue.
