### ISSUE TITLE
Is it possible to manually cache results that we know will not change during training? (help needed)

### ISSUE THREAD

**Issue by rwbfd** [google/jax#5232]
In some computation, certain constant will pop up. It seems that we should let jit decide what to cache(?). But is there a way to cache the results manually? Thank you very much.

**Comment by gnecula** [comment]
Hi! I do not quite understand your question. Can you give a simple example?

**Comment by rwbfd** [comment]
For example, let say we have the following silly function.

```
@jit
def stupid(input):
     y = jnp.ones((1,)) #This will never change.
     return y*input
```

The `y` in the code should be compiled to a constant and cached, so not each time the function is called, it is created again. However, we will never know in certain situation whether `jit` will do the job. In this simple case, it probably will. But what if we want to manually force this to cache (except maybe passing a lot of arguments around). Is this possible?

**Comment by gnecula** [comment]
In the example you wrote the computation of the constant for `y` is actually not cached. This makes sense, the programmer wrote that computation inside the jitted function, so it should happen as part of the jitted computation. You can verify this by adding `print(jax.make_jaxpr(stupid)(2))`. If you want the computation to happen at trace time, and only the resulting constant to be included in the computation, then use `np.ones` instead of `jnp.ones`. 

You can read more details at https://github.com/google/jax/blob/master/design_notes/omnistaging.md

**Comment by rwbfd** [comment]
Ok. Thanks for the reply. I think I will experiment with `make_jaxpr` to see what actually happens. I will close the issue now.
