### ISSUE TITLE
jax.random.categorical speed

### ISSUE THREAD

**Issue by mganahl** [google/jax#5246]
Hi, we are using jax to simulate bitstring sampling from wave functions. Currently we are using jax.random.choice for that. I'm looking into switching to sampling from log probabilities instead of regular probabilities using jax.random.categorical. In our applications (event spaces of size > 2**30) and number of samples O(10^5) jax.random.categorical is very slow (see code below).

thanks!

```python
import time
import jax
import jax.numpy as jnp
import numpy as np
import matplotlib.pyplot as plt
def gaussian(x, mu=0, sigma=1):
    return 1/(np.sqrt(2*np.pi)*sigma) * np.exp(-(x-mu)**2/(2*sigma**2))
    
def time_choice(Nmax=7, Smax=6):
    times = []
    Ns = np.round(10**np.arange(2,Nmax)).astype(int) + 1
    sigma = 1
    shapes = 10**np.arange(2,Smax)
    key = jax.random.PRNGKey(10)
    for s in shapes2:
        shape = (s,)
        times.append([])
        for N in Ns:
            x = np.linspace(-4*sigma, 4*sigma, N)
            p = gaussian(x,0,sigma)
            t1 = time.time()
            samples = jax.random.choice(key, a = jnp.arange(-N//2, N//2),shape=shape,p=p)
            samples.block_until_ready()
            times[-1].append(time.time() - t1)
    return Ns, shapes, times
def time_categorical(Nmax=6, Smax=5):
    times = []
    Ns = np.round(10**np.arange(2,Nmax)).astype(int)
    sigma = 1
    shapes = 10**np.arange(2,Smax)
    for s in shapes:
        shape = (s,)
        times.append([])
        for N in Ns:
            x = np.linspace(-4*sigma, 4*sigma, N)
            p = gaussian(x,0,sigma)
            logp = jnp.log(p)
            logp.block_until_ready()
            t1 = time.time()
            samples2 = jax.random.categorical(key,logp,shape=shape)
            samples2.block_until_ready()
            times[-1].append(time.time() - t1)
    return Ns, shapes, times

Ns1, s1, t1 = time_choice(7,6)
Ns2, s2, t2 = time_categorical(6,5)
for n, t in enumerate(t1):
    plt.loglog(Ns1[:len(t)], t, '-x', label=f'# samples ={s1[n]}')
plt.xlabel('||event space||')
plt.ylabel('runtime /[s]')
plt.title('choice')
plt.legend()
plt.draw()
plt.show()

for n, t in enumerate(t2):
    plt.loglog(Ns2[:len(t)], t, '-x', label=f'# samples ={s2[n]}')
plt.xlabel('||event space||')
plt.ylabel('runtime /[s]')
plt.title('categorical')
plt.legend()

```

**Comment by jakevdp** [comment]
This difference comes from the different approaches used in the algorithms.

 - For selecting N samples from N possibilites with unequal probabilities with repeats, `choice` sorts the *M* cumulated probabilities and performs N binary searches through them, which scales as approximately *O[N logM]*.

- For selecting N samples from M possibilities with unequal probabilities, `categorical` computes the maximum of `N` gumbel distributions of length `M`, which scales as approximately *O[NM]*.

You might ask why we don't change `categorical` to use the same algorithm as `choice`; it tuns out that the algorithm used in `choice` has several weaknesses:

- Because it relies on `scan`, it is relatively fast on CPU backends, but you'll find it to be far less performant on GPU backends – to the point where your benchmarks above favor `categorical`.
- Because it doesn't broadcast easily, it doesn't map well to XLA's execution model in the general multi-dimensional sampling case that `categorical` implements.
- Because it relies on searching through cumulative probabilities, it loses precision for probabilities that span orders of magnitude, so it's not well-suited to the log probabilities supported by `categorical`.

Does that make sense?

**Comment by mganahl** [comment]
thanks @jakevdp for the quick reply, this clarifies the matter!
