### ISSUE TITLE
more primitives for doubledouble? In particular reductions?

### ISSUE THREAD

**Issue by lukemetz** [google/jax#5271]
I am trying to implement some iterative linear algebra routines for matrix powers that require float64. Naturally I turned to the doubledouble interpreter but found that reductions are not implemented.

Is this something that could be added? Thanks!

**Comment by lukemetz** [comment]
@jakevdp as I believe you wrote this

**Comment by jakevdp** [comment]
The doubledouble transform still has a long way to go to be generally usable.

If you're mainly interested in float64 operations, is there a reason that you can't use `enable_x64` mode?

**Comment by lukemetz** [comment]
Ahh ok.

As per enable_x64 -- I was under the impression that that converts a lot of my code to run in float64 where as I only want small pieces (one function) to run in higher precision.

**Comment by jakevdp** [comment]
`enable_x64` does not necessarily convert all your code to float64, but it makes it so that 64-bit types are allowed by jax. So currently if you use `jnp.arange(10.0)`, it will return `float64` if `enable_x64` is True, and will return `float32` if `enable_x64` is False. Of course, you can always do `jnp.arange(10.0, dtype='float32')`, which will be 32-bit in either mode.

**Comment by lukemetz** [comment]
Ahh cool. This should do perfectly for my use case. Thanks!

Separate from that, I do think doubledouble is suuuper cool! I will close this issue though.
