### ISSUE TITLE
Why is `jnp.nonzero` not jittable?

### ISSUE THREAD

**Issue by langosco** [google/jax#5280]
I'm trying to use `jnp.nonzero(a)` inside a jitted function. The array `a` depends only on the input array shapes, so I expected it to work, since the output shapes are constant for a given input shape. But apparently `jnp.nonzero` always throws an error.

For example,
```
@jit
def example():
    a = np.array([0, 1, 2])
    return np.nonzero(a)
```
throws an error when called.

Is this the intended behaviour? If so, are there any workarounds?

**Comment by jakevdp** [comment]
Yes, this is intended.

The reason this is not jittable is because under JIT, the shapes of returned arrays must be static, i.e. dependent on the shape of the inputs rather than their contents. The `nonzero` function returns a value whose shape depends on the contents of the inputs, so it is not compatible with JIT.

There are no workarounds for the simple case you show above, but depending on your actual application you can often use the three-argument version of `jnp.where` instead.  For example, here is a non-jittable function:
```python
def f(a):
   return a[jnp.nonzero(a)].prod() 
```
and here is an alternative version of what is essentially the same function, but that is compatible with JIT:
```python
def f(a):
  return jnp.where(a != 0, a, 1).prod()
```

**Comment by langosco** [comment]
Thanks! 

I'm confused about the static shapes requirement: `jnp.nonzero` doesn't work even when embedded in a larger function where the shapes of the returned arrays are static. The thing I'm trying to do is return the indices of the off-diagonal elements of a square matrix, that is
```python
def offdiagonal_idx(matrix):
    n = matrix.shape[0]
    return np.nonzero(~np.eye(n, dtype=bool))
```
The output only depends on the shape of the input matrix, but still throws an error. Also, this worked in a previous version of jax, so there must have been a decision at some point to not allow this anymore.

**Comment by jakevdp** [comment]
if you've done `import numpy as np`, that should work without any issues: that's the approach I would recommend here:
```python
import numpy as np
import jax.numpy as jnp
from jax import jit

@jit
def offdiagonal_idx(matrix):
    n = matrix.shape[0]
    return np.nonzero(~np.eye(n, dtype=bool))

print(offdiagonal_idx(jnp.ones((3, 3))))
# (DeviceArray([0, 0, 1, 1, 2, 2], dtype=int32), DeviceArray([1, 2, 0, 2, 0, 1], dtype=int32))
```

**Comment by langosco** [comment]
Thanks a lot, this resolves my problem perfectly. The 'just use numpy for static computations' trick is super useful (might be worth adding to the docs, even though it seems obvious in retrospect). Also thanks for the ref to #3370. 

Cheers!
