### ISSUE TITLE
bad interaction of jax and numpy indexing

### ISSUE THREAD

**Issue by langosco** [google/jax#5417]
If I want to index a regular numpy array, I can do that like so:
```python
import numpy as onp
arr = onp.arange(5)
idx = onp.array([1,2])
arr[idx]
```
But if I then try to index that same array with `jnp.array` indices,
```python
import jax.numpy as jnp
j_idx = jnp.array([1,2])
arr[j_idx]
```
I get the following error:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-9c09f5614663> in <module>
      1 import jax.numpy as jnp
      2 j_idx = jnp.array([1,2])
----> 3 arr[j_idx]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

It seems that numpy interprets `jnp.array` indices as tuples instead of arrays. This creates problems when mixing `onp.array`s with jax; for example `jax.random.permutation` throws the same error when fed a numpy array as input.

**Comment by mattjj** [comment]
Thanks for the question!

I think this is an instance of #620; see [this comment](https://github.com/google/jax/issues/620#issuecomment-484344945) in particular.

This is essentially a bug in NumPy duck typing which we can't fix on the JAX side: NumPy has some [legacy special handling for short sequences used as indices](https://github.com/numpy/numpy/blob/8f31f95910d27da75941bbbbde7ef1ecec9b0f74/numpy/core/src/multiarray/mapping.c#L271-L282), and because that code path doesn't check for the presence of an `__array__` method on the indexing object, we have no way to adapt our JAX arrays to act exactly like NumPy's ndarrays in this case.

The best solution is to call `jnp.asarray` on the array being indexed:

```python
j_idx = jnp.array([1,2])
jnp.asarray(arr)[j_idx]
```

This defensive maneuver will mean JAX's array indexing logic always gets called, rather than NumPy's, and so you'll get the intended behavior.

What do you think?

**Comment by langosco** [comment]
Makes sense, thanks for the explanation!

**Comment by samuela** [comment]
Oof just ran into this as well (since flax rehydrates weights as numpy arrays, as opposed to jax.numpy arrays), and it really stumped me and @PythonNut for a minute. Turns out that the magic number is 31: any JAX array with length 31 or smaller throws the error, and works otherwise.
