### ISSUE TITLE
wrong value of jax.lax.lgamma(1.)

### ISSUE THREAD

**Issue by phylyc** [google/jax#5418]
It appears that the `lgamma` function gives the wrong value for argument 1.
```
>>> jax.lax.lgamma(1.)
DeviceArray(4.7683716e-07, dtype=float32)
>>> scipy.special.gammaln(1)
0.0
```
The issue may lie deeper, but I can't trace it further than that.

(I'm using Python 3.8.5 with jax version 0.2.3)

**Comment by jakevdp** [comment]
Hi @phylyc – thanks for the report.

In this case, I think the issue is due to standard imprecision in floating point arithmetic. In 32-bit precision (JAX's default), 4E-7 is effectively zero. If you switch to 64-bit, you'll see that the result is closer to zero, becuase 64-bit floats have more precision:
```python
import jax
jax.config.update('jax_enable_x64', True)

print(jax.lax.lgamma(1.))
# 8.881784197001252e-16
```

**Comment by phylyc** [comment]
Dear @jakevdp , thanks for the quick answer!

Thanks for pointing out the floating point precision issue. It does change my results slightly, so I'll use that when necessary going forward.
