### ISSUE TITLE
vmap CPU multi-core performance

### ISSUE THREAD

**Issue by cagrikymk** [google/jax#5506]
Hi everyone,
I am seeing weird behavior from "vmap" when I compile the code for CPUs. Even though the vectorized function is the computationally heaviest part of my code, I am seeing bad CPU utilization. 

The performance is decent for Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 cores) where I see 560% utilization. However, when I test the the same code on 2 X Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (2x14 cores), I see 340% utilization. I tried to force the code using only 1 socket but it didnt help. 

The performance on the Xeon CPU is 3x worse than the i7 one overall (in terms of the execution time). 
I am not expecting to see 70% + core utilization on all multi-core systems just using vmap but this seemed like a wild difference. 

I am using jax 0.1.76 and jaxlib 0.1.59.

**Comment by mattjj** [comment]
Thanks for the question!

`vmap` works by taking the map you express and "plumbing it down" onto every operation, e.g. turning matrix multiplies into batch matrix multiplies. That isn't always the best way to compute things: for example, if your code is embarrassingly parallel (i.e. you're using `vmap` without collective communication operations) and you have many cores available, rather than plumbing that loop down to every operation (and relying on the compiler to fuse operations back together as needed), it might be better to keep the map's loop at the top level and schedule it to multiple cores / OS threads. For example, if you're running parallel MCMC chains on CPU, that's probably a better approach.

You can do that with `jax.pmap`, though it's a bit awkward on CPU. (`pmap` is designed for mapping over hardware resources, but more often it's used to map over multiple hardware accelerator cores, like multiple GPUs or TPU cores; then we rely on XLA:GPU or XLA:TPU to manage parallel resources within each such device.) First, you have to tell XLA to create separate CPU devices, rather than viewing your CPU as a single device. Then when you use `pmap` your program instances will ultimately be mapped to distinct OS threads and thus hardware cores.

One way to force the XLA:CPU device count to a specific number is to use the shell environment variable `XLA_FLAGS=--xla_force_host_platform_device_count=NUM`, so like

```
env XLA_FLAGS=--xla_force_host_platform_device_count=28 python foo.py
```

You can also use the `os` module to set that value within Python, though you should probably do it before running any JAX operations.

You might then run into an annoying limitation with `pmap`: if your number of devices doesn't equal or exceed the size of the logical array axis you're mapping, then you'll get an error. The solution now is to manually use both `pmap` and `vmap` together with reshaping, though soon you'll be able to use `xmap` to more flexibly control this kind of thing. (cc @apaszke )

Would it make sense to try using `pmap` and setting the XLA:CPU device count? We should also talk about how to make this more ergonomic, but setting ergonomics aside we can at least figure out whether this helps your performance issue.

Let us know what you think!

**Comment by cagrikymk** [comment]
Thank you for the fast and thorough response!
Yes it makes perfect sense. I looked at #1408 and I couldn't exactly use it since I apply JIT to the main loss function and I need to use vmap or pmap inside that function. When I try to replace vmap with pmap, I was getting an error `can't specify device or backend for jit-of-pmap, got device=None and backend=cpu`. Is there a way to jit pmap while specifying the backend? 

I thought XLA would be able to figure out the correct mapping for vmap to maximize the performance but I understand it is not a trivial problem to solve. 

I am mainly focusing on the GPU performance but I was expecting out-of-the box vmap + CPU scalability to be close to linear for embarrassingly parallel work load but understand the point.

`xmap` sounds like a perfect solution for my use case!

Thank you!

**Comment by mattjj** [comment]
> Is there a way to jit pmap while specifying the backend?

Hmm, maybe, but it'd be easier to answer concretely if you could provide a minimal example showing what you want to do.

> I thought XLA would be able to figure out the correct mapping for vmap to maximize the performance but I understand it is not a trivial problem to solve.

In general, the XLA:CPU backend is the least developed and performs the fewest optimizations. XLA:TPU is the most advanced.

**Comment by JeppeKlitgaard** [comment]
I am trying to parallelize a function cross multiple CPU cores and have found it not to be as trivial as I was hoping. Given there are a few issues that seem to share my confusion on how to do this, I figure it might warrant bumping the issue here.

> The solution now is to manually use both pmap and vmap together with reshaping, though soon you'll be able to use xmap to more flexibly control this kind of thing. (cc @apaszke )

Since `xmap` has presumably matured a lot recently, could you @mattjj expand on this? The documentation on `xmap` seems to be incomplete.

From my understanding, one needs to introduce `resource_axis` in order to parallelize computation using `xmap`?

**Comment by nestordemeure** [comment]
I am currently instrumenting a large numerical codebase with JAX (we are evaluating several options and writing a paper on their applicability to this usecase) and I ran into this issue using the latest JAX version (`0.3.13`). 
A lot of our code is vectorised with `vmap` and we want to cover both the single GPU and multicore CPU usecases with a single codebase (making `pmap` a bad fit). JAX CPU parallelizes a single matrix multiplication with no problems but `vmap` (and `xmap`) seem unable to use of all the cores at their disposition.

Here is a small test case to reproduce the phenomenon, it applies a cosine to a very large array (a task that should be trivially parallelizable):

```python
import time, os, jax, numpy as np, jax.numpy as jnp
jax.config.update('jax_platform_name', 'cpu') # insures we use the CPU

def timer(name, f, x, shouldBlock=True):
   # warmup
   y = f(x).block_until_ready() if shouldBlock else f(x)
   # running the code several times
   start_wall = time.perf_counter()
   start_cpu = time.process_time()
   y = f(x).block_until_ready() if shouldBlock else f(x)
   end_wall = time.perf_counter()
   end_cpu = time.process_time()
   # computing the metric and displaying it
   wall_time = end_wall - start_wall
   cpu_time = end_cpu - start_cpu
   cpu_count = os.cpu_count()
   print(f"{name}: cpu usage {cpu_time/wall_time:.1f}/{cpu_count} wall_time:{wall_time:.1f}s")

# test functions
key = jax.random.PRNGKey(0)
x = jax.random.normal(key, shape=(500000000,), dtype=jnp.float64)
x_mat = jax.random.normal(key, shape=(10000,10000), dtype=jnp.float64)
f_numpy = np.cos
f_vmap = jax.jit(jax.vmap(jnp.cos))
f_xmap = jax.jit(jax.experimental.maps.xmap(jnp.cos, in_axes=[['batch']], out_axes=['batch']))
f_dot = jax.jit(lambda x: jnp.dot(x,x.T))

timer('numpy', f_numpy, x, shouldBlock=False)
timer('vmap', f_vmap, x)
timer('xmap', f_xmap, x)
timer('dot', f_dot, x_mat)
```

And the corresponding output (note that my processor has 128 cores, using 12 cores on a trivially parallel loop is very far from optimal):

```shell
numpy: cpu usage 1.0/128 wall_time:0.7s
vmap: cpu usage 11.8/128 wall_time:0.4s
xmap: cpu usage 11.7/128 wall_time:0.4s
dot: cpu usage 122.7/128 wall_time:0.5s
```

My processor is an `AMD EPYC 7763 64-Core` in case it might be useful.

**Comment by Birch-san** [comment]
@nestordemeure thanks for posting the repro; I'm having a similar issue trying to utilise all cores on an M1 Max, where it's presumed that [IREE doesn't utilize all CPU cores](https://github.com/google/jax/issues/8074#issuecomment-1148758064).

```
numpy: cpu usage 1.0/10 wall_time:0.7s
vmap: cpu usage 3.9/10 wall_time:0.8s
xmap: cpu usage 3.9/10 wall_time:0.8s
dot: cpu usage 9.2/10 wall_time:3.6s
```

looks like higher % utilization than on your CPU. not perfect either.

**Comment by EelcoHoogendoorn** [comment]
@nestordemeure 

Thanks for posting these benchmarks; I didnt know that JAX CPU multicore was still so poorly supported... I was hoping to leverage large CPU systems for what im working on, but looking at things like these, I suppose im best off restricting my ambitions so that they may keep fitting in a single GPU for now.

**Comment by CAClaveau** [comment]
Hi, I tried to reproduce on my laptop the above code of benchmarking given by @nestordemeure, but I get the following error with the 'xmap' version: `AttributeError: 'NoneType' object has no attribute 'empty'` coming from the following line#2148 `assert not mesh.empty` of the file "pxla.py". (I'm using the latest version of JAX). I am not familiar enough with the "xmap" function. Could you please check that the code given above is still valid, and update it if needed? Thank you for your help!

**Comment by mattjj** [comment]
I think this thread is pretty stale, so I'm closing it. Don't hesitate to open new issues (ideally with runnable repros!) if you have performance issues!
