### ISSUE TITLE
Improving jax.scipy.stats

### ISSUE THREAD

**Issue by vishwakftw** [google/jax#56]
Hi,

Are there any plans for improving the stats modules in jax.scipy? I look forward to contributing to this project by adding new distributions and properties for distributions (mean, variance for e.g.). Please let me know your thoughts about this.

Thank you.

**Comment by mattjj** [comment]
Thanks for your interest! Yes, we'd like to continue to build out the NumPy and SciPy coverage in JAX, including in jax.scipy.stats. Contributions there would be much appreciated!

I'll close this issue for now so that we can use finer-grained feature requests and pull requests to track specific functions to be added.

**Comment by vishwakftw** [comment]
Sure, no worries.

I’ll send in a PR with a few popular distributions in a few hours, if that’s fine.
