### ISSUE TITLE
Equivalent to autograd's elementwise_grad?

### ISSUE THREAD

**Issue by martiningram** [google/jax#564]
Hi there,

In autograd, I use the function "elementwise_grad" a fair bit. Is there an equivalent in jax? In particular, I would like to compute the elements of a diagonal Hessian, which I do in autograd by calling elementwise_grad twice:

    from autograd import elementwise_grad as egrad
    h = egrad(egrad(fun))(x)

Initially I thought

    vmap(grad(grad(fun)))(x)

would do the trick, but although it worked on a toy example, it gives a different result in general.

Hope that's enough information. Happy to put together a proper example if not, please let me know!

**Comment by mattjj** [comment]
Ah, unfortunately calling `elementwise_grad` twice won't give you the diagonal of the Hessian:

```python

```

I think @dougalm and I saw some issues on the Autograd issue tracker about this, but didn't have time to respond, and maybe those threads came to the incorrect conclusion that `elementwise_grad` would work here. It only works when the underlying function has a diagonal Jacobian, i.e. basically only for elementwise functions. It can't give you the diagonal of a general Hessian efficiently. (What it does is compute the VJP with an all-ones vector; when the Jacobian is diagonal, that reveals all the nonzero coefficients of the Jacobian, and similarly when the Hessian is diagonal then calling this twice would reveal all the nonzero coefficients of the Hessian. But if the Jacobian isn't diagonal then `elementwise_grad` is just giving you the sum of its rows. This confusion is a reason not to include it in JAX, and to prefer `vmap(grad(f))` for elementwise differentiation, since the `vmap` semantics are clearer.)

In general, computing the diagonal of the Hessian is as hard as computing the full Hessian itself. That is, you'd basically have to call `jax.hessian` and take its diagonal.

Does that make sense?

**Comment by martiningram** [comment]
It does! Thank you so much for the detailed response!
