### ISSUE TITLE
Old Jax GPU wheels

### ISSUE THREAD

**Issue by McLawrence** [google/jax#5646]
I don't know if this is the appropriate place to post this question:

Is there still a way to access very old jaxlib builds for GPU that are not at http://storage.googleapis.com/jax-releases/jax_releases.html ?

The project for which I need it uses `jax 0.1.21` and `jaxlib 0.1.11` which was previously hosted at https://storage.googleapis.com/jax-wheels

**Comment by hawkinsp** [comment]
Unfortunately not. We don't have a policy of keeping very old wheels around (and in fact, we are sometimes forced to delete them in places like Pypi because we need the space...)

I looked and I don't think we have those very old wheels anywhere any more. They were lost as part of the bucket move. That said, I think it makes sense to change our procedures to archive all wheels going forward.

I think your best bet in this case is to upgrade the code to work with a current `jax`. Hopefully this isn't too much of a burden!

The only other alternative I can think of would be to check out the code from GitHub from around that time and try to rebuild it, but it seems like updating the client code is probably a more forward-looking solution...
