### ISSUE TITLE
operator.iadd(np_array, jnp_array) silently fails

### ISSUE THREAD

**Issue by SuperElectric** [google/jax#5678]
In-place adding a `jnp.array` into a `np.array` using `operator.iadd` silently fails.

Desired behavior: It should work, just like `np_array += jnp_array` does.
Actual behavior: the operation is ignored.

Minimal example:
```
import numpy as np
import jax.numpy as jnp
import operator

my_sum = np.zeros(shape=())
my_value = jnp.array(10)
operator.iadd(my_sum, my_value)
print(my_sum)  # "0.0"
```

**Comment by jakevdp** [comment]
Thanks for the report! This issue can be boiled down to the following:
```python
class FakeDeviceArray:
  __array_priority__ = 100
  def __array__(self):
    return np.array(10)
  def __radd__(self, other):
    return np.asarray(self) + np.asarray(other)

arr = FakeDeviceArray()
my_sum = np.zeros(shape=())
operator.iadd(my_sum, arr)
print(my_sum)
0.0
```
JAX uses `__array_priority__` to ensure that operations between numpy arrays and JAX arrays result in JAX arrays... this means that a numpy defers mixed binary operations to JAX's implementation, and in particular means that a numpy value *cannot* be updated in-place.

Because in-place updates are not always possible, `operator.iadd` has a return value, and the equivalent of `my_sum += my_value` would be `my_sum = operator.iadd(my_sum, my_value)`.

**Comment by shoyer** [comment]
I think this is more or less working as intended, based on the semantics of Python's `+=` operator.

I'm curious why you found a need to use `operator.iadd` directly?

**Comment by SuperElectric** [comment]
>
> I'm curious why you found a need to use operator.iadd directly?


I'm using operator.iadd since I need to pass the operator into another
function as a function argument.

Here's the actual line that's using it:
https://github.com/deepmind/acme/blob/master/acme/environment_loop.py#L107

It takes a binary operator, and two data structures A and B with identical
tree structure, and applies the operator to all pairs of corresponding
leaves in A and B. Since you can't pass in '+=' as a function argument, I
had to pass in operator.iadd.

Could DeviceArray.__radd__ detect the use case of np_array += jnp_array
through run-time typechecking, and just do other += np.asarray(self)? If
not, could it throw an exception instead of failing silently?

**Comment by shoyer** [comment]
I really think you should be using the return value here, e.g.,
```python
      # Equivalent to: episode_return += timestep.reward
      episode_return = tree.map_structure(operator.iadd, episode_return, timestep.reward)
```

The problem is that Python's `operator.iadd()` does not make any guarantees about doing operations in-place. You would have the same issue with a class like Python's built-in `float` (which does not support in-place arithmetic).

> Could `DeviceArray.__radd__` detect the use case of `np_array += jnp_array` through run-time typechecking, and just do `other += np.asarray(self)`? If not, could it throw an exception instead of failing silently?

`__radd__` doesn't reveal that it came from an in-place operation, so this would pick-up `np_array + jnp_array` as well.

(This could conceivably be done via adding an `__array_ufunc__` method for NumPy, but that would have other weird knock-on effects like defining `np.add()` to use JAX when called on JAX arrays.)

**Comment by SuperElectric** [comment]
I see. Thanks for the explanation! 

Yes, using the return value of iadd is one workaround that we're considering.

We're also considering `np.add(np_array, jnp_array, out=np_array)`, which has the desirable-for-our-use-case property that it keeps `np_array` a Numpy array, whereas `np_array = iadd(np_array, jnp_array` overwrites it as a JAX DeviceArray.

Closing this issue.
