### ISSUE TITLE
Better error message for nans in scan.

### ISSUE THREAD

**Issue by MaxiLechner** [google/jax#5696]
When a nan is encountered in a scan the error message  refers to while.

FloatingPointError: invalid value (nan) encountered in while

This might be a bit confusing to beginners that don't know that scan is implemented in terms of while.
If the error message can't easily be changed to refer to scan instead then maybe replacing while with lax.while_loop would make the error message more clear.

**Comment by jakevdp** [comment]
Thanks for the report! Can you give an example of what you mean by "a nan is encountered in scan"? For example, I tried this and didn't see any error:
```python
import jax.numpy as jnp
from jax import lax

x = jnp.array([1, 2, jnp.nan, 3, 4])
lax.scan(lambda c, x: (c + x, x), 0, x)
```

**Comment by MaxiLechner** [comment]
Oh my fault I forgot to include that I have the jax_debug_nans flag set to True.

import jax.numpy as jnp
from jax import lax
from jax import config
config.update("jax_debug_nans", True)

x = jnp.array([1, 2, jnp.nan, 3, 4])
lax.scan(lambda c, x: (c + x, x), 0, x)

**Comment by jakevdp** [comment]
I see, thanks! The reason this is reported as happening in `while` is because it is: `lax.scan` is implemented in terms of a while loop, as you can see here:

https://github.com/google/jax/blob/2fabc5345dc3a0c779f229c844506355b44688ac/jax/_src/lax/control_flow.py#L1334

I don't think there's any easy way to propagate the name of the calling function through to the primitive, but the Python traceback does make the context clear. Does that make sense?
