### ISSUE TITLE
Utility for tracking total time spent on JIT compilations

### ISSUE THREAD

**Issue by jaehunro** [google/jax#5700]
It'd be great if there was some convenient jax util that could keep track of the total time spent on jit compilations/recompilations.
I can kind of approximate by timing the first runs for each jitted function for each set of input shapes but that seems unclean and possibly inaccurate.

**Comment by zhangqiaorjc** [comment]
I think you will measure it using the tensorflow profiler

https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras

It will show up as PjRtStreamExecutorClient::Compile traceme due to 

https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc;l=2105?q=PjRtStreamExecutorClient::Compile%20tensorflow

**Comment by jaehunro** [comment]
Thanks for the information and pointers. I figured I could use a profiler to measure it but I thought it would be nicer to just have an easy utility as part of jax (especially for users that lack experience running/understanding the output of a profiler).

Side note: Having something like a decorator that users can use to mark functions they want to specifically target and measure seemed useful as well.

I'll close this issue for now and if others desire this more, they can re open it.
