### ISSUE TITLE
LU decomposition runtime is dominated by lu_pivots_to_permutation on GPU

### ISSUE THREAD

**Issue by ahoenselaar** [google/jax#5880]
The actual decomposition in handled by cusolver. However, the pivots returned by `getrf` are transformed into a permutation matrix via `lu_pivots_to_permutation`. For an `(n, n)` matrix this transformation is implemented as a loop with `n` iterations. Even though the amount of data involved is small (`int32` vector of length `n`), this loop performs poorly and its runtime by far exceeds that of `getrf`.

Trace for a 75x75 doube-precision matrix on a V100.
![image](https://user-images.githubusercontent.com/3757431/109436381-165aa900-79d4-11eb-85bd-7e0de47fa50d.png)

Batching does not improve the situation much. Trace for a batch of 64 double-precision matrices with shape (75, 75):
![image](https://user-images.githubusercontent.com/3757431/109436834-65094280-79d6-11eb-9858-867199189ce7.png)

**Comment by mattjj** [comment]
Thanks for the report!

**Comment by mattjj** [comment]
Based on some comments from @hawknsp, I think the issue is that on GPU each iteration of the loop gets turned into a separate kernel launch, which is a current limitation of XLA:GPU. Our options for improving this include:
1. help XLA:GPU folks make loops faster (by gaining the ability to generate a single kernel launch for some loops);
2. write a custom GPU kernel (like we do for PRNG sampling, because there is a bad compile time / execution time tradeoff on GPU);
3. partially unroll [this loop](https://github.com/google/jax/blob/c9b7d751289f60a852f5e5585e3d99aff29fdaae/jax/_src/lax/linalg.py#L969) at the JAX Python level.

The first fix seems like the right one for the long term, but I don't know when it'll happen. The last one is more of a mitigation, but it seems like quite a good one, especially since we can just write the `fori_loop` as a `scan`, and use [`scan`'s built-in `unroll` value](https://github.com/google/jax/blob/aa438e6c6fd0e44e19494f5dee9adfd1658154ad/jax/_src/lax/control_flow.py#L1146).

**Comment by ahoenselaar** [comment]
Rewriting as a `scan` with `unroll=16` reduces the runtime by only 20%. The profile shows a large number of same-device memory transfer operations of size 300 (=75 * 4 bytes, i.e. the full permutation vector in this example), likely related to `copy` ops in the optimized HLO. These copies seem unnecessary and likely hurt performance.

![image](https://user-images.githubusercontent.com/3757431/109844900-6ec2be00-7c01-11eb-8b27-684657e71a64.png)


[1614762065673455.module_0000.before_optimizations.txt](https://github.com/google/jax/files/6077830/1614762065673455.module_0000.before_optimizations.txt)
[1614762065673455.module_0000.after_optimizations.txt](https://github.com/google/jax/files/6077831/1614762065673455.module_0000.after_optimizations.txt)
[1614762065673455.module_0000.after_optimizations-buffer-assignment.txt](https://github.com/google/jax/files/6077832/1614762065673455.module_0000.after_optimizations-buffer-assignment.txt)

**Comment by mattjj** [comment]
Wow interesting. Thanks so much for investigating the unrolling option.

@hawkinsp any thoughts on what XLA:GPU could do?

**Comment by hawkinsp** [comment]
I think we're going to have to give in and hand-write a kernel for this operation until such time as XLA/GPU improves. It's sort of a worst case for XLA on GPU: loopy code, very low compute intensity in the loop.

**Comment by ahoenselaar** [comment]
TF has [implemented a kernel](https://github.com/tensorflow/tensorflow/blob/dec8e0b11f4f87693b67e125e67dfbc68d26c205/tensorflow/core/kernels/linalg/lu_op_gpu.cu.cc#L39) for this very purpose.

**Comment by sebffischer** [comment]
@mattjj was there some progress on speeding up loops in XLA:GPU or is this custom call still needed?

**Comment by mattjj** [comment]
I think #6337 landed it as an FFI call, and that kind of FFI call is still necessary for performance.
