### ISSUE TITLE
Allow for the creation of dummy TpuDevices in a CPU environment

### ISSUE THREAD

**Issue by alewis** [google/jax#5916]
In a TPU environment, Jax currently provides a lot of useful information for distributed computing via the `TpuDevice` class; e.g.

```TpuDevice(id=0, host=0, coords=(0,0,0), core_on_chip=0)```

All of these fields are useful information. Unfortunately it is difficult to develop code which uses them, since they are not available in a non-TPU environment set up by setting e.g.   `os.environ["XLA_FLAGS"] = "--xla_force_host_platform_device_count=8" `.

Would it be possible to create a means to assign the relevant information to such a spoofed environment?

**Comment by froystig** [comment]
It wouldn't make sense to do this in jax, since those fields lack meaning in non-TPU context, even with that XLA flag. Meanwhile, making a Python object with fields of your choosing seems like it ought to be straightforward to set up in your own code.

Please reopen if I've misunderstood the request!
