### ISSUE TITLE
SLSQP for jax.scipy.optimize

### ISSUE THREAD

**Issue by JiahaoYao** [google/jax#6038]
currently, `jax.scipy.optimize` only supports `BFGS`. I wonder when `SLSQP` solver will be shipped? if not in the near time, I wonder how hard to transfer [slsqp](https://github.com/scipy/scipy/blob/e7b39b5b56e866c25cabda18a5dd43bf8f39c5f4/scipy/optimize/slsqp.py) to jax? Do we need to rewrite the [fortran code](https://github.com/scipy/scipy/blob/e7b39b5b56e866c25cabda18a5dd43bf8f39c5f4/scipy/optimize/slsqp/slsqp_optmz.f)? 

Thanks so much for any feedback!

**Comment by shoyer** [comment]
Yes, this would be interesting to consider supporting constrained optimization in `jax.scipy.optimize`. In general, yes, the solvers would need to get ported/rewritten in JAX to be suitable for inclusion in JAX proper. One concern with SciPy's SLSQP in particular is that I believe it does not scale to large problems, due to building up an explicit Jacobian. The `trust-constr` method is a newer one and likely better one, that I believe has a pure Python implementation (see https://github.com/antonior92/ip-nonlinear-solver).

My general impression is that techniques for constrained optimization are more specialized than non-constrained optimization, and more of an active research area. In this regard, it might be something better reserved for specialized libraries (e.g., a JAX wrapper of cvxpy: https://github.com/cvxgrp/cvxpylayers/issues/7). I am certainly not well-qualified to review such code, though I can read Nocedal's book as well as anyone else ;).

Ping @mblondel, in case he has anything to add :)

**Comment by JiahaoYao** [comment]
Thanks @shoyer, very much appreciate your comments! Thanks for pointing out the new implementation! Seem like easier to transfer to jax than the FORTRAN code. 

I also appreciate the jax cvxpy! Yea, thanks a lot. I am also interested if there is something need to contribute to hopefully with some guidance!

**Comment by mblondel** [comment]
No opinion on SLSQP, I never used it. Maybe @fabianp has an opinion.

**Comment by JiahaoYao** [comment]
close this issue because of no updates. and we can reopen if necessary.
