### ISSUE TITLE
Debugging nan when using 'pmap'

### ISSUE THREAD

**Issue by Ranapop** [google/jax#6044]
I was trying to set up error propagation by returning nan values as explained in this [issue](https://github.com/google/jax/issues/4257) and I noticed that to make it work for a _pmap_-ed function I also need to _jit_ it.

So something like this doesn't give me an error:
```python
from jax.config import config
config.update("jax_debug_nans", True)

@jax.pmap
def my_func(x):
  return jnp.nan

x = jnp.zeros((1,))
y = my_func(x)
```

While by adding `jax.jit` I get the error (which is what I want): 
```python
from jax.config import config
config.update("jax_debug_nans", True)

@jax.jit
@jax.pmap
def my_func(x):
  return jnp.nan

x = jnp.zeros((1,))
y = my_func(x)
```

So basically a _pmap_-ed function doesn't behave as a _jit_-ed function or a plain function in regards to debugging nans with `jax_debug_nans`. Adding `jax.jit` is an easy fix but I think it would help if this was documented, maybe [here](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#Debugging-NaNs) somewhere. Personally it took me quite a bit of time to figure out what was going on.

**Comment by skye** [comment]
We should just make `jax_debug_nans` work with pmap (and also `jax_debug_infs` while we're at it). pmap is generally supposed to work like jit + the parallel mapping, and we also generally don't recommend wrapping pmap in jit since it can result in extra data transfers. I'll work on a fix, thanks for reporting!
