### ISSUE TITLE
Inconsistent output from documentation for hessian

### ISSUE THREAD

**Issue by jkitchin** [google/jax#637]
I was trying to follow this example:

https://jax.readthedocs.io/en/latest/jax.html#jax.hessian

And  I don't get the same output as it suggests. Instead I get "DeviceArray{float32[2,2]}". It seems related to issue #173, but I would have thought the documentation would work as advertised. I had some similar issues in https://colab.research.google.com/github/google/jax/blob/master/notebooks/autodiff_cookbook.ipynb#scrollTo=fuz9E2vzro5E

```
import jax
g = lambda x: x[0]**3 - 2*x[0]*x[1] - x[1]**6
jax.hessian(g)(jax.numpy.array([1., 2.]))
```

#+RESULTS:
:results:
# Out [11]:
# text/plain
: DeviceArray{float32[2,2]}
:end:

I am pretty sure I am running the latest jax version:
```
print(jax.version.__version__)

import sys
print(sys.version)
```

#+RESULTS:
:results:
# Out [20]: 
# output
0.1.25
3.6.0 |Anaconda custom (x86_64)| (default, Dec 23 2016, 13:19:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]

:end:

Any ideas?

**Comment by mattjj** [comment]
Thanks for raising this!

We recently changed how these DeviceArray types are printed in a repl (i.e. we recently changed their `__repr__` method). DeviceArray is effectively a subclass of numpy.ndarray that is backed by device memory (e.g. GPU memory when you're using a GPU, or just CPU memory that XLA controls when using the CPU backend). When we wrote the documentation we had `__repr__` set up to print it out just like a regular ndarray, but we decided to make `__repr__` print out this other representation because (1) it's more explicit and less magical and (2) it avoids copying back to host memory.

This is a documentation bug on our end, in that we should update the docstring to be less confusing.

**Comment by jkitchin** [comment]
I see, if I print it, then it shows the values. Here is another confusing one to me.

```
def loss2(params_dict):
    preds = predict(params_dict['W'], params_dict['b'], inputs)
    label_probs = preds * targets + (1 - preds) * (1 - targets)
    return -np.sum(np.log(label_probs))

print(grad(loss2)({'W': W, 'b': b}))
g = grad(loss2)({'W': W, 'b': b})

print(g['W'])
```

#+RESULTS:
:results:
# Out [33]: 
# output
{'W': DeviceArray{float32[3]}, 'b': DeviceArray{float32[]}}
[-0.16965586 -0.8774649  -1.4901347 ]

:end:

**Comment by mattjj** [comment]
That reminds me, I think a few days ago we had a discussion in chat that the reason I labeled (1) above was the better one, and (2) wasn't important. A consequence is that we could have the `__repr__` method on DeviceArrays still print the full value, but indicate that they're DeviceArrays (as distinct from regular ndarrays). I'll take a stab at that, though we might continue to fiddle with the exact behavior.

**Comment by mattjj** [comment]
We now call into NumPy's own `array_repr` function, so the `__repr__` behavior should be pretty familiar. (Your second example calls `__repr__` because Python has the weird quirk of calling `__repr__` on the values in a tuple/list/dict container even when you call `__str__` on the container itself!)
