### ISSUE TITLE
Case where grad shape is wrong

### ISSUE THREAD

**Issue by Joshuaalbert** [google/jax#6452]
I have come across a case where `grad` of a scalar with respect to another scalar gives a vector. I have noticed at least one place where if you change the code you get a scalar (indicated by the fail clause).

- [x] Check for duplicate issues.
- [x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

```python
from jax import numpy as jnp, vmap, value_and_grad

FAIL = True


def f2(y, z):
    v1 = z
    v2 = jnp.sum(y) + z

    if FAIL:
        return jnp.logaddexp(v1, v2)
    else:
        return v1 + v2


def f1(y, z):
    v = vmap(lambda _y: f2(_y, z))(y)
    return jnp.sum(v)


if __name__ == '__main__':
    y = jnp.ones((3, 2))
    f = lambda z: f1(y, z)
    z = 0.1
    val, g = value_and_grad(f)(z)
    print(val.shape, g.shape)
    assert val.shape == ()
    assert g.shape == ()

```

``` python
jax.__version__ = 0.2.9
jaxlib.__version__ = 0.1.61
```

**Comment by Joshuaalbert** [comment]
Also confirmed it's still a bug in jax 0.2.12 and jaxlib 0.1.65

**Comment by mattjj** [comment]
Thanks for raising this!

If we put a `with jax.enable_checks(True)`  context around the `value_and_grad` call, we catch the error earlier, in the AD backward pass.

There was a shortcut that Dougal and I took when we first wrote the AD machinery, and this bug is a repercussion of it. The shortcut has to do with how broadcasting is handled. Basically, we disallowed implicit broadcasting in JVP rules, meaning broadcasting built into primitives so that `z:f32[3] = lax.mul(x:f32[], y:f32[3])` is well-typed. Instead, we required explicit broadcasting in JVP rules, so that we didn't have to worry about inserting reduce-sums in all broadcasting primitives' transpose rules.

This worked fine, though it was a little annoying because we had to make JVP rules call explicit broadcasts rather than relying on implicit broadcasting. But at least it was just internal code. Then when we added `custom_jvp`, this subtle requirement was exposed to users, though surprisingly it hasn't come up too much. But this bug shows us something more insidious: an interaction between `vmap` and `custom_jvp` (there's a `custom_jvp` on `logaddexp`) which is violating this no-implicit-broadcasts-in-JVP-rules requirement! (Basically because the `vmap` rule for `mul` likes to rely on implicit broadcasts.)

I can think of some quick fixes, but maybe this is the time to get rid of this shortcut once and for all...

In the meantime, if you need a workaround, I know this is dumb but it's the first thing that came to mind:

```python
def f2(y, z):
    v1 = z
    v2 = jnp.sum(y) + z

    if FAIL:
        return jnp.logaddexp(v1 + 0*v2, v2 + 0*v1)  # dumb workaround
    else:
        return v1 + v2
```

**Comment by Joshuaalbert** [comment]
Thanks Matt, i really appreciate the time you spend to share the how-and-why on things like this.

**Comment by mattjj** [comment]
Here's [an ancient TODO](https://github.com/google/jax/blob/f65a327c764406db45e95048dfe09209d8ef6d37/jax/_src/lax/lax.py#L2170-L2184) about this issue. We actually now have available all the info we need to solve this well...

**Comment by Joshuaalbert** [comment]
Wonderful!

**Comment by Joshuaalbert** [comment]
Regarding the temporary work-around you propose, I find it's not working. I heavily reduced a large algorithm to a MVCE and it appears that simply making that change to where one of the `logaddexp` appears is not sufficient. I suppose there are other cases of `custom_jvp`'s interacting with `vmap`'s elsewhere in the algorithm.

**Comment by mattjj** [comment]
I think I can get you a better fix sometime today.

**Comment by Joshuaalbert** [comment]
Also if you try wrapping with jit you get
```python
val, g = jit(value_and_grad(f))(z)
```
it gives `TypeError: No xla_result_handler for type: <class 'jax.core.UnshapedArray'>`.

Wrapping with jit gives the correct shape if the argument is at least 1d,
```python
val, g = jit(value_and_grad(f))(jnp.atleast_1d(z))
#g.shape -> (1,)
```
I haven't verified if the value of the gradient is correct though in this case.

**Comment by mattjj** [comment]
#6470 should fix this once and for all.

Would you be up for checking out that branch and verifying if it works with your codebase?

**Comment by Joshuaalbert** [comment]
#6470 fixed it in both the MVCE and the larger algorithm.
