### ISSUE TITLE
Jit behaviour with named tuples.

### ISSUE THREAD

**Issue by GJBoth** [google/jax#6455]
Hi,
I'm working on implementing some basic sparse matrix - dense vector multiplication for my project. As a first step, I implemented it using the coordinate list approach, and implemented it like this:
```
def sparse_mat_vec_mul_slow(sparse_mat: Union[COO, ], vec: jnp.ndarray):
    """Performs sparse matrix - dense vector multiplication"""
    return _sparse_mat_vec_mul_slow(sparse_mat, vec, sparse_mat.shape[0])

@partial(jax.jit, static_argnums=(2, ))
def _sparse_mat_vec_mul_slow(sparse_mat: Union[COO, ], vec: jnp.ndarray, shape: Sequence[int]):
    """Performs sparse matrix - dense vector multiplication"""
    prod = jnp.take(vec, sparse_mat.cols, axis=0) * sparse_mat.vals[:, None]
    return jax.ops.segment_sum(prod, sparse_mat.rows, shape)
```

where `sparse_mat` is a NamedTuple (mypy version) which contains the row indices, column indices, values and shape. If instead of giving my namedtuple to the inner function, I expand it in the outer function like this:
```
def sparse_mat_vec_mul_fast(sparse_mat: Union[COO, ], vec: jnp.ndarray):
    """Performs sparse matrix - dense vector multiplication"""
    return _sparse_mat_vec_mul_fast(*sparse_mat[:3], vec, sparse_mat.shape[0])

@partial(jax.jit, static_argnums=(4, ))
def _sparse_mat_vec_mul_fast(rows, cols, vals, vec, shape):
    """Performs sparse matrix - dense vector multiplication"""
    prod = jnp.take(vec, cols, axis=0) * vals[:, None]
    return jax.ops.segment_sum(prod, rows, shape)
```
I see a 2-3 times speed up! [Here](https://colab.research.google.com/drive/1-ZblBhwvpLWSkB56WmNGBd2VTiTC1tyO?usp=sharing)'s anotebook recreating the issue. Is jit struggling with namedtuples? Should I always expand them in an inner function as best practice, or am I missing something else?

**Comment by jakevdp** [comment]
Good question! The issue here is that when you pass a `NamedTuple` to a function, the tuple is flattened and *all* its contents are passed to the function. This includes the `shape`, which is a tuple on the host that needs to be pushed to the device when passed as an argument.

To make the fast version the equivalent of the slow version, you can write it this way:
```python
def sparse_mat_vec_mul_not_so_fast(sparse_mat: Union[COO, ], vec: jnp.ndarray):
    """Performs sparse matrix - dense vector multiplication"""
    return _sparse_mat_vec_mul_not_so_fast(*sparse_mat[:4], vec, sparse_mat.shape[0])

@partial(jax.jit, static_argnums=(5, ))
def _sparse_mat_vec_mul_not_so_fast(rows, cols, vals, unused_shape, vec, shape):
    """Performs sparse matrix - dense vector multiplication"""
    prod = jnp.take(vec, cols, axis=0) * vals[:, None]
    return jax.ops.segment_sum(prod, rows, shape)
```
You should see that it's execution is comparable to the slow version, because each time it's called it involves essentially calling `jax.device_put(sparse_mat.shape)` which has some overhead.

If you want to make your slow version avoid pushing the shape to device when used in a jitted function, you can register it as a custom pytree class with functions that define how it should be flattened; see https://jax.readthedocs.io/en/latest/pytrees.html#extending-pytrees for examples.

**Comment by GJBoth** [comment]
Thanks for the explanation, that makes a lot of sense. I tried turning shape into a `devicearray`, but that doesn't work either because it can't be a static argument in that case.  Making a custom pytree class is a good suggestion, but it's definitely looks like a lot of effort for something I have working already. Are there any other goodies I'd get by doing this, or is it just writing slightly more concise?

**Comment by GJBoth** [comment]
Thanks! Guess I was a little intimidated by the documentation, but I guess I'll spend some more time looking into pytrees etc. Related to this - do you know of a (centralized) effort to implement sparse matrices in Jax? I'm working on implementing compressed sparse row and columns, and I'd be happy to contribute it somewhere.

**Comment by jakevdp** [comment]
Yes! #6429 is an initial effort to add some low-level primitives that support sparse operations and lower to cusparse on GPU (the PR looks a bit weird because it's auto-generated from a set of changes that touches multiple code-bases). I'm still not sure what form the higher-level representation will take: we're hoping to start exploring how sparse operations interact with autodiff and think about what representation would be best.

**Comment by jakevdp** [comment]
Regarding the extra benefit of this registration: I believe it should allow you to access `A.shape` as a static value within the jitted computation, so you wouldn't need to explicitly pass the shape to the jitted function. I'm about 70% sure of that... I'd have to try it to be more confident.

**Comment by GJBoth** [comment]
That sounds neat - I wouldn't need the inner / outer function construction and that would be great! I'll try it tomorrow and let you know the results.

**Comment by jakevdp** [comment]
#6429 has landed, so in the master branch you can find sparse-related primitives in `jax.experimental.sparse_ops`.

**Comment by jakevdp** [comment]
See also related work here: #6466

**Comment by GJBoth** [comment]
> Regarding the extra benefit of this registration: I believe it should allow you to access `A.shape` as a static value within the jitted computation, so you wouldn't need to explicitly pass the shape and mark it as static. I'm about 70% sure of that... I'd have to try it to be more confident.

Turn that into 100% - you're right!  This makes it much nicer, thanks a lot!
For future reference, this works:

```
class COO(NamedTuple):
    """Defines a namedtuple for coordinate list sparse matrix (COO)."""

    rows: jnp.ndarray
    cols: jnp.ndarray
    vals: jnp.ndarray
    shape: Sequence[int]


def _coo_flatten(A):
    return A[:3], A[3]


def _coo_unflatten(aux_data, children):
    return COO(*children, aux_data)


register_pytree_node(COO, _coo_flatten, _coo_unflatten)

@jax.jit
def sparse_mat_vec_mul(sparse_mat: Union[COO, ], vec: jnp.ndarray):
    """Performs sparse matrix - dense vector multiplication"""
    prod = jnp.take(vec, sparse_mat.cols, axis=0) * sparse_mat.vals[:, None]
    return jax.ops.segment_sum(prod, sparse_mat.rows, sparse_mat.shape[0])
```
