### ISSUE TITLE
Minor typing issue

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#6473]
```python
import jax.numpy as jnp
x: jnp.ndarray = jnp.zeros(10)
y = x.reshape((10,))
reveal_type(x)  # a.py:4: note: Revealed type is 'jax._src.numpy.lax_numpy.ndarray'
reveal_type(y)  # a.py:5: note: Revealed type is 'numpy.ndarray'
x = y  # error: Incompatible types in assignment (expression has type "numpy.ndarray", variable has type "jax._src.numpy.lax_numpy.ndarray")
```

**Comment by jakevdp** [comment]
Thanks for the report! I suspect you'll find this issue barely scratches the surface of the typing issues in `jax.numpy`; almost none of the functions therein are accurately typed, mainly because the effort is blocked by fundamental limitations in the expressivity of Python type annotations (see e.g. #943)

**Comment by NeilGirdhar** [comment]
@jakevdp Yeah, no worries.  I figured it was a ways off.  Should I close this issue in favor of #943?
