### ISSUE TITLE
Unbounded memory growth on CPU

### ISSUE THREAD

**Issue by ikostrikov** [google/jax#6520]
I'm experiencing unbounded memory growth with a recent version of Jax. I've tested it locally and on colab.

```python
import os
import sys

import jax
import numpy as np
import psutil
from jax.interpreters import xla
import gc


@jax.jit
def fn(inputs: np.ndarray):
    return inputs.mean()

dataset = np.random.uniform(size=(10000, 100))

for i in range(1000000):
    indx = np.random.randint(len(dataset), size=256)
    inputs = dataset[indx]

    fn(inputs)

    if i % 1000 == 0:
        mem_info = psutil.Process(os.getpid()).memory_info()
        print(
            f'{i}, Real: {mem_info.rss/1e9}GB, Virtual: {mem_info.vms/1e9}GB'
        )

        # Doesn't help:
        # xla._xla_callable.cache_clear()

        # Doesn't help either: 
        # gc.collect()
```

Output for jax==0.2.9, jaxlib==0.1.59:

```bash
0, Real: 0.223453184GB, Virtual: 1.349890048GB
10000, Real: 0.226828288GB, Virtual: 1.353035776GB
20000, Real: 0.226828288GB, Virtual: 1.353035776GB
30000, Real: 0.226828288GB, Virtual: 1.353035776GB
40000, Real: 0.227098624GB, Virtual: 1.353035776GB
50000, Real: 0.22736896GB, Virtual: 1.353035776GB
60000, Real: 0.22736896GB, Virtual: 1.353035776GB
70000, Real: 0.22736896GB, Virtual: 1.353035776GB
80000, Real: 0.22736896GB, Virtual: 1.353035776GB
90000, Real: 0.22736896GB, Virtual: 1.353035776GB
```

Output for jax==0.2.12, jaxlib==0.1.65:
```bash
0, Real: 0.22757376GB, Virtual: 1.38182656GB
10000, Real: 1.257865216GB, Virtual: 2.451111936GB
20000, Real: 2.28675584GB, Virtual: 3.519348736GB
30000, Real: 3.316105216GB, Virtual: 4.587585536GB
40000, Real: 4.345274368GB, Virtual: 5.664210944GB
50000, Real: 5.373984768GB, Virtual: 6.731399168GB
60000, Real: 6.402883584GB, Virtual: 7.799635968GB
70000, Real: 7.4320896GB, Virtual: 8.868921344GB
80000, Real: 8.460988416GB, Virtual: 9.936371712GB
90000, Real: 9.490153472GB, Virtual: 11.01299712GB
```

**Comment by hawkinsp** [comment]
I'm fairly confident this bug has already been fixed by 
https://github.com/tensorflow/tensorflow/commit/2d6b33192c77c07661e5c7e01fef27ac28abd10a#diff-bd82809509b3b2b02607b18fecebefec12e3e43e733afb7b0cce391ff07b37b0

We'll need to make a new jaxlib release for you to get the fix (or you would need to build jaxlib from head), but the bug requires a very specific set of circumstances to reproduce: you need to:
a) pass classic NumPy arrays, and
b) only call a jit-ted function, without doing most other actions.

You can work around (a) by calling `jax.device_put` on your array first, and you can work around (b) by doing many things, for example, calling `.block_until_ready()` on any JAX arrays will trigger a garbage collection.

**Comment by hawkinsp** [comment]
I verified this bug is fixed with XLA from head. #6528 updates XLA to make sure that fix is part of any jaxlib built from head.

**Comment by hawkinsp** [comment]
I would expect that we will make a new jaxlib release in the next week or so including this fix. Hope that helps!

**Comment by ikostrikov** [comment]
Thanks a lot! I will be using the older versions in meanwhile.
