### ISSUE TITLE
Issue better error message when jax.numpy.pad() pad_widths mismatches array rank

### ISSUE THREAD

**Issue by jurahul** [google/jax#6605]
The following JAX code:

```
    y = jnp.pad(jnp.zeros((2,2)), [[0,0],[0,0],[0,0]], mode='wrap')
```
given an error:

```
ValueError: pad_width given unexpected structure: [[0 0]
 [0 0]
 [0 0]]. See docstring for valid pad_width formats.
```
This is because the length of the pad_widths list needs to match the rank of the array. Can we make this error message more explicit?

**Comment by jakevdp** [comment]
It would certainly be possible to be more explicit, but in this case it's tricky because there are so many possible reasons that the input is invalid. Here is the chain of options: https://github.com/google/jax/blob/9c63c772a97623453aecc0680dd4601cc8aa107a/jax/_src/numpy/lax_numpy.py#L2639-L2656

It's tough to guess what the user intended when there are so many possible correct inputs. Maybe in this case we could raise a more specific error if `nvals.ndim == 2 and nvals.shape[1] == 2 and nvals.shape[0] not in (1, nd)`. What do you think?

**Comment by mattjj** [comment]
One simple thing might be just to report `np.ndm(x)` in the error message.
