### ISSUE TITLE
Disable warning for No GPU/TPU found

### ISSUE THREAD

**Issue by altosaar** [google/jax#6805]
Minor idea - would be nice to be able to disable this warning for debugging ease:

`WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)`

The only place I found a reference to this was in this colab: https://colab.research.google.com/github/google/jax/blob/master/docs/notebooks/quickstart.ipynb#scrollTo=ehUS7s8xKkxK

```
# Execute this to consume & hide the GPU warning.
jnp.arange(10)
```

Which doesn't work outside of a notebook.

I tried using `export TF_CPP_MIN_LOG_LEVEL=3`, `import os; os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'` - any other ideas how to suppress? 

Thanks so much!

**Comment by mattjj** [comment]
If you intend to use the CPU, it is a bit annoying!

Here are two ways to suppress it:
1. set the shell environment variable `JAX_PLATFORM_NAME=cpu`
2. near the top of your main file, write `import jax; jax.config.update('jax_platform_name', 'cpu')`

Either of those things will tell JAX that you intend to use the CPU, so it won't warn about only having a CPU available.

**Comment by altosaar** [comment]
Awesome thanks so much Matt! That worked :)

**Comment by wookayin** [comment]
> 1. set the shell environment variable `JAX_PLATFORM_NAME=cpu`
> 2. near the top of your main file, write `import jax; jax.config.update('jax_platform_name', 'cpu')`
> 
> Either of those things will tell JAX that you intend to use the CPU, so it won't warn about only having a CPU available.

The name of config has changed from `jax_platform_name` to `jax_platforms`, so this will not work as of now (jax 0.3+)

The new way:

1. set the shell environment variable `JAX_PLATFORMS=cpu`
2. near the top of your main file, write `import jax; jax.config.update('jax_platforms', 'cpu')`

But many thanks @mattjj for the workaround!

**Comment by hawkinsp** [comment]
We deprecated `jax_platform_name` in place of `jax_platforms`. So I recommend using the new name.

**Comment by mattjj** [comment]
Indeed! I'm just clarifying that it does still work as of jax 0.3+. (Also it doesn't have a deprecation message...)

**Comment by wookayin** [comment]
@mattjj  Oh I see. The OP's concern was how to disable warnings, which works with the deprecated name `jax_platform_name` as well as the new name `jax_platforms` (I didn't know that). My case was about **how to disable GPU**, which however does not work with `jax_platform_name` (I came across this issue after Googling).

This is because of the line (`if FLAGS.jax_platforms:`) from line from: https://github.com/google/jax/blob/main/jax/_src/lib/xla_bridge.py#L235 -- the changeset adcab940b7894e0cb04a99fe291dfa81a68f817c turns out to be something more than a deprecation as the behavior is not exactly the same.

So the bottom-line is we should always use `jax_platforms`. It'd be up to you whether jax will make `jax_platform_name` work as well for disabling GPU, despite deprecation.

**Comment by soraros** [comment]
The new spelling `jax.config.update('jax_platforms', 'cpu')` alone doesn't seem to suppress the warning. Is that expected or did I miss something?

**Comment by bwohlberg** [comment]
The new name is not working for me:
```
$ python -c 'import jax; print(jax.__version__)'
0.3.6
$ python -c 'import jax; jax.config.update("jax_platform_name", "cpu"); jax.numpy.add(1, 1)'
[No warning]
$ python -c 'import jax; jax.config.update("jax_platforms", "cpu"); jax.numpy.add(1, 1)'
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
```

**Comment by mattjj** [comment]
Yeah, that seems buggy... we'll look into it!

**Comment by mattjj** [comment]
This should fix the issue: https://github.com/google/jax/pull/10272

**Comment by bwohlberg** [comment]
Could you please consider adding a mechanism for suppressing the warning that does not also disable GPU usage? The warning makes it quite painful to write warning-free code for both CPU and GPU platforms, and it's an absolute nightmare when using `jax` with `ray` because the warning gets spewed with every new process.

Or even better, just remove the warning. Considering that `jax` is supported on CPU-only platforms, so that usage without a GPU available is not unusual usage, it's not even clear that the warning actually fulfills any useful purpose.

**Comment by bwohlberg** [comment]
@mattjj: A reminder on the request to allow the no-GPU warning to be suppressed *independently* of forcing use of the CPU. For our [usage case](https://github.com/lanl/scico) case, at least, we would like to be able write code that transparently runs on a GPU when one is available, but otherwise reverts to CPU. The coupling of the warning and the device selection mechanism makes it very difficult to achieve this. It's also worth asking whether there's really a good argument for ever emitting the warning. For example, since GPU use is not supported on any recent OSX platforms, running with a CPU only would seem to be perfectly normal usage that doesn't warrant a warning.

**Comment by nalzok** [comment]
I second @bwohlberg's suggestion. We can instead respect an environment variable `JAX_EXPECT_PLATFORMS`. For example, if we have `JAX_EXPECT_PLATFORMS=gpu,tpu` then JAX should emit a warning when it falls back to CPU.

**Comment by Karl-Krauth** [comment]
@bwohlberg you can filter out the warning directly from the logging library. This won't print any warning:
```python
import logging
import jax.numpy as jnp
logging.getLogger("absl").addFilter(logging.Filter("No GPU/TPU found, falling back to CPU."))
jnp.arange(10)
```

**Comment by bwohlberg** [comment]
@Karl-Krauth: Thanks for the suggestion. For the most recent  version (0.4.2) of jax, this has to be
```python
import logging
import jax.numpy as jnp
logging.getLogger("jax._src.lib.xla_bridge").addFilter(logging.Filter("No GPU/TPU found, falling back to CPU."))
jnp.arange(10)
```
I'm not sure at which `jax` version the change occurred.

**Comment by bwohlberg** [comment]
It is worth pointing out, though, that, while useful, this is still a workaround. It would be preferable for JAX to implement a coherent   mechanism that doesn't combine the independent concepts of device selection and warning suppression in a way that complicates writing device-independent code.

**Comment by carlosgmartin** [comment]
I second @bwohlberg's proposal to drop the warning entirely. Perhaps this should be opened as an issue?

**Comment by bwohlberg** [comment]
> @Karl-Krauth: Thanks for the suggestion. For the most recent version (0.4.2) of jax, this has to be
> 
> ```python
> import logging
> import jax.numpy as jnp
> logging.getLogger("jax._src.lib.xla_bridge").addFilter(logging.Filter("No GPU/TPU found, falling back to CPU."))
> jnp.arange(10)
> ```

This no longer works in jax 0.4.8.

**Comment by hawkinsp** [comment]
@bwohlberg The file moved, it's `jax._src.xla_bridge`, but yeah let's drop the warning.

**Comment by jpiabrantes** [comment]
I am getting all these logs:

```sh
2024-01-27 16:01:32.822185: W pjrt_plugin/src/mps_client.cc:563] WARNING: JAX Apple GPU support is experimental and not all JAX functionality is correctly supported!
Metal device set to: Apple M1

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

Metal device set to: Apple M1
```

Any idea on how to disable them?

I've tried
```python
logging.getLogger("jax._src.xla_bridge").setLevel(logging.ERROR)
```

Did not work.
