### ISSUE TITLE
allow general pytrees in jvp

### ISSUE THREAD

**Issue by akssri** [google/jax#6828]
currently the primal and tangent args for  jax.jvp are limited to lists/tuples. 

support for general pytrees will help in not having to do the tree-flatten/unflatten manually.
this is esp. useful for frameworks like haiku which use dict-like structures for params.

_jvp already does tree-flatten/unflatten but general trees are disallowed here (for reasons as yet unclear),
https://github.com/google/jax/blob/master/jax/_src/api.py#L1754

**Comment by mattjj** [comment]
Hey @akssri!

Actually, [pytrees are allowed with `jvp`](https://github.com/google/jax/blob/d81a13cceafe765ee6ebbf3ebe2098ac4fe246d1/jax/_src/api.py#L1759-L1760). But the primals and tangents must be lists or tuples of pytrees. That just comes from the fact that Python functions can in general take multiple arguments, so that if for a function `f` you can evaluate `f(*xs)` then you can call `jvp` like `jvp(f, xs, xs)`.

Here's an example of using pytrees with `jvp`:

```python
In [1]: from jax import jvp

In [2]: def f(x, y):
   ...:     return x['hi'] + y['foo']
   ...:

In [3]: f({'hi': 1.}, {'foo': 2.})
Out[3]: 3.0

In [4]: jvp(f, [{'hi': 1.}, {'foo': 2.}], [{'hi': 3.}, {'foo': 4.}])
Out[4]: (DeviceArray(3., dtype=float32), DeviceArray(7., dtype=float32))
```

WDYT?

**Comment by akssri** [comment]
ah! this makes sense. thanks for clarifying @mattjj ! sorry for the trouble - i probably didn't pass the arguments properly when i was testing things out.

**Comment by mattjj** [comment]
No trouble at all! We like answering questions :)
