### ISSUE TITLE
Functions claim to return a view but return a copy

### ISSUE THREAD

**Issue by lukepfister** [google/jax#6831]
My understanding is the immutable-array policy means that `jnp` functions (eg, `transpose`) return a copy of an array, rather than a view. 

There are a few places in the docs where a function claims to return a view:  [atleast_2d](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.atleast_2d.html#jax.numpy.atleast_2d) and [atleast_3d](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.atleast_3d.html#jax.numpy.atleast_3d) state it in the top line of the docstring.   

Other functions, like [ravel](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ravel.html) or [transpose](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.transpose.html), have some verbiage about returning a view where possible in the "original docstring below" portion.  I suppose this is inevitable if the docstring is copied directly from the numpy functions.  

Perhaps the view/copy distinction could be added to the bulleted list in the `jax.numpy` [API doc page ](https://jax.readthedocs.io/en/latest/jax.numpy.html)?

**Comment by jakevdp** [comment]
Thanks -  the key phrase there (admittedly easy to miss) is *Original docstring below.*

Rather than creating new docstrings for all numpy/scipy functions, JAX wraps the original numpy/scipy docstrings, with automated modifications to the extent that is possible. This means that some details about the implementation will differ.

There's not really any way to fix this without rewriting all the docstrings from scratch, and the cost/benefit tradeoff has so far not favored that.

**Comment by jakevdp** [comment]
Updating the API doc page is a good idea

**Comment by jakevdp** [comment]
Hey, sorry, I realized I didn't read your initial report very closely... I guess I shouldn't be responding to issues so late in the day 😬 

Along with the change in #6836, I think we could also add an extra doc note to the particular functions you mention, where the incorrect information is in the top-line function description. I'll get on that as well.
