### ISSUE TITLE
Need a way to specify constants

### ISSUE THREAD

**Issue by remifan** [google/jax#6853]
I have a use case to jit a function that does slicing depending on a `dict` arguments
```
@jit
def foo(x, d: dict):
  return x[:d['num']] + d['val']

foo(jnp.arange(10), {'num': 5, 'value': np.arange(5)})
```
no surprise I got _IndexError: Array slice indices must have static start/stop/step to be used with NumPy indexing syntax._

static_argnums is yet not working as expected since I have an array in `d`
```
@partial(jit, static_argnums=1)
def foo(x, d: dict):
  return x[:d['num']] + d['val']

foo(jnp.arange(10), {'num': 5, 'value': np.arange(5)})
```
I got _ValueError: Non-hashable static arguments are not supported._

Here is a working dirty trick
```
@jit
def bar(x, d: dict):
  return x[:d['num'].shape[0]] + d['val']

bar(jnp.arange(10), {'num': jnp.zeros((5, 0)), 'val': np.arange(5)})
```
I got `DeviceArray([0, 2, 4, 6, 8], dtype=int32)`

Is there a way to specify argument `d['num']` as constant? 

The above weird use case is more reasonable in Flax whose variables are collected as a dict input.

**Comment by jakevdp** [comment]
Hi - thanks for the detailed report! Unfortunately, the `static_argnums` mechanism currently does not have enough granularity to achieve what you want. There's a bit of effort recently in this direction (see #6273) but the situation you have is not yet cleanly handled.

There are a couple options that might be suitable currently:

- use a jitted helper function where static parameters are passed as positional arguments
- represent your data as a custom type with a [custom pytree](https://jax.readthedocs.io/en/latest/pytrees.html#extending-pytrees) flattening that puts static parameters into `aux_data`

Let me know if that's unclear – I could provide an example if it would be helpful.

**Comment by remifan** [comment]
Thanks for the suggestions! It's great to hear there is an effort in supporting such granularity.
I have just learnt those 2 options you mentioned by following Jax's source codes, and it's very helpful at this moment.
Look forward to seeing further progress!

**Comment by NeilGirdhar** [comment]
You could also use `flax.struct.dataclass` and mark `num` as `pytree_node=False`.

**Comment by remifan** [comment]
> Since you're already using flax, an easy way to represent your data as a custom type as Jake suggested would be to use `flax.struct.dataclass`:
> 
> ```python
> @flax.struct.dataclass
> class Class:
>   num: int = struct.field(pytree_node=False)
>   value: Any
> ```

Thanks for providing specific Flax solution, it is working.

**Comment by jakevdp** [comment]
It looks like this question has been answered; I'm going to close the issue. Feel free to open another if you have further questions!

**Comment by eelregit** [comment]
> There are a couple options that might be suitable currently:
> 
>     * use a jitted helper function where static parameters are passed as positional arguments
> 
>     * represent your data as a custom type with a [custom pytree](https://jax.readthedocs.io/en/latest/pytrees.html#extending-pytrees) flattening that puts static parameters into `aux_data`

This is super helpful! @jakevdp

I want to understand better the difference between the two, since I noticed that in the latter case I can actually use non-hashable `aux_data`, like a `jnp.ndarray`.
But then how JAX finds which jitted version to use?
And do you expect any difference in performance?

**Comment by jakevdp** [comment]
For any custom class Python defaults to creating a hash function based on the object ID, without reference to any of the classes members or contents:
```python
import jax.numpy as jnp

class Foo:
  def __init__(self, x):
    self.x = x

f = Foo(jnp.arange(4))
first_hash = hash(f)

f.x = jnp.ones(10)
second_hash = hash(f)

print("This is bad if True:", first_hash == second_hash)
# This is bad if True: True
```
This means that if you create a PyTree class and use it as a static argument, then mutate it, and pass it to the function again, you will get unexpected results. There's some more information & discussion of this foot-gun in this issue: https://github.com/google/jax/issues/9024

If you create a new PyTree class each time, you will have a different object (and thus a different hash) and your function will be recompiled each time you call it.

There are ways you can hack around using `jnp.ndarray` as a static argument (essentially by wrapping it in some class that defines `__hash__`), but I wouldn't recommend it because it's easy to inadvertently do the wrong thing, and this kind of problem is usually better solved by re-writing your code in a manner that conforms to typical JAX approaches.

**Comment by NeilGirdhar** [comment]
> I want to understand better the difference between the two, since I noticed that in the latter case I can actually use non-hashable

If you put non-hashable data into static fields, the JIT lookup will fail.  Jax doesn't currently give you an error for doing that yet.

>  There's some more information & discussion of this foot-gun in this issue

Another related issue #7826

**Comment by ayaka14732** [comment]
Regarding the original problem, I believe that the most straightforward solution is to change `dict` to `namedtuple`. The `dict` type is not hashable simply because it is mutable, while `namedtuple` is not.

**Comment by NeilGirdhar** [comment]
> The `dict` type is not hashable simply because it is mutable, while `namedtuple` is not.

It's not just the dictionary.  There's an array inside it, which won't be hashable even if you put it into a named tuple.

Also, in my opinion, you should avoid using named tuple as a handy container for Jax.  As convenient as it is, it's usually poor design since:
- you don't usually want to bring in iterability, and
- it doesn't allow you to specify static fields.

An augmented dataclass is better design.

Also, I may be mistaken, but I vaguely remember some thread mentioning making named tuples no longer pytrees.

**Comment by MRiabov** [comment]
I'll add that namedtuples were slower; I don't remember why, but dataclass is faster than namedtuple.
