### ISSUE TITLE
jax.lax.sign with complex input 

### ISSUE THREAD

**Issue by PhilipVinc** [google/jax#6854]
I was trying to make  `jax.scipy.special.logsumexp` work with complex valued numbers.

I stumbled upon this complex-valued `jax.lax.sign` behaviour.
It seems wrong to me.

```python
>>>import jax
>>> jax.lax.sign(jax.numpy.array(-1.3075261+1.0559573j))
DeviceArray(-0.7779765+0.6282934j, dtype=complex64)
>>> jax.lax.sign(jax.numpy.array(1.3075261+.0559573j))
DeviceArray(0.99908555+0.04275718j, dtype=complex64)
```

I expected something more akin to: 
```python
>>> jax.lax.sign(jax.numpy.array(1.0-1.0j))
DeviceArray(0.70710677-0.70710677j, dtype=complex64)
```

**Comment by jakevdp** [comment]
Thanks for the report! Agreed this is a bit unexpected, but by design `lax.sign` returns the complex phase for complex inputs (see the [docs](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.sign.html)). If you want a `sign` operation that behaves more like `np.sign`, you can try using `jnp.sign`: https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.sign.html

**Comment by PhilipVinc** [comment]
Yes indeed. Sorry for the noise.
I noticed the doc string too late...
