### ISSUE TITLE
Confusing differences between numpy and JAX type promotion

### ISSUE THREAD

**Issue by gnecula** [google/jax#6874]
The following computes an int16, as expected
```
np.int16(1) + jnp.int16(2) + 3
```

But the following computes an int32, because `3 + np.int16(1)` results in `np.int64(1)` (and if JAX_ENABLE_X64=0 this gets canonicalized to a `int32`).
```
3 + np.int16(1) + jnp.int16(2)
```

For now I will just change the documentation, but I think it is fair to classify this as a surprise.

**Comment by jakevdp** [comment]
We don’t have any control over numpy type promotion semantics, so I’m not sure what we can do here?

**Comment by gnecula** [comment]
I understand that it is not clear how to solve this. We can try to document it better, but most people would not get to that piece of documentation.

How bad would it be to treat `nd.array` the same as Python scalars? I think that then we would not have this particular problem. 

One problem that I can imagine is that it would be hard to truly control the type of the inputs, e.g., `jnp.sin(np.float16(1.))` would be the same as `jnp.sin(1.)`, and the only way to control the type of the argument would be to use `jnp.float16(1.)` or `jnp.array(1., np.float16)`.

**Comment by jakevdp** [comment]
Just to say it out loud, the issue is not that type promotion is non-associative. If you replace `a + b` with `jnp.add(a, b)` in the examples above, the results will be equivalent. Rather, the issue is that ``+`` is overloaded based on the types of the operands, and we're seeing the difference between numpy type promotion (in `np.add`) and JAX type promotion (in `jax.add`).

Fundamentally, then, this inconsistency comes from the design decision of making JAX functions polymorphic to numpy and JAX arrays. We could think about treating numpy arrays as weakly-typed, but this would still result in inconsistencies, particularly at JIT boundaries. If we wanted to be totally safe, we could make implicit casts of numpy objects to JAX objects an error – that would fix these inconsistencies, but at some cost to user convenience.

**Comment by gnecula** [comment]
> the issue is not that type promotion is non-associative.

You are right, I changed the title.

**Comment by gnecula** [comment]
I am closing this as won't fix. I mostly wanted this discussion recorded.
