### ISSUE TITLE
Run tests with CPU mode when on CPU+GPU version

### ISSUE THREAD

**Issue by tataudat** [google/jax#696]
I have built the package with 

```
python build/build.py --enable_march_native --enable_mkl_dnn --enable_cuda
pip install -e build
pip install -e .
```

I think this should build a CPU + GPU version.

When I tried to run `pytest -n 2 tests examples -W ignore`, some of the tests failed. It appeared to me that some of the functions are only support in CPU mode.

I also tried `JAX_ENABLE_X64=1 JAX_NUM_GENERATED_CASES=100 pytest -n auto tests` and `JAX_ENABLE_X64=0 JAX_NUM_GENERATED_CASES=100 pytest -n auto tests`, but neither of them worked.

**Comment by skye** [comment]
Can you share the failures you're seeing?

**Comment by mattjj** [comment]
I suspect it's that our `jtu.skip_on_devices` utility doesn't actually do anything in OSS, so things like linalg tests (which are sometimes only implemented on XLA:CPU) will just fail on GPU instead of skipping.

We should revise that helper function to check the platform name directly rather than checking whether the `jax_test_dut` flag is set.

**Comment by mattjj** [comment]
When both CPU and GPU are available and no `jax_platform_name` flag is set, we [preferentially select the GPU backend](https://github.com/tensorflow/tensorflow/blob/54421d86c9db831cb00c4e8cea3d1aeddc2ee15d/tensorflow/compiler/xla/python/xla_client.py#L167-L217). After we merge #690, you'll be able to write this to set the backend from the shell (if you have a posix shell):

```bash
JAX_PLATFORM_NAME=cpu pytest -n auto tests -W ignore
```

A second issue is that CPU-only tests were failing in OSS rather than being skipped. Our internal GPU test harnesses set the `jax_device_dut` flag, and our `skip_on_devices` helper decorator read that flag. But running tests directly via `pytest` doesn't set that flag, and so CPU-only tests weren't skipped, leading instead to the failures you saw. A commit in #690 also fixes that issue by improving the `skip_on_devices` helper to check the platform name (if `jax_device_dut` isn't set directly).

Merging #690 is going to automatically close this issue, but please ping it or reopen it if this doesn't solve the problem!

**Comment by proteneer** [comment]
Not to necro this but this seems to do trigger my non-JAX GPU code to also stop working. I'm guessing you guys are setting something like CUDA_VISIBLE_DEVICES to globally disable CUDA?

**Comment by hawkinsp** [comment]
No, we don't do anything like that. Something else must be going on. Could you file a new issue with more details? Thanks!

**Comment by proteneer** [comment]
Thanks - this is a little hard to repro because I'd have to introduce another easy-to-install library that uses the GPU.

**Comment by matthewfeickert** [comment]
> When both CPU and GPU are available and no `jax_platform_name` flag is set, we [preferentially select the GPU backend](https://github.com/tensorflow/tensorflow/blob/54421d86c9db831cb00c4e8cea3d1aeddc2ee15d/tensorflow/compiler/xla/python/xla_client.py#L167-L217). After we merge #690, you'll be able to write this to set the backend from the shell (if you have a posix shell):
> 
> ```shell
> JAX_PLATFORM_NAME=cpu pytest -n auto tests -W ignore
> ```

@mattjj So does this mean that if you want to be able to toggle using the GPU and the CPU (use case: do a performance comparison of the speedup you get with code using JAX on the GPU (without having to switch between virtual environments with two versions installed)) the preferred way of doing this is by setting the environment value? So either setting it through the Shell like you show above, or by doing

```python
import os
os.environ["JAX_PLATFORM_NAME"] = "cpu"
```

? Or is there recommended API?

**Comment by skye** [comment]
Setting JAX_PLATFORM_NAME is the best way to do this. You can also manually `device_put` values and/or use the `backend` argument to various functions like `pmap` to run things on CPU, but the env var is the best way to set the platform globally (e.g. for performance comparisons).
