### ISSUE TITLE
JAX BFGS runtime problem

### ISSUE THREAD

**Issue by joacorapela** [google/jax#6960]
This issue related to #5284. The convergence problem was indeed solved. However the runtime of JAX with JIT compilation is two orders of magnitude higher than that of scipy.optimize with autograd
The output of the code given below is (the true convergence value should be 0.0):

> scipy.optimize convergence value 3.480804300303699e-14, elapsed time: 0.033438920974731445
> jax.scipy.optimize convergence value 2.7845142136892713e-13, elapsed time: 1.173757553100586

```python
import time                                                                                                                                   
import scipy.optimize
import autograd.numpy as anp
import autograd
import jax
import jax.numpy as jnp
import jax.scipy.optimize
import jax.config

jax.config.update("jax_enable_x64", True)

def zakharov_jaxNumpy(x):
    def zakharovFromIndices(x, ii):
        sum1 = jnp.sum(jnp.power(x, 2))
        sum2 = jnp.sum(0.5*ii*x)
        answer = sum1+sum2**2+sum2**4
        return answer

    ii = jnp.arange(1, len(x)+1, step=1)
    answer = zakharovFromIndices(x=x, ii=ii)
    return answer

def zakharov_autogradNumpy(x):
    def zakharovFromIndices(x, ii):
        sum1 = anp.sum(x**2)
        sum2 = anp.sum(0.5*ii*x)
        answer = sum1+sum2**2+sum2**4
        return answer

    ii = anp.arange(1, len(x)+1, step=1)
    answer = zakharovFromIndices(x=x, ii=ii)
    return answer

jEvalFunc = zakharov_jaxNumpy
aEvalFunc = zakharov_autogradNumpy
aGradFunc = autograd.grad(aEvalFunc)

@jax.jit
def minimize_jit(x0):
    out = jax.scipy.optimize.minimize(fun=jEvalFunc, x0=x0, method="BFGS")
    return out

x0 = [600.0, 700.0, 200.0, 100.0, 90.0, 1e4]
toleranceChange = 1e-9
maxIter = 10000
jx0 = jnp.array(x0)
ax0 = anp.array(x0)

startTime = time.time()
aOptimRes_x0 = scipy.optimize.minimize(fun=aEvalFunc, x0=ax0, method='L-BFGS-B', jac=aGradFunc)
aElapsedTime = time.time()-startTime

startTime = time.time()
jOptimRes_x0 = minimize_jit(x0=jx0)
jElapsedTime = time.time()-startTime

print("scipy.optimize convergence value {}, elapsed time: {}".format(aOptimRes_x0.fun, aElapsedTime))
print("jax.scipy.optimize convergence value {}, elapsed time: {}".format(jOptimRes_x0.fun, jElapsedTime))
```

**Comment by jakevdp** [comment]
Here are some related issues where the runtime of `jax.scipy.optimize` is discussed:  #6568 #5993 #5876

The short answer is: JAX is a different implementation and may be slower than scipy in some cases.

**Comment by jakevdp** [comment]
A couple notes specific to your example:

- your `minimize_jit` timing is probably measuring compilation time rather than runtime – the Python-side runtime in your benchmark as written will be basically instantaneous because of [Asynchronous dispatch](https://jax.readthedocs.io/en/latest/async_dispatch.html) - you probably want to time `result.block_until_ready()`
- in general, JAX has some small constant overhead related to moving data from the host to device. When you benchmark against scipy for very small arrays, this overhead will likely dominate. Benchmarking with larger arrays will make JAX's runtime performance more clear.
- As mentioned above, JAX's BFGS implementation is different than scipy, and has different convergence tolerances, etc. which make direct comparison difficult.

I'm going to close this issue, because I think these things are suitably discussed in places like #6568. Feel free to add to the thread here if you think there's some aspect I've missed!
