### ISSUE TITLE
xmap regression

### ISSUE THREAD

**Issue by kingoflolz** [google/jax#6962]
Possibly related to #6959 , but there seems to be additional regressions in xmap unrelated to the multi-host case. One simplified example is provided in the colab below:
https://colab.research.google.com/drive/18nU5rz8CF7YDYPSuPqJH38Dc7HkroYOn?usp=sharing

The example works with jax == 0.2.12, but not with the latest version.

Full stack trace:
```
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-2-2f2533018f84> in <module>()
     65                                             axis_resources={'shard': 'mp', 'batch': 'dp'})
     66 
---> 67     run_xmap(params, x)

8 frames

/usr/local/lib/python3.7/dist-packages/jax/experimental/maps.py in fun_mapped(*args)
    577       backend=backend,
    578       spmd_in_axes=None,
--> 579       spmd_out_axes_thunk=None)
    580     if has_output_rank_assertions:
    581       for out, spec in zip(out_flat, out_axes_thunk()):

/usr/local/lib/python3.7/dist-packages/jax/experimental/maps.py in bind(self, fun, *args, **params)
    764   def bind(self, fun, *args, **params):
    765     assert len(params['in_axes']) == len(args)
--> 766     return core.call_bind(self, fun, *args, **params)  # type: ignore
    767 
    768   def process(self, trace, fun, tracers, params):

/usr/local/lib/python3.7/dist-packages/jax/core.py in call_bind(primitive, fun, *args, **params)
   1549       params_tuple, out_axes_transforms)
   1550   tracers = map(top_trace.full_raise, args)
-> 1551   outs = primitive.process(top_trace, fun, tracers, params)
   1552   return map(full_lower, apply_todos(env_trace_todo(), outs))
   1553 

/usr/local/lib/python3.7/dist-packages/jax/experimental/maps.py in process(self, trace, fun, tracers, params)
    767 
    768   def process(self, trace, fun, tracers, params):
--> 769     return trace.process_xmap(self, fun, tracers, params)
    770 
    771   def post_process(self, trace, out_tracers, params):

/usr/local/lib/python3.7/dist-packages/jax/core.py in process_call(self, primitive, f, tracers, params)
    604 
    605   def process_call(self, primitive, f, tracers, params):
--> 606     return primitive.impl(f, *tracers, **params)
    607   process_map = process_call
    608 

/usr/local/lib/python3.7/dist-packages/jax/experimental/maps.py in xmap_impl(fun, name, in_axes, out_axes_thunk, donated_invars, global_axis_sizes, axis_resources, resource_env, backend, spmd_in_axes, spmd_out_axes_thunk, *args)
    596       axis_resources, resource_env, backend,
    597       spmd_in_axes, spmd_out_axes_thunk,
--> 598       *in_avals)
    599   distributed_debug_log(("Running xmapped function", name),
    600                         ("python function", fun.f),

/usr/local/lib/python3.7/dist-packages/jax/linear_util.py in memoized_fun(fun, *args)
    260       fun.populate_stores(stores)
    261     else:
--> 262       ans = call(fun, *args)
    263       cache[key] = (ans, fun.stores)
    264 

/usr/local/lib/python3.7/dist-packages/jax/experimental/maps.py in make_xmap_callable(fun, name, in_axes, out_axes_thunk, donated_invars, global_axis_sizes, axis_resources, resource_env, backend, spmd_in_axes, spmd_out_axes_thunk, *in_avals)
    619     jaxpr, out_avals, consts = pe.trace_to_jaxpr_final(fun, mapped_in_avals)
    620   out_axes = out_axes_thunk()
--> 621   _check_out_avals_vs_out_axes(out_avals, out_axes, global_axis_sizes)
    622   # NOTE: We don't use avals and all params, so only pass in the relevant parts (too lazy...)
    623   _resource_typing_xmap([], dict(axis_resources=axis_resources,

/usr/local/lib/python3.7/dist-packages/jax/experimental/maps.py in _check_out_avals_vs_out_axes(out_avals, out_axes, global_axis_sizes)
   1401     if undeclared_axes:
   1402       undeclared_axes_str = sorted([str(axis) for axis in undeclared_axes])
-> 1403       raise TypeError(f"One of xmap results has an out_axes specification of "
   1404                       f"{axes.user_repr}, but is actually mapped along more axes "
   1405                       f"defined by this xmap call: {', '.join(undeclared_axes_str)}")

TypeError: One of xmap results has an out_axes specification of ['shard', ...], but is actually mapped along more axes defined by this xmap call: batch
```

**Comment by apaszke** [comment]
The colab is not accessible for me, so I can't reproduce this. Can you please post a script or open up the notebook?

**Comment by kingoflolz** [comment]
Sorry about that, should be public now

**Comment by shawwn** [comment]
@jekbradbury points out that https://github.com/google/jax/pull/6950 might be a potential solution. Specifically, that PR adds the ability to call `.grad()` with `reduce_axes=('batch',)`. The error only seems to happen during the backwards pass, so although I haven't confirmed that this PR definitely fixes this issue, it seems >40% likely that it could.

I'm not happy with this fix, for two reasons:

1. It adds extra complexity. @kingoflolz' simple example should work just fine, without exploding, by default. But right now, the solution would be for users to add `reduce_axes=('batch',)` to their `grad()` computations, which is pretty much the exact opposite of "principle of least surprise."

2. @kingoflolz' example used to work! The latest version of Jax is 0.2.14. But two versions ago, jax==0.2.12 ran @kingoflolz's code just fine. Something changed between then and now, and no one seems to have a clear understanding of what broke. (In fact, the current hypothesis is that the jax 0.2.12 worked by accident, and that the lack of errors may have been masking a deeper problem.)

A word on @kingoflolz example. The code is quite simple: pass in two tensors, using `in_axes=(['shard', ...], ['batch', ...])` and `out_axes=('shard',)`. In other words, the first tensor has 8 values, one for each TPU core; the second tensor is a single training example, replicated across all TPU cores; then the result is a `ShardedArray` of 8 values, one per TPU core. (Each TPU core produces its own result in parallel.)

In other words, it's something that pretty much *every Jax user* will want to do (if they want to do model parallelism at all). Which means that this error might bite pretty much every Jax user.

So this is roughly the "hello world" of `xmap`, and I feel strongly that it would be a mistake not to make sure it works by default, with no extra work from the end user. (i.e. forcing users to specify `reduce_axes=('batch',)` seems like a design mistake, even if it fixes this problem.)

jax's simplicity is a [key strategic advantage](https://gist.github.com/shawwn/c0be857201dd28607aa8c5e86f6f4b5e). Going forward, it sounds like `xmap` is the intended API for model parallelism. Avoiding small mistakes now will help so many users later on -- especially since everyone might run into this problem, just like @kingoflolz did, and just like I would've if I'd tried to use `xmap` for serious work.

(It's unclear whether there's any workaround at all for this problem right now. I spent about a half hour trying to think of some way to sidestep the error, but either I'm not too clever or this bug is sort of insidious.)

It feels like no one from Google is presently using `xmap` for serious work, because any non-toy example seems like it would trigger this error. (It sounds like `pjit` is used by most Jax researchers for model parallelism, or perhaps [sharding constraints](https://github.com/google-research/google-research/blob/2bdca9b1704e5ba36ece7f2a46f913200b85b981/flax_models/mlperf/transformer/models.py#L317-L319). Either way, not `xmap`.)

I'll try to investigate why it seems to work in jax 0.2.12 but fails in latest (0.2.14).

**Comment by paramjeet2021** [comment]
I am also facing the same error but to resolve this I moved to Jax = 0.2.12 but unable to import jax

```
With Jax==0.2.12 I get the following error:

import jax
2021-07-20 11:07:32.634036: F external/org_tensorflow/tensorflow/core/tpu/tpu_executor_init_fns.inc:110] TpuTransferManager_ReadDynamicShapes not available in this library.
Aborted (core dumped)
```
import jax product this output and abort command.

**Comment by skye** [comment]
@kingoflolz thanks for the repro and @shawwn thanks for the verbal explanation, they're both very helpful. Thanks @paramjeet2021 for reminding us to think about this :)

If I'm understanding correctly, you're basically implementing the same behavior as pmap: shard one value across the 8 devices, replicate one value across devices, and get a sharded result out. You're doing this with xmap by creating a (1,8) device mesh, mapping the sharded input across the size-8 axis and the replicated value across the size-1 axis, and specifying that the output value should be mapped across the size-8 axis (since it should be sharded and not replicated).

The easiest way to fix the error in this case is to remove the size-1 axis and just use a 1D (8,) mesh. You can then specify `None` in_axes for the replicated input (instead of `["batch", ...]`). Values missing the named axis corresponding to a physical mesh axis will be replicated across that physical axis, so `None` = no named axes --> full replication across devices.

---

More generally, you're getting this error because the output is really mapped across both mesh axes, and xmap doesn't know where to materialize the size-1 axis in the output array. Here's a simpler example of the same error:
```python
def f(x, y):
  return x + y

xmapped_f = xmap(f,
            in_axes=(["a"],
                     ["b"]),
            out_axes=["a", ...])  # need to include "b" to fix

X = jnp.arange(6)
Y = jnp.arange(8) * 10
r = xmapped_f(X, Y)  # error: "... is actually mapped along more axes defined by this xmap call: b"
```
Here's what's going on: we're mapping `X`'s single dimension to a named axis `a`, and `Y`'s to `b`. Neither of the named axes are mapped to a physical mesh axis (we don't even have a physical mesh), so they're each implicitly mapped to a vectorization resource axis (think two vmaps). The idea is the same as if we did it over a device mesh though (device mesh provides physical resources axes).

So we're xmapping over two named axes, `a` (size 6) and `b` (size 8), so the output `r` has to have at least one size-6 and one size-8 dimension. How do we get 6*8 `x, y` values to pass to `f` to populate the output? We broadcast `X` and `Y` over their respective missing dimensions. Something like this if we were using positional axes:
```python
import numpy as np

X = np.arange(6) # 'a'
Y = np.arange(8) * 10 # 'b'
# implicit xmap broadcast
X_b = np.repeat(X[:, None], 8, axis=1) # assume 'a' is first positional axis
Y_b = np.repeat(Y[None, :], 6, axis=0) # assume 'b' is second positional axis
print(X_b + Y_b)
```
```
[[ 0 10 20 30 40 50 60 70]
 [ 1 11 21 31 41 51 61 71]
 [ 2 12 22 32 42 52 62 72]
 [ 3 13 23 33 43 53 63 73]
 [ 4 14 24 34 44 54 64 74]
 [ 5 15 25 35 45 55 65 75]]
```
You can see that I arbitrarily assigned positional output axes to `a` and `b` for the that example. How does `xmap` choose? It doesn't, you have to tell it with `out_axes`! Hopefully now you can better understand the error: we're telling xmap that the `a` should be the first positional output axis, but it still doesn't know where to put `b` (in this case there's only one choice, but that wouldn't be the case if we had more named or positional axes in the mix). So here's how we can fix it:
```python
def f(x, y):
  return x + y

xmapped_f = xmap(f,
            in_axes=(["a"],
                     ["b"]),
            out_axes=["a", "b"]) # fully specified

X = jnp.arange(6)
Y = jnp.arange(8) * 10
r = xmapped_f(X, Y)
print(r)
```
```
[[ 0 10 20 30 40 50 60 70]
 [ 1 11 21 31 41 51 61 71]
 [ 2 12 22 32 42 52 62 72]
 [ 3 13 23 33 43 53 63 73]
 [ 4 14 24 34 44 54 64 74]
 [ 5 15 25 35 45 55 65 75]]
```
Or we could switch it around:
```python
def f(x, y):
  return x + y

xmapped_f = xmap(f,
            in_axes=(["a"],
                     ["b"]),
            out_axes=["b", "a'"])  # swapped!

X = jnp.arange(6)
Y = jnp.arange(8) * 10
r = xmapped_f(X, Y)
print(r)
```
```
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]
 [60 61 62 63 64 65]
 [70 71 72 73 74 75]]
```
Does this make any sense? If not, just do the fix I said above :)

**Comment by kingoflolz** [comment]
Thanks for the detailed response @skye !

I'm still not sure how to totally resolve this issue though in the actual code though. For some more background, a 2d mesh is necessary to implement both model and data parallelism, so the simple fix of changing to a 1d mesh would not work.

The behavior for fully specifying the output sharding is also not particularly clear, as ideally I would like to tell xmap that a dimension should be reduced (or is already reduced over) and thus does not need to be included in the output. I've tried a few formulations of this but it still seems to have the same error unfortunately.

**Comment by jekbradbury** [comment]
If a named axis is reduced over (e.g. with a psum, or for now a psum_id_rev
because psum doesn’t have the right autodiff behavior), then xmap should be
fine with returning it without turning that named axis into a positional
axis. Perhaps your psum_id_rev primitive (if you’re using one) doesn’t
remove the named axis from the aval of its output (see the upstream psum or
the psum_id_rev we added in xmap tests for how to do this).

**Comment by kingoflolz** [comment]
Assuming this is the code you are talking about?

https://github.com/google/jax/blob/d25f4b34b8f5cc4d4e068c024569523175016379/tests/xmap_test.py#L1320-L1333

I don't see anything in particular that would do anything special to the avals, and it appears like the code which does that is here?

https://github.com/google/jax/blob/64510bd5b69933cb6bec62f63b9b7ba2f1eff3fc/jax/_src/lax/parallel.py#L630-L637

**Comment by shawwn** [comment]
By the way, I'd like to request that this github issue be kept open, even if someone figures out the "right way" to write the code. There's a bug here -- I'm almost certain of it. There's no reason xmap should be throwing an error, but the colab notebook shows an error. That's a bug, and the current discussion is sweeping that bug under the rug.

I've been looking into it, and I have a few things to report, but I don't feel like writing it up yet. One strange issue here is that the haiku RNG key is being sharded, which *causes the haiku model parameters to also be sharded*. In other words, **the model params being initialized the sharded rng key**, which then **causes a sharding constraint in the resulting parameters**.

This was highly unexpected -- merely using an xmap'ed RNG key to create a value shouldn't cause the resulting value to be xmap'ped. But it is.

It took awhile of tracing this in haiku to figure out what the heck was going on. But suffice to say, this xmap regression happens to be demonstrating a tricky, subtle xmap issue that seems likely to bite us in the future until we hunt down in detail what's going on.

(I've been doing this on and off for a few weeks, mostly off. But now that the conversation has been revitalized, I'll try to do some more bug hunting on this. It's tricky to debug because it involves running jax 0.2.12 side by side with the latest version and tracing exactly where the differences are in the debugger.)

**Comment by shawwn** [comment]
A simpler way to phrase this: remember, this issue is showing something that *used to work* in jax 0.2.12. The code was valid as written, and it produced a correct result on an actual TPU. So the latest jax is throwing an error that isn't really an error, which is worrisome, and it seems important for someone to track down exactly what's going on before the issue gets closed.

**Comment by shawwn** [comment]
Oh, sorry for spamming, but I thought of another maybe-persuasive point: Notice that @kingoflolz xmap regression works for the forward pass, but errors on the backwards pass. If @skye's explanation were the whole story, then the error should be happening in both the forward pass and the backwards pass, I think. But only erroring in the backwards pass seems to hint at a deeper problem.

I encourage everybody to open up [Ben's colab notebook](https://colab.research.google.com/drive/18nU5rz8CF7YDYPSuPqJH38Dc7HkroYOn?usp=sharing) to see for themselves just how strange the error is. Careful though -- if you notice how odd it is, you might not be able to stop hunting for the problem. ;)

**Comment by shawwn** [comment]
Uh... So, after saying all of that, I think I should sheepishly come back with hat in hand and say that there's no bug here. @skye's explanation was correct in every detail. In fact, it got me thinking about the real problem, which turned out to give the real solution.

@kingoflolz Here's your notebook's code:

```py
    run_xmap = jax.experimental.maps.xmap(fun=bwd_old,
                                          in_axes=(["shard", ...],
                                                     ["batch", ...]),
                                            out_axes=["shard", ...],
                                            axis_resources={'shard': 'mp', 'batch': 'dp'})
```

The solution is to change `out_axes=["shard", ...],` to `out_axes=["batch", "shard", ...],`:

```py
    run_xmap = jax.experimental.maps.xmap(fun=bwd_old,
                                          in_axes=(["shard", ...],
                                                     ["batch", ...]),
                                            out_axes=["batch", "shard", ...],
                                            axis_resources={'shard': 'mp', 'batch': 'dp'})
```

Which ... is entirely obvious in hindsight. I'd feel silly for chasing myself in circles for a month over this, except everyone else missed it too. :)

Okay! So, it's dinner time, but I'll be back to explain:

1. how I figured out this was the solution,

2. why it previously worked in jax 0.2.12, and

3. why it errors now (and more importantly, why it's correct to error now -- I fully agree with the new design, which I didn't expect to feel!)

(In short, though, xmap was incorrectly letting you return part of a sharded tensor. As of jax > 0.2.12, that's no longer allowed -- correctly! -- and I'll illustrate why that's important.)

**Comment by apaszke** [comment]
Judging by the last comment this was a missing check that we've added at some point, so it's really working as intended. Please reopen if there are still some problems that I missed.

**Comment by matthew-piziak** [comment]
Hej @apaszke (and others :wave:),

I'm interested in experimenting with text-generation models and to that end I'm trying to run GPT-J-6B inference on a TPU Cloud Research machine. I'm a bit out of my depth, but if you don't mind here are my observations regarding how this issue impacts the [GPT-J-6B Inference Demo](https://colab.research.google.com/github/kingoflolz/mesh-transformer-jax/blob/master/colab_demo.ipynb) hosted on Colab. 
### Observations

First, I see a reference to a so-called "regression" with `xmap` in `jax` version `0.2.13`.

```python
# jax 0.2.12 is required due to a regression with xmap in 0.2.13
!pip install mesh-transformer-jax/ jax==0.2.12 tensorflow==2.5.0
```

Second, I see a seeming incompatibility between the `0.2.12` version and the TPU environment:

`TpuTransferManager_ReadDynamicShapes not available in this library. Aborted (core dumped)`

That issue is also reported in https://github.com/google/jax/issues/7334.

### Catch-22

Based on my reading of this issue, `xmap` has stopped letting one return a piece of a sharded tensor, and the old behavior should not be depended upon. That makes sense and indeed I wouldn't expect any further mitigation from the `jax` maintenance team, since `xmap` warns the user that it is experimental. This is fully an issue of downstream usage, but nevertheless if you'd offer me any wisdom here I'd appreciate it.

The issue:
- As far as I know GPT-J-6B is the most powerful public autoregressive text-generation weight set.
- GPT-J-6B only works on model v1 of `mesh-transformer-jax`.  
- v1 only works with JAX 0.2.12.
- Dependency set `mesh-transformer-jax+jax==0.2.12+tensorflow==2.5.0` aborts (as above, tested in a TPU v3 environment).
- When used with `jax>=0.2.13`, it fails as above.

In summary, the model I planned to use is semi-deprecated. [This comment](https://github.com/kingoflolz/mesh-transformer-jax/issues/67#issuecomment-886395688) says it's not likely to be fixed by the `mesh-transformer-jax` team.

Gosh, I don't know if this is a `mesh-transformer-jax` issue or not. I feel a bit embarrassed because I feel like there isn't a right place to post this. I suppose that I'm really looking for big-picture advice, this is where it all began, and you have the big-picture context.

Ultimately, what would you recommend for an experimenter who does not have access to proprietary models?  

Options:
- Find and fix the `xmap` usage in model v1 of `mesh-transformer-jax`, restoring GPT-J-6B.
- Use an alternative model.
- Attempt to train a new model on v2 of `mesh-transformer-jax`.
- Something else?

I appreciate your patience with my pre-JAX-familiarity notes. You have good documentation; I ought to read through it and I will do that shortly. Thanks and best wishes.

**Comment by shawwn** [comment]
Hi! Wonderful comment, and you're not alone. I'm sending this mostly as a
reminder to myself not to let you fall through the cracks -- it's 11pm
right now, so I won't be able to get to this until some other time. But if
it goes too long without you getting a reply, please ping me or DM me on
twitter (https://twitter.com/theshawwn).

The JAX team really is awesome, and I suspect they'll be along with an
answer, but this darn issue is a tricky one. Basically, it was a situation
where there was a breaking API change (yuck!) for good reason (oh...) and
it happened to break the only popular thing using xmap (GPT-J).

I actually complained a lot about the breaking change, but was dragged
kicking and screaming to the conclusion that it was a good thing. I hate
when developers take the attitude of "correctness matters more than dev
experience," but in this case the correctness was sort of important.

Anyway, I'll try to make sure someone comes along with a detailed answer
about what to do next. Maybe it'll be me.

**Comment by matthew-piziak** [comment]
@shawwn You're so kind! I will happily take you up on that, thank you.

**Comment by 6r1d** [comment]
@shawwn, I'd also appreciate an answer here!

**Comment by pcuenca** [comment]
Sorry to keep derailing this interesting issue, I'm interested in GPT-J too and happy to continue the discussion elsewhere.

After reading this thread and especially @shawwn's recommendations, I attempted to fix generation [here](https://github.com/pcuenca/mesh-transformer-jax/commit/1d999b1dd3d600ede6f1e75e0aaf74224c15788d). It seems to work in JAX 0.2.21, but I'm new to `xmap` and am not totally sure what I'm doing. I don't have a need for training or fine-tuning yet, so I'll be experimenting with this unless someone more experienced suggests anything better.

Regarding @matthew-piziak's observations, I suppose you could always downgrade your environment using the method outlined in [`init_ray.sh`](https://github.com/kingoflolz/mesh-transformer-jax/blob/master/scripts/init_ray.sh). I didn't follow that path because it replaces the system's `libtpu`, and I need the instance for other projects.

**Comment by Eichhof** [comment]
I was running now into the same issue. I would like to fine-tune GPT-J using mesh-transformer-jax on Google Cloud TPU. It does not work as mesh-transformer-jax requires jax 0.2.12 which does no more work on Google Cloud TPU.

Does anybody has a solution?
