### ISSUE TITLE
jaxpr of summation is slightly inefficient

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#7088]
```python
from functools import reduce
from operator import add

import jax.numpy as jnp
from jax import make_jaxpr

l  = [jnp.arange(i, i + 3) for i in [5, 8]]

def use_sum(l):
    return sum(l)

def use_reduce(l):
    return reduce(add, l)

print(make_jaxpr(use_sum)(l))
print(make_jaxpr(use_reduce)(l))
```
Produces
```
{ lambda  ; a b.
  let c = add a 0
      d = add c b
  in (d,) }
{ lambda  ; a b.
  let c = add a b
  in (c,) }
```
It would be nice to ellide the zero from the sum.  (It already seems to know to cast the zero to the array's dtype.)

**Comment by jakevdp** [comment]
Thanks for the question! The reason the jaxpr includes an addition with zero is because this is what the Python `sum` function does: it starts with an initial value (here, zero) and adds each element of the list to it.

Python's `reduce`, on the other hand, starts with the first value in the list and adds the remaining values in turn. JAX's jaxpr representation simply records the sequence of operations being performed by Python.

Once these sequences of operations are JIT-compiled, however, XLA generally will do this kind of optimization. You can check that by generating the optimized code as described [here](https://github.com/google/jax/discussions/7068#discussioncomment-910454) (note this is a non-public API that is subject to change):
```python
c = jax.xla_computation(use_sum)(l)
backend = jax.lib.xla_bridge.get_backend()
e = backend.compile(c)
print(e.hlo_modules()[0].to_string())

c = jax.xla_computation(use_reduce)(l)
backend = jax.lib.xla_bridge.get_backend()
e = backend.compile(c)
print(e.hlo_modules()[0].to_string())
```
The result shows that the optimized version of the two functions are essentially identical, aside from differences in metadata:
```
HloModule xla_computation_use_sum__4.9

ENTRY %xla_computation_use_sum__4.9 (parameter.1: s32[3], parameter.2: s32[3]) -> (s32[3]) {
  %parameter.1 = s32[3]{0} parameter(0), metadata={op_type="add" op_name="xla_computation(use_sum)/add" source_file="<ipython-input-25-eace9d59dad5>" source_line=10}
  %parameter.2 = s32[3]{0} parameter(1)
  %add.7 = s32[3]{0} add(s32[3]{0} %parameter.1, s32[3]{0} %parameter.2), metadata={op_type="add" op_name="xla_computation(use_sum)/add" source_file="<ipython-input-25-eace9d59dad5>" source_line=10}
  ROOT %tuple.8 = (s32[3]{0}) tuple(s32[3]{0} %add.7)
}

HloModule xla_computation_use_reduce__1.6

ENTRY %xla_computation_use_reduce__1.6 (parameter.1: s32[3], parameter.2: s32[3]) -> (s32[3]) {
  %parameter.1 = s32[3]{0} parameter(0)
  %parameter.2 = s32[3]{0} parameter(1)
  %add.4 = s32[3]{0} add(s32[3]{0} %parameter.1, s32[3]{0} %parameter.2), metadata={op_type="add" op_name="xla_computation(use_reduce)/add" source_file="<ipython-input-25-eace9d59dad5>" source_line=13}
  ROOT %tuple.5 = (s32[3]{0}) tuple(s32[3]{0} %add.4)
}
```

**Comment by NeilGirdhar** [comment]
Oh, that's really interesting.  I didn't know about `backend.compile`!  Thanks for clarifying.  I guess I can go back to using `sum`.
