### ISSUE TITLE
[ROCm] running unit test in parallel

### ISSUE THREAD

**Issue by reza-amd** [google/jax#7323]
Hi all,
I wanted to know you recommendation on running unit tests in parallel (for a multi-GPU machine), but not running more than one test on each GPU. For example, in a machine with 8 GPUs, I want to run 8 tests in parallel.
In TensorFlow, you use bazel "run_under" argument with [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/gpu_build/parallel_gpu_execute.sh) script to control the number of unit tests running in parallel per GPU. 
I appreciate if you can provide more information about your solution for JAX in your internal CI builds to provide the same controllability with "pytest".
@hawkinsp

**Comment by hawkinsp** [comment]
Internally we run tests under Bazel, but we didn't want to force opensource users to have to do that, since it's not very Pythonic. One option is that we can opensource and support a Bazel-based approach to testing, and perhaps we should do that.

The other option is to use `pytest-xdist`, which is what we usually recommend since `pytest` is more familiar to the opensource community.

It's possible to run multiple tests on the *same* GPU using `pytest-xdist`. On an NVIDIA GPU you can do something like this:
```
XLA_PYTHON_CLIENT_ALLOCATOR=platform pytest -n 12 --tb=short tests examples
```
where `n` is chosen such that the tests don't run out of memory on your GPU. You need something like 1GB of GPU memory per parallel test. I would imagine the same thing works under ROCm.

The `XLA_PYTHON_CLIENT_ALLOCATOR=platform` environment variable stops JAX from preallocating GPU memory. This is needed so the test runners can share GPU memory. Using the platform allocator is typically much slower, but this doesn't matter that much for the JAX tests which do relatively few GPU operations (as opposed to Python work and XLA compilations).

To support multiple GPUs, it's possible to round-robin the tests across multiple GPUs with a patch along the following lines:
```
diff --git a/conftest.py b/conftest.py
index d881cff1..811ab064 100644
--- a/conftest.py
+++ b/conftest.py
@@ -13,14 +13,23 @@
 # limitations under the License.
 """pytest configuration"""

+import os
+
 import jax
 import numpy
 import pytest

-
 @pytest.fixture(autouse=True)
 def add_imports(doctest_namespace):
   doctest_namespace["jax"] = jax
   doctest_namespace["lax"] = jax.lax
   doctest_namespace["jnp"] = jax.numpy
   doctest_namespace["np"] = numpy
+
+def pytest_configure(config):
+  try:
+    worker_id = config.workerinput["workerid"]
+  except:
+    return
+  if worker_id.startswith("gw"):
+    os.environ['CUDA_VISIBLE_DEVICES'] = str(int(worker_id.replace("gw", "")) % 2)
```
We could check in something similar to that patch.

Unfortunately this isn't ideal because this means each test only gets one GPU, which means you'll get no coverage for multi-GPU tests.

**Comment by reza-amd** [comment]
Thanks for the patch. We have `HIP_VISIBLE_DEVICES` to adopt it for ROCm. However, I also think the bazel-based solution would be ideal as we can test our changes similar to you and it makes our future communication much easier. If this is the case, when do you think it will happen?

**Comment by yashk2810** [comment]
> I also think the bazel-based solution would be ideal as we can test our changes

I am working on exporting BUILD files so that we can use `bazel test` externally too. I can't give you an exact date as to when it will happen, because we are going through an infrastructure revamp but it is on the roadmap and it should happen soon. I am actively working on it :)

**Comment by reza-amd** [comment]
Hi @yashk2810, do you have any update on using ```bazel``` for running unit tests?
I have also a question about unit tests that need multiple gpus. I like to run tests with single gpu requirement to run in parallel (one test per gpu), and after all gpus are available, run the tests with multi-gpu requirements serially. Do you know a way to filter tests with multi-gpu requirement?

**Comment by hawkinsp** [comment]
I can confirm that with #11359 something like the following will work:
```
bazel test --//jax:build_jaxlib=false //tests/... --test_env=XLA_PYTHON_CLIENT_ALLOCATOR=platform --run_under=parallel_gpu_execute.sh --test_output=errors
```

I think we should add something similar to that script to the JAX repository and then we can declare this bug fixed.

**Comment by hawkinsp** [comment]
I think we can declare this fixed. I also want to change our GPU CI builds to work this way but I can do that separately.
