### ISSUE TITLE
jnp.float16 hangs matmul

### ISSUE THREAD

**Issue by msaroufim** [google/jax#7431]
I'm not sure if this is a bug or expected behavior but couldn't find a similar issue here so thought I'd post

Repro

The below code just runs seemingly forever where the `float32` and `bfloat16` variants run just fine. Is `float16` supported? I tried both a GPU and TPU in collab and noticed the same issue.

```python
import jax.numpy as jnp
from jax import grad, jit, vmap
from jax import random

import jax; jax.config.update('jax_platform_name', 'cpu')

key = random.PRNGKey(0)
x = random.normal(key, (10,))
print(x)

size = 3000
x = random.normal(key, (size, size), dtype=jnp.float16)
%timeit jnp.dot(x, x.T).block_until_ready()  # runs on the GPU
```

`x = random.normal(key, (size, size), dtype=jnp.float32)` runs just fine

**Comment by jakevdp** [comment]
Thanks for the report & the clear repro. This seems like something that @hawkinsp might have ideas about.

**Comment by hawkinsp** [comment]
The issue is that the implementation of float16 matrix multiplication in XLA/CPU appears to be very slow. XLA/CPU actually just calls an Eigen kernel for float16 matmuls, and it seems to be very slow indeed. A similar kernel is also used by TF, and it is equally slow.

https://github.com/google/jax/pull/7462 works around by computing float16 matmuls in float32 and casting back on CPU.
