### ISSUE TITLE
`vmap` doesn't handle non-JAX-types in non-vmap'd outputs

### ISSUE THREAD

**Issue by patrick-kidger** [google/jax#7603]
Not sure if this counts as a bug or a feature request.

```python
import jax

def make1(x):
    return [x, 0]

def make2(x):
    return [x, object()]

jax.vmap(make1, out_axes=[0, None])(jax.numpy.zeros(2))
# [DeviceArray([0., 0.], dtype=float32), 0]
jax.vmap(make2, out_axes=[0, None])(jax.numpy.zeros(2))
# TypeError: Output from batched function <object object at 0x7f372dbf9860> with type
# <class 'object'> is not a valid JAX type
```

If we're not vmap'ing the value anyway, it'd be nice if non-JAX-types can be valid outputs from vmap'd functions.

In contrast the in-axis equivalent does work:
```python
jax.vmap(lambda x, y: x, in_axes=(0, None))(jax.numpy.zeros(2), object())
# DeviceArray([0., 0.], dtype=float32)
```

**Comment by patrick-kidger** [comment]
FWIW there is the following workaround:

```python
import jax
from typing import Generic, TypeVar

_T = TypeVar('_T')

class RefHolder(Generic[_T]):
    def __init__(self, value: _T):
        self.value = value

def _refholder_flatten(self):
    return (), self.value

def _refholder_unflatten(value, _):
    return RefHolder(value)

jax.tree_util.register_pytree_node(RefHolder, _refholder_flatten, _refholder_unflatten)

###

def make(x):
    return [x, RefHolder(object())]

jax.vmap(make, out_axes=[0, None])(jax.numpy.zeros(2))
# [DeviceArray([0., 0.], dtype=float32), <__main__.RefHolder object at 0x7fd6c3126f10>]
```

**Comment by jakevdp** [comment]
I think this is by design: functions passed to vmap are traced, and therefore their outputs are required to be valid JAX types, which can be a normal numeric scalar or array, or a custom type that you have registered.

The `in_args` version works because the tracing in vmap is only with respect to batched arguments; note however that if you wrap the function in `JIT` (which traces with respect to all arguments) you'll get the same error there as well.

**Comment by patrick-kidger** [comment]
I don't see that "functions passed to vmap are traced" implies that "their outputs are required to be valid JAX types".

The `in_axes`-specified inputs are wrapped in a `BatchTrace` and each JAX operation handles them appropriately. But here, the non-JAX output does not depend on any of the JAX inputs, so it's fine.

To use your jit analogy, it depends only on `static_argnums`.

**Comment by jakevdp** [comment]
Sorry, I guess I'm not understanding your intent here: are you trying to describe how things *are*, or how they *ought to be*? I was describing the former.

**Comment by patrick-kidger** [comment]
Likewise, the former.

As far as I can see, the requirement that unbatched outputs be JAX types is not necessary from a technical standpoint. The existence of the workaround is evidence of this. As such, I think it's a bug that this exception is being thrown spuriously.

**Comment by jakevdp** [comment]
Thanks, that makes sense! In that case, I disagree with your point about non-jax types and static argnums within JIT. JIT functions require outputs to be valid jax types, regardless of whether they are derived from static or traced inputs. As a trivial example:
```python
>>>jax. jit(lambda: object())()
TypeError: Value <object object at 0x7fc663759ff0> with type <class 'object'> is not a valid JAX type
```
Since `vmap` uses some of the same tracing mechanisms, it likewise requires JAX-compatible outputs.

As to whether this could be changed: I think in theory, yes it could, but I suspect it would require a fairly substantial rewrite of 
JAX internals. I doubt that would be a priority for the team without some equally substantial motivation in terms of either better user experience or cleaner abstractions in the code.

**Comment by patrick-kidger** [comment]
Hmm fair point about JIT not currently supporting this either. I think the same argument -- that this isn't necessary from a technical standpoint -- actually applies to JIT as well. Indeed the `RefHolder` workaround works there too.

Anyway, fair enough if this would be complicated to handle. I'll stick to using `RefHolder` as a workaround.

**Comment by mattjj** [comment]
Thanks for raising this, and for the discussion!

The main reason we want transformed functions (like vmapped or jitted functions) to have outputs which are pytrees of jax types is that otherwise an object is opaque, and it could be a container smuggling a Tracer. That kind of smuggling leads to really bad errors.

For folks who know what they're doing and really want to work around the issue, pytrees are the way to go. At least that requires the programmer to be very explicit about what's being split out as metadata.

(Actually jit and perhaps vmap used to support this, but we intentionally made these errors.)

**Comment by patrick-kidger** [comment]
That makes a lot of sense. Thanks for the response!
