### ISSUE TITLE
Issues with value type promotion in JAX. 

### ISSUE THREAD

**Issue by sschoenholz** [google/jax#768]
At the time of writing this, JAX automatically upcasts python values upcast to the highest dtype available. For example, if x64 mode is enabled then the following code will produce a float64, `np.array([1, 2, 3], dtype=np.float32) * 1.0`. In order to guarantee that a calculation is performed at a specific dtype, it is therefore necessary to explicitly cast all values to the desired dtype. 

While this is not inherently problematic (it might even be desirable to have some kind of explicit typing), I think the current system could use some improvement. My main issue is that the upcasting is silent. Therefore, suppose you have a long piece of code and have accidentally out of habit included a line line `y = x ** 2.0`. Now, the output of the expression will be upcast silently. This means that unless you are explicitly checking dtype information your calculation might be slower than you expect / not fit into memory as easily. Moreover, to find the errant multiply, you have to proceed by just looking through the code line by line. This is all the worse if you initially wrote code e.g. to operate at float32 and then decide you want to be able to use float16s since code does not preserve type information by default.

At the moment I can think of a few possible improvements to the status quo without going as far as numpy's casting which (as Matt points out) is challenging within jit compilation.

1. Force users to specify the dtype of values and give an error otherwise.
2. Give a warning when a python value gets upcast.
3. Be able to set the default casting type through a flag.

While I'm sure there are better options out there, I think any of these three would be QoL improvements. I might be partial to some combination of 2/3 since I think the common case is that a user wants a consistent dtype across their calculation.

**Comment by mattjj** [comment]
Thanks for raising this. Let's try to write some examples!

Here's an example test script:

```python
from __future__ import division
from __future__ import print_function

import itertools as it

import numpy as onp
import jax.numpy as np

from jax import jit
from jax.config import config
config.update("jax_enable_x64", True)

scalarish_vals = [1.,
                  onp.float32(1.), onp.float64(1.),
                  onp.array(1, onp.float32), onp.array(1, onp.float64)]

for lhs, rhs in it.product(scalarish_vals, repeat=2):
  onp_res  = onp.result_type(    onp.add(lhs, rhs))
  np_res   = onp.result_type(     np.add(lhs, rhs))
  jit_res  = onp.result_type(jit(np.add)(lhs, rhs))
  jit2_res = onp.result_type(jit(lambda x: np.add(x, rhs))(lhs))

  if not (onp_res == np_res == jit_res == jit2_res):
    print("    onp", onp_res)
    print("     np", np_res)
    print("jit  np", jit_res)
    print("jit2 np", jit2_res)
    print()
```

I think we always want those to agree, and hence for the script not to print anything out. That's indeed what happens on master.

Before #733 (see also #732), it would print out these lines:

```
<type 'float'> float64 , <type 'numpy.float32'> float32
    onp float64
     np float32
jit  np float64
jit2 np float64

<type 'float'> float64 , <type 'numpy.ndarray'> float32
    onp float64
     np float32
jit  np float64
jit2 np float64

<type 'numpy.float32'> float32 , <type 'float'> float64
    onp float64
     np float32
jit  np float64
jit2 np float32

<type 'numpy.ndarray'> float32 , <type 'float'> float64
    onp float64
     np float32
jit  np float64
jit2 np float32
```

So far so good for the master branch. But things get dicey if we add this to the script:

```python
lhs = onp.array([1, 2, 3], dtype=onp.float32)
for rhs in scalarish_vals:
  onp_res  = onp.result_type(    onp.add(lhs, rhs))
  np_res   = onp.result_type(     np.add(lhs, rhs))
  jit_res  = onp.result_type(jit(np.add)(lhs, rhs))
  jit2_res = onp.result_type(jit(lambda x: np.add(x, rhs))(lhs))

  if not (onp_res == np_res == jit_res == jit2_res):
    print("    onp", onp_res)
    print("     np", np_res)
    print("jit  np", jit_res)
    print("jit2 np", jit2_res)
    print()
```

Now on master that prints:

```
<type 'numpy.ndarray'> float32 , <type 'float'> float64
    onp float32
     np float64
jit  np float64
jit2 np float64

<type 'numpy.ndarray'> float32 , <type 'numpy.float64'> float64
    onp float32
     np float64
jit  np float64
jit2 np float64

<type 'numpy.ndarray'> float32 , <type 'numpy.ndarray'> float64
    onp float32
     np float64
jit  np float64
jit2 np float64
```

Notice that `jax.numpy` always agrees with itself, regardless of whether `jit` is present. That's good! But `jax.numpy` disagrees with `numpy`. Not so good!

That was the intended tradeoff of #733, namely that maintaining jit-invariance was more important than following NumPy details. But this NumPy detail is convenient because, as @sschoenholz points out, we like to write naked literals in Python code.

But this test script shows me a mistake in my understanding: I thought that this special handling (avoiding promotion when interacting with a scalar) was specific to Python scalar literals, but it seems to behave the same for Python literals as for NumPy scalars and 0D ndarrays. Maybe that means we can have our cake and eat it too...

**Comment by mattjj** [comment]
I just pushed abe4f61, which makes all the above will-it-print tests pass. Still exploring more, but it's promising.

**Comment by mattjj** [comment]
It makes numpy tests fail though :( still looking to see if we can have our cake and eat it too!
