### ISSUE TITLE
add a shape inference function to api.py

### ISSUE THREAD

**Issue by mattjj** [google/jax#798]
A couple users (including @lukaszkaiser) have requested a way to do shape inference. Maybe we can provide something like `eval_shape` (taking example arguments, as here, or maybe shape tuples):

```python
from __future__ import print_function

# Look at all these internal imports! Not for the faint of heart.
from jax.abstract_arrays import ShapedArray, raise_to_shaped
from jax.api_util import pytree_to_jaxtupletree, pytree_fun_to_jaxtupletree_fun
from jax.core import get_aval
from jax.interpreters import partial_eval as pe
from jax.util import unzip2
import jax.linear_util as lu
from jax.tree_util import build_tree


def abstractify(x):
  return raise_to_shaped(get_aval(x))

def eval_shape(f, *args):
  jaxtuple_args, in_trees = unzip2(map(pytree_to_jaxtupletree, args))
  f, out_tree = pytree_fun_to_jaxtupletree_fun(lu.wrap_init(f), in_trees)
  out = pe.abstract_eval_fun(f.call_wrapped, *map(abstractify, jaxtuple_args))
  return build_tree(out_tree(), out)


###

import jax.numpy as np

def fun(x, y):
  return np.tanh(np.dot(x, y) + 3.)

x = np.ones((2, 3))
y = np.ones((3, 4))
out = eval_shape(fun, x, y)
print(out)


def fun1():
  x = np.ones((2, 3))
  y = np.ones((3, 4))
  return np.tanh(np.dot(x, y) + 3.)
out = eval_shape(fun1)
print(out)


def fun2(x, y):
  a, b = x
  return a + b + y

x = (np.ones(2), np.ones(2))
y = 3.
out = eval_shape(fun2, x, y)
print(out)


def fun3(x, y):
  return x[0] + x[1] + y

x = (np.ones(2), np.ones(2))
y = 3.
out = eval_shape(fun3, x, y)
print(out)


def fun4(x, y):
  return {'hi': x[0] + x[1] + y}

x = (np.ones(2), np.ones(2))
y = 3.
out = eval_shape(fun4, x, y)
print(out)
```

**Comment by lukaszkaiser** [comment]
Yes, having a function like this would be amazing! But, more precisely, we'd like to have a function:

eval_shape(fun, *args_shapes)
  return shape of f(ran on rags with shapes as in args_shapes)

2 things that the above code still doesn't do
* using shapes and types instead of values (should be simple)
* removing the need for type of input
  (not super important, but would be very clean; is that technically possible though?)

One more bug to check would be with indexing:

def fun3(x, y):
  a = x[0][0]
  b = x[0][1]
  c = x[1]
  return a + b + c + y

But in general it's a great idea!

Thanks Matt!!

**Comment by mattjj** [comment]
Thanks for catching these bugs, Lukasz. Just updated the code in the OP to handle the `fun3` case. I think it might be getting close now...
