### ISSUE TITLE
lax.fori_loop suffers precision issue under fast math mode

### ISSUE THREAD

**Issue by fehiepsi** [google/jax#829]
The following repro script shows the issue

```
import jax
import jax.numpy as np
from jax import lax, random, ops
from jax.config import config; config.update('jax_platform_name', 'cpu')

def f(x):
    r = random.normal(random.PRNGKey(0))

    def body_fn(i, val):
        val = val + 0.01 * r
        return val

    return lax.fori_loop(0, 10, body_fn, x)


def g(x, prim=True):
    collection = np.zeros((1,))

    def body_fn(i, state):
        val, collection = state
        val = f(val)
        collection = ops.index_update(collection, i, val)
        return val, collection

    if prim:
        _, collection = lax.fori_loop(0, 1, body_fn, (x, collection))
    else:
        _, collection = body_fn(0, (x, collection))
    return collection[0]


print(f(1.).copy(), g(1., False).copy(), g(1., True).copy())
```
which yields
```
0.97941554 0.97941554 0.9794158
```

When disabling fast-math-mode, the issue also happens with operators involving `np.linalg.cholesky` or `sp.linalg.solve_triangular` but it is complicated to make a simple repro script (and I can solve it by `jitting` the `fori_loop`) so I would like to defer it to another issue.
cc @mattjj

**Comment by hawkinsp** [comment]
I think this is working as intended.

Note the `r` value is a compile-time constant; it doesn't depend in any way on the inputs to `f`. In fast-math mode, LLVM is most likely able to hoist the repeated addition of `0.01 * r` out of the loop and replace it with a constant. The difference in output is because you lose precision from repeated addition. In fact, the fast-math output is arguably *more* precise. If you disable fast-math mode, I'm guessing for some reason LLVM is unable to perform the optimization (perhaps because it is forbidden by reassociation rules).

Here's a simpler reproduction without using much of JAX:

```
In [1]: from jax import random

In [2]: import numpy as onp

In [3]: r = onp.array(random.normal(random.PRNGKey(0)) * 0.01)
/usr/local/google/home/phawkins/p/jax/jax/lib/xla_bridge.py:130: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')

In [4]: r
Out[4]: array(-0.00205842, dtype=float32)

In [5]: x = onp.float32(1)

In [6]: for _ in range(10):
   ...:     x = x + r
   ...: 

In [7]: x
Out[7]: 0.97941554

In [8]: onp.float32(1) + onp.float32(10) * r
Out[8]: 0.9794158
```

Hope that helps!
