### ISSUE TITLE
slow Transposed Convolution (conv_transpose, conv_general_dilated?)

### ISSUE THREAD

**Issue by belger-dussen** [google/jax#8537]
I'm having massive slow down when using transposed convolution layer. 

I noticed this problem when I was converting tf models to haiku models. And I tested on flax and the result was the same.
I'm guessing some issues in conv_general_dilated or in conv_general_dilated, but I could not find by myself.

I've attached some test code using flax. I think conv and tranposed conv layers should take almost the same time, but transposed conv layer takes 4-5 times more.

https://colab.research.google.com/drive/1BSHfyB5hrUs_tVcoBJlBPVU4zpesgAxk?usp=sharing

**Comment by shoyer** [comment]
Are you running this on CPU, GPU or TPU?

**Comment by belger-dussen** [comment]
I'm running on GPU. I haven't tested on TPU.

**Comment by apaszke** [comment]
I looked into it and it looks like a blind spot in cuDNN. Tracing GPU execution indicates that the regular convolution uses a different algorithm than its transpose in the 3D case (winograd vs implicit GEMM), which seems to be the reason for the slowdown. After replacing 3D convolutions with 2D convolutions the chosen kernels still use different algorithms (winograd vs FFT), but the overall runtime ends up being almost equal (0.18s vs 0.19s). I don't think there's anything we can do to fix this, except hope that NVIDIA will write more kernels for 3D transposed convolutions 😕

I'll close this since there doesn't seem to be any action we can take, but please feel free to reopen if you have any reason to suspect that it is an error on our (or XLA's) side.

**Comment by belger-dussen** [comment]
@apaszke 
Thank you for checking this problem!
I will use NN upsampling and convolution instead.

**Comment by psmaragdis** [comment]
I cannot see the original notebook above since it's been removed since, but at least in the case of 1d convolution this problem still persists and I believe it is not a cuDNN blind spot.

Transpose convolutions using both cpu and gpu backends are significantly slower than regular convolutions in Jax (so likely not a CUDA problem).  Additionally, here is an example comparing them to their Torch counterparts; regular convolutions are just as performant between the two frameworks but transpose convolutions are much slower when using Jax.

https://colab.research.google.com/drive/19g_VmTrK0bScC6p5sqbuND7n0FVi4GqW?usp=sharing
