### ISSUE TITLE
Old jaxlib version gone from PyPI?

### ISSUE THREAD

**Issue by thisiscam** [google/jax#8640]
Hi,

I just noticed that versions of jaxlib older than 0.1.60 are gone from the package index. 
I'm wondering if this is intentional (I couldn't find any documentation on this)?

Some times one really need to fix all the versions and dependencies for a project. 
For example, when publicizing an artifact, it would be really nice to reference a jax version, instead of packaging the jax source with the artifact. 
I understand that PyPi is not supposed to be an archivable (i.e., there's no guarantee on if/when things might disappear), but jax version 0.1.59 is just about a year old --- it seems surprising that it's entirely gone after this short amount of time?

**Comment by hawkinsp** [comment]
We remove old versions from pypi because of space limitations. I don't think we can avoid that: even if we requested more pypi quota, it could delay but not remove that requirement.

However, we are keeping older versions (including the CPU-only wheels) in the GCS bucket that contains the GPU wheels: https://storage.googleapis.com/jax-releases/jax_releases.html
because we aren't space-limited there. You should be able to use `pip` to install from that index, using a command line like:

```
pip install jax==VERSION -f https://storage.googleapis.com/jax-releases/jax_releases.html
```

Hope that helps!

**Comment by thisiscam** [comment]
Thanks!
