### ISSUE TITLE
Provide a way to disable compilation (and throwing an exception if compilation is attempted)

### ISSUE THREAD

**Issue by sherjilozair** [google/jax#8655]
This is useful to write a context manager that ensures that compilation doesn't occur where it's not supposed to.

Previously we did this by monkey patching jax.xla.backend_compile. However, since it's now become an internal function, it would be nice if jax provided an alternative way to implement a function like this.

**Comment by skye** [comment]
@froystig this reminds me of your event logging thing... like maybe it could provide a way to trigger a custom callback whenever compilation happens?

**Comment by froystig** [comment]
> compilation doesn't occur where it's not supposed to

Could you elaborate on "not supposed to"? Is jax doing something unexpected?

We can work to improve event logging in the system so that compilation consistently triggers a log event. If we use Python's `logging` (maybe absl's too) then programmatic event capture might be possible as well. I suspect the latter is what @skye has in mind. We've considered something like this, but either way it would be good to understand this request in more detail.

**Comment by sherjilozair** [comment]
> Could you elaborate on "not supposed to"? Is jax doing something unexpected?

No. For downstream applications, we often want to control where and when compilation happens. A common pattern is to "warm up" the model by initialising and running it once on dummy input and then using it for training or inference where we don't want compilation to happen for many reasons. This works most times, but sometimes there could be a mismatch between dummy input and real input or the real input shapes might change during training or inference, and we'd like to catch such bugs explicitly and not have jax silently compile with the new input shapes.

Since compilation takes much longer than a typical function call, we'd like to separate the two (AOT-like). This helps with measuring performance, etc.

**Comment by jakevdp** [comment]
I don't think there's any built-in API for this currently. This may be a good application for the ahead-of-time compilation that @froystig and others have been working on. I could imagine an API that lets you compile a function for a particular set of inputs, and which returns a function that raises an error if called with inputs that don't match.

**Comment by froystig** [comment]
> I could imagine an API that lets you compile a function for a particular set of inputs, and which returns a function that raises an error if called with inputs that don't match.

That's how the AOT path behaves:

```python
>>> from jax import jit
>>> f = jit(lambda x: x + 4).lower(1).compile()

>>> f(3)
DeviceArray(7, dtype=int32, weak_type=True)

>>> f([3])
...
TypeError: function compiled for PyTreeDef(((*,), {})), called with PyTreeDef((([*],), {}))

>>> f(3, 3)
...
TypeError: function compiled for PyTreeDef(((*,), {})), called with PyTreeDef(((*, *), {}))

>>> f(3.)
...
TypeError: Computation compiled for input types:
  ShapedArray(int32[], weak_type=True)
called with:
  ShapedArray(float32[], weak_type=True)
```

It'd be great if AOT is useful here, and I agree that it sounds like it may be.

That said, we do intend to log all compilation events today when `--jax_log_compiles` is configured. If we don't log consistently already, then we can use this issue to track that we do. @sherjilozair, if you configure the system to log compiles (via flag, environment variable, `jax.config` update, or the `jax.log_compiles` context manager), is there a particular compilation that you suspect is happening but that you aren't seeing logged?

I'd also still like to understand whether/why this request is specifically for the system to raise exceptions (per the issue title), rather than to log. Is logging sufficient?

**Comment by sherjilozair** [comment]
Is there any more documentation about AOT compilation? Particularly about its compatibility with pmap? AOT compilation sounds like exactly what we need.

We prefer exception over logging simply because we prefer that an input mismatch fails loudly (the same way type errors would fail compilation in a typed language). Logging is also workable solution, especially if we can write failing tests based on what is logged.

**Comment by froystig** [comment]
> Is there any more documentation about AOT compilation?

It's under active development, tracked in #7733. I don't plan to document it much until it's (closer to) complete.

> Particularly about its compatibility with pmap?

It works with pmap! Just replace `jit` with `pmap` in the above example.

> AOT compilation sounds like exactly what we need.

Excellent.

> We prefer exception over logging simply because we prefer that an input mismatch fails loudly (the same way type errors would fail compilation in a typed language). Logging is also workable solution, especially if we can write failing tests based on what is logged.

AOT will raise exceptions, so I think we're set, provided you're OK using an API that's not fully documented yet and may still change slightly.

**Comment by froystig** [comment]
Closing this since it seems resolved even by the current state of AOT. Please reopen if/as needed!
