### ISSUE TITLE
OptimizeResults types different from scipy OptimizeResults

### ISSUE THREAD

**Issue by tetterl** [google/jax#8677]
The JAX OptimizeResults class uses different type annotations than the scipy equivalent class. E.g. in the JAX code the success flag is typed as `Union[bool, jnp.ndarray]` while in scipy it's a `bool`. Is there any reasons for this typing in JAX or is this a bug?

- https://github.com/google/jax/blob/0d939e68c53d82c6d826ba3777511a8a21318f4d/jax/_src/scipy/optimize/minimize.py#L21
- https://github.com/scipy/scipy/blob/v1.7.1/scipy/optimize/optimize.py#L82

**Comment by nicholasjng** [comment]
Not a maintainer, but I believe the reason is that the return type changes based on whether or not you transform (`jit, vmap,...`) your minimization function in JAX.

That is, when using `jax.scipy.optimize.minimize` eagerly (on CPU, no JIT/vmap/etc.), you will get Python objects in return (bools, ints, floats etc.), while with transformations, everything including scalars, like a success boolean would be, gets inevitably cast to a `jnp.ndarray`.

**Comment by mattjj** [comment]
To add to @nicholasjng's excellent answer: for simplicity, JAX doesn't distinguish scalar types from 0d arrays. Because the success flag might be produced by a JAX-transformed function or by a jax.numpy function, and because JAX really only has array types (not scalars), that means we use the `jnp.ndarray` annotation here.

If we could provide finer-grained information, we might want to annotate it like `jnp.ndarray[shape=(), dtype='bool']` to indicate that the array will always be 0d and have dtype bool; but we don't have the capability to add annotations like that.

So it's not a bug, though still there may be ways we could try to refine such annotations in the future.

Hope that answers the question! If not, please let me know and/or reopen the issue.
