### ISSUE TITLE
What is the correct way to check that something is array-like?

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#8701]
I guess that the new version of Jax has it so that `jax.numpy.ndarray` no longer inherits from `np.ndarray`, which is great.  Unfortunately, other packages like Seaborn and Pandas are relying on `isinstance(x, np.ndarray)` in a few places.  This causes their behavior to change, and forces me to cast to `np.ndarray`.

I was just wondering, what should they be doing instead?  Is it looking for the [array interface](https://numpy.org/doc/stable/reference/arrays.interface.html)?  But `jax.numpy.ndarray` doesn't expose that.  If it's something else, I'll post the appropriate issues on their trackers.  If there's no way to check yet, that would be good to know.

Thanks.

**Comment by jakevdp** [comment]
i don't believe JAX `DeviceArray` object would ever have satisfied `isinstance(x, np.ndarray)` (there was a change recently that made it so that numpy array objects would not satisfy `isinstance(x, jnp.ndarray)`, but that seems tangential to your question).

The most permissive way for libraries to handle this, I think, would be to call `np.asarray(x)` on inputs, and let numpy decide if it can convert the result.

If you want something a bit more restrictive but that would still accept explicitly array-like objects that aren't instances of `np.ndarray`, perhaps something like this would be sufficient:
```python
def is_arraylike(x):
  return hasattr(x, '__array__') or hasattr(x, '__array_interface__')
```

**Comment by NeilGirdhar** [comment]
@jakevdp Thank you. I only spent about 15 minutes on this, but when I updated to Jax master, I started getting crashes in pandas/seaborn that were fixed by converted to numpy array.

If I run into this again, I'll submit an issue to them with a link here.

**Comment by jakevdp** [comment]
One recent change that may be relevant is that iteration over jax arrays now returns jax arrays, where it used to return numpy arrays. So if you had code like this:
```python
import jax.numpy as jnp
import numpy as np
x = list(jnp.ones((2, 3)))
isinstance(x[0], np.ndarray)
```
it would previously have returned True, and now returns False.

**Comment by NeilGirdhar** [comment]
Good thinking.  That could be it.  When I looked at their code, they were doing things like iterating and checking types.
