### ISSUE TITLE
Jax issue with numpy

### ISSUE THREAD

**Issue by JiahaoYao** [google/jax#876]
When I import other packages when contains `import numpy`, it contradicts with the jax numpy. How do people solve this when they want to use jax but also need to import other packages?

**Comment by mattjj** [comment]
We use NumPy a lot in our implementation; we follow the convention of `import numpy as onp` and `import jax.numpy as np`, but you could imagine other conventions, like `import jax.numpy as jnp` if the issue is name conflicts.

If the issue is instead wanting to use an existing NumPy library with jax.numpy, I don't think we have a great solution. Maybe you could monkey-patch the module in-memory, as in `some_module.np = jax.numpy`.

@shoyer and #611 may have a better long-term solution, where regular NumPy can learn how to work with JAX.

What do you think?

**Comment by JiahaoYao** [comment]
That is good, thanks @mattjj !
