### ISSUE TITLE
Implementation `numpy.matrix`

### ISSUE THREAD

**Issue by andylamp** [google/jax#881]
Thanks for the cool library - is there any roadmap or an eta for you to port `numpy.matrix`; as it stands currently the dot (`*`) sign produces the Schur's product instead of the natural matrix multiplication one. It would be really convenient to use the natural notation if possible and to do that cleanly without much hacks `numpy.matrix` is needed.

Or better yet, would you be open to receive a pull request of such an addition - depending on how much work would be involved into achieving that...

**Comment by hawkinsp** [comment]
In general, we welcome PRs.

However for `numpy.matrix` specifically I note the following comment in the NumPy docs:

https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html
```
Note: It is no longer recommended to use this class, even for linear algebra. Instead use regular arrays. The class may be removed in the future.
```
So I'd be tempted to never add it to Jax in the first place, rather than to add it and then remove it whenever numpy does.

Can you use the `@` operator in Python 3 instead?

**Comment by andylamp** [comment]
oh snap - I didn't see the deprecation for `numpy.matrix` - bummer; I was using `@` sign anyway but always felt a bit weird. Since this is a `numpy` design decision I completely agree that this should not make it's way in `jax` itself due to deprecation and thus closing the issue.

thanks for the super fast reply.
