### ISSUE TITLE
Large memory needed in gathering operations

### ISSUE THREAD

**Issue by Dapid** [google/jax#891]
[Here][1] is a simplified example of my problem. While I can compute the gradients of a single input, I quickly run out of memory. Is there a way to make it more memory efficient?

With a batch size of 6 I need 2157 MiB, but the gradients are of shapes (6, 50, 21) and (6, 50, 50, 21, 21), which are 25 MiB, but I am incurring in a 100x overhead. Am I doing something wrong? Can we help jax be smarter? Can I profile or inspect the graph to figure out which operations are taking the space?

[1]: https://gist.github.com/Dapid/e980a26e063838d472f46db1b7df59bd

**Comment by hawkinsp** [comment]
From a quick look, this looks very similar to #824.

Can you try to use a single large gather (e.g., using advanced indexing) rather multiple lookups in a loop?

(That said, I suspect we can improve the memory usage of your code as written, too.)

**Comment by Dapid** [comment]
The problem of #824 was dynamic slice. I don't think I can get rid of the loop, in the real case each iteration depends on `r`, but I will rethink it.

**Comment by mattjj** [comment]
Nice code!

Under a `jit` I would expect the sparse gradients to be accumulated efficiency, but we should investigate if something is going wrong there. In Autograd we also accumulated sparse gradients that arose from indexing efficiently (without having `jit`) because Dougal added [a special SparseObject](https://github.com/HIPS/autograd/blob/541a70b8a754356fe52e2d6caa7f4aa94c18cf05/autograd/numpy/numpy_vjps.py#L700) that [the gradient-summing machinery knew how to deal with](https://github.com/HIPS/autograd/blob/541a70b8a754356fe52e2d6caa7f4aa94c18cf05/autograd/core.py#L158-L186). We could do that in JAX too if necessary, though I'd be interested to figure out why `jit` might not be doing the optimization here.

**Comment by hawkinsp** [comment]
We identified an issue where the the gradient to gather/dynamic slice ended up explicitly instantiating arrays full of zeros; PR #914 should help a lot here.

Note that you most likely want the matrices such as `J` to be arguments to your `jit`-ted function; as it is they are constants captured lexically. Unless their values are constants this probably doesn't do what you want.

**Comment by hawkinsp** [comment]
I checked in the fix. Please let us know if it works for you!

**Comment by Dapid** [comment]
It has improved a lot, thanks!

Is there a way to profile memory usage?
