### ISSUE TITLE
Get rid of bazel

### ISSUE THREAD

**Issue by KOLANICH** [google/jax#895]
Do we really need bazel in order to just compile lapack.pyx?

**Comment by hawkinsp** [comment]
bazel is used to compile not just lapack.pyx, but also XLA, which is pulled in from TensorFlow as a submodule. It's not feasible to replace it.

Can you say more about what problem Bazel is causing for you? Perhaps we can address that instead.

**Comment by hawkinsp** [comment]
I should add: most users can probably use a precompile Jaxlib (e.g., from Pypi, or one of the CUDA wheels referenced by `README.md`)

**Comment by KOLANICH** [comment]
can xla be put into a separate module, that can be used prebuilt, keeping jax free of compilation? I mean using basel fir building is infeasible.

**Comment by hawkinsp** [comment]
That's already what we do. We have two Python modules: `jaxlib`, which is almost all C++, and `jax`, which is pure Python. You can use a prebuilt `jaxlib` (and that's what we recommend), even if you use `jax` from Github head.

(The slightly confusing part is that the Jax repository contains a little part of jaxlib, mostly just the build rules and `lapack.pyx`.)

**Comment by KOLANICH** [comment]
>The slightly confusing part is that the Jax repository contains a little part of jaxlib, mostly just the build rules and lapack.pyx.

Thanks for the info!

Should we build that part using `setuptools` machinery instead of bazel?

>Can you say more about what problem Bazel is causing for you? Perhaps we can address that instead.

Bazel have plenty of issues making it not very suitable for users' machines. But the most of problems with bazel I know about is that it loads large stuff from the net, like tensorflow git repo, and for the case of tensorflow - its submodules, and builds them automatically. It is very slow if build is done not on build farm with fast internet, ssd, new CPUs and lot of ram, but on a usual PC, especially if that PC is not hi-end. A better approach is to have a federation of repos (or even better a distributed decentralysed network like ipfs) of prebuilt modules authenticated by digital signatures and built reproducibly. So my machine wouldn't have to rebuild everything. It is only one of many issues with bazel.

**Comment by hawkinsp** [comment]
No, there's no point building the few leftover parts without Bazel; you'd still need Bazel to build most of jaxlib (XLA). The two are built together. We have thought about removing the remaining parts of jaxlib from the jax repository and moving them in with XLA at some point, which would make the distinction a bit clearer, although that hasn't happened yet.

XLA and its dependencies can't be distributed in binary form because they don't have stable ABIs. So they must be built from source. `jaxlib` is pretty much exactly the minimal version of XLA you would have to build and distribute.

FWIW, we routinely build jaxlib on a laptop with Bazel. It does take 20-30 minutes or so or a recent Macbook. If that's too much overhead, I would suggest using a prebuilt version. For downloads sizes: jaxlib tracks TensorFlow and LLVM head very closely. It won't work with versions that even a few days old frequently. There isn't a lot of alternative here.

**Comment by surak** [comment]
Well, pretty much because of this: https://github.com/bazelbuild/bazel/issues/4137#issuecomment-610518610

We have bazel on the system (for tensorflow) - yet jax compiles (wrongly) its own bazel for whatever reason, and fails later because it links to the cluster's gcc, and later looks for the libraries on the /usr/lib64. There are many other places where this happen (hardcoded locations in bazel).

**Comment by surak** [comment]
Same for nasm, cython, and the multitude of problems that bazel brings. Go and ask the people who actually deal with software compiles, the responsible in every linux distro, in package managers, what they think about bazel. It's more trouble than worth.

**Comment by ClayJay3** [comment]
Nah, let's get rid of bazel. CMAKE is more convenient.
