### ISSUE TITLE
Some JAX flags cannot be set by environment variables

### ISSUE THREAD

**Issue by ayaka14732** [google/jax#9034]
Currently, the `JAX_ENABLE_X64` flag can be set by environment variable:

```sh
$ export JAX_ENABLE_X64=True
$ python
>>> from jax.config import config
>>> config.FLAGS.jax_enable_x64
True
```

However, some flags cannot:

```sh
$ export JAX_XLA_BACKEND=tpu_driver
$ export JAX_BACKEND_TARGET="grpc://$COLAB_TPU_ADDR"
$ python
>>> from jax.config import config
>>> config.FLAGS.jax_xla_backend
''
>>> config.FLAGS.jax_backend_target
''
```

**Comment by mattjj** [comment]
Thanks for raising this!

@skye since you were looking at this stuff recently, could you take a look at this issue?

**Comment by bharatnishant** [comment]
@mattjj in which module should I look fot this?

**Comment by mattjj** [comment]
> in which module should I look for this?

@bharatnishant are you asking about these particular flags, or about configuration options in general?

In general, the 'good' config stuff is in jax/_src/config.py. That config stuff is good because it has a uniform way to set up environment variables, flags, and context managers. Some flags are defined elsewhere, and you can find those just by grepping for them.

The `jax_xla_backend` option is instead [defined in xla_bridge.py](https://github.com/google/jax/blob/68e9e1c26d5d9439d03d09a10b8f9b26e8258383/jax/_src/lib/xla_bridge.py#L57), but as you can see it's deprecated in favor of [`jax_platforms`, which does have an env var](https://github.com/google/jax/blob/68e9e1c26d5d9439d03d09a10b8f9b26e8258383/jax/_src/lib/xla_bridge.py#L69). @ayaka14732 I suggest using `export JAX_PLATFORMS=tpu_driver` instead of using `JAX_XLA_BACKEND`.

As for `JAX_BACKEND_TARGET`, it looks like that [doesn't have an environment variable](https://github.com/google/jax/blob/68e9e1c26d5d9439d03d09a10b8f9b26e8258383/jax/_src/lib/xla_bridge.py#L60). Maybe we should add one there...

I don't think #9118 touches `JAX_BACKEND_TARGET`, so I'll add an environment variable there now (in an ad-hoc way, rather than using general jax/_src/config.py stuff). @skye lmk if that's mistaken.

**Comment by bharatnishant** [comment]
@mattjj I wanted to know about the configuration options in general. 
After you have made changes, is it needed to be changed in jax/_src/config.py as well for a proper fix? Should I add it there too?

**Comment by mattjj** [comment]
Ah, I see!

I'm not sure if it's worth making jax_platforms or jax_backend_target use our general-purpose config machinery because AIUI those are likely to be set once per process (so we don't need the context manager stuff, handling state changes in a thread-safe and jit-sensitive way, or anything else). I could be wrong though.

@skye WDYT about making jax_platforms or jax_backend_target use the machinery in jax/_src/config.py?

@bharatnishant if you're looking for places to help, there may be other spots which are more fruitful.

**Comment by skye** [comment]
Hi sorry, lost track of this! #9142 looks great.

@mattjj I agree with your analysis of jax_platforms and jax_backend_target. The only reason I can think of for using the standard config machinery is to have all flags/env vars in one place (and we can just throw away the context manager). I don't feel strongly either way.
