### ISSUE TITLE
dynamic_update_slice start index adjustment fails when vmapped

### ISSUE THREAD

**Issue by Ryul0rd** [google/jax#9083]
The documentation for `dynamic_update_slice` explains "If the update slice is too large to fit in the array, the start index will be adjusted to make it fit" and this behavior does indeed seem to work normally but fails when I apply vmap. No update occurs if the update slice would not fit even if the update slice would still be partially in the array as in the example below.

```python
zeros = jnp.zeros(5)
ones = jnp.ones(3)

for i in range(1, 4):
    print(jax.lax.dynamic_update_slice(zeros, ones, (jnp.array(i, dtype=int),)))

print(jax.vmap(jax.lax.dynamic_update_slice, (None, None, 0))(zeros, ones, (jnp.arange(1, 4),)))

# [0. 1. 1. 1. 0.]
# [0. 0. 1. 1. 1.]
# [0. 0. 1. 1. 1.]
# [[0. 1. 1. 1. 0.]
#  [0. 0. 1. 1. 1.]
#  [0. 0. 0. 0. 0.]]
```

**Comment by jakevdp** [comment]
Thanks for the report; it looks like this is a bug in the `dynamic_update_slice` batching rule: https://github.com/google/jax/blob/04369a35888581b2c93abccffbe61fb3db8c460e/jax/_src/lax/slicing.py#L918-L936

On first look, I think the issue may be that it should use `mode=CLIP` rather than `mode=PROMISE_IN_BOUNDS`, but I'd have to dig deeper to be sure.
