### ISSUE TITLE
Feature request: `jax.scipy.special.erfi`

### ISSUE THREAD

**Issue by jorenham** [google/jax#9098]
The "imaginary error function" from [`scipy.special.erfi`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.erfi.html), is defined as `erfi(z) = -i erf(i z)`. Counterintuitively, the return value is real for real arguments. 

Today, `erfi` rolled out of an equation in an optimization problem I'm working on, I tried implementing this as:

```python
import jax.numpy as jnp
from jax.scipy.special import erf

def erfi(x):
    return -jnp.imag(erf(1j * x))
```

But this failed: `TypeError: erf does not accept dtype complex64. Accepted dtypes are subtypes of floating.`. This also is the case when I tried implementing it using the incomplete gamma function.
Although I'm not sure why this restriction is in place, an implementation of `erfi` should be doable without using complex numbers altogether. 

Similarly, Dawson's Integral function ([`scipy.special.dawsn`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.dawsn.html)) could be implemented, as it can easily be written in terms of `erfi` (see https://mathworld.wolfram.com/DawsonsIntegral.html), and I read somewhere that it is numerically more stable than `erfi`, but don't quote me on that.

**Comment by hawkinsp** [comment]
It looks to me like our best bet might be to port the implementation of Dawson integrals from TensorFlow into JAX or XLA.

https://www.tensorflow.org/api_docs/python/tf/math/special/dawsn
and the key piece of code is:
https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/core/kernels/special_math/special_math_op_misc_impl.h

Probably the best thing to do would be to add it to XLA so both JAX and TF can share it when using XLA.

**Comment by WoLpH** [comment]
I'm a complete noob when it comes to jax and how it's implemented, but after having a quick look I'm wondering if we can't simply enable the Dawson integrals here:
https://github.com/tensorflow/tensorflow/blob/18480747b04ed1b416e2d3852d495e02c438f251/tensorflow/compiler/mlir/xla/transforms/legalize_tf_patterns.td#L627-L670

That seems to be the place where these functions are linked.

**Comment by dieterichlawson** [comment]
Any updates on this? I am also interested in `erfi` either in JAX or XLA.

**Comment by mattjj** [comment]
Matt MacKay and Dieterich both making a feature request!

I don't have any updates, but AIUI one could just write [the implementation that @hawkinsp linked](https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/core/kernels/special_math/special_math_op_misc_impl.h) in Python, in terms of `jax.numpy` calls, and the `jit` it to get the result. (It's preferable from a maintenance perspective to put these in XLA just so we don't have to maintain a full math library in JAX, but otherwise the generated code would be the same.) @hawkinsp correct me if I'm wrong.

I'll mention this in our chat room to see if anyone has cycles for it, though this may be ripe for an external contribution as well... 😇

**Comment by mattjj** [comment]
@srvasude just pointed out that you can probably use `tfp.math.dawsn` with the [TensorFlow Probability JAX backend](https://www.tensorflow.org/probability/examples/TensorFlow_Probability_on_JAX).

**Comment by matthewmackay** [comment]
Thanks for taking a look @mattjj! tfp.math.dawsn worked perfectly. Feel free to close this issue.
