### ISSUE TITLE
jax2tf no_xla implementation for scatter_*, advice requested

### ISSUE THREAD

**Issue by oliverdutton** [google/jax#9269]
Jax2tf currently does not support scatter_* in non XLA terms (see [docs](https://github.com/google/jax/blob/main/jax/experimental/jax2tf/converters_eval/no_xla_limitations.md))

I am planning on implementing this as I need it, but first I wanted to check - is it possible, or is there a very solid reason for why it simply isn't expressible in the tensorflow ops?

Is this a foolish plan?

I want to do it in non-XLA terms so I can use tf2onnx so it can be used as an ONNX model

I was thinking about using a combination of:
- `tf.math.unsorted_segment_{prod,sum,...}` for getting the updates to the array 
- `tf.scatter_nd` for applying those updates

Note (to self): `x.at[indexs].get()` does has a non-XLA implementation.

**Comment by oliverdutton** [comment]
The add looks very simple to port across for a simple case.

```python
import tensorflow as tf
import jax.numpy as jnp

indexs = jnp.arange(0,12,3)
x = jnp.arange(12)+2.2
update = -300.

def scatter_add_tf(x, indexs, update):
    updates = tf.broadcast_to(update, indexs.shape)
    indexs = tf.expand_dims(indexs, -1)
    return tf.tensor_scatter_nd_add(x, indexs, updates)

scatter_add_tf(x, indexs, update), x.at[indexs].add(update)

#(<tf.Tensor: shape=(12,), dtype=float32, numpy=
# array([-297.8,    3.2,    4.2, -294.8,    6.2,    7.2, -291.8,    9.2,
#         10.2, -288.8,   12.2,   13.2], dtype=float32)>,
#DeviceArray([-297.8,    3.2,    4.2, -294.8,    6.2,    7.2, -291.8,
#                 9.2,   10.2, -288.8,   12.2,   13.2], dtype=float32))
```

**Comment by gnecula** [comment]
Hi, we are implementing the no_xla support as needed. You are right that scatter is not yet supported, and thank you for considering adding it. The obvious main requirement is semantic correctness (and this should be verified with tests; see below). 

Another (soft) requirement is that the translation should use as few TF ops as possible, because otherwise it becomes hard to expect that the performance of the translated code to be good (one can always encode any semantics with a soup of low-level TF ops, but then we place an unreasonable burden on the downstream runtime to ensure good performance).  

We would welcome additions, but please keep them simple, and well-documented, in case we need to debug them later. Also, please ensure that there are tests. Take a look at `tests/primitive_harness.py`, specifically at `_make_scatter_harness`. This will define a set of combinations of argument shapes and parameters that will be tested by `tests/primitives_test.py:test_prim`. By default all primitives harnesses are tested only with XLA enabled. To create harnesses specifically with `enable_xla=False` you will have to add parameter `enable_xla` to the harness. See how this is done for `gather`. There we duplicate almost all harnesses with `enable_xla=True` and `False`. If you are only going to add support for a few cases of `scatter` maybe it makes sense to add primitive harnesses for those cases. 

One complication is that currently the primitives_test.py is not run automatically in github; it is run only internally when we import the code in the Google repo. I recommend that you run the tests manually:

```
pytest -r a --verbosity 1 -s jax/experimental/jax2tf/tests/primitives_test.py -k scatter
```

**Comment by gnecula** [comment]
@marcvanzee PTAL

**Comment by oliverdutton** [comment]
Response to the useful advice given in the linked pull request (now closed)

I have found other routes for the task than through no_xla, closing task. Thank you for your suggestions and comments.

For if of importance to later people:
- Scatter_{add,mul,min,max} implemented for simple 1d indexs into a 1d array (other cases not checked)

Again, thank you.
