### ISSUE TITLE
Notebook erroring out when running many iterations

### ISSUE THREAD

**Issue by raphpapercup** [google/jax#928]
When running the following notebook: https://github.com/ericjang/nf-jax/blob/c6636a010bb744a48185eb3f622d32336e929990/nf-tutorial-jax.ipynb, I have found that if you run all 1e4 iterations in a row, then evaluate y.max(), the notebook crashes. However if you run say 1000 iterations, then run y.max(), then run 1000 iterations, then run y.max(), etc, all the way to reach 1e4 iterations, the notebook does not crash and things work as expected.

**Comment by mattjj** [comment]
@hawkinsp could this be related to async execution?

@raphpapercup which backend is this on (CPU or GPU)? Could you try running `y.block_until_ready()` every 1000 iterations, instead of `y.max()`, just to help us diagnose the bug? See [the async dispatch docs](https://github.com/google/jax/blob/master/docs/async_dispatch.rst) for an explanation of why it might be related.

**Comment by hawkinsp** [comment]
If this is running on CPU, I can believe it might well be related to async execution; you could easily run OOM. We probably need to limit how far ahead the Python code can run. Could you please verify which backend you were using? Thanks!

**Comment by hawkinsp** [comment]
I believe this was fixed by the stream pacing mechanism referenced above.
