### ISSUE TITLE
Document `.lower()`

### ISSUE THREAD

**Issue by hawkinsp** [google/jax#9717]
(e.g., I wanted to link to the documentation from https://github.com/google/jax/discussions/9716 ... but there is no documentation!)

**Comment by rokity** [comment]
What you mean?

**Comment by rokity** [comment]
Can you assign to me the task? I can do it as my first contribution to JAX project.

**Comment by hawkinsp** [comment]
@rokity I'll leave it up to @froystig if he wants to do that. (He wrote the code, so he would be the natural person to document it.)

**Comment by froystig** [comment]
Thanks for offering! This would be a difficult contribution to make without more context, since this API has some attributes that are not finalized and should not be considered stable/public yet. These exceptions will need to be highlighted in documentation especially. It would be easiest for me to take this one. Once I do, if you read it and find anything unclear, a PR with improvements is always welcome.

If you are looking for contribution opportunities more broadly, you might find ideas by browsing issues labeled ["contributions welcome"](https://github.com/google/jax/labels/contributions%20welcome) or ["good first issue"](https://github.com/google/jax/labels/good%20first%20issue).

**Comment by rokity** [comment]
Thanks for the help I'll watch other issues this days. I'm trying to became a contributor on the field of AI so thanks for the tips and helps.

**Comment by froystig** [comment]
Closed by #12204
