### ISSUE TITLE
protocol/types for compilation wrappers

### ISSUE THREAD

**Issue by froystig** [google/jax#9808]
Let's set up a protocol for the return type of `jit`, `pmap`, `pjit`, and `xmap`. These essentially have `__call__` and `lower`.

This would:
* improve documentation;
* enable pytype annotations; and
* allow for some easier checks in internals that expect such a thing as input.

cc @hawkinsp

**Comment by hawkinsp** [comment]
A protocol seems like a good way to go.

(Nominal inheritance would be harder to do because mixed Python/C inheritance appears not to be used that often and I'm not entirely sure how to do it correctly without digging a lot more into how inheritance is implemented in Python, but a Protocol does not require any cooperation from the implementation.)
