### ISSUE TITLE
Distribution of jax.random.dirichlet samples is incorrect for small values of the concentration parameters

### ISSUE THREAD

**Issue by benanne** [google/jax#9896]
`jax.random.dirichlet` seems to produce incorrect distributions for small values of the concentration parameters (i.e. where most of the probability mass should be on the vertices of the simplex).

I've only tested this for 3D input (because this can easily be visualised in 2D), so I don't know if it happens for other dimensionalities.

I'm producing samples as follows:
```
samples = jax.random.dirichlet(key, 0.01 * np.array([1.0, 1.0, 1.0]), (100000,))
```

On CPU and TPU, there seems to be an additional vertex added to the simplex (i.e. it's actually 4D, projected into 2D), which lives at the barycenter of the three existing vertices.

On GPU, the problem is even worse, with additional extra vertices at the midpoints between each pair of vertices (so 4 spurious vertices in total).

Visualisations and more info at http://go/jax-dirichlet-simplex-issue

**Comment by jakevdp** [comment]
Thanks for the report - I believe this is a floating point precision issue. In both numpy and JAX, the dirichlet distribution is implemented via the average of an N-dimensional gamma distribution. JAX generates these numbers in float32, while numpy generates them in float64. Additionally, it looks like JAX never rounds a generated value to zero.

Observe the following for JAX:
```python
from jax import random
import matplotlib.pyplot as plt

key = random.PRNGKey(0)
out = random.gamma(key, 0.01, (10000,))
print(out.dtype)
# float32
print(out.min())
# 1.1754944e-38
print((out == out.min()).sum())
# 4160
```
and for NumPy:
```python
import numpy as np
out = np.random.gamma(0.01, size=10000)
print(out.dtype)
# float64
print(out.min())
# 0.0
print((out == out.min()).sum())
# 7
```
The `NaN` values in numpy occur when all three dimensions hit the minimum value of zero (`0 / (3 * 0)` is `NaN`); the added simplex in the JAX version comes from the equivalent situation in JAX, where all three branches hit the nonzero minimum value generated by `jax.random.gamma`: `a / (3 * a)` is `0.3333`)

The way to fix this would be to allow for infinitely small values to be generated by the gamma distribution, but look at this:
```python
print(np.finfo(np.float32).tiny)
# 1.1754944e-38
```
JAX is already generating the smallest possible nonzero float32 value when α is this small.

So what could we do? The easiest thing to do would be to allow `gamma` to generate zeros, in which case JAX would behave like numpy and return NaNs. Better would be to find a way to generate log-gamma rather than gamma, in which case precision at the small end would not be limited by the precision of float32. I'm not sure how easy that would be, but it's worth looking into.

What do you think?
