### ISSUE TITLE
Inconsistent behaviour between numpy.prod and jax.numpy.prod

### ISSUE THREAD

**Issue by umgupta** [google/jax#9958]
Please:

- [x] Check for duplicate issues.
- [x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

`jax.numpy.prod` does not work with tuples but `numpy.prod` works just fine. See MWEs below

```python
import numpy
print(numpy.prod((1,128)))
# 128
print(numpy.prod((128,)))
#128
```

The same code crashes for `jax.numpy`
```python
import jax
print(jax.numpy.prod((1,128)))
```

Error mesage:
```TypeError: prod requires ndarray or scalar arguments, got <class 'tuple'> at position 0.```

**Comment by jakevdp** [comment]
This is an intentional difference between the two packages: numpy will automatically cast lists or tuples to arrays, while JAX deliberately avoids such implicit casting because it can hide performance issues. See https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#non-array-inputs-numpy-vs-jax for more information.
